### PR TITLE
Communicate directly to CAN devices from klipper serialqueue.c code

### PR DESCRIPTION
**Pull request by KevinOConnor**
This PR is for discussing a change to Klipper so that it can directly communicate with CAN devices (instead of using the CanSerial proxy tool.)

The main advantage of doing this is that it reduces the "number of moving parts" and it may make debugging and error handling a little easier.

The code on this PR does work for testing purposes, but it has a couple of serious flaws:
* The new "can id assignment daemon" (in `scripts/canbus_assigner.py`) was written for testing.  (The code is based on testing code from @bondus.)  A real assignment daemon would need to persist state and be more "bullet proof".  (Without more safety tests, there is a nasty failure scenario where multiple Klipper devices on the same CAN bus could obtain the same can id and commands could go to the wrong board, causing potentially serious damage.)
* The new serialqueue.c code could do a better job of batching writes and better handle cases where the transmit buffers fill.  We really want to have 8-byte writes on the CAN bus when we can.

This PR changes the Klipper CAN "id assigment" protocol.  In order to use the code on this branch, it would be required to reflash all CAN devices.  The new protocol has just two pairs of CAN ids - an assigned pair for rx/tx data and a global "admin" pair for sending "admin commands".  The rx/tx data pair is only used for transmitting data.  The "admin" pair sends messages that generally follow the following format: `<1-byte cmdid><6-byte uuid><1-byte encoded_can_id>`.  There are currently 4 admin commands (sent from host to mcu) and 2 responses (sent from mcu to host):
```
CMD_QUERY_UNASSIGNED = 0
CMD_QUERY = 1
CMD_SET_CANID = 2
CMD_REBOOT = 3
RESP_NEED_CANID = 32
RESP_HAVE_CANID = 33
```

With this branch, there is still a separate "can assignment daemon", but this separate daemon only assigns ids - it doesn't read/write any of the normal Klipper command traffic.  An assignment workflow might look something like:
1. the klippy host code starts
2. the host code queries for a given uuid (CMD_QUERY)
3. the given mcu responds that it doesn't have a data canid pair (RESP_NEED_CANID)
4. the canbus_assigner.py code assigns the data canid pair (CMD_SET_CANID)
5. the mcu obtains the assignment; it responds that it has a canid pair (RESP_HAVE_CANID)
6. the serialhdl.py code obtains the mapping from uuid to data canid pair and starts up the serialqueue.c code with a can fd that filters just on that pair
7. finally, all regular traffic is transmitted directly from serialqueue.c to the mcu over that data canid pair.

@Delsian , @bondus - FYI.

Comments?
-Kevin

### CODE REVIEW

**Comment by Delsian** [comment]
Wonderful. It was my dream before writing can-serial. Next big step - implementing BLE-Mesh to control hotends without wires (and porting code to NRF52) :)

**Comment by Arksine** [comment]
Looks good!  I'm curious, would it be worthwhile to generate the UUID from the MCU name?  That way the configuration would guarantee unique IDs and it would be easy to remember.

**Comment by bondus** [comment]
> Looks good! I'm curious, would it be worthwhile to generate the UUID from the MCU name? That way the configuration would guarantee unique IDs and it would be easy to remember.

The IDs are generated on the MCU based on a unique serial of the MCU itself. When you hook up a board the canbus_assigner.py daemon will log what boards it finds.
The assignment process does not work properly at the moment, if you restart canbus_assigner.py all boards must be restarted manually. Work in progress :)

**Comment by Arksine** [comment]
Ah, so that hasn't changed.  I had assumed that the ID was being assigned to the board based on the one supplied to printer.cfg.

**Comment by bondus** [comment]
I had a slightly different idea when changing the protocol.
The idea is that all nodes, assigned and unassigned, alway respond to the QUERY_ALL (that is currently QUERY_UNASSIGNED).
This will allow the assigning daemon to find all boards, even "old" boards that already have a CANID assigned, and resolve any possible CANID conflicts. 
The current test assigner do not have a good method to handle old boards at the moment, it simply resets them. That can be improved. There will be no need for any persistence of CANIDs for the boards

```
diff --git a/src/generic/canbus.c b/src/generic/canbus.c
index 23f0f232..082a5254 100644
--- a/src/generic/canbus.c
+++ b/src/generic/canbus.c
@@ -86,7 +86,7 @@ console_sendf(const struct command_encoder *ce, va_list args)
  ****************************************************************/

 // Available commands and responses
-#define CANBUS_CMD_QUERY_UNASSIGNED 0
+#define CANBUS_CMD_QUERY_ALL 0
 #define CANBUS_CMD_QUERY 1
 #define CANBUS_CMD_SET_CANID 2
 #define CANBUS_CMD_REBOOT 3
@@ -134,10 +134,9 @@ can_send_uuid(void)
 }

 static void
-can_process_query_unassigned(uint32_t id, uint32_t len, uint8_t *data)
+can_process_query_all(uint32_t id, uint32_t len, uint8_t *data)
 {
-    if (!canbus_assigned_id)
-        can_send_uuid();
+    can_send_uuid();
 }

 static void
@@ -181,8 +180,8 @@ can_process(uint32_t id, uint32_t len, uint8_t *data)
     if (!len)
         return;
     switch (data[0]) {
-    case CANBUS_CMD_QUERY_UNASSIGNED:
-        can_process_query_unassigned(id, len, data);
+    case CANBUS_CMD_QUERY_ALL:
+        can_process_query_all(id, len, data);
         break;
     case CANBUS_CMD_QUERY:
         can_process_query(id, len, data);
```

**Comment by KevinOConnor** [comment]
> The idea is that all nodes, assigned and unassigned, alway respond to the QUERY_ALL

Ah, I missed that.  Will that work though?  For example, if one has 5 boards on a CAN bus, wouldn't they all respond at the same time, all get a transmission conflict, and some of them reliably not get their responses transmitted?

There's a similar conflict with QUERY_UNASSIGNED, but that conflict eventually works itself out as the nodes get assignments.

> There will be no need for any persistence of CANIDs for the boards

That assumes there isn't a transmission error during the initial query processes.  If the host doesn't see some responses or the node misses some queries, or if the node is disconnected for some amount of time, then it raises the possibility the host doesn't have a complete list of nodes.

There's a pretty nasty failure scenario if two nodes somehow get assigned the same ids.  Consider two boards on the same bus - one has a heater hooked up to a mosfet, and another has a fan hooked up to a mosfet.  If the two nodes get the same id and the host commands a fan on, it could result in a run away heater.

Because of the severity of that error, I'd feel more comfortable with the assigner keeping a persistent list of all uuids and never reusing an assigned id.

-Kevin

**Comment by bondus** [comment]
>  Will that work though? For example, if one has 5 boards on a CAN bus, wouldn't they all respond at the same time, all get a transmission conflict, and some of them reliably not get their responses transmitted?

Collisions will get detected and frames will get retransmitted. Enabling the error frame dumping in canbus_assigner you can see a bunch of bit stuffing errors when QUERY_ALL is done, most likely they are from collision when all nodes send at the same CANID at the same time. I wish I had a CAN capable scope to see exactly what's going on. 
It still works flawlessly, even if there is something bad going on.
Perhaps we can add a tiny random delay on the responses to avoid this. Just 0-100 us will make it extremely unlikely.

> There's a pretty nasty failure scenario if two nodes somehow get assigned the same ids. Consider two boards on the same bus - one has a heater hooked up to a mosfet, and another has a fan hooked up to a mosfet. If the two nodes get the same id and the host commands a fan on, it could result in a run away heater.

That's a good point. However unlikely an error like that is, it must never happen. I think the periodic QUERY_ALL method is 100% reliable, but I can not guarantee it at the moment.  It needs to be investigated further. 

One option is to flip the protocol around and have the nodes makes themselves heard. Unassigned nodes will query at start up and quite frequently query for an ID, assigned nodes will announce their presence and ID less frequently. There will be no QUERY_ALL command at all.

**Comment by KevinOConnor** [comment]
> Collisions will get detected and frames will get retransmitted.

Will that work for many boards though?  Can we be sure 5+ retransmit attempts will be done by the hardware?  I guess it could work.

> Perhaps we can add a tiny random delay on the responses to avoid this. 
[...]
> One option is to flip the protocol around and have the nodes makes themselves heard.

I guess either of those could work, but adding persistent storage to the assigner daemon seems like it is simpler.  The file could also serve as a means of informing users what uuids are available when they first wire up a board.

FWIW, I'm thinking the assigner daemon could do something like:
1. At startup, read the "uuid to can_id" map from file into memory
2. Once a second send a QUERY_UNASSIGNED message
3. On any unknown uuid (in RESP_HAVE_UUID or RESP_NEED_UUID): lock the file, reread the file, add the new uuid mapping, write the updated file, unlock the file.  If the unknown uuid already had a can_id we can reuse that, or otherwise assign it a new random can_id in the range of 0 to 255.
4. For any known uuid that needs a can_id (RESP_NEED_UUID), just send it the previously assigned can_id using the in-memory mapping.

-Kevin

**Comment by bondus** [comment]
ID persistence is inconvenient but the safer option. I'll implement it and clean up the assigner code.
The other parts seems to work very well.

**Comment by KevinOConnor** [comment]
FYI, I added batching of message blocks to the master branch and rebased this branch on top of that work.  This should help maximize the CAN bandwidth (by encouraging 8 byte CAN packets).

-Kevin

**Comment by KevinOConnor** [comment]
@bondus - any updates?  I can also work on the "assigner daemon".

Thanks,
-Kevin

**Comment by KevinOConnor** [comment]
I updated this branch with a new canbus_assigner.py module that supports persistent id mappings.  I think at this point the only thing needed before merging is documentation updates and a start script for the new canbus_assigner daemon.  I'll try to look at that in the next couple of days.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, I have updated this branch with some basic documentation on using the new CAN bus system.  (See the new docs/CANBUS.md and docs/CANBUS_protocol.md files on this branch.)

If there are no further comments, I'll look to commit in a few days.

-Kevin

**Comment by bondus** [comment]
Hey Kevin, 
I have not worked much on this lately, sorry for that. Thanks a lot for keeping up the work on this
I tested the latest commits. It works as expected on my desk test setup with 6 boards with steppers without a printer attached.
Most available cheap CAN bus adapters struggle hard under the load we put them through. They drop and reorder packets both on send and receive, it seems like the only test case is to sniff packets of you car CAN bus. The only reliable CAN adapters I found under $100 are the STM32F0 based ones with the candleLight firmware. Or using the beaglebone native CAN, the old beagle is a rock. 
This has caused me a lot of headache supporting the Huvud board. It needs documentation 
/pontus
--- 

    On Thursday, 4 March 2021, 19:45:49 CET, KevinOConnor <notifications@github.com> wrote:  
 
 


FYI, I have updated this branch with some basic documentation on using the new CAN bus system. (See the new docs/CANBUS.md and docs/CANBUS_protocol.md files on this branch.)

If there are no further comments, I'll look to commit in a few days.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, I'm going to hold off on this series for a little longer.  It occurred to me that it may be possible to eliminate the canbus_assigner.py daemon.

One of my fears was that two nodes may be assigned the same node id, which could possibly lead to commands going to the wrong device (with possibly severe damage resulting).  Thinking on this further, however, in order for that situation to occur, the two devices would have to go through the entire identify sequence (downloading of the data dictionary, clock measuring, etc.).  In that situation, the two nodes should be able to detect each other's traffic.  So, if we add some code to each mcu to verify no other device is sending messages using the same node id, then I think we can have confidence that no two nodes could have the same node id past the identify sequence.

If we can remove the concern about two nodes having the same node id, then I think klippy (and console.py, etc.) could assign node ids themselves.  That should simplify the code and remove the need for an extra daemon.

-Kevin

**Comment by KevinOConnor** [comment]
I have redone this branch so that it no longer requires the canbus_assigner.py code.  New instructions for running are on the branch ( https://github.com/KevinOConnor/klipper/blob/work-can-20210207/docs/CANBUS.md ).

With this new code, the CAN protocol no longer uses CMD_QUERY nor RESP_HAVE_CANID.  I've left those message types in for now, but may remove them in the future.

Note that if you've installed the previous canbus_assigner service, then you'll need to stop and uninstall it before using this updated code.  Something like:
```
sudo systemctl stop canbus_assigner.service
sudo rm /lib/systemd/system/canbus_assigner.service
sudo systemctl daemon-reload
```

-Kevin

**Comment by KevinOConnor** [comment]
> With this new code, the CAN protocol no longer uses CMD_QUERY nor RESP_HAVE_CANID. I've left those message types in for now, but may remove them in the future.

FYI, I went ahead and simplified the protocol to just two commands and one response (CMD_QUERY_UNASSIGNED, CMD_SET_NODEID, and RESP_NEED_NODEID).

-Kevin

**Comment by boardthatpowder** [comment]
This branch works for me using a waveshare can hat, but not with a canable pro (clone) running candlelight. The `canbus_query.py` returns `Total 0 uuids found`, but I see the `can0` interface using `ifconfig`, and I can use `cansend` to send data to it.

**Comment by KevinOConnor** [comment]
> This branch works for me using a waveshare can hat, but not with a canable pro (clone) running candlelight

That's certainly odd.  Does the master branch run okay with the canable pro?  Also, double check your terminating resistors - the waveshare can hat has, unfortunately, a 120 Ohm resistor permanently soldered on - I'm unsure what the canable has.

-Kevin

**Comment by boardthatpowder** [comment]
Reverted to master and recompiled Huvud firmware, installed cansorial, etc. It worked.

Reverted back to the branch, recompiled Huvud firmware, removed censorial, etc. The canbus_query.py failed detecting.

I extracted the canbus id from the censerial id from master (`serial: /tmp/ttyCAN0_4a33c75fd66` became `canbus_uuid=4a33c75fd664`) and it works. So the problem appears to be just with `canbus_query.py`.

**Comment by KevinOConnor** [comment]
> The canbus_query.py failed detecting.

Ah, the canbus_query.py tool will only report devices that have not been initialized.  Once Klipper or another tool starts communicating with the device, then canbus_query wont report it.  If you want to detect a device again, you'd need to stop klipper, reset the device, and then run canbus_query.py .

-Kevin

**Pull request merged**
