### PR TITLE
TMC2660 Updates

### PR DESCRIPTION
**Pull request by FHeilmann**
These two commits are aimed to bring the tmc2660 code more in line with the TMC2130 code.

- The mandatory sense_resistor configuration parameter is added, duet2 users should use 0.051 for this parameter
- Current calculation is changed to use that new sense_resistor value
- The code now uses the tmc2130 helper functions for register access.

~~I refrained from using `set_config_field` because it would cause incomaptibilities for a large portion of the tmc2660 config (since set_config_field does not support `get_choice`).~~

- During the implementation of this I also found the source of the bug that I was seing (drivers raising the current too late when coming out of idle). This bug should be gone now.

- This PR also implements INIT_TMC for the tmc2660 and adds SET_TMC_FIELD to set arbitrary register values at runtime.

- Florian

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!  Looks good to me.  I'll look to commit in the next day or so.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  One minor thing I noticed was that driver_VSENSE was being set from the config file.  I think it should be possible to set that automatically from the run_current setting.  Basically, if run_current is ever such that CS would not exceed 31 when vsense is zero, then vsense should be set to zero.  That is, vsense could be thought of as another bit in CS.

-Kevin

**Comment by FHeilmann** [comment]
That can certainly be done. I had a look at the datasheet to figure out if setting vsense dynamically offers any benefits.

On the upside it gives more "robust current regulation" and finer granularity when vsense is 0, however it "nearly doubles the heat dissipation in the sense resistor" .

At least in my opinion the downsides outweigh the advantages to a point where I would even suggest hardcoding vsense to 1, partially because I am not aware of any reports of "not robust enough regulation". 

If you still would like me to go ahead I'll look into submitting another PR. 

Bests, 
Florian

**Comment by KevinOConnor** [comment]
Bleh. The trinamic specs are very confusing and filled with tons of wiz-bang marketing speak.

My read of the spec is that vsense has no impact on the current travelling though the sense resistor.  (It can't really - as the current flowing through the sense resistor is always effectively equal to the current flowing through the coils.)  What I think the spec is trying to say is that one should choose a sense resistor so that CS is equal to 31 at the maximum run_current.  One can thus choose a sense resistor with CS=31 and VSENSE=0, or with CS=31 and VSENSE=1.  Choosing a sense resistor such that CS=31/VSENSE=0 would result in a higher resistor ohms and would effective increase the heat dissipation of that sensor.  However, in this application, the sense resistor has already been chosen, and the only thing to set is VSENSE.  So, we want to choose a VSENSE that maximizes the precision of the driver.

This also leads to another subtle detail about the tmc drivers - the current levels produced by the driver is limited to 32 distinct values (63 if including plus/minus current).  So, despite all the wiz-bang features of 256 micro-steps, step interpolation, etc. the actual current sine wave produced by the driver is quantized to a relatively small number of values.  That's why it would be desirable to set vsense correctly - if the run_current is relatively small (relative to the maximum current one can select via the given sense resistor) then the quantization becomes even more coarse.

So, to take an example, with the current generic-duet2.cfg default of run_current=1.0, the ultimate CS value becomes 6 - which means that the sine wave produced by the driver would be limited to only 7 distinct levels (13 if you include plus/minus current).  Setting the vsense driver to zero would increase this to 13 distinct levels (27 if you include plus/minus current), which should make for a smoother sine wave.

-Kevin

**Pull request merged**
