### PR TITLE
Enhance and document "Jinja2" gcode templates

### PR DESCRIPTION
**Pull request by KevinOConnor**
This series improves the implementation of the Jinja2 templates and provides some basic documentation on their usage.

The `status` pseudo-variable has been renamed to `printer`.  In addition to extracting state, some modules now include callable "actions".  For example, "printer.gcode.action_respond_info()" can send a message to OctoPrint.

A "named tuple" coordinate wrapper was added as `printer.gcode.gcode_position` and `printer.toolhead.position` so that it is easier to access the current position.  For example, one can use `printer.toolhead.position.x`.

A `SET_GCODE_VARIABLE` command was added so that macros can save state for use by other macros.

Finally, a new Command_Template.md document was added with information on gcode macros and template evaluation.

@FHeilmann, @mcmatrix - FYI.

-Kevin

### CODE REVIEW

**Comment by alecplumb** [comment]
This looks good, I just have two issues:

1) Is there a need for "actions" when the same functionality could be exposed as a gcode command? For example, instead of calling the template `{ printer.gcode.action_emergency_stop() }` why not just call an `EMERGENCY_STOP` (or `M112`) gcode?

2) I found it confusing (admittedly, before this documentation existed) that expressions are delimited by `{` and `}`, instead of the jinja2 standard `{{` and `}}`. Since this documentation points to the jinja2 documentation for details, wouldn't it make more sense to use the same delimiters?

**Comment by KevinOConnor** [comment]
Thanks for reviewing.

> Is there a need for "actions" when the same functionality could be exposed as a gcode command? 
For example, instead of calling the template { printer.gcode.action_emergency_stop() } why not just call an EMERGENCY_STOP (or M112) gcode?

There's a big difference between the two in timing.  The "action" is executing at the time of evaluation, while the command is executed after any previous commands have completed.  This is particularly important when we port the menu and filament sensors - as we want an emergency stop (and similar) to execute immediately and not wait for any previous commands to complete.

> I found it confusing (admittedly, before this documentation existed) that expressions are delimited by { and }, instead of the jinja2 standard {{ and }}. Since this documentation points to the jinja2 documentation for details, wouldn't it make more sense to use the same delimiters?

We could change it over.  However, that would break compatibility with user's macros (that use the existing parameter evaluation).  Also, I expect most people will only use very simple expressions and a single brace is a little more succinct.

-Kevin

**Comment by mcmatrix** [comment]
A nice development.
I was thinking about `gcode_macro` `variables` usage for filament menu.
The unload/load filament length is different for each user.
Can these variables to be used a more generic way. Let's say that
I have made default loading/unloading menu scripts that use the variable value from users config.
```ini
[gcode_macro FILAM]
variable_unload_len: 50
variable_load_len: 50
```
but without or empty gcode, there's no point of making a macro and registering it as klippers gcode.

Maybe it's better to separate variables from `gcode_maro` and make more generic
variable module or without gcode script macro is just variable storage and not registered as gcode?

**Comment by KevinOConnor** [comment]
Thanks for reviewing.

> Maybe it's better to separate variables from gcode_maro and make more generic
variable module

FWIW, I did consider that, but my fear was that a "gcode_variable" config section could turn into a "laundry list" of "global variables".  I thought associating the variables with the macros that primarily use them might be easier to understand.  My thinking right now is to take a "wait and see" approach to get a feel for how much this feature is used and in what ways.

-Kevin

**Pull request merged**
