### PR TITLE
Refactor tmc drivers

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is a large series intended to refactor the code in tmc2130.py, tmc2208.py, tmc2660.py, and tmc5160.py.  The goal is to make it easier to support future drivers (such as the tmc2209) and to make it easier to support other types of communication methods (such as tmc5160 uart mode, tmc2208 via analog mux).

@FHeilmann , @Stephan3 - would you be able to verify that the tmc5160, tmc2660, and tmc2130 continue to work properly?

Thanks.
-Kevin

### CODE REVIEW

**Comment by FHeilmann** [comment]
I'll try to test this ASAP. One suggestion. the TMC2130 class has served as a 'helper provider to the other TMCs, but now that you're expanding on this, wouldn't it make sense to pull all of the common code out to a tmc_common.py of sorts? It feels kind of awkward to me to import something in the shape of `tmc2130.<x>` in the code of an unrelated driver.

**Comment by KevinOConnor** [comment]
Thanks.

> wouldn't it make sense to pull all of the common code out to a tmc_common.py

Yes - I was going to do just that.  However, I thought moving the code around might make bug fixing harder.  So, I figured it would be better to verify everything then make the code move.

That said, it's not totally clear to me what would go into a common location vs staying in the individual drivers.  But certainly, the FieldHelper and TMCCommandHelper code would be better off outside tmc2130.py .

-Kevin

**Comment by Stephan3** [comment]
I can test that and try bring 2209 in there. I received samples from watterott

**Comment by FHeilmann** [comment]
I ran a short test print (30m) and everything seems to work as intended.

**Comment by Arksine** [comment]
Would it make sense to move all of the trinamic drivers into their own folder, then have the user enter the type similar to the display?  It would break current configurations but it would organize the tmc driver code.

**Comment by KevinOConnor** [comment]
> Would it make sense to move all of the trinamic drivers into their own folder, then have the user enter the type similar to the display? It would break current configurations but it would organize the tmc driver code.

It's possible to do that.  It would reduce the number of files in the extras/ directory, but I'm not sure it would be much of an improvement to the tmc code itself.

-Kevin

**Comment by Stephan3** [comment]
Sorry being late. Confirmed working for TMC5160 tmc2208 and tmc2130. Sensorless homing is not tested

**Comment by KevinOConnor** [comment]
Great.  Thanks!

-Kevin

**Pull request merged**
