### PR TITLE
Adding 'dead time control' temperature control

### PR DESCRIPTION
**Pull request by akpch**
This is 'dead time control' algorithm. I used it with Repetier and loved it. This is description: https://www.repetier.com/dead-time-control/

Controlled by following parameters in the 'extruder' or 'heatbed' section:
control: deadtime
dt_deadtime: 10  #dead time in seconds as described in the link
dt_deriv_time: 0.5 #minimum poll interval, default is deadtime/10

Signed-off-by: Alexander Ka <shushera38-git@yahoo.com>

### CODE REVIEW

**Comment by hg42** [comment]
this is nice...

I actually heat my bed in two steps with a defined wait in between because the dead time isn't taken into account by the PID algorithm. At some time I actually thought about implementing an algorithm like that. I didn't know, someone already had a solution.

**Comment by akpch** [comment]
Thanks :) Given enough time PID should self-adjust as well. Perhaps we need better PID autotune routine. But this is more straightforward. BTW it works better for me when figuring out dead time on the top - after switching off the heater at the target temp, watching klippy.log helps.

**Comment by KevinOConnor** [comment]
Interesting.  FYI, I spent a lot of time back in February working on a first-order-plus-dead-time model for the heater.  I ultimately abandoned it because it was doing poorly at disturbance rejection.  That said, the automated detection of the heater gain, time constant, and dead time worked remarkably well.  I'll have to rebase the code and push it up for others to look at.  I'll also have to take a look at how this algorithm works.

That said, I'm in the process of reworking heater.py to make it a bit more flexible.  The goal is to support custom thermistors via the config file.  That will likely cause some minor conflicts with your code.  I suspect I wont be able to take a close look at this patch until next week.

Thanks,
-Kevin

**Comment by akpch** [comment]
Sure, do your changes, I will merge and re-issue later. This works well on my X5S when heatbed underpowered but bit too aggressive when there is plenty of power. I need to add anther parameter that will maintain lower heating rate once temperature is reached, same as PID_INTEGRAL_DRIVE_MAX in Repetier.

**Comment by KevinOConnor** [comment]
FYI, I pushed up my past FOPDT code - it's on the work-fopdt-20180405 branch:

cd ~/klipper ; git fetch ; git checkout origin/work-fopdt-20180405 ; sudo service klipper restart

This branch adds two features: a HEATER_CALIBRATE command, and a FOPDT heater control mechanism.

The HEATER_CALIBRATE command works similarly to PID_CALIBRATE (for example, HEATER_CALIBRATE HEATER=heater_bed TARGET=60 WRITE_FILE=1).  Be sure to only start this command when the heater is at "room temperature" (otherwise, you wont get good results).  It will run a "bump test" to the target temperature, analyze how the heater cools, and then report the FOPDT gain/time constant/delay time parameters of the heater.  If you use the WRITE_FILE=1 option you can also do some additional graphical analysis with "./scripts/fopdt.py /tmp/heattest.txt" if you want (see docs/Debugging.md for details on installing matplotlib).

The second part - the fopdt control mechanism - allows one to set "control: fopdt" in a heater section and set the appropriate gain/time_constant/delay_time instead of the pid parameters.  In my tests, this experimental control mechanism that I came up with does an excellent job of seeking to a new temperature (it doesn't overshoot or undershoot at all).  Unfortunately, it does poorly with "disturbance rejection", and ultimately I "shelved it".

I suspect the first part (heater_calibrate) will be of more interest to you.  It should come up with the same delay time (aka dead time) for your code.

-Kevin

**Comment by madejackson** [comment]
I tried to implement Dead Time as 

> Thanks - I got a chance to review the code. On the technical side, the adc_callback (now temperature_callback) needs to always call heater.set_pwm() on every invocation.
> 
> Looking a little more closely though, I think this code is basically equivalent to using the existing PID code with pid_deriv_time = dt_deriv_time, pid_kp = 255, pid_ki = 0, pid_kd = 255 * dt_dead_time. So, unless I'm missing something, it doesn't seem like we need to add additional code for this.
> 
> The reason why I say it looks equivalent is the patch basically does: `output = (projected_temp >= target_temp) then 0.0 else 1.0` which is very similar to: `output = constrain(target_temp - projected_temp, 0.0, 1.0)` putting aside the range constraint, that's: `output = target_temp - projected_temp` projected_temp is basically: `projected_temp = temp + dead_time * temp_deriv` so output is basically: `output = temp_erorr - dead_time * temp_deriv` In contrast, the pid is: `output = Kp*temp_error + Ki*temp_integ - Kd*temp_deriv` So, you can get basically the same thing by setting kp/ki/kd accordingly.

I startet years ago with repetier and Deadtime was doing its work wonderfully without tuning at all.
Later I used marlin and was never happy with PID. Now using Klipper and same. PID just isn't optimal: regular Overshooting and  inaccurate swinging +/-5°C. Dead Time in Repetier is far more accurate +/-1°C

I tried to implement Dead Time using these "settings" and failed miserably. pid_deriv_time isn't recognized by Klipper and when i disabled this line in my cfg, Temp overshot and weren't able to cooldown to desired temp at all. I'm either too dumb or this issue shouldn't be closed.

**Comment by akpch** [comment]
> I tried to implement Dead Time using these "settings" and failed miserably. pid_deriv_time isn't recognized by Klipper and when i disabled this line in my cfg, Temp overshot and weren't able to cooldown to desired temp at all. I'm either too dumb or this issue shouldn't be closed.

I just use this patch locally. But it was never ported to the latest Klipper version so not sure what will happen there.

**Comment by madejackson** [comment]
Thanks for your reply,

Kevin's solution does not work for me. See for example here:

image

Deadtime=20 -> Temp is swinging around 153-158°C when setting it to 150°C

I might try to adapt the patch to latest version.

**Comment by madejackson** [comment]
So after analyzing the site about [Dead-Time from repetier](https://www.repetier.com/dead-time-control/) it seems repetier limits the power output to 50% after initial heatup: image

Thinking back this is somewhat my experience I had with repetier in the past.

limiting klipper to 50% immediately improved the accuracy of kevin's settings:
image

**Pull request closed without merging**
