### PR TITLE
Clarifying speed variable in [probe]

### PR DESCRIPTION
**Pull request by dushyantahuja**
Clarifying that the speed variable in [probe] section affects all axes.
Signed Off: Dushyant Ahuja <dusht.ahuja@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks, but I'm not sure I understand this change.  The probe speed setting should only apply to the Z axis.

-Kevin

**Comment by dushyantahuja** [comment]
I have an extremely slow Z axis - max speed 0.5 mm/s - and when I use PROBE_CALIBRATE - the XY move to the probe position is also at 0.5mm/s - which is excruciating. And the first few times, I did not even realise that the XY axes were moving.

I looked at the code in probe.py, and it has the following:
self.speed = config.getfloat('speed', 5.0, above=0.)
self.lift_speed = config.getfloat('lift_speed', self.speed, above=0.) 


and lines 265 onwards:

        # Move the nozzle over the probe point
        curpos[0] += self.x_offset
        curpos[1] += self.y_offset
        self._move(curpos, self.speed)

This basically moves the nozzle using the probe 'speed' variable.

**Comment by GarthSnyder** [comment]
I have noticed this as well. My Z axis is pretty fast, but I have `speed` set to 2 since I've noticed that slower speeds increase the repeatability of the BLTouch. Everything works fine except that when the head shifts the nozzle over to the probe location on PROBE_CALIBRATE, it does it at speed 2.

I don't think this is a doc bug; the move code that @dushyantahuja cited above should be using `lift_speed` instead of `self.speed`. Immediately before this move is the Z retraction, so this move is guaranteed to be an XY-only move.

**Comment by KevinOConnor** [comment]
Ah, I understand now.  Yes - this looks like something to be addressed in PROBE_CALIBRATE instead of in the [probe] documentation.

-Kevin

**Comment by dushyantahuja** [comment]
What's the difference between speed and lift_speed in that case? Do we
still need two variables?

**Comment by ld3300** [comment]
It looks to me like the code is right, I think your documentation addition is correct.  Does setting a speed and a lift speed make a difference on your machine?

**Comment by KevinOConnor** [comment]
The `speed` parameter is intended to be the descent speed when probing, the `lift_speed` parameter is intended to be the speed of upward movement during multi-sampling.  Neither parameter is intended to be used for XY movement - the PROBE_CALIBRATE command just happens to be using the `speed` parameter for this because it didn't have another speed available to it.  I'd say we should document this as a quirk of PROBE_CALIBRATE and possibly add an explicit speed parameter to that command.

-Kevin

**Comment by dushyantahuja** [comment]
Sounds good - I can modify the pull request. In PROBE_CALIBRATE, can we
move the XY using the default XY speed instead?
------------------
Dushyant Ahuja

**Pull request closed without merging**
