### PR TITLE
Add support for BMP280 and BME680 sensors

### PR DESCRIPTION
**Pull request by 1am3r**
This adds support for BMP280 and BME680 sensor ICs,
along with fixing calibration data readout for BME280.

Gas sensor readout for the BME680 is just the raw compensated value.
To get actual meaningful values, more research is needed.

Signed-off-by: Michael Kurz <michi.kurz@gmail.com>

### CODE REVIEW

**Comment by Arksine** [comment]
After looking close, it does look like I had an error in H5 where I'm taking the wrong bits from address 0xE5 that you corrected.  However I think your change to H1 is incorrect.  H1 should be assigned to address 0xA1 and you have it assigned to 0x88.

**Comment by 1am3r** [comment]
You're totally right. You have no idea how often I looked over these values and still got it wrong. Thanks, I'll correct it.

I should have done the readout fix in a different commit to make it easier to review, totally forgot it. Sorry.

**Comment by KevinOConnor** [comment]
Thanks.  It looks good to me.  One thing I noticed is that docs/Command_Templates.md should be updated.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by Larbaco** [comment]
so...
Can you add support for the BMP180 too?

here is the datasheet: https://cdn-shop.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf
here is some python implementation: https://github.com/m-rtijn/bmp180/blob/master/bmp180/bmp180.py
Here is some C implementation: https://github.com/SMFSW/arm_i2c_drivers/blob/master/BMP180.h

**Pull request merged**
