### PR TITLE
Added Anycubic 4Max printer config files with and without BLTouch sen…

### PR DESCRIPTION
**Pull request by Montbel**
Added a default config file for the Anycubic 4Max with BLTouch.
Added a default config file for the stock Anycbic4Max.

Signed-off-by: Christian Toulon christian@bouncy-studio.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks good.  A few things minor things would help though:
- The comments at the top of the file should specify what type of micro-controller to compile for.  Does this printer use the atmega2560?
- The max_extrude_cross_section should not be specified in an example config - it's a sanity check that should not be disabled by an example config.
- it would be great to add these new configs to test/klippy/printers.test 

I can make the above changes if you wish.

-Kevin

**Comment by Montbel** [comment]
Hi Kevin,

Thanks for your message.

> Le 21 mars 2019 à 17:19, KevinOConnor <notifications@github.com> a écrit :
> 
> Thanks. In general it looks good. A few things minor things would help though:
> 
> The comments at the top of the file should specify what type of micro-controller to compile for. Does this printer use the atmega2560?
> The max_extrude_cross_section should not be specified in an example config - it's a sanity check that should not be disabled by an example config.
> it would be great to add these new configs to test/klippy/printers.test
> I can make the above changes if you wish.
> 
Yes please :-)

Thanks tor this great piece of software, it has changed my printer to a new hi precision one.

Best regards,

Christian

**Comment by KevinOConnor** [comment]
Okay, thanks.  I made the config look more like the other configs and committed it (commit 5bcf9f02).  It didn't look like the bltouch config was a "stock" config, so I did not commit that (we currently only commit stock configs to the config/ directory).  Also, using hardware pwm can cause bad effects on many fans and it should not be needed except in some rare cases - can you confirm everything works okay with the normal pwm setup?

-Kevin

**Comment by Montbel** [comment]
> Okay, thanks. I made the config look more like the other configs and committed it (commit 5bcf9f0 <https://github.com/KevinOConnor/klipper/commit/5bcf9f02cf5c307eb4a323dcf4c21b1ac9d22d67>). It didn't look like the bltouch config was a "stock" config, so I did not commit that (we currently only commit stock configs to the config/ directory). Also, using hardware pwm can cause bad effects on many fans and it should not be needed except in some rare cases - can you confirm everything works okay with the normal pwm setup?

You’re right, the BLTouch is not a stock config.

Yes, everything works OK with the normal PWM setup.

**Comment by TheMunkee** [comment]
When I tried running Klipper on my 4max I couldn’t get the extruder to run slower. I couldn’t figure it out and I reflashed marlin back on to use while I figured it out. I’m hopping I can try your settings and see if that works. I am also about to install a BLTouch sensor in mine as well. Where can I find this config file of yours to try out?

**Comment by Montbel** [comment]
Hi TheMunkee,
you can find mu config for the 4Max with BLTouch here 
https://github.com/Montbel/klipper
in the config folder.
And the support for the BLTouch here
https://www.thingiverse.com/thing:3461356
Regards

**Comment by TheMunkee** [comment]
Beautiful! Thank you! One more question for 4Max users. How do you implement a tmc2208 upgrade on Klipper and does anyone have any info on UART on our trigorilla board? All I see is people doing legacy mode and people doing UART have boards with available AUX1 that we don’t have. Can you still control the chips through UART with Klipper even?

**Comment by Montbel** [comment]
Right now I use the Legacy mode and did not yet dug into connecting the TMC2208 through UART.

**Comment by TheMunkee** [comment]
Hmm. Ok. And that did do a lot for the sound? So you just plugged them in and that’s it?

**Comment by Montbel** [comment]
It did a lot for the sound ! I also changed all the fans as they became the noisiest after the driver change.
I followed this tutorial (for i3 mega but it's the same board)
https://www.youtube.com/watch?v=QP8dZ8cUEBA
An interesting thing is how he changes the orientation of the motor connectors.

**Comment by TheMunkee** [comment]
Is there a way to reverse the direction of the stepper motors in software like in marlin? How did you connect your bl touch exactly?

**Comment by Montbel** [comment]
I did reverse the motors by turning the connectors on the motherboard.

You can see how I connected the BLTouch on my thingiverse page :

https://www.thingiverse.com/thing:3461356

Basically I connected the servo of the BLTouch to the only servo port (3 wires) on the board that has headers and the switch (2 wires) on the Z-  limit switch header (removing the existing plugs to the stock Z- switch)

See photo on the link above.

Regards

**Comment by TheMunkee** [comment]
I noticed the PID section is missing in the extruder part of the config file. Is that on purpose? Should I be doing something different than the stock example config parameters?

**Comment by TheMunkee** [comment]
And in the bed section. I thought “control:” needed to be specified. Either watermark or PID.

**Comment by TheMunkee** [comment]
Sorry... I should have read the whole thing. I see it all at the end.  If I do have one more question. I see you added a fan to the stepper motor for the extruder. It said you connected it to Arduino pin 44. Where is that located physically on the board. I guess what I’m asking is how did you wire up that fan?

**Comment by Montbel** [comment]
I did not added the fan, I just replaced the stock one with a quitter one.
For the wiring refer to this link :https://www.thingiverse.com/thing:2931772
The one you are looking for is "Cooling block fan" on the hand drawn schematic.

**Comment by TheMunkee** [comment]
Thank you very much! You have been a lot of help. I now have everything working except for the bltouch. I’ve got the machine printing though and that is a huge improvement in and of itself. 

I guess there are different versions of the sensor and some are slightly longer. I think I have the V2 and the mount you recommended has the sensor to close to the bed and it seems to crash on the  X axis. I think I’m going to try design one that holds it between the cooling fan and extruder or something

**Comment by Montbel** [comment]
Great if your printer works correctly. 
About the BLtouch, I own a genuine V2 (I guess) with a plastic needle. I too had to modify the support as my bltouch was also too low. Maybe the throat holding the heat bloc of your printer is shorter than mine. Mine is 40mm long and the z offset is about 1,5 mm. 

--
Christian Toulon
christian@toulon.cx
"Le bonheur n'est réel que s'il est partagé."

**Pull request closed without merging**
