### PR TITLE
[WIP] Add sam4e8e port based on ATMEL ASF 3.40

### PR DESCRIPTION
**Pull request by FHeilmann**
This is my attempt at porting klipper to the SAM4E8E MCU that is used on the Duet Wifi and Duet Ethernet series. It is based on the ATMEL ASF 3.40 framework which provides some nice, zero overhead abstractions which made this port a lot easier. I stripped the ASF (50k files) back to the files that are needed for this port+ the files that should be useful when adding other MCUs supported by the ASF (once this is merged I'll submit another pull request to migrate the SAM3X8E port over to the ASF too).

Unfortunately in my testing the port hasn't been 100% stable (maybe because doing sudo service klipper restart a lot is not so good) so I'm posting this as WIP for other people to test and give suggestions and feedback on how to improve it.

Those of you who want to use this port on a Duet wifi/Ethernet be advised that the support for the TMC2660 stepper drivers is also needed (I'll submit a PR for them shortly). Otherwise the drivers won't power up and nothing will move.

This port also requires a newer version of bossac to flash the duet. It can be installed using the following commands (assuming octopi and a standard klipper installation):

```
sudo apt-get install build-essential usbutils
git clone https://github.com/shumatech/BOSSA.git ~/klipper/tools/bossa
cd klipper/tools/bossa
make bin/bossac
```
should give a few errors about wx-config not being available but it should compile. To flash press the "erase" button on your duet, connect it to the rpi and execute 

```
make flash FLASH_DEVICE=/dev/ttyACM0
```
sometimes the duet switches to /dev/ttyACM1 so if flashing fails using above command, try using ACM1 instead.

Finally, keep in mind that this is WIP and very much beta, so don't use this for any production stuff as it might contain critical bugs.

Finally I want to thank andreq and Maglin for the support and help with this port. Also huge thanks to pminnieur for supplying a board I could use to test.

Signed-off-by: Florian Heilmann <Florian.Heilmann@gmx.net>

### CODE REVIEW

**Comment by FHeilmann** [comment]
@KevinOConnor if you want to review the PR more easily I can split it into two. One adding the ASF, the other adding the actual port.

**Comment by KevinOConnor** [comment]
Have you been able to find anything stating the ASF license is compatible with the GNU GPL?  I haven't been able to find anything in my searches.  I fear it may not be compatible (specifically the "you may use Microchip software and any derivatives exclusively with Microchip products" statement seems problematic).

Ugh - I hate the "license of the week" methodology that some embedded chip companies like to promote.  :-(

-Kevin

**Comment by KevinOConnor** [comment]
Well, we can ask @dc42 if he knows of any documents regarding GNU GPL and Atmel ASF license compatibility.  You could also ask Atmel/Microchip if they can point to a public statement on it.

My fear is that the statement "you may use Microchip software and any derivatives exclusively with Microchip products" (or the similar "This software may only be redistributed and used in connection with an   Atmel microcontroller product") is not compatible with the GNU GPL.

-Kevin

**Comment by FHeilmann** [comment]
Save for the last bit the license seems to be the 3 clause BSD license which according to here

https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility

Is GPL compatible. I'll get in touch with atmel and ask for a comment.

**Comment by KevinOConnor** [comment]
FYI, I found that microchip has the CMSIS files for the SAM4 (as well as SAM3) available with a reasonable license (Apache 2.0) at: http://packs.download.atmel.com/  (The atpack files are just zip files.)

I also noticed that the SAM3 peripherals are almost identical to the SAM4 peripherals (with the exception of USB).  I suspect a good portion of the code could be shared between SAM3 and SAM4.

The current Klipper SAM3 code is based on just the CMSIS files.  Is there something that ASF has that we need?  (Granted, USB is a pain, but the SAM4 USB controller looks pretty sane and a driver could be written to leverage the src/generic/usb_cdc.c code..)

-Kevin

**Comment by FHeilmann** [comment]
If I'll end up not being able to get a statement from Microchips legal department that will be the way to go, and likely the route I'll further pursue. Aside from the simplicity, an advantage of the ASF would be that porting klipper to any Atmel MCU would become very easy once the SAM4 port is merged.

**Comment by dc42** [comment]
1. FWIW the library used in the Arduino Due core sources at https://github.com/arduino/ArduinoCore-sam/tree/master/system/libsam/source appears to be based on the ASF.
2. Yes the SAM4 peripherals are mostly similar to the SAM3 peripherals. The main differences are:
- SAM3X has USB OTG, SAM4E/4S have device mode USB
- The SAM4E has two Analog Front Ends (AFEs) instead of ADCs. The SAM4S has ADCs like the SAM3X.
- The timers on the SAM4S are 16 bits wide. The timers on the SAM4E and SAM3X are 32-bits wide.
- The SAM4E has a cache and a single-precision FPU. The SAM3X and SAM4S have neither.
There are of course also differences in how many of each peripheral unit is present and which devices have a PDC.

HTH David

**Comment by FHeilmann** [comment]
So I filed a support ticket with Microchip and they replied, however, I still have the open question with them whether I am allowed to make their statement public. @KevinOConnor how do you want to go about this once I get confirmation from them to publicize the statement?

In other news, the port is giving me a hard time. One night it was working flawlessly, one night later, without making any changes, the communication with the MCU times out as soon as I attempt to go faster than F9000.

This is, thus, not ready for prime-time yet.

**Comment by KevinOConnor** [comment]
> So I filed a support ticket with Microchip and they replied, however, I still have the open question with them whether I am allowed to make their statement public. @KevinOConnor how do you want to go about this once I get confirmation from them to publicize the statement?

Well, that depends on what the statement is.  :-)  But, assuming all is well, it would be good to support the SAM4.  I think we'll need to make sure everything is stable before merging to the main branch though.

> In other news, the port is giving me a hard time. One night it was working flawlessly, one night later, without making any changes, the communication with the MCU times out as soon as I attempt to go faster than F9000.

Is this with USB or with serial?  Do you have the ability to communicate via serial?

-Kevin

**Comment by KevinOConnor** [comment]
@FHeilmann - while we're waiting on a public statement, could you send me an email (kevin@koconnor.net) so I can get a heads up?

Thanks,
-Kevin

**Comment by FHeilmann** [comment]
eMail sent. Regarding your question: This is via USB serial, as the SAM4 implements serial over USB I haven't really bothered to bring up the legacy serial yet, but I can do so if you think that could solve the problem.

**Comment by hg42** [comment]
> MCU times out as soon as I attempt to go faster than F9000

F9000 sounds like my experience with the lpc1768 port from cruwaller.

This was solved by Kevin's reimplementation of the USB serial.

**Comment by FHeilmann** [comment]
@hg42 thanks for the input, what bugs me is that I was able to easily achieve F42000 the other day ^^ I'll look into getting regular serial up and running, lets see how that goes.

**Comment by FHeilmann** [comment]
Closing this for now, the ASF license just doesn't work with GPLv3 so I'll have to remove it.

**Pull request closed without merging**
