### PR TITLE
Support M73-indicated progress as an extra

### PR DESCRIPTION
**Pull request by FeepingCreature**
Record M73 progress, display on ST7920 LCD, as well as linear estimate for time remaining.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Is it better to handle this in gcode.py directly?

**Comment by KevinOConnor** [comment]
Thanks.  One thing I noticed is that the "time" module should not be pulled in (timing has special requirements in Klipper - there's some info on this in the docs/Code_Overview.md file) - in any case, the method already has the eventtime variable which can be used in its place.

One hurdle to using this is the fact that M73 is not a commonly produced command.  In general, I have a preference to implement "extended" human-readable commands over legacy g-code commands (eg, "SET_PROGRESS PERCENT=... TIME_REMAINING=...").  Perhaps you could work with @mmone to get his Klipper plugin to produce regular progress updates?  As for where to implement the command - I'd prefer not to put it in gcode.py, but adding it directly to display.py is fine.

Other minor comments:
- would be nice if the hd47780 display was also updated
- might be simpler to write the "-" to the screen before calling draw_time() and thus avoid having to modify draw_time()

-Kevin

**Comment by FeepingCreature** [comment]
As far as I can tell, M73 is rare because most plugins use M117 to set progress messages. (Which is worthless for progress bar/ETA purposes.) However, both Octoprint and Cura have M73 plugins, so I'm not sure how a SET_PROGRESS command could be implemented. (TIME_REMAINING is definitely printer settings dependent? It makes sense for Octoprint but not Cura.)

**Comment by FeepingCreature** [comment]
* time module removed
* extra removed, command handling moved into display
* "-" printed separately

**Comment by KevinOConnor** [comment]
Okay, thanks.  Would be great to see HD44780 support and a human readable version of M73 (in addition to M73 if you wish) in the future.  I have an HD44780 display, so can run some quick tests if you want.

**Pull request merged**
