### PR TITLE
controller_fan: Add support for a fan cooling the controller-board

### PR DESCRIPTION
**Pull request by Master92**
Whenever a stepper driver or a heater becomes active, it is desirable to turn on a fan cooling the associated parts on the controller board. This module implements such a functionality that turns on a fan whenever a stepper or specified heater turns on, decelerates it to a configurable speed when all of the watched parts turn off, and returns to an off-speed, when a user-defined timeout is met.

As discussed in #1065 

Signed-off-by: Nils Friedchen <Nils.Friedchen@googlemail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me.  One question though - how is the shutdown_speed supposed to work?  If I'm reading the code correctly, it looks like it sets the fan speed to shutdown_speed after the idle timeout - shouldn't it just turn the fan off?

-Kevin

**Comment by Master92** [comment]
Yep, that's the way it works. I use that parameter because I practically derived my module from the fan module and you can configure that parameter there.
As the default for shutdown_speed is 0 it practically simply turns the fan off after the idle_timeout - at least if you don't configure it to anything else.

-Nils

**Comment by KevinOConnor** [comment]
The shutdown_speed sets the fan speed when the micro-controller software goes into an error state.  The intent is to allow one to turn on fans in the event of a failure (for example, a heater malfunction).  I think you want to use 0 for the off speed.

-Kevin

**Comment by Master92** [comment]
Okay I'll do that change later this day then.

-Nils

**Comment by KevinOConnor** [comment]
Looks good to me.  If there are no further comments I'll commit in the next few days.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, the printer_state() method was just recently removed (it was replaced with registered event callbacks).  I can update the code if you wish, but it'll take me a few days to get to it.

-Kevin

**Comment by Master92** [comment]
Oh, thanks for the hint! I suppose you now have to call the MCU's register_config_callback() with a callable that sets up the module as soon as the printer is ready? If this is true, I will convert the module myself so that you can concentrate on more important tasks.

-Nils

**Comment by Master92** [comment]
Alright, I found the commit where you introduced the change. I will make the necessary changes tomorrow and push them to this pull request.

-Nils

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by lmcbmai** [comment]
I upgraded to the latest version but it did not work with [controller_fan] settings.

When entire [controller_fan] section is commented out Klipper service loads without issues and Octoprint shows Ready state. As soon as I add [controller_fan] section and restart Klipper the last part of the log shows this:
`Starting serial connect
Loaded MCU 'mcu' 77 commands (v0.7.0-85-g32632c8-20190110_200246-VERTEX-H / gcc: (GCC) 5.4.0 binutils: (GNU Binutils) 2.26.20160125)
MCU 'mcu' config: RECEIVE_WINDOW=192 SOFT_PWM_MAX=256 STEP_DELAY=0 SERIAL_BAUD=250000 ADC_MAX=1023 PWM_MAX=255 CLOCK_FREQ=16000000 MCU=atmega2560 STATS_SUMSQ_BASE=256
MCU error during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 136, in _connect
    cb()
  File "/home/pi/klipper/klippy/mcu.py", line 631, in _connect
    self._check_config()
  File "/home/pi/klipper/klippy/mcu.py", line 589, in _check_config
    self._name,))
error: Failed automated reset of MCU 'mcu'
Failed automated reset of MCU 'mcu'
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

Failed automated reset of MCU 'mcu'
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer`

My [controller_fan] section contains the following line. I tried to comment them out from bottom up one-by-one to check if a particular setting in this section is causing troubles, but the result did not change.

`[controller_fan]
pin: PE4
max_power: 0.8
shutdown_speed: 0
cycle_time: 0.010
hardware_pwm: False
kick_start_time: 0.100
idle_timeout: 30
idle_speed: 0.8
heater: stepper_x,stepper_y,stepper_z,extruder`

Right now I have the latest code running with entire [controller_fan] section commented out. 
I'd be glad to assist with further testing, in needed.

Thanks
Best regards,
Boris

**Comment by jakep82** [comment]
You aren't supposed to call out steppers in your list of heaters. The default is extruder, so you don't need that line at all, and any steppers will activate the fan by default. You don't need to define them anywhere.

**Comment by Master92** [comment]
Strange, I tried to replicate your error but wasn't able to. Maybe you have a duplicate pin? Could you please send your printer.cfg or klippy.log?

It is sure annoying that the printer won't work with an incorrect config but as this is the case with almost all other modules too, I will not edit this one to accept a stepper as a heater. In any case this is definitely not true.

-Nils

**Comment by lmcbmai** [comment]
Pasting my printer.cfg below. Please note that until today's upgrade I used pin PE4 in section [static_digital_output my_output_pins]. Prior to reassigning it to [controller_fan], I commented out entire [static_digital_output my_output_pins].
`
# This file serves as documentation for config parameters of corexy
# style printers. One may copy and edit this file to configure a new
# corexy printer. Only parameters unique to corexy printers are
# described here - see the "example.cfg" file for description of
# common config parameters.

# DO NOT COPY THIS FILE WITHOUT CAREFULLY READING AND UPDATING IT
# FIRST. Incorrectly configured parameters may cause damage.

# The stepper_x section is used to describe the X axis as well as the
# stepper controlling the X+Y movement.
[stepper_x]
step_pin: PF0
dir_pin: PF1
enable_pin: !PD7
step_distance: .00625
endstop_pin: ^!PE5
position_endstop: 206
position_max: 206
homing_speed: 60

# The stepper_y section is used to describe the Y axis as well as the
# stepper controlling the X-Y movement.
[stepper_y]
step_pin: PF6
dir_pin: PF7
enable_pin: !PF2
step_distance: .00625
endstop_pin: ^!PJ1
position_endstop: 208
position_max: 208
homing_speed: 60

[stepper_z]
step_pin: PL3
dir_pin: !PL1
enable_pin: !PK1
step_distance: .000234375
endstop_pin: ^!PD3
position_endstop: 0
position_max: 194

[extruder]
step_pin: PA4
dir_pin: PA6
enable_pin: !PA2
step_distance: .00666667
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PB4
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PK5
control: pid
pid_Kp=29.496 
pid_Ki=1.478 
pid_Kd=147.111
min_temp: 0
max_temp: 270

# [extruder1]
# step_pin: PC5
# dir_pin: PC3
# enable_pin: !PC7
# step_distance: .00666667
# nozzle_diameter: 0.400
# filament_diameter: 1.750
# heater_pin: PB5
# sensor_type: EPCOS 100K B57560G104F
# sensor_pin: PK7
# control: pid
# pid_Kp: 63.0
# pid_Ki: 2.25
# pid_Kd: 440
# min_temp: 0
# max_temp: 270

[heater_bed]
heater_pin: PH6
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PK6
control: watermark
control: pid
pid_Kp=72.090 
pid_Ki=1.663 
pid_Kd=781.275
min_temp: 0
max_temp: 120

[fan]
pin: PH5
max_power: 0.44

#[controller_fan]
# pin: PE4
# max_power: 0.8
# shutdown_speed: 0
# cycle_time: 0.010
# hardware_pwm: False
# kick_start_time: 0.100
# idle_timeout: 30
# idle_speed: 0.8
# heater: stepper_x,stepper_y,stepper_z,extruder

#[static_digital_output my_output_pins]
# pins: PE4

[mcu]
serial: /dev/ttyUSB0
# pin_map: arduino

[printer]
kinematics: corexy
#   This option must be "corexy" for corexy printers.
max_velocity: 300
max_accel: 3000
max_z_velocity: 25
max_z_accel: 30

[display]
lcd_type: hd44780
rs_pin: PA5
e_pin: PA7
d4_pin: PC0 
d5_pin: PC2 
d6_pin: PC4
d7_pin: PC6
click_pin: ^!PA1
encoder_pins: ^PH1, ^PH0
`

**Comment by Master92** [comment]
Huh, I'm very sorry but I do not find any error in that config. Maybe @KevinOConnor can help in that case because I also can't find any directly controller_fan-related error message in the log you posted an hour ago.

Last idea: Comment in only the first two lines of the controller_fan (take care of preceding blanks), issue a FIRMWARE_RESTART, power cycle your mcu and restart the klipper service. What's the last lines of your logfile after that procedure?

-Nils

**Comment by lmcbmai** [comment]
Just tried, no difference. Log file contains exactly the same as I've pasted earlier followed by countless number of the following entries that keep coming.

``
got {'#receive_time': 166.285173478, u'next_clock': 2610400000L, u'oid': 5, u'value': 7850, '#name': u'analog_in_state', '#sent_time': 166.152151551}
got {'#receive_time': 166.38091701899998, u'next_clock': 2612000000L, u'oid': 15, u'value': 7849, '#name': u'analog_in_state', '#sent_time': 166.152151551}
got {'#receive_time': 166.57242103, u'next_clock': 2615200000L, u'oid': 5, u'value': 7854, '#name': u'analog_in_state', '#sent_time': 166.152151551}
got {'#receive_time': 166.684528998, u'next_clock': 2616800000L, u'oid': 15, u'value': 7842, '#name': u'analog_in_state', '#sent_time': 166.152151551}
got {'#receive_time': 166.877289623, u'next_clock': 2620000000L, u'oid': 5, u'value': 7840, '#name': u'analog_in_state', '#sent_time': 166.152151551}
``

**Comment by lmcbmai** [comment]
When I comment in just [controller_fan] with nothing under it, I get this error:

``
root@VERTEX-H:/home/pi# tail -f  /tmp/klippy.log
    self.fan = fan.PrinterFan(config)
  File "/home/pi/klipper/klippy/extras/fan.py", line 16, in __init__
    self.mcu_fan = ppins.setup_pin('pwm', config.get('pin'))
  File "/home/pi/klipper/klippy/configfile.py", line 53, in get
    return self._get_wrapper(self.fileconfig.get, option, default)
  File "/home/pi/klipper/klippy/configfile.py", line 31, in _get_wrapper
    v = parser(self.section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'pin' in section: 'controller_fan'
``

**Comment by Master92** [comment]
No, I'm sorry, I really can't find any error explicitly caused by my module as the line referenced by the error message points to a "klippy:connect" line. This state however is never used by my module. I am really sorry that using this gets you in trouble!

Maybe it would be best if you opened an issue explaining this so that others can find a solution more easily. However I will certainly look deeper into this this weekend and will report if when I found a solution.

-Nils

**Comment by lmcbmai** [comment]
No worries, Nils. My setup is one of a kind. I converted Velleman Vertex K8400 printer into H-bot and switched from Marlin to Klipper. Nevertheless my design is posted on Thingiverse https://www.thingiverse.com/thing:3145721  I've not heard from anyone attempting to do the same.

K8400 has controller board shown here https://www.velleman.eu/products/view/?id=430954 that is described in Marlin firmware as "derived from 3Drag Controller". I have the schematics of the board and had no problem mapping pins in printer.cfg Here it is:
k8400-mainboard_schematic

Let's wait and see if somebody else reports similar issue. On my side - I will try to "play" with settings and study the code. I was software developer back in 90's and this can be a good chance to refresh my memories :) It will also help me better understand Klipper's inter-workings. I will report back if I find the cause.

Many thanks for your time and support.
Best regards,
Boris

**Comment by lmcbmai** [comment]
Hi Nils,

I have good news, bad news
- Good news is that from this morning Klipper started to work normally with  [controller_fan] section in configuration file.
- The bad news is - I did not do anything differently. Just powered printer on and was planning to start troubleshooting this issue. So, we still don't know what was causing it. 

I ended up using the following configuration:
```
[controller_fan]
pin: PE4
max_power: 0.8
shutdown_speed: 0
cycle_time: 0.010
hardware_pwm: False
kick_start_time: 0.100
idle_timeout: 60
idle_speed: 0.8
heater: extruder,heater_bed
```
I also reduced idle timeout to 60 seconds, otherwise fan was remaining on for 6min (300sec + 60sec) after the last motor movement. 
```
[idle_timeout]
timeout: 60
```
Now it goes off after 2 minutes, which is 1 minute longer than original behavior, but that's fine. 

I think we can mark this issue as resolved.

Thanks
Best regards,
Boris

**Comment by lmcbmai** [comment]
Quick update: Setting up idle_timeout to 60 seconds does not play well when I need to enable heater for changing filaments between prints, clean the nozzle or heat the bed prior to leveling. All heaters go off in 1 minute, way before reaching target temperatures. Ended up reverting idle_timeout to default 5 minutes. :(

-b

**Comment by kakou-fr** [comment]
I tried the controller_fan section, with : 
```
heater: stepper_x,stepper_y,stepper_z,extruder
```
I have this error : 
`Unhandled exception during ready callback
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 160, in _connect
    cb()
  File "/home/pi/klipper-stable/klippy/extras/controller_fan.py", line 27, in handle_ready
    for n in self.heater_name.split(',')]
  File "/home/pi/klipper-stable/klippy/heater.py", line 258, in lookup_heater
    "Unknown heater '%s'" % (heater_name,))
Error: Unknown heater 'stepper_x'`

**Comment by corrado-c** [comment]
Hello @lmcbmai  ! sorry for the intrusion, but I wanted to recover and modify a double extruder 3drag, so black card, and I think it is the corresponding VM8400MB. In the configuration files I find only 8200 or 8800 I was going to abandon everything until I found this !!! fantastic! I'll try your cfg file right away!
thank you!!!!!



Have other changes been made during this time?

**Comment by lmcbmai** [comment]
Hi @corrado-c,
Back in early 2019 when I posted here I was testing Klipper and after about a month of trying decided to move on and using Repetier since. Those old versions of Klipper had some kind of issue when Raspberry PI and mainboard would often go out of sync (at least in my setup) that would cause print failure.  3 years have passed and I cannot recall the exact error message. I'm sure it is fixed by now and Klipper is much more reliable. I am hoping to try it again one day, but for the last 3 years my both printers run Repetier with no issues and I don't want to mess up with them at the moment.
Thanks

**Comment by corrado-c** [comment]
i am playing with K8400 card, everything seemed ok but i noticed a problem:
if I turn on the K8400 board but Raspberry is turned off or somehow disconnected or does not communicate, the bed heats up. So somehow the PH6 pin stays high, (it also happens with PH6 and PE4 but they are fans and that's okay).
All right when Klipper tells the MCU to turn it off, the platter is off and the fans on.
P.S. as it seems to me that there is no official documentation for this card I wrote here ... sorry if I'm wrong.

**Pull request merged**
