### PR TITLE
[WIP] morgan_scara: Initial support for RepRap Morgan style SCARA printers

### PR DESCRIPTION
**Pull request by noahwilliamsson**
Is this something that would be of interest to this project (or those in #154)?  I have [something](https://i.imgur.com/sqqJlaG.jpg) resembling a [RepRap Morgan](https://reprap.org/wiki/RepRap_Morgan),  a four-bar linkage with two rockers sharing a common Z axis, which is what this code supports.

Other SCARA variants like those with five-bar linkages (e.g. [RepRap Wally](https://www.youtube.com/watch?v=iVg7WrgHJik)) or those like [RepRap Helios](https://www.youtube.com/watch?v=CJ2F-YjHe2k) are not supported.

Not yet implemented:

- end stops (so arm rotation is not limited)
- homing (position manually and use overrides)

Also, I couldn't figure out if I was supposed to use `PrinterRail` or `PrinterStepper` when neither of the two steppers "own" an axis, so I went with the latter.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks useful to me.

The main distinction between a PrinterRail and a PrinterStepper is that a PrinterRail has an endstop associated with it.  So, as I understand it, a "morgan reprap" would use PrinterRails.

FYI, we do ask that the Signed-off-by line contains your full name.  The copyright notices should also.

Let me know if you need any assistance with the remaining items.

-Kevin

**Comment by KevinOConnor** [comment]
Any updates on this?  Is this something I can help with?

-Kevin

**Comment by Chleba** [comment]
I have MPScara with RAMPS 1.4 on Arduino Mega, so I could test something for you guys. I'm just not familiar with Klipper, but I have some time to do some testing.

**Comment by klHaribo** [comment]
This kinematic is very Interimsring to me too.
I saw the arm length in the printer section. So different arm length will be  Impossible to calibrate?

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive.  As mentioned above (and in #154) let me know if I can help.

-Kevin

**Pull request closed without merging**
