### PR TITLE
Update anycubic-i3-mega-2017.cfg

### PR DESCRIPTION
**Pull request by bartolomeus**
- I changed the hotend and heated bed sensors. These are now the same as defined in Marlin source code for the i3 Mega.
- Added mintemp for the extruder.
- Changed heat bed control to PID and added the PID tune results from Klipper.
- Changed the PID tune results of the hotend. These results are from using Klipper.
- Raised max z accel from 10 to 60

### CODE REVIEW

**Comment by KevinOConnor** [comment]
In order to directly take a pull request the commit message must have a signed-off-by line as described in docs/CONTRIBUTING.md .

@dgz - can you comment on these changes?

**Comment by KevinOConnor** [comment]
Sorry - meant for @mjedlinski to review the changes.

**Comment by mjedlinski** [comment]
Looks OK to me.
My PIDs are different:
Hotend:
pid_Kp: 21.188
pid_Ki: 0.872
pid_Kd: 128.719

Bed:
pid_Kp: 74.248
pid_Ki: 2.097
pid_Kd: 657.094

**Comment by mjedlinski** [comment]
@bartolomeus we are both forgot something.
Can You add this to Yours PR ?

[pwm_output stepstick_fan]
pin: ar7
value: 1

**Comment by bartolomeus** [comment]
@mjedlinski I don't see any reference to that setting, What does it do?

**Comment by mjedlinski** [comment]
Anycubic have stepstick fan connected to trigorilla fan1 port (pin ar7).Above setting enables this fan.

**Comment by KevinOConnor** [comment]
Okay, thanks. I updated the config with just the heater settings (commit 7a11b78f).  For the "stepstick fan" can a heater_fan be used instead (eg, [heater_fan stepstick_fan] pin: ar7)?

**Comment by mjedlinski** [comment]
You're right. It's better idea. You can add "heater: 150.0" too. Stepstick fan wont engage to soon and don't stay turn on longer than needed.

**Comment by KevinOConnor** [comment]
Okay - I added the stepstick fan definition (commit 1b3ef8a8).  I didn't bother optimizing it with a particular temperature as I think users can do that themselves if they wish.

**Pull request closed without merging**
