### PR TITLE
Add M119 command, an alias to QUERY_ENDSTOPS to docs

### PR DESCRIPTION
**Pull request by ysoldak**
Fixes: #441 

It says QUERY_ENDSTOPS is an alias for M119, while in code it is vice-versa.
Still, for docs it seems to better this way, since people are used to MXXX commands first.

Signed-off-by: Yurii Soldak <ysoldak@gmail.com>

### CODE REVIEW

**Comment by hg42** [comment]
the gcode commands usually provide only subsets of the named commands.
E.g. M204 only sets one parameter of SET_VELOCITY_LIMIT.
Here it is an alias, but this could change, if QUERY_ENDSTOPS would be extended.
So my opinion is M119 should reference QUERY_ENDSTOPS, not vice versa.

**Comment by ysoldak** [comment]
Well, in that case the doc can be changed later, as the functionality changes.
Now (with this change) it reflects the current state.

I do feel a bit bad documentation names aliases backwards, it follows the structure of the document though.

Feel free to reject/close the PR, I have no hard feelings about it, this is just docs.

**Comment by hg42** [comment]
this is only my opinion, Kevin will decide

**Comment by hg42** [comment]
on a quick look, there no other references between named commands and gcodes.
I also think it's not necessary. The gcodes will usually follow the standards and it doesn't matter if they are implemented.

**Comment by KevinOConnor** [comment]
On Fri, Jun 29, 2018 at 04:10:44AM -0700, Yurii Soldak wrote:
> It says QUERY_ENDSTOPS is an alias for M119, while in code it is vice-versa.
> Still, for docs it seems to better this way, since people are used to MXXX commands first.

Thanks.  The reason I did not document M119 (nor M206) is that I view
the traditional g-code commands (eg, M123) only as a means of
supporting common 3rd party software (eg, OctoPrint, Printrun, Slic3r,
Cura, etc.) in their standard configurations.  To the best of my
knowledge, no popular software automatically produces M119 (nor M206).
I'd prefer the use of QUERY_ENDSTOPS (and SET_GCODE_OFFSET).

That said, I can see where it would be confusing to have commands
available that aren't in the documentation.  I guess we should update
the documentation to say that these commands are available, but the
alternatives should be preferred.

-Kevin

**Comment by ysoldak** [comment]
Thanks, @KevinOConnor 
Makes sense, and this sort of knowledge, design decisions, is valuable and nice to have in docs.

**Comment by hg42** [comment]
@KevinOConnor 
> I view the traditional g-code commands (eg, M123) only as a means of supporting common 3rd party software...

I can understand this, but please consider there are a lot of people that use klipper and other firmwares together.
It is helpful, if all firmwares use a common set of commands for the usual operations. Otherwise you have to reprogram button commands etc. when switching printers.
Some hosts allow to switch the firmware "flavor" together with the printer.

Currently things like restart/firmware_restart and several missing commands to adjust parameters are deal breakers.

**Comment by KevinOConnor** [comment]
Thanks.  I added M119 and M206 to the docs - worded a little differently (commit f3ac1a23).

-Kevin

**Pull request closed without merging**
