### PR TITLE
add virtual_sd gcode_dir option

### PR DESCRIPTION
**Pull request by florianschroen**
Add the possibility to move gcode to a subfolder of virtual_sdcard path.

This may be required for klipper+dwc2 and gcode listing via printer menu "SD Card".

### CODE REVIEW

**Comment by manu7irl** [comment]
AFAIK, It is not really needed as dwc2 creates the sub-folder named gcode as soon as you upload a file through it, then it is handled automatically... No need for klipper to get the job done on this part.
But another subsequent problem is that those files presented under path_to_virtual_sd/gcodes are not accessible through an lcd. 
Because klipper does not handle subfolder s under the virtual_sd path.
IMO, This will be a better idea to add a way to only handle subfolders created under the virtual_sd path, by modifying the fetch behavior in virtual_sd.py.

**Comment by KevinOConnor** [comment]
If there is an enhancement for dwc2 it should be raised with the dwc2 developers.  Otherwise, any dwc2 work here would start with a code submission for dwc2 followed immediately by a developer willing to address the resulting review comments.

-Kevin

**Comment by manu7irl** [comment]
@KevinOConnor this is right nothing to add here but, as we speak about the virtual_sd could it be handling subfolders to get the lcd sdcard card to diplay them? Because it is not so convenient to scroll 30 to 50 to get to a specific file. And this is a klipper related problem for some. Not dwc2 related.

**Comment by florianschroen** [comment]
same for me. I have a cron which moves all gcodes older than x day to a subfolder. This gives me the ability to find the file I am searching for.  ;-)
Adding browsable subfolders to the lcd-menu is the best to do. But someone has to code this.
And adding a possibility to order files by date (youngest first) would be even better (in addition).
I don't know if I can get the complete skill to do this, or when to do.

**Pull request closed without merging**
