### PR TITLE
Create printer-tronxy-p802e

### PR DESCRIPTION
**Pull request by camatthew88**
Made a file for the tronxy p802e. It works great

### CODE REVIEW

**Comment by camatthew88** [comment]
https://github.com/KevinOConnor/klipper/issues/2664

**Comment by camatthew88** [comment]
Matthew Blankenbehler
mablankenbehler23@whitnall.com

**Comment by KevinOConnor** [comment]
Thanks.  In order for me to directly commit, the commit message needs to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .  However, I can usually commit an example config file using my signed-off-by line if you prefer.

The printer config files end in a ".cfg" suffix and contain the year the printer was released.  What year is this printer from?

Also, please be sure the config file actually works as attached (some of the heater_bed config options that are required to be present have been commented out).

-Kevin

**Comment by camatthew88** [comment]
The release date is unknown. I know the file works because I use it on my own printer. https://www.tronxy.com/p802-series/tronxy-p802e-3d-printer.html is the website

**Comment by camatthew88** [comment]
I dont know how to sign it. Can you please sign it

**Comment by camatthew88** [comment]
Im ready to merge

**Comment by KevinOConnor** [comment]
Thanks.  I'll need a year for the printer.  It can be approximate - for example, if you purchased yours in 2019 then 2019 is fine.

-Kevin

**Comment by camatthew88** [comment]
fixrf it

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
