### PR TITLE
Document menu_root

### PR DESCRIPTION
**Pull request by dushyantahuja**
Document the previously undocumented menu_root parameter in the [display] section

### CODE REVIEW

**Comment by dushyantahuja** [comment]
The parameter is referenced in menu.py
https://github.com/KevinOConnor/klipper/blob/97da129793e55b08c7742fbef2a6b91e4afaef4b/klippy/extras/display/menu.py#L649

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Also, it looks like there is a typo in the comment ("in" is repeated twice).

-Kevin

**Comment by dushyantahuja** [comment]
Corrected.
Signed-off-by: Dushyant Ahuja <dusht.ahuja@gmail.com>

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
