### PR TITLE
Probe improvements

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is a notice that I plan to make some non-backwards compatible changes to the config file:
* Configs that use probe:z_virtual_endstop will no longer specify a position_endstop in the stepper_z config section.  The position_endstop will now automatically be set from the probe's z_offset parameter.
* The manual_probe config option has been removed from the delta_calibrate, bed_tilt, and bed_mesh config sections.  Instead, the DELTA_CALIBRATE, BED_TILT_CALIBRATE, and BED_MESH_CALIBRATE commands have been extended to support a "METHOD=manual" parameter.

In addition to the above changes, this series adds a number of cleanups to the probing code that will hopefully make the probing code more robust.

cd ~/klipper ; git fetch ; git checkout origin/work-probe-20180926 ; sudo service klipper restart

I don't have all the different variations of the hardware, so additional testers would be helpful.

@Arksine , @mzbotreprap - can you verify this series looks correct on your hardware?

-Kevin

### CODE REVIEW

**Comment by LazaroFilm** [comment]
That’s great news! I was about to write about the redudnayof the two Z offset parameters, and was getting tired changing them both.  Should I delete the position_endstop in the stepper_z section? Or if it and it will just be ignored?

**Comment by Arksine** [comment]
Hi @KevinOConnor, I have tested this branch on both the Prusa i3 MK3 and Ender 2 and everything works as expected.  It will definitely help users that confuse/forget the z endstop position with the z_offset.   Great work!

**Comment by theopensourcerer** [comment]
Quick question then. Currently on my CoreXY I have z_stepper settings as:

```
position_endstop: 0
position_min: -0.75
```
And then in my probe section:
```
z_offset: 0
```
So I do not  use the z_virtual_endstop.

Is there anything I will need to be aware of after this change? I am guessing not.

**Comment by chainsol** [comment]
Happy to report on my build this caused no problems, and I appreciate the change to the endstop position - It was annoying when I forgot to change both, so this is a nice improvement.

**Comment by KevinOConnor** [comment]
Thanks!

@theopensourcerer - you shouldn't need any change then.

-Kevin

**Comment by theopensourcerer** [comment]
Started a a print on this test branch and it all looks fine so far - using BED_MESH_CALIBRATE, no changes to my config. (CoreXY, Precision Piezo probe, optical Z min endstop).

FWIW Probe results (3 probes per point):

```
probe at 10.002,10.000 is z=0.993750 
probe at 10.002,10.000 is z=0.978750 
probe at 10.002,10.000 is z=0.978750 
probe at 83.748,9.999 is z=0.612500 
probe at 83.748,9.999 is z=0.611250 
probe at 83.748,9.999 is z=0.610000 
probe at 157.500,9.999 is z=0.941250 
probe at 157.500,9.999 is z=0.940000 
probe at 157.500,9.999 is z=0.923750 
probe at 231.250,10.001 is z=0.535000 
probe at 231.250,10.001 is z=0.536250 
probe at 231.250,10.001 is z=0.540000 
probe at 305.002,10.001 is z=0.872500 
probe at 305.002,10.001 is z=0.875000 
probe at 305.002,10.001 is z=0.885000 
probe at 305.001,103.331 is z=1.096250 
probe at 305.001,103.331 is z=1.105000 
probe at 305.001,103.331 is z=1.091250 
probe at 231.249,103.331 is z=0.738750 
probe at 231.249,103.331 is z=0.725000 
probe at 231.249,103.331 is z=0.722500 
probe at 157.500,103.329 is z=1.136250 
probe at 157.500,103.329 is z=1.130000 
probe at 157.500,103.329 is z=1.136250 
probe at 83.750,103.332 is z=0.765000 
probe at 83.750,103.332 is z=0.766250 
probe at 83.750,103.332 is z=0.765000 
probe at 10.001,103.330 is z=1.157500 
probe at 10.001,103.330 is z=1.157500 
probe at 10.001,103.330 is z=1.166250 
probe at 10.000,196.660 is z=1.258750 
probe at 10.000,196.660 is z=1.246250 
probe at 10.000,196.660 is z=1.236250 
probe at 83.749,196.662 is z=0.852500 
probe at 83.749,196.662 is z=0.843750 
probe at 83.749,196.662 is z=0.850000 
probe at 157.499,196.659 is z=1.275000 
probe at 157.499,196.659 is z=1.273750 
probe at 157.499,196.659 is z=1.272500 
probe at 231.248,196.661 is z=0.850000 
probe at 231.248,196.661 is z=0.847500 
probe at 231.248,196.661 is z=0.843750 
probe at 305.001,196.661 is z=1.165000 
probe at 305.001,196.661 is z=1.146250 
probe at 305.001,196.661 is z=1.137500 
probe at 305.000,289.991 is z=1.068750 
probe at 305.000,289.991 is z=1.066250 
probe at 305.000,289.991 is z=1.093750 
probe at 231.250,289.988 is z=0.795000 
probe at 231.250,289.988 is z=0.787500 
probe at 231.250,289.988 is z=0.773750 
probe at 157.501,289.992 is z=1.258750 
probe at 157.501,289.992 is z=1.247500 
probe at 157.501,289.992 is z=1.250000 
probe at 83.752,289.989 is z=0.847500 
probe at 83.752,289.989 is z=0.850000 
probe at 83.752,289.989 is z=0.848750 
probe at 9.999,289.990 is z=1.198750 
probe at 9.999,289.990 is z=1.213750 
probe at 9.999,289.990 is z=1.200000 
Mesh Bed Leveling Complete 
```

**Pull request merged**
