### PR TITLE
Adapting to the new Probe value behaviour

### PR DESCRIPTION
**Pull request by VoronDesign**
Now performs calculations from perspective of the gantry, not the bed.

Signed-off-by: Maks Zolin <mzolin@vorondesign.com>

### CODE REVIEW

**Comment by VoronDesign** [comment]
Those other 2 commits should be in a separate PR

**Comment by VoronDesign** [comment]
Ok, this is a mess, let restart this process

**Comment by KevinOConnor** [comment]
FYI, take a look at the PROBE_ACCURACY command that was recently added (and is in klippy/extras/probe.py).

-Kevin

**Comment by VoronDesign** [comment]
Well look at that! Someone beat me to it. We’ve been using my hacked version internally, I just didn’t get around to PR’ing it. Glad there’s a better version now.

**Pull request closed without merging**
