### PR TITLE
Fysetc S6 generic configuration

### PR DESCRIPTION
**Pull request by towe96**
Version 2.
Does not include the pins for the UART and I2C connectors.

Also fixed the "Mhz" spelling in two files, though I wanted that to go into a seperate pull request.

Signed-off-by: Tobias Weiß t.weiss@bk.ru

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Otherwise looks good to me.

-Kevin

**Comment by tonn0297** [comment]
i wanna ask if you can make so the 12Mhz crystal is selected in low level config or make a note about it? had some issues getting it flashed untill i found the issue about it

**Comment by ade** [comment]
agree with @tonn0297 about adding a note about 12mhz, also, should add at note that you must flash at 0x08000000, overwriting the Fysetc bootloader, as klipper does not work with it as you already found :)

**Comment by KevinOConnor** [comment]
Thanks.

One minor comment - the software spi should not be needed for tmc2130 drivers.  Instead, one should be able to set "spi_bus: spi1".

-Kevin

**Comment by towe96** [comment]
You're correct, works fine.

**Pull request merged**
