### PR TITLE
config: Add Skr v1.4 configuration

### PR DESCRIPTION
**Pull request by john-yan**
Added a configuration for latest skr v1.4 board from bigtreetech.

Configuration is tested based on skr v1.4 turbo on ender 5 with bmg extruder, tmc2208.

Signed-off-by: John Yan john.yan1019@gmail.com
Signed-off-by: Kevin O'Connor kevin@koconnor.net

### CODE REVIEW

**Comment by john-yan** [comment]
Please merge it if you see fit.

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

I can generally commit config files under my signed-off-by line if you prefer, however.

-Kevin

**Comment by john-yan** [comment]
@KevinOConnor Thanks for the comment! Updated.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
