### PR TITLE
stm32f0 spi fixes

### PR DESCRIPTION
**Pull request by sensille**
Please consider these 2 commits for integration. On stm32f070cb, spi did not work at all, this is fixed in one commit. I checked with the datasheets of stm32f1 and stm32f4 and this version should also work, but i can't test it.
The other commit adds alternate pinnings for spi1/2. I also checked with other datasheets and found them present on all I checked, but I haven't found an exhaustive list of all devices' alternate functions to check against.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

The adding of the two additional spi aliases is fine, but those two aliases would not work on the stm32f1.

To fix spi on the stm32f0, could the following be used instead?
```diff
--- a/src/stm32/spi.c
+++ b/src/stm32/spi.c
@@ -4,6 +4,7 @@
 //
 // This file may be distributed under the terms of the GNU GPLv3 license.
 
+#include "board/io.h" // readb
 #include "command.h" // shutdown
 #include "gpio.h" // spi_setup
 #include "internal.h" // gpio_peripheral
@@ -53,6 +54,11 @@ spi_setup(uint32_t bus, uint8_t mode, uint32_t rate)
         gpio_peripheral(spi_bus[bus].miso_pin, spi_bus[bus].function, 1);
         gpio_peripheral(spi_bus[bus].mosi_pin, spi_bus[bus].function, 0);
         gpio_peripheral(spi_bus[bus].sck_pin, spi_bus[bus].function, 0);
+
+        // Configure CR2 on stm32f0
+#if CONFIG_MACH_STM32F0
+        spi->CR2 = SPI_CR2_FRXTH | (7 << SPI_CR2_DS_Pos);
+#endif
     }
 
     // Calculate CR1 register
@@ -82,7 +88,7 @@ spi_transfer(struct spi_config config, uint8_t receive_data,
         spi->DR = *data;
         while (!(spi->SR & SPI_SR_RXNE))
             ;
-        uint8_t rdata = spi->DR;
+        uint8_t rdata = readb((void*)&spi->DR);
         if (receive_data)
             *data = rdata;
         data++;
```

-Kevin

**Comment by sensille** [comment]
Ah, there are already functions for byte-wise access, good. I will change to using them and split the fix-commit in two, a strict fix commit and the other for the performance improvement. Then you can still decide if you want to take it or not. 
For fixing the spi issue it is at least also necessary to make the write a byte access.

**Comment by sensille** [comment]
Force push. I split the fix commit in two, one for the fix, one for the performance improvement. The fix is changed according to your proposal. I also added a commit which adds an alternate pinning for UART2. Please let me know if should make a separate PR for it.

**Comment by KevinOConnor** [comment]
Thanks.  I applied this and also applied a couple of minor fixes on top (commit c8a93cb3 and aea15250).

-Kevin

**Comment by KevinOConnor** [comment]
FYI, I'm not sure why, but commit a2c309a2 is causing crashes on one of my stm32f103xb boards.  It's highly reproducible.  The code looks okay, so I'm not sure what the source of the issue is.  It may be a chip errata.  Until we can track it down, I reverted that commit (in commit 121249c9).

-Kevin

**Pull request merged**
