### PR TITLE
Create printer-creality-ender3-fysect-f6.cfg

### PR DESCRIPTION
**Pull request by SimoneBnc**
This is my current config file for Fysect F6 + TMC2208 running on my Ender 3 with stock creality display

Signed-off-by: Simone Bonacini <bonacini.simone@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I do think it would be good to add an example file for the fysetc f6.  I think it should be named config/generic-fysetc-f6.cfg .  The example will need to have a comment header like the other "generic" example files.  In order for me to directly commit a change, the commit messages needs to have a signed-off-by line (see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).  For a example config though, I can update the comments and do the sign-off if you'd prefer that.

-Kevin

**Comment by SimoneBnc** [comment]
It is my first pull request ever on Github, I don't know how the process work so feel free to do the necessary changes on the file name and internal sections too if you want to make it more "generic"

**Comment by KevinOConnor** [comment]
Thanks.  I made some minor changes (to make the config more like the other example configs) and committed this change (15da5cc5).

FYI, when I said "generic" above I was just referring to config files that start with a "generic-" prefix.  That's the current convention for example config files that apply to a control board that may be used in a variety of printers.

-Kevin

**Comment by KevinOConnor** [comment]
I did not intend to make any changes to that - did I mess something up?  I did remove values that were set to their defaults (heater_temp=50 and heater=extruder by default) as I think that's easier for users to understand when first faced with a config.

-Kevin

**Pull request closed without merging**
