### PR TITLE
hall_filament_width_sensor, added virtual runout sensor

### PR DESCRIPTION
**Pull request by test3210-d**
module: hall_filament_width_sensor
added virtual runout sensor

Signed-off-by: Denis Ignatenko deniss979@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks good to me.  Some minor comments:
1. It is a good idea to update config/example-extras.cfg with the new parameters (the description can just say "See [filament_switch_sensor] for a description of these parameters").
2. I don't think it's necessary to add a `runout_detect` config option.  If a user does not specify runout_gcode nor insert_gcode, then it is effectively disabled anyway.  If a user does specify one of those parameters then they obviously want to enable it.

The above are minor, so it's not necessary to do them if you don't agree.

-Kevin

**Comment by test3210-d** [comment]
Fixed

**Comment by Arksine** [comment]
Just out of curiosity, does the ADC callback run on the main thread?

**Comment by KevinOConnor** [comment]
The ADC callbacks are run in a background thread.  Good catch - it would not be valid to call the RunoutHelper from the background thread (and doing much more than update a variable from the background thread would likely require locks to be added).

-Kevin

**Comment by Arksine** [comment]
I thought so, just wanted to check to make sure I wasn't missing something.  I remember verifying that the buttons use the Reactor to push the update to the main thread.  We should be able to get get away with something similar here:

```python
is_filament_present = self.diameter > self.runout_dia
self.reactor.register_async_callback(
    lambda e, s=self, fp=is_filament_present: 
    s.runout_helper.note_filament_present(fp))
```

**Comment by test3210-d** [comment]
i agree, moved from adc callback

**Comment by KevinOConnor** [comment]
Thanks.  Be aware that the adcX_callback() functions can be called at any time - so that means that self.lastFilamentWidthReadingX and self.diameter variables can change at any time.  You might want to do add locks to the code or copy these variables to local variables once in any given action, so as to avoid odd situations where a variable changes mid-action.

Separately, if would be great if you could make the config/example-extras.cfg updates match the style and conventions of that file.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
