### PR TITLE
Add printer config for the CR-20 by Creality3D

### PR DESCRIPTION
**Pull request by urish**
Tested this configuration with my printer and successfully completed a test print with good results.
I couldn't get the LCD to work yet, but other than that the printer seems to be completely functional.

### CODE REVIEW

**Comment by urish** [comment]
By digging into Creality's source code, it seems like they use a "DOGM SPI LCD" in this printer, which seems to be using the [UC1701](https://github.com/olikraus/u8glib/wiki/device#uc1701-128x64) controller, with the following pin mappings: CS = 25, A0 = 27, and the hardware SPI pins for MOSI / 
 SCK. 

Any pointers how to make this work with Klipper?

**Comment by KevinOConnor** [comment]
If it's a uc1701 then take a look at config/printer-creality-ender2-2017.cfg .  The marlin pins can be mapped via the description at: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-convert-a-marlin-pin-number-to-a-klipper-pin-name

If this printer doesn't use an actual arduino, it's generally preferable to use the micro-controller pin names instead of the arduino aliases.

-Kevin

**Comment by urish** [comment]
Update: I got the LCD to work!

I will update the PR with the micro-controller pin names in a few

**Comment by urish** [comment]
Here we go, I tested the update version (with the pin names) and everything seems to function correctly, including the LCD

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.  However, commits need to have a signed-off-by line as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Comment by KevinOConnor** [comment]
Oh - quick question - are you sure the click pin is "^PC2" instead of "^!PC2" - the click pins are usually inverted.  (Symptoms of an inverted click pin is a button press not being recognized until the release; long press not working; etc.)

-Kevin

**Comment by urish** [comment]
Good catch - I think it might be inverted, checking now

**Comment by urish** [comment]
Yes, it has to be `^!PC2` as you suggested. The button is much more responsive now, thanks!

**Comment by KevinOConnor** [comment]
Okay - thanks.  If you can send a PR with the change, that would be great.

-Kevin

**Pull request merged**
