### PR TITLE
config: add Flsun Q5 config

### PR DESCRIPTION
**Pull request by FrYakaTKoP**
in cooperation with chaosdrucker

Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>

### CODE REVIEW

**Comment by frap129** [comment]
Do you use the stock probe for delta_calibrate with good results? I've been calibrating in manual mode on my Q5

**Comment by FrYakaTKoP** [comment]
Actually i don't have a Q5. I'm just committing the config because the owner of the printer can't handle github ¯\_(ツ)_/¯

But yes he is using the stock probe to calibrate the printer.

**Comment by frap129** [comment]
Ahh, ok. You may want to change the `arm_length` values to 215, which is the length set in the stock firmware. After running enhanced delta calibration, all my `arm_length`'s are between 214 and 216.5, so I believe that's correct. Also, my extruder `rotation_distance` is calibrated to 7.2384. Obviously this varies between machines, but its less than 1/3 of what your config has it set to, which would lead me to believe that yours is a bit off for a stock machine. Otherwise this is pretty close to my config.

**Comment by FrYakaTKoP** [comment]
``arm_length``:
 it's working great on the Printer we have to test. It was the length calculated by the adv. Calibrate. But we actually have some other people in the Community with a Q5 (which wait on the "how to" video we like to release) who can verify the config. Don't know if we should rather use the "stock" value or what we tested as working.
 
 ``rotation_distance`` yes we got about 3-times higher value. Did you see that we use ``gear_ratio: 66:22`` which is 3:1  ;)

**Comment by KevinOConnor** [comment]
Thanks.  Just to clarify, the flsun q5 comes with the mks robin board in its stock configuration?

-Kevin

**Comment by FrYakaTKoP** [comment]
Yes, it does. We have about 5 People which have tested this configuration on their printers. Only thing we are unsure, is the arm length. We will guide those people through adv. calibration and report as soon we have enough data. Strange thing to me is that both variants of the config (arm length 218 vs 215) works great after auto calibration. Arm we only have only  one device which has this 218 length the other is in the 215 range. If we consider @frap129 which also landed more in the 215 range i tend do change the example config back to 215. I hope we have clearer result this weekend.

**Comment by FrYakaTKoP** [comment]
we did some data collection and it looks like most of the printers have indeed a armlength around 215mm, i updated the config. Other thing is the Endstop position which seems to vary alot between printers too, but if i understand it correctly a auto calibrate will correct the endstop positions.

@KevinOConnor our test users (~5) are happy with the config as a template for the q5, please merge it or let me know if we should provide more data or test something.

-FrY

**Comment by KevinOConnor** [comment]
Thanks.  I committed this and made a couple of minor changes on top (commit a1072be7).

-Kevin

**Pull request merged**
