### PR TITLE
stm32f0 build updates

### PR DESCRIPTION
**Pull request by KevinOConnor**
Hi @Delsian .  Could you take a look at this series and verify that everything still works?  It's mainly just build changes so I think it should be okay.

It does enable the full -fwhole-program and -flto so there is a good chance it will also improve overall performance.

Also, what's the status of the current CAN support?  I noticed that ST has marked the HAL CAN support that Klipper currently uses as "Legacy".  Their v1.10.0 release of STM32Cube has a new driver for CAN.

Thanks.
-Kevin

### CODE REVIEW

**Comment by Delsian** [comment]
Thanks, will check it tomorrow on my printer.

**Comment by KevinOConnor** [comment]
Thanks.  Any luck with that test?

Also, it seems the stm32f0 is very similar to the stm32f1 and stm32f4.  Do you have any thoughts on merging them together (as in PR #1846)?

-Kevin

**Comment by KevinOConnor** [comment]
Hi @Delsian,

There's been a bunch of interest in Klipper support for the stm32f070 and stm32f042 recently.  As part of that interest, the src/stm32/ directory now supports building these targets with USB support.  The src/stm32f0/ directory contains the stm32f042 code with CAN support.

Would you be interested in helping port the CAN code to the code in the src/stm32/ directory?  In particular, this would involve writing a "bare metal" driver for the stm32 CAN module.  The same CAN hardware is also in the stm32f103 and stm32f4xx chips, so if we could port the CAN code over it would allow it to be tested and deployed on more chips.

Thanks,
-Kevin

**Comment by Delsian** [comment]
@KevinOConnor ok, I'll check.
Unfortunately I have small problem with checking new branches - all my f042 boards now working in my printer and I prefer not to touch working setup. I hope to solder new stm board soon for development.

**Comment by KevinOConnor** [comment]
Okay, thanks for the update.  I'm going to close this branch as I think the next step is to try and get the src/stm32f0/ code integrated into src/stm32/ .

-Kevin

**Pull request closed without merging**
