### PR TITLE
Software SPI Implementation

### PR DESCRIPTION
**Pull request by fragginright**

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I wonder if we can limit the amount of changes to spicmds.c and thermocouple.c.  How about something like cd6479c8 (which is on a demo work-software-spi-20190209 branch I just created).  This is just demo code (that is totally untested) - but ideally all the software spi work could then be done in the spi_software.c file and no changes would be needed to thermocouple.c.

-Kevin

**Comment by kakou-fr** [comment]
i just installed today a re-arm. but like i have a RRD and TMC2130 SPI, i switched to marlin.
Do you thing i could test this version ? or it need more works ?

**Comment by kakou-fr** [comment]
There is a problem line 29 in bus.py

                "config_spi_from_software oid=%d sw_oid=%d pin=%s"
                " mode=%d rate=%d shutdown_msg=%s" % (
                    self.oid, software_spi_oid, mode, speed, shutdown_msg)]

pin=%s but correspond to mode that is %d
so pin arg is missing or "pin=%s" must be removed

**Comment by kakou-fr** [comment]
i tried but : 

Sending MCU 'mcu' printer configuration...
Protocol error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 137, in _connect
    cb()
  File "/home/pi/klipper-swspi/klippy/mcu.py", line 633, in _connect
    self._check_config()
  File "/home/pi/klipper-swspi/klippy/mcu.py", line 583, in _check_config
    self._send_config(None)
  File "/home/pi/klipper-swspi/klippy/mcu.py", line 557, in _send_config
    self._serial.send(c)
  File "/home/pi/klipper-swspi/klippy/serialhdl.py", line 132, in send
    cmd = self.msgparser.create_command(msg)
  File "/home/pi/klipper-swspi/klippy/msgproto.py", line 297, in create_command
    raise error("Unable to encode: %s" % (msgname,))
error: Unable to encode: config_spi_from_software
Got error 0 in read: (0)Success

**Comment by fragginright** [comment]
module: klilpper

Adds software SPI to MCU that are capable of bit-banging.

Signed-off-by: Matt Janus <FragginRight@variabl.es>

**Comment by kakou-fr** [comment]
not working for me : 

DUMP_TMC stepper_x
GCONF:      ffffffff
GSTAT:      ffffffff
IOIN:       ffffffff
TSTEP:      ffffffff
XDIRECT:    ffffffff
MSCNT:      ffffffff
MSCURACT:   ffffffff
CHOPCONF:   ffffffff
DRV_STATUS: ffffffff
PWM_SCALE:  ffffffff
LOST_STEPS: ffffffff

**Comment by kakou-fr** [comment]
and the debug log : 
config_software_spi oid=1 sclk_pin=41 mosi_pin=32 miso_pin=40
config_spi_from_software oid=0 sw_oid=1 pin=33 mode=3 rate=4000000 shutdown_msg=''
config_software_spi oid=3 sclk_pin=41 mosi_pin=32 miso_pin=40
config_spi_from_software oid=2 sw_oid=3 pin=36 mode=3 rate=4000000 shutdown_msg=''
config_software_spi oid=5 sclk_pin=41 mosi_pin=32 miso_pin=40
config_spi_from_software oid=4 sw_oid=5 pin=42 mode=3 rate=4000000 shutdown_msg=''
spi_send oid=0 data='\x80\x00\x00\x00\x00'
spi_send oid=0 data='\xec\x14\x00\x83\x84'
spi_send oid=0 data='\x90\x00\x08\x11\x11'
spi_send oid=0 data='\x91\x00\x00\x00\x00'
spi_send oid=0 data='\x93\x00\x00\x00\x00'
spi_send oid=0 data='\xed\x00\x04\x00\x00'
spi_send oid=0 data='\xf0\x00\x05\x04\x80'

**Comment by KevinOConnor** [comment]
Thanks.  There were some errors in the bus.py sample code I sent over (I should have checked for the multi-mcu case).  I also fixed two errors in the spi_software.c code (outbuf & 0x80, and the mode check looks like it was backwards).  Merged patch with my changes is on the work-software-spi-20190209 branch (commit ad17b8b7).

I was able to bring up my ssd1306 display in software spi mode with this patch.

-Kevin

**Comment by kakou-fr** [comment]
tested with 3 tmc and the config posted before, looks good 👍 thks you

DUMP_TMC stepper_x
GCONF:      00000000
GSTAT:      00000001
IOIN:       110000f8
TSTEP:      000fffff
XDIRECT:    00000000
MSCNT:      00000008
MSCURACT:   00f7000c
CHOPCONF:   14008384
DRV_STATUS: 80110000
PWM_SCALE:  00000000
LOST_STEPS: 00000000
DUMP_TMC stepper_y
GCONF:      00000000
GSTAT:      00000001
IOIN:       110000f8
TSTEP:      000fffff
XDIRECT:    00000000
MSCNT:      00000008
MSCURACT:   00f7000c
CHOPCONF:   14008384
DRV_STATUS: 80110000
PWM_SCALE:  00000000
LOST_STEPS: 00000000
DUMP_TMC stepper_z
GCONF:      00000000
GSTAT:      00000001
IOIN:       11000078
TSTEP:      000fffff
XDIRECT:    00000000
MSCNT:      00000020
MSCURACT:   00f20030
CHOPCONF:   16028384
DRV_STATUS: 80130000
PWM_SCALE:  00000000
LOST_STEPS: 00000000

**Comment by KevinOConnor** [comment]
Okay, thanks.  I committed it to the master branch (commit 98ed4628).

-Kevin

**Pull request closed without merging**
