### PR TITLE
Added sample configuration file for Bigtreetech Octopus board

### PR DESCRIPTION
**Pull request by tgiphil**
Source is the Bigtreetech repo:

https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/blob/main/Firmware/klipper/Octopus%20klipper.cfg

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Please see the example config file guide at: https://www.klipper3d.org/Example_Configs.html .  Also, commits need to have a signed-off-by line for me to commit directly - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by katodo** [comment]
Hi, I received Octopus Board these days, is this pull request already merged in the master repo? I don't know GitHub very well

**Comment by tgiphil** [comment]
> Hi, I received Octopus Board these days, is this pull request already merged in the master repo? I don't know GitHub very well

Not yet. It still needs to be updated to match the example config. However, you can view it within the commit or the link above.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like it has gone stale.

-Kevin

**Pull request closed without merging**
