### PR TITLE
Use builtin ARM DWT and SysTick timers on ARM-CortexM3/M4 chips

### PR DESCRIPTION
**Pull request by KevinOConnor**
It turns out the ARM CM3 and later chips have a builtin 32bit timer on the "Debug and Watch Trace" (DWT) unit.  It's possible to use this timer (along with the standard SysTick timer) to simplify the code and improve its performance.

-Kevin

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@FHeilmann - if you get a chance, could you verify everything looks okay on the Duet2 Wifi/Eth and check what the new benchmarks are?

-Kevin

**Comment by FHeilmann** [comment]
Hi Kevin,

unfortunately the printer crashes with timer too close errors on this branch.

[GARDEN_PIG.gcode.txt](https://github.com/KevinOConnor/klipper/files/2827403/GARDEN_PIG.gcode.txt)
[klippy3.log](https://github.com/KevinOConnor/klipper/files/2827401/klippy3.log)

Benchmarking was still possible though. Here are the results: 

Duet Wifi on commit `f85c612` using `gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516`

3 Steppers: set ticks 555 649K
2 Steppers: set ticks 526 456K
1 stepper: set ticks 526 228K

**Comment by KevinOConnor** [comment]
Thanks.  That error is almost certainly due to a defect in the new code.  I did find one error (NVIC_clearPendingIrq is not valid on the SysTick IRQ).  I've pushed a fix for that.  It's hard to say if that was the only error.  I'll try to run some simulated prints.

The raspbian arm gcc is a bit dated and it wont compare well with the other benchmarks.  Attached is a compiled version using a recent arm gcc from my local Fedora box, if you want to try with that.
[klipper-sam4e8e-1a841222.bin.gz](https://github.com/KevinOConnor/klipper/files/2828846/klipper-sam4e8e-1a841222.bin.gz)

-Kevin

**Comment by FHeilmann** [comment]
Tried your fixed commits today, a print completed without issue, but since the crashes were intermittent I might just have been lucky.
I upgraded my rpi toolchain to

`arm-none-eabi-gcc 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]`

on commit `1a84122` the benchmarks were as follows:

code: 
```
allocate_oids count=4
config_stepper oid=0 step_pin=PD6 dir_pin=PD11 min_stop_interval=0 invert_step=0
config_stepper oid=1 step_pin=PD7 dir_pin=PD12 min_stop_interval=0 invert_step=0
config_stepper oid=2 step_pin=PD8 dir_pin=PD13 min_stop_interval=0 invert_step=0
config_stepper oid=3 step_pin=PD5 dir_pin=PA1 min_stop_interval=0 invert_step=0
finalize_config crc=0
```
results:
```
4 Steppers: set ticks 807  595K
3 Steppers: set ticks 552 652K
2 Steppers: set ticks 524 458K
1 stepper: set ticks 526 228K
```

so no real changes in the benchmark results I'm afraid.

**Comment by KevinOConnor** [comment]
Thanks.  I've merged this branch.

It is interesting that the at91sam line of devices shows little improvement with this change, while the STM32, LPC176x, and SAMD51 devices show significant improvement.

-Kevin

**Pull request closed without merging**
