### PR TITLE
config:  Ultimaker v2 default config example

### PR DESCRIPTION
**Pull request by Hello1024**
This config is tested working on the Ultimaker v2.  It likley also works
on the Ultimaker v2+.

It requires the power limiting module
(https://github.com/KevinOConnor/klipper/pull/3877) or the system will
power off at random while printing due to being out of power.

Signed-off-by: Oliver Mattos <oliver@omattos.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Happy to add an example for the Ultimaker printer.  However, all the example config files are added to the regression tests, and I noticed this config would not work as currently defined (at a minimum, the extruder pid settings would need to be defined).  Also, it would be preferable to add an example config with the current code, and not depend on the power_limit feature.

-Kevin

**Comment by Hello1024** [comment]
Unfortunately the ultimaker2 doesn't work at all without the power limit.  Even with the workaround of heating the bed then the extruder, there are brief moments where the 24 volt power supply sags to 8 volts and the arduino resets.   That happens mostly at the end of the first layer of printing and the fans spin up and both the bed and extruder PID's go to max power for 10 seconds or so.

We could perhaps add the ultimaker 2 profile with the heater bed disabled entirely?

**Comment by KevinOConnor** [comment]
FWIW, if the power supply on this printer is so underpowered that it can't run the bed when other peripherals are powered, then I'd tend to call it a "broken printer" and recommend not using the heater bed at all.

Separately, it is possible to time the PWM updates in the host python code (the mcu code will closely follow a schedule).  I'm not sure it would be worth the effort to do that though.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive.

-Kevin

**Pull request closed without merging**
