### PR TITLE
Fix issue 403 use max_speed

### PR DESCRIPTION
**Pull request by wizhippo**
Signed-off-by Douglas Hammond  <wizhippo@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Wouldn't this change cause the fan to never turn off if it is in watermark mode?

**Comment by wizhippo** [comment]
You are correct.  Should it if a min speed is defined?  I'm fine either way.

**Comment by KevinOConnor** [comment]
The min_speed is 0.3 by default, so I don't think it should use min_speed.  I'd recommend fixing just the primary issue in one commit, and then use a different commit if a different high-level behavior for watermark is desired.

**Comment by KevinOConnor** [comment]
Thanks.

**Pull request merged**
