### PR TITLE
Support for writing calibration data to printer.cfg

### PR DESCRIPTION
**Pull request by KevinOConnor**
I'm currently planning to add support for a SAVE_CONFIG command that will allow users to automatically write calibration data to their printer.cfg file.  This pull request adds this support for the PID_CALIBRATE, BED_TILT_CALIBRATE, and DELTA_CALIBRATE commands.  With this change, users need only run the calibration command and the new SAVE_CONFIG command to apply the new settings - users wont be asked to copy-and-paste the new config values into their config, nor will then need to manually RESTART.

Admittedly, this support is a bit "goofy" - the new calibration data is stored at the end of the printer.cfg file in a special configuration block.  If the new calibration data supersedes a config parameter that the user had previously specified, then the original config parameter is commented out when printer.cfg is written.  If the user later updates the config to set a value for a particular parameter then that setting will take precedence over any settings in the SAVE_CONFIG block.  The reason the code does it this way is I want to preserve comments the user may have in their config, avoid user confusion on what config settings are being used, and make it simple to backup/restore settings.

The "enhanced delta printer calibration" (issue #615) needs an automated save and restore mechanism to be effective.  Similarly, it's highly desirable for bed mesh leveling.

-Kevin

### CODE REVIEW

**Comment by knoopx** [comment]
This is a really useful feature, however I was wondering, wouldn't it be easier to write calibration data into a separate file? That way there's no need to mess with user cfg. If calibration cfg is present, it simply overrides user settings.

**Comment by KevinOConnor** [comment]
> This is a really useful feature, however I was wondering, wouldn't it be easier to write calibration data into a separate file? That way there's no need to mess with user cfg. If calibration cfg is present, it simply overrides user settings.

Writing the calibration data to a separate file is simpler to implement.  However, I'm concerned that it would lead to confusion.  It's sometimes necessary to update a parameter that the user has specified - for example on DELTA_CALIBRATE the user must configure an initial delta_radius value and the calibration code later comes up with a new delta_radius.  If the new delta_radius is stored in a separate config file then the user will still have the original delta_radius in their main config file and it wont be obvious that it is no longer in effect.  I'm hoping that writing back out the printer config file with updates will make the printer configuration more transparent.

-Kevin

**Comment by ruevs** [comment]
I like your latest approach (commenting the manually configured setting and heaving it take precedence if it is uncommented). It seems like a good trade-off.
One thing I would suggest is to add a comment in the commented out setting. For example instead of:
`#position_endstop: 273.0`
use:
`#[Commented out by SAVE_CONFIG]position_endstop: 273.0`
or something similar.
In this way it will be easier for the users to distinguish automatically commented out parameters from ones they might have commented out manually. In addition the above becomes an invalid parameter so the user will have to delete the [...] comment in order to re-enable it. This will (hopefully) make them think more about the impact.

**Comment by Arksine** [comment]
@theopensourcerer  I will add support for saving mesh data.  I already have an initial version of it, I just need to update it and put some finishing touches on it.  I'll do that after Kevin merges this PR.

**Comment by AxMod3DPrint** [comment]
>   Writing the calibration data to a separate file is simpler to implement. However, I'm concerned that it would lead to confusion. 
Just as a note, writing out to a separate file is the way Smoothie does it, all the endstop trims and new radius get written to the config-override file, which is auto generated on a M500.

**Comment by dushyantahuja** [comment]
I would agree with Kevin, the config override file in Smoothie tends to
confuse the user.

I had changed my Z axis configuration - so changed the number of steps in
my config file. And of course nothing changed, because the config override
file was overiding my change.

Keeping it all in one file would avoid that confusion.

**Comment by BlackStump** [comment]
I am another that prefers Kevins idea, a separate config override file can easily be overlooked and has been with other firmwares that use that system ....leads to confusion then a doulp moment.

**Comment by LazaroFilm** [comment]
I also agree about having only one file, but going further, wouldn’t it be better to keep the “save_config” values right next to the user written ones. For instance, after a PID Autotune, comment out the pre existing values, then add a line right under with the new values, maybe add a comment at the end of the line stating it was saved/written by Klipper instead of having them all at the bottom? It would allow the user to see the new values, compare them, and decide which to keep/uncomment.

**Comment by Arksine** [comment]
@LazaroFilm I think your suggestion would require a custom parser, the built-in config parser wouldn't be able to apply it.  Another thing to keep in mind is that not all persistent values will have corresponding settings.  For example, bed_mesh will save probed z values.  Depending on how many profiles you save, the persistent storage for bed_mesh could get quite large, which would make navigating the printer.cfg difficult if it were interspersed with the configured values.

**Comment by KevinOConnor** [comment]
This series was merged as part of merging #615.

@ruevs - I like your suggestion of adding additional comments when commenting out the old config items.  However, I couldn't think of a good comment prefix/suffix - so I've gone ahead and merged the current code.  I'd like to see if we get further feedback, and then decide how to best update the comments.

-Kevin

**Comment by ysoldak** [comment]
Late to the party, sorry.

I'd say make `[delta_calibrate]` block to be first class citizen, i.e. no `#*#` commented lines that are applied in reality, just regular block added by SAVE_CONFIG routine to the end of the file, with a descriptive comment. SAVE_CONFIG then assumes control over that block and any user changes (why they would want to edit it anyway?) to it be overwritten.

As for endstop, angles and radius adjustments -- put them directly into respective blocks, commenting any respective previous values. May want to add a flag comment at the end of added config line, marking it autogenerated, so subsequent SAVE_CONFIG commands just overwrite it.

This way we have straightforward plain configuration file w/o any confusing hidden overrides and simple contract what SAVE_CONFIG can and will do.

**Comment by KevinOConnor** [comment]
@ysoldak - I agree that would be the most seamless for the user if everything works as expected.  However, my fear with that approach is that a user may not easily recognize what contents are generated by SAVE_CONFIG, and they may accidentally modify areas of the SAVE_CONFIG section.  That could lead to bad corner cases in future SAVE_CONFIG invocations (eg, comments lost, config sections lost, etc.).  By highlighting every line of the SAVE_CONFIG block I think there is a lower chance of misinterpretation.

Now that SAVE_CONFIG support has been merged, I'm inclined to leave it as is and evaluate the overall feedback after several weeks.

-Kevin

**Comment by ysoldak** [comment]
Add a “checksum” field to blocks generated by SAVE_CONFIG command to verify if they were modified :)

**Pull request closed without merging**
