### PR TITLE
add probe X- and Y-offset for bed leveling

### PR DESCRIPTION
**Pull request by salfter**
I cleaned up the request a bit so it should be less troublesome to integrate.

### CODE REVIEW

**Comment by FHeilmann** [comment]
make sure you're specifying defaults (0 in your case) when you get the config parameters to make travis happy (it fails because the standard configs don't have the offset variable and you don't specify a default)

**Comment by KevinOConnor** [comment]
Thanks.  However, I don't think we want to change the interpretation of the coordinate system for probes.  Currently, all the coordinates are relative to the tip of the nozzle.  This change would result in the user adding bed_tilt probe coordinates in the config relative to the position of the probe.  (It has no impact on the tilt calculation itself, as tilt measuring is not impacted by the probe's xy offset.)  Changing the interpretation of the positions for bed tilt calibration may not have much of an impact, but it would be subtly wrong for delta calibration, for example.

-Kevin

**Comment by oderwat** [comment]
It will get important if mesh bed leveling gets introduced eventually.

**Comment by KevinOConnor** [comment]
> It will get important if mesh bed leveling gets introduced eventually.

Yes.  

FWIW, the probe's XY offset should also be used in the calculation of z_adjust within BED_TILT_CALIBRATE.  I haven't had time to implement that (and the impact of the xy offset in that calculation is not normally noticeable).

In my opinion, however, in both case we'll still want to use coordinates relative to the nozzle tip.

-Kevin

**Comment by oderwat** [comment]
I think that we should consider that giving coordinates in nozzle tip position can easily "break" the probing. You always need to be aware that the probe still is touching the bed.

So I think it would have value if we add the offsets and really define the probing points for the probe tip, while also checking with max/min coordinates of the nozzle as defined for the "reachable" area (where the stepper can drive too). Which also does not need to match the "printable" area (where the nozzle touches the bed at position of z = 0). 

Stuff gets complicated if one looks into the details. I was going to make a PR for this on Marlin some time ago but kept it for myself, because it easily becomes a mess if you want to cover all cases. I guess it is OK to leave those to the user but having a "correct" way to define such areas would make everything saver I guess.

I also remember people being totally puzzled because their prob points where not working. Because they forgot, that the head needs to move to a different position for reaching the probe points.

I think letting the user define a "reachable area" and a "bed size" with the "home" getting set inside the reachable area and then using a probe offset could help with reasoning about things?

BTW: I was astonished that the Z ADJUST is reflected on the coordinates of the display. I do understand that it is easier to have the "real stuff" everywhere. But that also makes it harder to understand what is happening from time to time.

**Comment by salfter** [comment]
It looks like https://github.com/KevinOConnor/klipper/commit/3387cccdcfe953e5733df61187b8f5731b38c1e0 added probe X- and Y-offsets to the probe section of the config, presumably for use with mesh bed leveling.  I've updated my patch to use the values stored there.

**Comment by KevinOConnor** [comment]
I've updated the docs to be clear that the config is expecting nozzle coordinates (commit a8d4a7ef).

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this, as I think we do want the config coordinates to be nozzle coordinates.

-Kevin

**Pull request closed without merging**
