### PR TITLE
docs: Clarify BLTouch X/Y offsets

### PR DESCRIPTION
**Pull request by dmp450**
Signed-off-by: Derek Perrin derek@derekperrin.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  As per the discussion in issue #1486, I've updated the BLTouch.md document to point to the Probe_Calibrate.md document (commit de124677).

-Kevin

**Comment by ThomasW69** [comment]
It looks liker ther are najor changes in the handling of offsets with the latest version. I ched out the latest klipper version today and now my printer tries to probe the BED_MESH_CALIBRATE with bltouch off the bed (with same printer.cfg as before).

**Comment by ThomasW69** [comment]
Is position_endstop  the position of the endstop relative to the probe or the nozzle?? I always had  a zero in this parameter but it looks like that this now is included in the coordinates calculation.

**Comment by GarthSnyder** [comment]
@ThomasW69, I'm not a maintainer but I think I know the answer to your queries. I'm sure someone will correct me if I'm wrong.

1) I don't think probe offset handling has changed.

2) BED_MESH_CALIBRATE now uses probe coordinates rather than nozzle coordinates. You don't need to do any offsetting yourself now, but you'll need to adjust the mesh boundaries in printer.cfg.

3) If you are asking a general question about position_endstop for all axes, set the coordinate to align with the nozzle, ignoring the probe. If you are using the probe as a Z axis endstop, I don't think you use position_endstop at all. Not entirely sure about that last part - it's not my configuration.

**Comment by ThomasW69** [comment]
@GarthSnyder 
Thanks for the answer. By Testst I have also found out that in the meantime. But it is extremely confusing that the whole thing was not implemented consistently. So the coordinates of the BED_MESH_CALIBRATE are still given with the offset of 40mm. This means that I can't measure the complete bed as it was before because the nozzle goes beyond the bed and creates an out of range error. My bed at the CR-10 has 310x310mm and I have to parameterize at least 350mm because of the offset, so that the LEveling does not stop with an error. the last line looks like this
// sample at 284,999.325,005 is z=2,455000
Strangely enough, a Z coordinate of 325 is given here. This means that my nozzle should be 15mm behind the end of the bed (if it were the nozzle coordinate). But it does not!  It is a good 30mm free on the bed to the back. Somehow it does not fit anymore.

**Comment by GarthSnyder** [comment]
@ThomasW69, how did this ever work? It’s typical for there to be areas of the bed that can’t be reached by the probe, especially if the probe has a large offset. But that’s typically due to physical limitations on the travel of the head. Everything that was reachable before should still be reachable now.

The “// sample at” Messages come from the probing module, which is separate from the bed mesh module. Those coordinates continue to be in nozzle space.

**Comment by ThomasW69** [comment]
> Those coordinates continue to be in nozzle space.
No, they don't. When I get a y-coordinate of 325 my nozzle is at 285 and my probe is at 245 (mesured with calipers.

**Comment by GarthSnyder** [comment]
That does sound strange. You should open a separate issue for this.

**Pull request closed without merging**
