### PR TITLE
fix  overflow  issue on 12 bit adc

### PR DESCRIPTION
**Pull request by test3210-d**
module: hall_filament_width_sensor
Increasing measure stability

Signed-off-by: Denis Ignatenko deniss979@gmail.com

### CODE REVIEW

**Comment by mcmatrix** [comment]
Tried these values and it's working.

**Comment by KevinOConnor** [comment]
Thanks, but commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by test3210-d** [comment]
module: hall_filament_width_sensor
Increasing measure stability

Signed-off-by: Denis Ignatenko deniss979@gmail.com

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
