### PR TITLE
delta_mfe: Motorized Flying Extruder for Deltas

### PR DESCRIPTION
**Pull request by paigashaona**
This set of changes implements control of an extra motor by which the
extruder can be "wenched" up and down, hanging over the effector. This
lowers the mass on the carriages while still allowing a short bowden
tube.

signed-off-by: Paiga Shaona <paigashaona@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Interesting, thanks.

Some comments / questions:
1 - It isn't necessary to add any C code - the delta_mfe.py code can just do `rail_mfe.setup_itersolve('cartesian_stepper_alloc', 'z')` to reuse the C code in kin_cartesian.c.
2 - Does the rail_mfe also go through a homing procedure?
3 - Instead of duplicating the delta.py code, could the new code just import it?  (For example, by defining a DeltaMFEKinematics class that has a member variable self.delta_kinematics and having all of its methods call self.delta_kinematics.method() where needed.)

-Kevin

**Comment by paigashaona** [comment]
I completely screwed up my git tree somehow... I fixed the changes (and build) but am fighting git on my local tree before I push again, hang on.

**Comment by KevinOConnor** [comment]
Thinking about this further - could a delta_flying_extruder.py module be written that creates the given stepper and then calls `printer.lookup_object("toolhead").get_kinematics().add_rail(rail_mfe)`.  (Along with the appropriate `add_rail()` method added to kinematics/delta.py.)  The delta_calibrate.py code works a similar way.  This way there isn't a need to add a new kinematics class - most of the work would be the new "extras" module.

-Kevin

**Comment by paigashaona** [comment]
I was originally trying to figure out how to do such a thing. I only implemented it as a new kinematics class as I didn't see any other way of adding to the kinematics equations. I'll look into doing that instead though.

**Comment by KevinOConnor** [comment]
Any further updates on this?  If you're unsure of how to setup an "extras" module to do this, I can mock something up.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I'm going to close this as it looks like the conversation has concluded.  FYI, if there is further interest in the future, commit 90bc1679 does something similar for the extruder motor.

-Kevin

**Pull request closed without merging**
