### PR TITLE
CREATE CONFIG  printer-creality-cr10s-pro.cfg

### PR DESCRIPTION
**Pull request by MyMakibox**

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, I'm not sure what to make of this config as it seems to be saying - don't use this config..  Is there no ability to configure the tmc2208 driver on these boards?

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin

**Comment by MyMakibox** [comment]
> Thanks. However, I'm not sure what to make of this config as it seems to be saying - don't use this config.. Is there no ability to configure the tmc2208 driver on these boards?
> 
> -Kevin

It was an attempt to make it work that appeared to succeed. The problems take some time to manifest.

**Comment by KevinOConnor** [comment]
FYI, there is now a workaround for the tmc2208 in standalone mode (PR #2597).  So, feel free to resubmit this config file.  (Please add a signed-off-by line if you do - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).

-Kevin

**Pull request closed without merging**
