### PR TITLE
Support for STM32F401

### PR DESCRIPTION
**Pull request by smark-**
This PR adds support for the STM32F401 microcontrollers for an upcoming board we are developing

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by shouidar** [comment]
I'm also doing some mods to support an stm32F401ve board (mine uses an external 25MHz Osc). 
Noticed that you this PR will cause the FREQ_PERIPH to be 21MHz, any reason why using 21MHz instead of the 42 MHz for peripherals on APB1 and 84 MHz for peripherals on APB2 as indicated by the datasheet?
Also if USB is enable the Q divider will end up equal to 3 (pll_freq/FREQ_USB = (84000000 * 2)/48 = 3.5, and an invalid USB clock.
Thankyou for clarifying.

**Comment by pragun** [comment]
Shouidar, are you planning to use usbserial? I'm also trying to get a STM32F401 board running w USBSerial and my board also uses 25Mhz. I've modified the clock init to the following:

```static void
enable_clock_stm32f40x(void)
{
#if CONFIG_MACH_STM32F405 || CONFIG_MACH_STM32F407 || CONFIG_MACH_STM32F401
    uint32_t pll_base = 1000000, pll_freq = CONFIG_CLOCK_FREQ * 4, pllcfgr;
    if (!CONFIG_STM32_CLOCK_REF_INTERNAL) {
        // Configure 168Mhz PLL from external crystal (HSE)
        uint32_t div = CONFIG_CLOCK_REF_FREQ / pll_base;
        RCC->CR |= RCC_CR_HSEON;
        pllcfgr = RCC_PLLCFGR_PLLSRC_HSE | (div << RCC_PLLCFGR_PLLM_Pos);
    } else {
        // Configure 168Mhz PLL from internal 16Mhz oscillator (HSI)
        uint32_t div = 16000000 / pll_base;
        pllcfgr = RCC_PLLCFGR_PLLSRC_HSI | (div << RCC_PLLCFGR_PLLM_Pos);
    }
    RCC->PLLCFGR = (pllcfgr | ((pll_freq/pll_base) << RCC_PLLCFGR_PLLN_Pos)
                    | (4 << RCC_PLLCFGR_PLLP_Pos)
                    | ((pll_freq/FREQ_USB) << RCC_PLLCFGR_PLLQ_Pos));
    RCC->CR |= RCC_CR_PLLON;
#endif
}
```
I've also set 
`#define FREQ_PERIPH (CONFIG_CLOCK_FREQ / 2)`

Before making these changes I was getting a USB Device Not Recognized in windows and a USB enumeration error in Linux. With these changes, I don't get anything -- no errors, and no usbserial device enumerated. 

Any help would be appreciated!

**Comment by pragun** [comment]
I fixed this for STM32F401 running odd crystals such as 25Mhz.

See pull request: https://github.com/KevinOConnor/klipper/pull/3940

**Pull request merged**
