### PR TITLE
Module: output_pin, tmc2103, tmc2208 - add support for power on initialization

### PR DESCRIPTION
**Pull request by amblidex**
The tmc chips require power to both VCC and VM before they can be successfully initialized. Klipper currently initializes these chips at startup, which works fine if they are fully powered up at that time. However, things are problematic with controlled power sources such as an ATX power supply on RAMPS because the power is enabled during startup and the tmc chips need time with power active before they can be initialized. Also, if the VM power is powered off then back on, the tmc chips remain inactive and need to be initialized again. The current workaround for both of these cases is to restart Klipper. See issue: https://github.com/KevinOConnor/klipper/issues/497

This change adds the ability for output_pin to emit change events with a delay, and for the tmc drivers to receive events to initialize the driver. For the specific case of RAMPS+ATX, one would configure PS_ON through output_pin with delayed events enabled, and the tmc driver would be configured to receive the init event.

Signed-off-by: Frank Kang <amblidex@outlook.com>

### CODE REVIEW

**Comment by wizhippo** [comment]
@amblidex You still need to tie VM to VCC with a schottky diode correct?

**Comment by amblidex** [comment]
@wizhippo No, not with this type of initialization. If you connect VM to VCC with a diode, the chips probably don't need any special handling for init since VM will always be powered. This patch is for the case where VM is not always powered.

**Comment by wizhippo** [comment]
That is what I am wondering.  The method you are taking means no diode needed?

**Comment by amblidex** [comment]
yep, no diode needed

**Comment by wizhippo** [comment]
Really?  For the 3.3-5v version?  How is this avoided? Thought that this was at the hardware level as stated on the waterott faq ? Any info on how late intializing avoids the issue?

**Comment by amblidex** [comment]
We're talking about 2 different things here. Adding the diode does 2 things:
1) Synchronize power to VM when VCC is present, making chip/driver init simpler
2) Protect the chip when using VIO < 5v

Since this patch deals with chip/driver init, I assumed we were talking about case #1. If you have the diode, VM is essentially always powered on, and this patch doesn't benefit that case. 

Case #2 is primarily a hardware concern, and this patch doesn't change whether your setup needs the protection of the diode or not.

**Comment by wizhippo** [comment]
Thanks you.  Thought I was missing something.

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback is that I fear this implementation would be complex for users.  I don't think regular users will find the "event callback" system easy to understand.  (And I'd struggle to explain it.)

As an alternative approach, what do you think about adding a `TMC_RESEND_INIT STEPPER=stepper_x` command.  Then users could add those commands to their homing_override or START_PRINT macro if necessary?

-Kevin

**Comment by amblidex** [comment]
Can't disagree that this approach is a bit complex and low level, but I do think the TMC init code does need to be coupled with the power pin state because it is timing dependent.

My first hack to get things working was actually a new init command as you are suggesting, but I found it cumbersome. This requires power to be off at Klipper startup since a delay is needed from the initial power up. Also, I couldn't figure out how to create a single delay and init all steppers, instead each stepper axis init had to have its own delay causing this to be a serial process.

My second version was a new extras module that was more specific to this purpose. It controlled the power gpio state and had predefined power events that the TMC drivers were aware of. Also it explicitly implemented the Marlin style M80 and M81 gcode commands. It was much simpler to use since a user would just define in config:

[power_control]
pin: !ar13

and everything would work. But I ended up with the current version because this just felt like a special case of output_pin, and it seemed useful to have a general event capability for output_pin. That previous approach was definitely much more user friendly, but I wasn't sure if you would think it was unnecessary duplication of output_pin functionality.

**Comment by amblidex** [comment]
@KevinOConnor - OK I think this command approach works with the addition of delay capability and is simpler to implement and use. Ultimately, I think as soon as the printer is powered, everything should be in a valid state and working. I was uneasy with the initialization tied to homing or some other start gcode, as that seemed like another workaround. But by adding delay capability to the init command, it can be sequenced directly with power on and the initialization of the tmc drivers is seamless for the user.

I've pushed a new revision that adds INIT_TMC as well as an optional "init_delay_time" option for the tmc2130/tmc2208 config. The delay time will apply to both the start up init as well as use of INIT_TMC. This way the initialization of TMC drivers can work whether the default startup is power on or off, and the re-initialization can be integrated with a custom M80 command like:

[gcode_macro M80]
gcode:
        SET_PIN PIN=psu_power VALUE=1
        INIT_TMC stepper=stepper_x
        INIT_TMC stepper=stepper_y
        INIT_TMC stepper=stepper_z

along with setting "init_delay_time" on each of the [tmc2130] or [tmc2208] sections.

BTW, I had to change the register read/write exception on the tmc2208 to a log message. Otherwise, if printer is started powered off an exception is thrown and klipper is halted.

**Comment by KevinOConnor** [comment]
Thanks.  I have a few comments on the code:
1. INIT_TMC would need to be synchronized to the "print time" - as an example of how this is done, take a look at servo.py:cmd_SET_SERVO().  (Specifically, call toolhead.get_last_move_time(), call self.spi.get_mcu().print_time_to_clock(), pass that to self.spi.spi_send(..., minclock=clock) .)
2. Once the command is time synchronized, then init_delay_time is not needed (users can instead add a G4 to their scripts).
3. I don't think the tmc2208 change to a warning is correct.  I'd separate that out from the introduction of INIT_TMC.

-Kevin

**Comment by amblidex** [comment]
Thanks for the review. It does seem better to be able to use G4 for timing instead of internally for INIT_TMC and I can make that change. How do we deal with providing a delay for init during Klipper startup if the power is configured to be turned on immediately at startup? Is there any other way beside how I have it now with the callback request during `klippy:connect`?

Ok, will revert the tmc2208 exception/warning change. Are you saying that halting the system is the desired behavior? If so, how do we avoid this situation if the printer is started with power off and the tmc2208 driver tries to initialize automatically as it does right now?

**Comment by amblidex** [comment]
Kevin, also for the 2208 driver - is there a way to schedule sending of the serial commands with the clock time like there is for SPI communications? It wasn't obvious to me if there is.

**Comment by KevinOConnor** [comment]
> How do we deal with providing a delay for init during Klipper startup if the power is configured to be turned on immediately at startup?

Perhaps I've misunderstood the goal, but I'm not sure we should do that.  As I understand it, the trinamic drivers require motor power to be on prior to spi/uart power.  So, it's an error to do otherwise and it is fine for Klipper to report an error.  The user can clear the error by issuing a RESTART command.

>  is use of "print time" valid during the connect event, or is the callback needed?

It is not valid to call toolhead.get_last_move_time() from the init nor the connect methods.  In this particular case, it's possible to use a time of 0.0 to effectively schedule the transmission as soon as possible.

> for the 2208 driver - is there a way to schedule sending of the serial commands with the clock time like there is for SPI communications? 

That's not easy to do right now.  A simple alternative would be to call toolhead.wait_moves() at the top of cmd_INIT_TMC() instead of doing explicit time scheduling.

-Kevin

**Comment by amblidex** [comment]
> Perhaps I've misunderstood the goal, but I'm not sure we should do that. As I understand it, the trinamic drivers require motor power to be on prior to spi/uart power. So, it's an error to do otherwise and it is fine for Klipper to report an error. The user can clear the error by issuing a RESTART command.

I think we do have a little disconnect here. Ok, to back up all the way, if you want to use an ATX power supply with RAMPS and Klipper, one needs to define an `output_pin` that controls the ATX power supply. VCC to RAMPS and the TMC chips is provided by the Arduino, but VM and other higher power components are connected to the ATX supply. VM needs to be enabled and some time needs to pass after the ATX supply is turned on for the voltage to stabilize and for the TMC chips to accept initalization.

Case 1 - `output_pin` for ATX enabled at start with `value: 1`
1) Klipper is started
2) Hopefully `output_pin` is executed first and ATX power is enabled
3) Initialization of TMC drivers executed from module init/connect. However this fails because not enough time has passed since enabling ATX/VM in step 2. TMC2103 init fails silently, but TMC2208 init throws exception and halts Klipper.

_Desired behavior_ - everything starts up, powers up and is successfully initialized
_Current workaround_ - restart Klipper every time one starts up the printer, since init will succeed the second attempt because ATX/VM is now already enabled before startup
_Enhancement needed_ - delay on TMC init at startup

Case 2 - `output_pin` for ATX disabled at start with `value: 0`
1) Klipper is started
2) Init of TMC drivers executed from module init/connect. TMC2103 fails silently, but TMC2208 throws exception and halts Klipper.

_Desired behavior_ - Klipper is able to start up, and user is later able to enable power and have the TMC chips initialized when ready to use the printer via M80 macro. This is how I prefer to use my printer and how I had it set up with Marlin.
_Current workaround_ - none possible
_Enhancement needed_ - start Klipper without successful TMC driver init, and INIT_TMC command to allow drivers initialization on demand

**Comment by KevinOConnor** [comment]
Alas, I don't know of a good way to accomplish that.  Delays during the init sequence could result in race conditions (g-code moves read and processed prior to the init sequence being sent).

This is further complicated by the bad behaviour of the tmc2208 in standalone mode.  The code needs to make sure it can program the tmc2208 as otherwise the drivers will run in standalone mode where there is a good chance they will fail mid-print.  So, just printing a warning is definitely not sufficient.

Longer term, with some host code reorganization, it may be possible to catch the motor enable event and initialize the tmc driver at that point.

-Kevin

**Comment by amblidex** [comment]
I've pared down my PR to just adding INIT_TMC. Doesn't solve the startup init problem, but having INIT_TMC will improve usability for users that use the 2103/2208 driver chips with software switchable power supplies.

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.  If there are no further comments I'll look to commit in the next couple of days.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I squashed these patches and merged them (commit c039b33f).

-Kevin

**Comment by AxMod3DPrint** [comment]
Thanks for this @amblidex it's been bugging me since I reported the issue in #497 but I may not have explained it correctly and I'm no programmer so I had no idea where to start...

**Pull request closed without merging**
