### PR TITLE
Update stm32f0 libs 

### PR DESCRIPTION
**Pull request by clearchris**
ADC on stm32f070 doesn't work without this library update.  

Unfortunately, the CAN HAL changed, this library update breaks CAN.  I'll take a look at stm32f0 CAN.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  As we discussed on IRC, I think it would be worthwhile to see if new stm32 ports could be integrated into the stm32/ directory.  I'm concerned about the quality of the stm32 hal libraries and would generally prefer to not rely on them.

I've created a work branch with a mock up of stm32f070 support:

git fetch ; git checkout work-stm32f0-20190916

This is very primitive and only compile tested.  (It's unlikely to work on real hardware.)  However, hopefully it demonstrates how the stm32f070 could be integrated into the stm32/ code.

Cheers,
-Kevin

**Comment by KevinOConnor** [comment]
Any updates on this?

-Kevin

**Comment by clearchris** [comment]
Yes, it's not currently working, I'm going through my list of usual stuff, I should have a report back to you soon.

**Comment by KevinOConnor** [comment]
FYI, we were able to bring up usb on a tsop20 stm32f042 chip on the (recently updated) work-stm32f0-20190916 branch.  So, I suspect the stm32f070 should now be close to working.

-Kevin

**Comment by clearchris** [comment]
So you ended up using the hal startup scripts, eh?  I have been digging through the common one, haven't found out what in particular was causing the problem, but if you are ok using the hal scripts, that's fine with me too.  My build isn't even reaching main() before it hits DefaultHandler and endlessly loops.

I'll try the new build and report back.  IIRC, the clocks are slightly different than stm32f042, but if I can get to main() I'll have the other issues resolved quickly.

Thanks!  C


________________________________

**Comment by KevinOConnor** [comment]
The work-stm32f0-20190916 branch is still bare metal - some errors were found in the usbfs.c and clock bring-up which were fixed.

-Kevin

**Comment by clearchris** [comment]
Ok, latest usb changes appear to work.  Clocks also seem to work.  Working on getting stm32f0 adc working so I can test fully.  Thanks!

**Comment by KevinOConnor** [comment]
FYI, I've merged in the code on the work-stm32f0-20190916 branch into the master branch.

-Kevin

**Comment by clearchris** [comment]
Withdrawn because of the stm32f0 branch being depricated in favor of stm32 common code.

**Pull request closed without merging**
