### PR TITLE
Add example configs for fysetc spider board

### PR DESCRIPTION
**Pull request by GerogeFu**
Add example configs for fysetc spider board

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In order for me to commit there would need to be a signed-off-by line in the commit message - see: https://www.klipper3d.org/Overview.html .  The change would also need to pass the build tests.

The generic-fysetc-spider-voron2.cfg wouldn't be a good candidate for the master Klipper branch (as we only commit "stock" printer configs to the github repository).  The generic-fysetc-spider.cfg would be a useful addition though.  The non-stock configs can be shared on the discourse forum - there's some info on this at: https://www.klipper3d.org/Example_Configs.html

-Kevin

**Comment by GerogeFu** [comment]
Ok , i see , what do i need to do ? Make another PR or rebase with a new PR and force push ?

**Comment by GerogeFu** [comment]
I made another PR : https://github.com/KevinOConnor/klipper/pull/4192

**Comment by KevinOConnor** [comment]
Closing this as the spider config was merged as part of #4192 .

-Kevin

**Pull request closed without merging**
