### PR TITLE
example for shared hot end dual extruder

### PR DESCRIPTION
**Pull request by ld3300**
Add 2 sample usages for tool changes.  One minimalist and one with filament position tracking variables.

Signed-off-by: David Smith davidosmith@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Hi.  I'd recommend adding these types of examples to `sample-multi-extruder.cfg` or `sample-idex.cfg`.  I'd keep `sample-macros.cfg` for more generic macros (not specific to multiple extruders).

That said, I don't understand what these macros do or why a user would want them over the existing examples in `sample-multi-extruder.cfg` / `sample-idex.cfg`.  Also, I noted some typos and incorrect syntax in the examples - before adding something like this we'd need to make sure it was "battle tested" as an incorrect example is likely to cause confusion.

Cheers,
-Kevin

**Comment by ld3300** [comment]
Thanks Kevin,

Give me a bit to check out your notes.  Appreciate it as always.

-David

**Comment by DroneMang** [comment]
Thank you for working on this.  The idex and multi extruder examples are useful but would require tweaking.  Tracking the location of filament is useful as you don't have to make sure which filament is loaded before the print, otherwise the filaments would run into each other or not be in the nozzle so jams or you miss the first 20 mm of filament in the print.  I may be able to test this later.
-DroneMang

**Comment by ld3300** [comment]
What I was looking at doing was adding the info to the multi extruder example file.  I've been travelling, so I'm a bit slow.  I'm actually going to close this commit for now, to make Kevin's life easier.  When I have figured out the best minimal way to add the example I will open a new PR.

-David

**Pull request closed without merging**
