### PR TITLE
add support for BTT mot-exspander

### PR DESCRIPTION
**Pull request by Coffee0297**
Hello, just a config for the mot-exp that plugs in to the display headder and gives 3 more stepper outputs.

Signed-off-by: Tonny Møller tonn0297@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I think this file should be named "sample-bigtreetech-exp-mot.cfg" so that it is similar to the other config files.  Also, it would be preferable to not copy the documentation from other config files (as doing so introduces a maintenance burden when we make changes to the documentation as we then have to find every copy and change that).  Instead, I'd add "# See the example.cfg file for a description of available parameters." to the top of the file.

-Kevin

**Comment by Coffee0297** [comment]
i changed the line and renamed. what do you mean by the "copy the documentation from other config files"? the pins are defined and can't change with user hardware config. or did you just mean to add the line so if the description for the individual lines change you don't have to change all the files?

Kind regards Tonny

**Comment by KevinOConnor** [comment]
> what do you mean by the "copy the documentation from other config files"? 

The new file has:
```
# Pin names may be preceded by an '!' to indicate that a reverse polarity
# should be used (eg, trigger on low instead of high). Input pins may
# be preceded by a '^' to indicate that a hardware pull-up resistor
# should be enabled for the pin.
```
which appears to be copied from example.cfg.  I generally prefer to avoid that.

-Kevin

**Comment by Coffee0297** [comment]
Thats understandeble 👍 that shuld be gone now.
Kind regards Tonny

**Comment by KevinOConnor** [comment]
Thanks.  The change is fine.  However, it looks like something weird happened with the editor you used - the file's newlines look to be corrupted.  The file should have a single "unix style" newline character (ascii 0x0a) at the end of each line.

-Kevin

**Comment by Coffee0297** [comment]
Yea i just saw that. i used the online text editor, that apparently created some issues. shuld be fixd now.

Kind regards Tonny

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by phentrophil100** [comment]
Hello , what CS pin and serial TX i can use for m1,m2,m3?

**Comment by rubirides-dev** [comment]
Sorry for my question,  where do you put this cfg file? I have the EXP board connected, i enabled -#define HAS_BTT_EXP_MOT 1
but the motor connected to it doesnt work???
please help

**Comment by kyaron** [comment]
Sorry for my question, where do you put this cfg file? I have the EXP board connected, i enabled -#define HAS_BTT_EXP_MOT 1
but the motor connected to it doesnt work???
please help

**Comment by Coffee0297** [comment]
> 
> 
> Sorry for my question, where do you put this cfg file? I have the EXP board connected, i enabled -#define HAS_BTT_EXP_MOT 1
> but the motor connected to it doesnt work???
> please help

https://github.com/KevinOConnor/klipper/blob/master/config/sample-bigtreetech-exp-mot.cfg 
shuld tell you all you need
#define HAS_BTT_EXP_MOT 1 is a marlin command

**Pull request merged**
