### PR TITLE
Add BIBO2 Touch Printer

### PR DESCRIPTION
**Pull request by coryking**
Added basic configuration for a BIBO2 Touch printer.

Commented out the chunks you'd want if you were setting up a BLTouch probe.

Signed-off-by: Cory R. King <me@coryking.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Please see the example config file guide at: https://www.klipper3d.org/Example_Configs.html

-Kevin

**Comment by coryking** [comment]
I’ll get this updated in the next few days, thanks!

**Comment by coryking** [comment]
Also need to validate that the rotation_distance is correct. This config came from a FB group for my printer and was slightly modified by me.

**Comment by coryking** [comment]
Hey @KevinOConnor, I think I'm done. Lemme know if you'd like to see any other changes!

**Comment by KevinOConnor** [comment]
Sorry, but this change doesn't seem to follow the guidelines at ( https://www.klipper3d.org/Example_Configs.html ) - for example - not using arduino aliases, not specifying host specific configs (like virtual_sdcard), missing the common header block describing the micro-controller at the top of the file, and others.  We want the example config files to look similar as that reduces our long-term maintenance burden.

-Kevin

**Comment by coryking** [comment]
Hey Kevin,

I'll take a look when I get some time! We'll get there eventually!

**Pull request closed without merging**
