### PR TITLE
Added example config for Ender 3 Pro with 32-bit Creality 4.2.2 board

### PR DESCRIPTION
**Pull request by mpfl**
Creality silently started shipping Ender 3 Pros with a 32-bit 4.2.2 board, similar to the Ender 3 V2's board. Differences being the older style LCD, and HR4988 drivers instead of shiny TMCs.

I just got my board fully working with BLTouch and LCD by borrowing from the Marlin example config.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  How does this config differ from the existing config/printer-creality-ender3-v2-2020.cfg ?

-Kevin

**Comment by mpfl** [comment]
The Ender 3 Pro has a traditional monochrome dot matrix LCD display, so I’ve added the pins for that. The Ender 3 V2 has a new touch screen instead.

The bigger difference is that the V2 has TMC2208 drivers, but the existing config/printer-creality-ender3-v2-2020.cfg does not seem to have those configured correctly.

**Comment by KevinOConnor** [comment]
Okay, thanks.  Commits will need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Also, maybe the file should be named: printer-creality-ender3pro-2020.cfg

-Kevin

**Comment by mpfl** [comment]
Sorry, hadn't come across that sign off practice before and I naughtily didn't read CONTRIBUTING.md before, well, contributing. Since you can't (or shouldn't) retrospectively change commit messages, I hope a comment on each commit will suffice.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
