### PR TITLE
Example config file for a stock 250mm build VORON2 printer

### PR DESCRIPTION
**Pull request by Boffgithub**
Example config file with comments, for a stock 250mm build VORON2 printer to be used as a base for creating working Klipper configs.
This matches the manual diagrams exactly for the controller layout and pins used.

Signed-off-by: Ben Warren boffdroid@gmail.com

### CODE REVIEW

**Comment by Boffgithub** [comment]
OK no problem, I think having a pointer to configs on the Voron repo for other sizes and controllers is a great idea.  As long as @Maglin is happy then we can either edit his or overwrite it with this one. 

I'll add the info about the other configs in the Voron repo to the comments at the top of this file anyway.

**Comment by KevinOConnor** [comment]
Any further update on this pull request?

-Kevin

**Comment by Boffgithub** [comment]
Just waiting for @Maglin to get back to me, I've messaged him for his thoughts on it.
If I get no response in the next day or two then I'll say to overwrite it, as it now has the links back to the Voron repo in the comments at the top of the file as suggested (and @Maglin config is in that repo too)

**Comment by Boffgithub** [comment]
Hi Kevin, yes can you please overwrite the existing VORON config and replace it with this version.  I have spoken with @Maglin and he's happy to do so.

Thanks

Signed-off-by: Ben Warren [boffdroid@gmail.com](mailto:boffdroid@gmail.com)

**Comment by KevinOConnor** [comment]
I'm fine with updating the existing config file.  This pull request should perform that work though.  Also, the config should be updated to address the whitespace errors that are causing travis-ci to fail the build.

As for the changes itself, I'd prefer that the example config files not repeat default values.  (So, for example, if there is a "max_power=1" default then I'd prefer the config to not specify "max_power=1".)  I'd also prefer if the example configs did not copy-and-paste parameter descriptions from the main config documentation.  (Doing so adds an ongoing maintenance burden as then we need to modify many locations if the documentation changes.)

Thanks,
-Kevin

**Comment by Boffgithub** [comment]
Hi Kevin

The idea behind the parameter descriptions was to try and make it easier for newcomers to use and to try and cut down on the repeated questions that get asked.  Not everyone reads the documentation - as I'm sure you know ;)

Anyway, I've removed all the whitespace and it seems that Travis is happy now.  I've also removed all of the default values and all of the duplicate parameter descriptions.  If there is anything I've overlooked please let me know and I'll get it sorted.

I've also deleted the original VORON2 config file, so this PR should do it all now.  Although Travis is giving an error now that I've deleted the file.  My apologies if 've done it wrong I don't have much experience using Git.

Cheers
Boff
Signed-off-by: Ben Warren [boffdroid@gmail.com](mailto:boffdroid@gmail.com)

**Comment by KevinOConnor** [comment]
Thanks.  The reason for the Travis errors is that test/klippy/printers.test needed to be updated for the new config file name.  I fixed it up, made a couple of minor changes to the config, and committed this change (commit a03e3180).

-Kevin

**Pull request closed without merging**
