### PR TITLE
Add support for STM32F072 (used in the TurboCAN board)

### PR DESCRIPTION
**Pull request by henrikssn**
See https://github.com/henrikssn/TurboCAN

Temp compensation logic is common across STM32F0: https://techoverflow.net/2015/01/13/reading-stm32f0-internal-temperature-and-voltage-using-chibios/

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .

Separately, I'm not sure why the stm32f070 specific temperature code was removed.  That chip is different from the stm32f042/72.

-Kevin

**Comment by henrikssn** [comment]
> Thanks. Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .
> 
> Separately, I'm not sure why the stm32f070 specific temperature code was removed. That chip is different from the stm32f042/72.
> 
> -Kevin

You are correct, the stm32f0x0 seems to be special compared to the stm32f0x1/0x2/0x8. I'll add that code back and rename the methods so make this clear.

**Comment by henrikssn** [comment]
> Thanks. Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .
> 
> Separately, I'm not sure why the stm32f070 specific temperature code was removed. That chip is different from the stm32f042/72.
> 
> -Kevin

I have applied both of your suggestions.

-Erik

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
