### PR TITLE
config for Anet A8 Plus.

### PR DESCRIPTION
**Pull request by gufi**
I've created a config file for the anet a8 plus. very similar to the anet. with a few tweaks for the pid tuning values, print volume and steps

### CODE REVIEW

**Comment by gufi** [comment]
This PR cannot currently be merged. I finally got every thing up and running but i had to disable the printer screen entirely in order to get the thing to stop sending pause commands. I'm not sure what i need to do to configure the screen properly but for now i've disabled it since octoprint does every thing anyway

**Comment by KevinOConnor** [comment]
Okay - I'll hold off on merging.

The most recent configs now define aliases for the EXP1 and EXP2 pins (see, for example: 
https://github.com/KevinOConnor/klipper/blob/8f5c15d4dc6a6f592a09e1d5ed80516d5deb8100/config/generic-ramps.cfg#L86 ).  So, if you can find the pin definitions for the plugs, then you should be able to just cut-and-paste the HD44780 definition from sample-lcd.cfg.  I would comment out all the buttons until you can get the display up and running.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by gh90st** [comment]
Hello, 
I found the correct configuration for the display and encoder of the Aner A8 plus.
you can find it here below.

**Pull request closed without merging**
