### PR TITLE
menu: Extended the functionality of Octoprint menu

### PR DESCRIPTION
**Pull request by crzcrz**
This PR extends the functionality of the _Octoprint_ menu by displaying the list of Octoprint files in it and starting printing when a file is selected.

This allows to quickly start a print without reaching for a computer or a smartphone (if the printer is equipped with an LCD).

Signed-off-by: Stanislav Kljuhhin <stanislav.kljuhhin@me.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Certainly an interesting idea.  I'd like to get feedback to see what others think of this module.

Some minor notes:
- The existing menu should not be replaced with the octoprint menu (as that would change behaviour for users that don't use this new module).
- The contents of example-octoprint.cfg should be added to the config/example-extras.cfg document and not be a new file.
- If we were to merge this, we'd need to update the virtualenv requirements, as I suspect most people will not know how to add an additional python module.
- If a new command is added it should also be documented in docs/G-Codes.md
- Ideally, the MenuOctoprint() code could be added to extras/octoprint.py instead of to the menu code (but I'm not sure if that's easy to do or not - perhaps @mcmatrix knows).

-Kevin

**Comment by fxbisto** [comment]
For those of us using the virtual SD card function: does this add any extra functionality?

**Comment by crzcrz** [comment]
@KevinOConnor thank you for taking the time to review this.

> * The existing menu should not be replaced with the octoprint menu (as that would change behaviour for users that don't use this new module).
> * Ideally, the MenuOctoprint() code could be added to extras/octoprint.py instead of to the menu code (but I'm not sure if that's easy to do or not - perhaps @mcmatrix knows).

All the extra functionality in the octoprint menu is strictly conditional. I implemented it such that if the `octoprint` module is not configured the behaviour of the menu is unchanged. I would like to believe that this also addresses your second point.

> * If we were to merge this, we'd need to update the virtualenv requirements, as I suspect most people will not know how to add an additional python module.

I was not sure how you would take such dramatic changes to the installation scripts, which is the only reason I did not touch the virtualenvs and added a manual installation note to the example configuration instead. I will update the PR to address this and the two points below, to keep it up to date.

> * The contents of example-octoprint.cfg should be added to the config/example-extras.cfg document and not be a new file.
> * If a new command is added it should also be documented in docs/G-Codes.md

**Comment by crzcrz** [comment]
> For those of us using the virtual SD card function: does this add any extra functionality?

It offers an alternative to the virtual SD functionality. Potentially it can be extended to do even more, such as displaying some extra information for the file about to be printed, like estimated print time for example.

I know that one can configure the virtual SD and point it to the octoprint upload folder, but to me it always seemed like a workaround, given that octoprint provides a nice API.

**Comment by fxbisto** [comment]
I use the virtual SD because it prints faster, and with the "Detailed Progress" plugin it still prints ETA's and such on the LCD during an SD print.
Printing directly from OP causes micro-stutters, leaving blobs and zits on my prints even though I'm using a Pi 3B+
I can see the benefits of your implementation for those with an LCD who don't use virtual SD with 'Detailed Progress' though :)

**Comment by alekssobolewski** [comment]
@crzcrz I tried to implement your solution, but it crashes klipper as soon as I press the encoder button on LCD.

Here is the fragment of log file:
```python
Unhandled exception during run
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 171, in run
    self.reactor.run()
  File "/home/pi/klipper/klippy/reactor.py", line 176, in run
    g_next.switch()
  File "/home/pi/klipper/klippy/reactor.py", line 203, in _dispatch_loop
    timeout = self._check_timers(eventtime)
  File "/home/pi/klipper/klippy/reactor.py", line 82, in _check_timers
    t.waketime = t.callback(eventtime)
  File "/home/pi/klipper/klippy/reactor.py", line 22, in invoke
    self.callback(eventtime)
  File "/home/pi/klipper/klippy/extras/buttons.py", line 105, in <lambda>
    (lambda e, s=self, b=ord(b): s.handle_button(e, b)))
  File "/home/pi/klipper/klippy/extras/buttons.py", line 111, in handle_button
    callback(eventtime, (button & mask) >> shift)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 1587, in click_callback
    self._short_click_callback(eventtime)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 1594, in _short_click_callback
    self.begin(eventtime)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 1176, in begin
    self.root.populate_items()
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 310, in populate_items
    self.append_item(name)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 298, in append_item
    item.populate_items()
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 853, in populate_items
    self._populate_files()
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 848, in _populate_files
    'width': (self._manager.cols-1)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 476, in __init__
    super(MenuCommand, self).__init__(manager, config, namespace)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 328, in __init__
    super(MenuItem, self).__init__(manager, config, namespace)
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 32, in __init__
    self._name = self._asliteral(config.get('name'))
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 156, in _asliteral
    s = str(s).strip()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)
```

How I tried to implement it:
- created file octoprint.py in ~/klipper/klippy/extras
- edited menu.py
- changed [menu __ octoprint] type to octoprint in menu.cfg
- added [octoprint] section with API key in printer.cfg
- installed requests and logging in ~/klippy-env
- I sourced the code from 13a974e5c655aff16af09497a812fa8468c6a3c6

**Comment by crzcrz** [comment]
@alekssobolewski It looks like you have non-ascii characters in one of your file names.

I will try to reproduce and fix this.

**Comment by alekssobolewski** [comment]
@crzcrz Thanks for interest. Do you mind the file names stored in /api/files? Then it may be the case, I have there some files with Polish characters like "ą" or "ł".

**Comment by crzcrz** [comment]
@alekssobolewski If you are at your printer now and have a bit of time, may I ask you to try enabling the Virtual SD card and confirming that it also crashes upon populating the menu if there are files with Unicode names? You will have to revert the changes from this PR, or course.

```
# A virtual sdcard may be useful if the host machine is not fast
# enough to run OctoPrint well. It allows the Klipper host software to
# directly print gcode files stored in a directory on the host using
# standard sdcard G-Code commands (eg, M24).
#[virtual_sdcard]
#path: ~/.octoprint/uploads/
#   The path of the local directory on the host machine to look for
#   g-code files. This is a read-only directory (sdcard file writes
#   are not supported). One may point this to OctoPrint's upload
#   directory (generally ~/.octoprint/uploads/ ). This parameter must
#   be provided.
```

**Comment by alekssobolewski** [comment]
@crzcrz I have enabled the VSD, and it is working properly. All files are listed in the new "SD Card" tab.

**Comment by crzcrz** [comment]
@alekssobolewski How do Unicode characters like "ą" or "ł" look on the printer LCD?

**Comment by alekssobolewski** [comment]
@crzcrz After renaming a random file to "łą.gcode" it was displayed as Chinese characters on the LCD :stuck_out_tongue:

**Comment by KevinOConnor** [comment]
Thanks.  I apologize for my delay in re-reviewing.  The changes look fine to me.  @mcmatrix - are you okay with the changes to menu.py?

-Kevin

**Comment by mcmatrix** [comment]
Hi, the menu changes are fine, but I suggest to wait until # 1518 is ready.

**Comment by KevinOConnor** [comment]
FYI, with the merge of #2344 , the menu has now been converted to use Jinja2 templates.

-Kevin

**Pull request closed without merging**
