### PR TITLE
toolhead: Fix potential non-smooth velocity for delayed moves

### PR DESCRIPTION
**Pull request by dmbutyugin**
Background: decisions about delaying trapezoid generation for moves
depend on 'smoothed' acceleration computation. Attainable velocities for
each move, on the other hand, are computed using the full acceleration.
Then it is possible that the start velocity for the delayed move is
smaller than its end velocity, e.g. if start velocity is limited by max junction
velocity but the 'smoothed' velocity isn't limited by it yet. Limiting mc_v2
and me_v2 by ms_v2 can lead to velocity jumps between the moves,
usually of small magnitude.

Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Do you have a test case that shows this problem?

I'm confused by the use of max() - there should never be a move with a cruising velocity greater than its start or end velocity.

-Kevin

**Comment by dmbutyugin** [comment]
Yes, here's the simple test-case:
```
M82
G92 E0  ; see below
G28
SET_VELOCITY_LIMIT ACCEL=300 ACCEL_TO_DECEL=100 SQUARE_CORNER_VELOCITY=20
G1 F6000 X10 Y10 Z1  ; Z does not matter
G1 F100 E0.001  ; to make sure the next move starts at 0 mm/sec
G1 F6000 X20 Y10
G1 F6000 X20.46984631 Y10.171010072  ; 20 degrees turn, 0.5 mm len
;  velocity jump here from 20.624 to 24.495
G1 F6000 X21.409538931 Y10.513030215  ; the same direction, 1 mm
G1 F100 E0
```

You can either log and check the arguments passed to Move.move method to see the velocity jump, or have a check like [this](https://github.com/dmbutyugin/klipper/commit/6b3cf52911dbc06056e2e86058738a0d7ceb1452) to get a run-time error.

I also have a real-world report with ACCEL=1000 and ACCEL_TO_DECEL=500, but I made this case with not very realistic accelerations just to keep it very simple.

**Comment by dmbutyugin** [comment]
The way I read that code, it is expected that the moves in delayed[] list always decelerate, that's why
```
mc_v2 = min(peak_cruise_v2, ms_v2)
```
which then makes sense. The problem is they always decelerate when using accel_to_decel acceleration, with full acceleration and the right junction speeds me_v2 can turn out to be larger than ms_v2, in which case the move in delayed[] list should accelerate a bit to match the next move's ms_v2.

**Comment by KevinOConnor** [comment]
Thanks.  Definitely a bug.

I don't think the fix is to accelerate in the delayed list though - the delayed list shouldn't have any accelerations (otherwise it would violate the maximum "acceleration to deceleration" invariant).

As an alternative I think the maximum velocity limits could be carried forward - something like:
```diff
--- a/klippy/toolhead.py
+++ b/klippy/toolhead.py
@@ -157,8 +157,9 @@ class MoveQueue:
                     if delayed:
                         # Propagate peak_cruise_v2 to any delayed moves
                         if not update_flush_count and i < flush_count:
-                            for m, ms_v2, me_v2 in delayed:
-                                mc_v2 = min(peak_cruise_v2, ms_v2)
+                            mc_v2 = peak_cruise_v2
+                            for m, ms_v2, me_v2 in reversed(delayed):
+                                mc_v2 = min(mc_v2, ms_v2)
                                 m.set_junction(min(ms_v2, mc_v2), mc_v2
                                                , min(me_v2, mc_v2))
                         del delayed[:]
```

-Kevin

**Comment by dmbutyugin** [comment]
Thanks, Kevin. I was thinking about this solution as well, but at first I though that the same problem could occur after the last delayed moved. After thinking about it more, I see that this cannot happen. So I 'fixed' the fix.

**Comment by dmbutyugin** [comment]
BTW, do you want to add the test somewhere? Though the current Klipper code does not perform any validation of this kind AFAICT.

**Comment by KevinOConnor** [comment]
Okay, thanks - commit 9fcd3e75.

> BTW, do you want to add the test somewhere?

I'm not sure this would fit well in the regression test cases.  We could add a runtime check, but I believe this code was on the "fast path" for performance.

Separately, I know this code is not easy to understand (I struggle with it myself, and I wrote it), so I appreciate you tracking this down and reporting it.

-Kevin

**Comment by dmbutyugin** [comment]
OK, thanks! 
> I'm not sure this would fit well in the regression test cases...

Yes, I agree with this.

**Pull request closed without merging**
