### PR TITLE
HD44780 new text glyph - fan

### PR DESCRIPTION
**Pull request by mcmatrix**
New custom character `FAN` for HD44780 display.
image

### CODE REVIEW

**Comment by mcmatrix** [comment]
Strange, in Travis site it's passed but here it's in pending state.

**Comment by KevinOConnor** [comment]
Thanks.  If we're adding a new icon it would be great to have that icon used in the main status display.

I'm a little leery about adding the \07 hack to the menus.  How about we update the menus to use write_glyph() (either directly or indirectly) prior to adding the fan?

Travis can be a little flaky - I restarted the build which seems to have fixed it.

-Kevin

**Comment by mcmatrix** [comment]
That menu update to use new display method was on my list.
Not just prior to this but I can rearrange.
Don't merge this yet.

I'll arrange all the necessary changes for the menu system and the default menu.

**Comment by mcmatrix** [comment]
Actually, I was thinking. You could still merge this PR then the icon will be already in the system.
Later when changing menu system and default menu I'll change anyway those `\x0X` to
icon names. 
If it's okay for you.

**Comment by KevinOConnor** [comment]
Okay, thanks.

-Kevin

**Pull request merged**
