### PR TITLE
Features: sample-macros.cfg, M118, SD card sort

### PR DESCRIPTION
**Pull request by ndupont-net**
As advised, here are my contributions through a pull request :

Creation of sample-macros.cfg including the implementation of M300 (Play Tone)

Implementation M118 (Serial print), a revised ECHO command that doen't echo its own gcode call.
This one allows to work with the Action Commands plugin of Octoprint.

Sorted file list, by creation date, latest appearing first when using virtual_sdcard. Really usefull when using the LCD, no effect on the way Octoprint lists the files.

Signed-off-by: Nicolas Dupont <ndupont@ndupont.net>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I made a couple of minor comment changes and committed the M300 work (commit ccb660a0).

I'm not sure about the M118 change - in general the goal is to only add support for traditional g-codes that are produced by common 3rd party software (when in their standard configurations) as described in: https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md .  I'm not aware of any software that produces M118 by default, so I'm not sure it makes sense to add it to Klipper.  Also, when adding new functionality to Klipper we prefer to add it in "extras" modules - not in the main gcode.py code.

The change to virtual_sdcard.py is fine, but it should be modified to follow the indentation of the rest of the file (in particular, wrap lines to no more than 80 characters).  Also, please submit it as a separate pull request as it's unrelated to the M300 changes in this pull request.

Thanks again,
-Kevin

**Comment by ndupont-net** [comment]
Excellent, thanks!

I'll check the proper way to wrap lines to 80 char. As I'm a total newbie in Python, I just had no clue.

Regarding M118, it comes more to a possibility to make the most of all the Octoprint action commands features, and 1.3.10 even comes further with the default addition of Command prompt.
As Klipper is quite designed to be used with Octoprint, it makes sense to follow the Octoprint train IMHO.

But again, a revised ECHO function that wouldn't reply the 'ECHO ' command back would be sufficient (M117 style) and a GCODE macro could to the last wrapping to M118.

Greetings

Nicolas

**Comment by daveliberato** [comment]
Me and a collegue were having problems with integrating M118 with Klipper to show some question boxes in Octoprint. Will give this a try.

**Comment by KevinOConnor** [comment]
Thanks, but please post the virtual sdcard patch in a new github pull-request.  It's hard to review/accept the change when it is combined with other unrelated changes.

-Kevin

**Comment by KevinOConnor** [comment]
Are there any further updates on this?

-Kevin

**Comment by ndupont-net** [comment]
Hi Kevin, I will post an additionnal pull request asap, we can close this one.

Greetings

Nicolas

**Pull request closed without merging**
