### PR TITLE
Update font8x14.py - for uc1701 displays

### PR DESCRIPTION
**Pull request by mbgroot**
Replacing the font for uc1701 display with a Terminus (http://terminus-font.sourceforge.net) for better display on the screen.

Signed-off-by: Evgeny Zelenin <m-b-g@yandex.ru>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Pull requests need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

As discussed in issue #1564 I suspect we'd need to make the font choice configurable (as some may prefer the existing font).  Also, it's important to me that the code copyright and origin be well documented in the code.  So, if this font originated from http://terminus-font.sourceforge.net then the code should relay that along with its copyright requirements.

Cheers,
-Kevin

**Comment by mbgroot** [comment]
> Pull requests need to have a signed-off-by line

I added to the first message, okay?

**Comment by KevinOConnor** [comment]
Thanks.  The signed-off-by line is fine.  What are your thoughts on my two comments at: https://github.com/KevinOConnor/klipper/pull/1590#issuecomment-488382869 ?

-Kevin

**Comment by mbgroot** [comment]
Choosing the font is good. But where to do it - in the configuration file?

> What are your thoughts on my two comments

The second comment is about the font license?

**Comment by KevinOConnor** [comment]
What's the status of this PR?  It sounds good to be able to have additional fonts in Klipper, but the code would need to be configurable and the copyrights/origin would need to be clear.

-Kevin

**Comment by mbgroot** [comment]
> What's the status of this PR? It sounds good to be able to have additional fonts in Klipper, but the code would need to be configurable and the copyrights/origin would need to be clear.

I won't be able to choose a font - my programming skills aren't enough. Terminus Font is licensed under the SIL Open Font License - https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

**Comment by KevinOConnor** [comment]
Okay, thanks.  If I get a chance I'll try to add an option to the code to allow the user to select the current font.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive - I can reopen if I (or someone else) gets a chance to make the fonts configurable.

-Kevin

**Pull request closed without merging**
