### PR TITLE
Basic Bash uninstall script for RasPi

### PR DESCRIPTION
**Pull request by AxMod3DPrint**
Basic BASH uninstall script, will need checking by users before merge. As per discussion in #867

Signed off by Ax Smith-Laffin (AxMod3dPrint) - ax@darknetweb.co.uk

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!  I'll look to commit after the v0.7.0 release.

One suggestion, out of an abundance of caution, would be to replace the last three rm lines with:
```
echo "To fully remove the Klipper software and configs, run the following command:"
echo "  rm -rf ~/klippy-env/ ~/klipper/ ~/printer*.cfg
```

-Kevin

**Comment by AxMod3DPrint** [comment]
Either way really. Although if you're going to uninstall Klipper fully, my preference is to fully automate it over having the end user run the uninstall and then have to copy/paste another line. This is why there is the check at the start.  I can change it to the following

```
echo  "Please make sure you have backed up your configs should you wish to re-install."
read -p "This will uninstall Klipper from your system, are you sure?" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
```

**Comment by KevinOConnor** [comment]
Thanks.  I've given this some further thought, and I don't feel comfortable issuing an "rm -rf" on a user directory in a script.  (For fear, the user may have placed something they value in one of those directories.)  I can make the change if you wish.  As for the big warning - another option would be to not warn at all and just remove the Klipper system files (as there is no real harm in removing those system files).

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I made the above change (and a few minor additional changes) and committed the uninstall script (0ba1f510).

-Kevin

**Comment by KevinOConnor** [comment]
Any further comments on this?

-Kevin

**Pull request closed without merging**
