### PR TITLE
Add ezboard configuration

### PR DESCRIPTION
**Pull request by th3fallen**
Signed-off-by: Clark Tomlinson <fallen013@gmail.com>

### CODE REVIEW

**Comment by th3fallen** [comment]
Third try is the charm, now with working default screen pinouts thanks to @Apulo

**Comment by KevinOConnor** [comment]
Thanks, but it looks like the comments are cut-and-paste from the documentation - that becomes a maintenance burden.  This and other things to check for are at: https://www.klipper3d.org/Example_Configs.html

-Kevin

**Comment by th3fallen** [comment]
@KevinOConnor good callouts, should be resolved now

**Comment by th3fallen** [comment]
fixed those whitespace issues from the CI too

**Comment by KevinOConnor** [comment]
Thanks.  I see a bunch of differences between this config and the one provided by @twopuncakes at https://github.com/KevinOConnor/klipper/issues/2764#issuecomment-855345131 .  It seems having the tmc driver definitions would be useful.

@twopuncakes - would you be willing to sign-off on your config (as described at https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md (agree to the terms at https://github.com/KevinOConnor/klipper/blob/master/docs/developer-certificate-of-origin ).

-Kevin

**Comment by th3fallen** [comment]
> Thanks. I see a bunch of differences between this config and the one provided by @TwoPuncakes at [#2764 (comment)](https://github.com/KevinOConnor/klipper/issues/2764#issuecomment-855345131) . It seems having the tmc driver definitions would be useful.
> 
> @TwoPuncakes - would you be willing to sign-off on your config (as described at https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md (agree to the terms at https://github.com/KevinOConnor/klipper/blob/master/docs/developer-certificate-of-origin ).
> 
> -Kevin

With @twopuncakes permission i've merged our two configs into my PR so we should be good now.

**Comment by th3fallen** [comment]
stupid CI.... should be fixed now

**Comment by KevinOConnor** [comment]
Okay - I committed this example config file along with some minor fixes on top (commit f00281d1).

-Kevin

**Pull request merged**
