### PR TITLE
Add support for named [fan]s and gcode to control them

### PR DESCRIPTION
**Pull request by bondus**
Adds the option to name [fan]s and to control it with a new GCODE command SET_FAN_SPEED.
It is backwards compatible, an unnamed [fan] will still be controlled with M106 and M107.

This is useful for multi-head printers such as toolchangers or IDEX machines. 
The idea is that the SET_FAN_SPEED is used in GCODE macros to control the part cooling fans depending on what head is active.
Other uses are possible of course.

### CODE REVIEW

**Comment by bondus** [comment]
Sorry for the commit history mess. I'll study how to get a proper workflow for cleaner pull requests.

**Comment by KevinOConnor** [comment]
Thanks.  At a high-level the change seems useful to me.  I think it would be preferable to keep `[fan]` for the part cooling fan and introduce a new `[fan_generic my_fan]` for new fans.  This can be done by creating a new fan_generic.py module and importing fan.py from it (take a look at how heater_fan.py does this).

Also, I just committed some organizational changes to the fan.py code (commit 3a576086).  Hopefully that wont conflict too badly with your work.

-Kevin

**Comment by bondus** [comment]
Your commits did conflict with mine. 
I had it as [generic_fan] before, naming along the lines of other kind of fans. 
I'll rename as suggested and avoid the conflicts.

**Comment by bondus** [comment]
> I would suggest adding support for fan numbers for M106 & M107 via a Pnnn parameter, this is what is used in most slicers.

M106 and M107 can be implemented using gcode_macros. Combined with the T0, T1, T2... macros for an idex/toolchanger you can turn on/off fans when tool changing and have M106/M107 affect the current active tool. I could expand the example config files for IDEX to include these features.

Example snippets from a working IDEX config file:
```
[gcode_macro PARK_extruder1]
gcode:
    SET_FAN_SPEED FAN=extruder1_partfan SPEED=0
    {% if printer.toolhead.homed_axes == "xyz" %}
    SAVE_GCODE_STATE NAME=park1
    G90
    G1 X-68 F15000
    RESTORE_GCODE_STATE NAME=park1
    {% endif %}

[gcode_macro T1]
gcode:
    PARK_{printer.toolhead.extruder} # park current
    ACTIVATE_EXTRUDER EXTRUDER=extruder1
    SET_DUAL_CARRIAGE CARRIAGE=1
    SET_GCODE_OFFSET Y=0
    SET_FAN_SPEED FAN=extruder1_partfan SPEED={printer["gcode_macro M106"].fan_speed}

[gcode_macro M106]
rename_existing: M906
variable_fan_speed: 0
gcode:
    SET_GCODE_VARIABLE MACRO=M106 VARIABLE=fan_speed VALUE={params.S|float / 255.0}
    SET_FAN_SPEED FAN={printer.toolhead.extruder}_partfan SPEED={params.S|float / 255.0}
    M906 S{ params.S }

[gcode_macro M107]
rename_existing: M907
gcode:
    M106 S0
```
I should fix the pull request...

**Comment by SteveJWallace** [comment]
I just think if we are going to support M106, we should implement it as most slicers expect it to behave and we shouldn't require users to create macros to make it work as it is expected. This raises the effort for people to use klipper. For instance when you tell cura that you have two extruders and extruder 1 has fan 0 and extruder 2 has fan 1 it automatically let you set separate fan speeds and all of the fan control tweaks you can make per tool in Cura. It generates M106 Snnn and M106 P1 Snnn as appropriate.

> > I would suggest adding support for fan numbers for M106 & M107 via a Pnnn parameter, this is what is used in most slicers.
> 
> M106 and M107 can be implemented using gcode_macros. Combined with the T0, T1, T2... macros for an idex/toolchanger you can turn on/off fans when tool changing and have M106/M107 affect the current active tool. I could expand the example config files for IDEX to include these features.
> 
> Example snippets from a working IDEX config file:
> 
> ```
> [gcode_macro PARK_extruder1]
> gcode:
>     SET_FAN_SPEED FAN=extruder1_partfan SPEED=0
>     {% if printer.toolhead.homed_axes == "xyz" %}
>     SAVE_GCODE_STATE NAME=park1
>     G90
>     G1 X-68 F15000
>     RESTORE_GCODE_STATE NAME=park1
>     {% endif %}
> 
> [gcode_macro T1]
> gcode:
>     PARK_{printer.toolhead.extruder} # park current
>     ACTIVATE_EXTRUDER EXTRUDER=extruder1
>     SET_DUAL_CARRIAGE CARRIAGE=1
>     SET_GCODE_OFFSET Y=0
>     SET_FAN_SPEED FAN=extruder1_partfan SPEED={printer["gcode_macro M106"].fan_speed}
> 
> [gcode_macro M106]
> rename_existing: M906
> variable_fan_speed: 0
> gcode:
>     SET_GCODE_VARIABLE MACRO=M106 VARIABLE=fan_speed VALUE={params.S|float / 255.0}
>     SET_FAN_SPEED FAN={printer.toolhead.extruder}_partfan SPEED={params.S|float / 255.0}
>     M906 S{ params.S }
> 
> [gcode_macro M107]
> rename_existing: M907
> gcode:
>     M106 S0
> ```
> 
> I should fix the pull request...

**Comment by KevinOConnor** [comment]
I'm not sure what the status of this PR is.  The latest code on this branch doesn't actually add the SET_FAN_SPEED command.

Cheers,
-Kevin

**Comment by bondus** [comment]
Again sorry for the git mess. I'll improve my workflow for the next PR.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
