### PR TITLE
Use a median filter for temperature smoothing

### PR DESCRIPTION
**Pull request by KevinOConnor**
This change replaces the current "exponential average" temperature filter with a median filter.  A median filter is better at rejecting spikes, which is important for Smoothieboard users.  It shouldn't have any adverse impact, so the plan is to use the median filter for all boards.

This is a change to overall heater operation for all Klipper users.  So, testing on a variety of boards would be appreciated.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
To test this code, ssh into the host machine and run:

cd ~/klipper ; git fetch ; git checkout origin/work-median-filter-20190104 ; sudo service klipper restart

-Kevin

**Comment by derdigge** [comment]
Hello @KevinOConnor 

I tried that branch and it helps. Pins (all?) are grounded as mentioned in #842. The klippy log and config is atached here, so you get feedback on that patch.

Here is a screenshot. The left side is with master Branch and grouded pins (see klippy log)
The right side is with median-filter branch. PID autotune fails after two steps. The turnarrounds arent detected right due to noise i think.
unbenannt

The data is also available here in a spreadsheet, dont know if this helps.
[t0_screen.xlsx](https://github.com/KevinOConnor/klipper/files/2743030/t0_screen.xlsx)


Thanks for your work! Tomorrow i will apply two of theese boards to my main printer (Voron 2.1) and create the config for it. I would be happy to help debugging this. I will post an update here.

BR
derdigge

[klippy.log](https://github.com/KevinOConnor/klipper/files/2743020/klippy.log)

**Comment by KevinOConnor** [comment]
The PID_CALIBRATE command wasn't using the smoothed temperatures, so it wasn't able to function properly.  I've updated the branch with a change to PID_CALIBRATE.

cd ~/klipper ; git fetch ; git checkout origin/work-median-filter-20190104 ; sudo service klipper restart

Separately, your extruder temperature appears highly volatile - is the thermistor type correct?  Does the board use a standard 4.7K pullup?

-Kevin

**Comment by derdigge** [comment]
Hello @KevinOConnor 

never seen that high level of volatility. But as its a config from scratch it could be the case. I have this thermistor installed. 
https://www.amazon.de/gp/product/B06ZZFY8MK/ref=oh_aui_search_asin_title?ie=UTF8&psc=1

and in config i usaly use EPCOS 100K B57560G104F. Not sure if this is right. I never had to care about that on my atmega boards before.

I will check the pullup resistor as i will install 2 boards of this kind today and report back. The PID calibrate works not correct and delivers reasonable results BTW. For have stable temps i still have to increase the smoothing time to 5.0.

Thanks a lot, this is doing well so far.

BR
unbenannt

derdigge

**Comment by KevinOConnor** [comment]
FYI, a generic 100K thermistor is almost always a "NTC 100K beta 3950".

-Kevin

**Comment by KevinOConnor** [comment]
@derdigge - if you pull the code on the work-median-filter-no-raw-20190111 branch, does it make the temperature reports more or less stable for you?

cd ~/klipper ; git fetch ; git checkout origin/work-median-filter-no-raw-20190111 ; sudo service klipper restart

-Kevin

**Comment by derdigge** [comment]
printer is up and running with dual mcu and printing well. still not happy with the adc results. I need to build a new toolhead and some cable management things. Afterwards i will try your branch with new triangle labs hotend. I will report back then. Meanwhile another issue with that board occured. the usb restart dosent work. Maybe we can take care of that to improve klippersupport for that board also.

I can reset the boards on pi 3b+ with:

`echo '1-1' |sudo tee /sys/bus/usb/drivers/usb/unbind
#sleep 1
echo '1-1' |sudo tee /sys/bus/usb/drivers/usb/bind
`

but the rpi_usb method fails.

**Comment by derdigge** [comment]
@KevinOConnor not bad the results are good with your branch.
unknown

**Comment by derdigge** [comment]
after a pid calibrate and an hour of printing here are more screenshots and rawdata in excel.
un_1

maximum scaled:
un_2

data:
[data_work-median-filter-no-raw-20190111.xlsx](https://github.com/KevinOConnor/klipper/files/2751068/data_work-median-filter-no-raw-20190111.xlsx)

**Comment by KevinOConnor** [comment]
@derdigge - thanks.  Is that with the work-median-filter-no-raw-20190111 or with work-median-filter-20190104?  Does the "no-raw" addition improve things?

@mattthebaker - interesting.  So, if I understand you correctly, Smoothieware takes 128 samples over 128ms, ultimately discards half of them, and averages the remaining 64 samples?  For reference, the main Klipper code averages 8 samples over 8ms and does that every 300ms.  This median filter branch does the same, but then keeps a rolling window of (typically) 7 of these "300ms" measurements and uses the median from it.

Given this problem seems limited to the lpc176x chip, it might be worthwhile to try a median filter in its low-level gpio_adc_read() function.  The lpc176x adc is fast (only 6us per measurement), so we could try measuring 7 times for each 1ms measurement, discarding 6 of them via a median filter.  Only problem would be if the lpc176x noise corrupts all the measurements taken in a small time-frame.

-Kevin

**Comment by mattthebaker** [comment]
@KevinOConnor yes. They take 32 samples, discard the upper/lower quartiles, then average the middle 16.  That produces one oversampled measurement.  Then they do a rolling average of the last 4 of those measurements when the ADC value is readout.  The 32 samples happen consecutively (32ms), but the rolling average is only computed on read, so its dependent on how often the ADC is read.  If the ADC is read every 0.5s then the average is over 2s.

Here it is in code if that makes more sense: https://github.com/mattthebaker/Smoothieware-CHMT/blob/edge/src/libs/Adc.cpp#L95

Thanks for the primer on Klipper ADC reads and this branch.  The scheme is very similar with a fast and slow averaging.

Ideally you want to run the median filtering first thing in the filter chain, so that outliers are not averaged in.  It probably does belong in firmware and agree it makes sense as lpc176x only.

I have not studied the noise source specifically, but I think the risk is pretty high to sample over only 100us.  Something like a supply voltage dip could easily hit all the measurements.

I have a fast -- average O(n) -- median algorithm based on public domain code I could contribute, but if there is no desire to change n, a macro implementation is faster and simpler.

**Comment by mattthebaker** [comment]
I took a little look at the lpc176x adc code.  I'm not sure how I would go about issuing multiple reads in the Klipper timing system.  I pushed up my fast median finding algorithm in case it is useful.  It's an iterative implementation of quick-select for finding the nth element of an array.  I didn't change the data type because the code as-committed has been thoroughly tested.  I am away from my Pi right now so it isn't really compiled in, but it has no dependencies.

https://github.com/mattthebaker/klipper/commit/87ebb1a8b63b1909e7d36b34047aedcb980609f5

**Comment by derdigge** [comment]
@KevinOConnor I "feel" no difference with both of them.
I replaced the Hotend this morning and will do 1hour print of each and provide the data. Thanks for your effort.

**Comment by derdigge** [comment]
Hello again @KevinOConnor 

as promised here is the data. The difference is small but the no raw is slightly better. In the sheet there are screenshots and all raw data as best as possible, It is all with the same toolhead. The dataset 4 is with enclosure i builded up during the afternoon. i did not see a difference just keep in mind.

If it does not break or you dont want me to test the next idea comming out your brain this should be merged.

[data_work_skr1.1.xlsx](https://github.com/KevinOConnor/klipper/files/2752545/data_work_skr1.1.xlsx)

**Comment by KevinOConnor** [comment]
Thanks.

I decided to try the median filter in the lpc176x low-level code.  Any chance you could give that a shot?

cd ~/klipper ; git fetch ; git checkout origin/work-lpc176x-median-20190112 ; sudo service klipper stop ; make flash ; sudo service klipper start

I don't have an lpc176x printer, but I am able to replicate the spikes on my lpc1768 dev board - if I run a simulated print with the analog pin connected to some resistors, I see spikes roughly once every 2 minutes.  With the above branch, I didn't see any spikes at all after several hours.

-Kevin

**Comment by derdigge** [comment]
Okay @KevinOConnor i can do that tomorrow. Afaik i need to flash using sdcard. Do i got it right you entered smoothing onto the firmware, so its done on the board? we had a longer discussion on Discord about that with @mattthebaker . As i´ve understood he has same idea allready implemented in smoothie.

**Comment by mattthebaker** [comment]
@derdigge Kevin implemented median of 5 in firmware.  Looks clean and fast by the way.

I looked up some some of the LPC board schematics.  There is little to no filtering on the analog reference inputs, which is a likely candidate for why the ADC is noisy.  THx have large filter caps (tRC=47ms), whereas AREFP has none.  Normally supply noise would be common-mode when measuring a resistor divider (affects reference and signal proportionally), but the filter capacitance on THx adds a phase delay to the noise.

I don't know that you could cut out the THx filter entirely, as you still want to reduce noise sources coupled through the wiring.  It would have been wise for the board designers to test and if effective include an input filter of equivalent tRC on AREFP.  The THx filter looks similar to arduino boards, however the acquisition time on the AVR would be much slower and less susceptible.  Obviously its too late to fix in hardware (though if I get a chance I will test it because I'm curious).  LPC has no internal reference voltage that would be more stable.

Look forward to seeing the median filter results.

**Comment by KevinOConnor** [comment]
Thanks.  FWIW, I don't think the problem is board level.  I think the lpc176x chip itself has a defect in its ADC.  Specifically:
1. When the problem occurs (at least for me), it's always a single reading of 0xfff (or close to that) coming from the adc.  That is, it doesn't show the pattern of noise - it's always an extreme and always biased in one direction.  ADC reads just 5us before and after basically always reports the exact correct measurement, which is again not consistent with noise.
2. It seems every board with the lpc176x chip has this problem.  I haven't seen a report of anyone getting consistently good adc measurements with this chip.
3. No other chip shows this problem on any other board.  There's a wide range of 3d printer boards and only this chip shows these extreme spikes.

I too look forward to seeing the results of further testing with the micro-controller based median filter (work-lpc176x-median-20190112).  It's a bit easier if we can address this in the lpc176x specific code.

-Kevin

**Comment by Alexdad76** [comment]
For your attention. 
[BIGTREETECH SKR V1.1 Control Board 32 ](https://ru.aliexpress.com/store/product/BIGTREETECH-SKR-V1-1-32-ARM/718232_32962443179.html?spm=a2g0v.12010108.1000016/B.1.2c3139c9vqe8EQ&isOrigTitle=true) with TMC2208.
[klippy_SKR_1-1.zip](https://github.com/KevinOConnor/klipper/files/2753374/klippy_SKR_1-1.zip)

**Comment by mattthebaker** [comment]
Hmm, yeah, sounds like errata.

LPC176x errata, page 8, section 3.3: https://www.nxp.com/docs/en/errata/ES_LPC176X.pdf .  Normally you wouldn't list system noise as a chip defect, so it is definitely more susceptible than it should be.

> That is, it doesn't show the pattern of noise - it's always an extreme and always biased in one direction.

That is a critical observation for a SAR (successive approximation) ADC.  Looking more into the specs, I don't see any mention of "sample and hold", acquisition time, or capacitance related to the analog in.  So the ADC must be running live against the input rather than buffering the observed value through the measurement.  A short, fast disturbance early in the conversion will cascade and throw off the rest of the bits.  If it were sampled, noise would be averaged over the sampling interval.

A median filter remains the right solution.  Errata suggests that fast noise is the root cause of the corruption.  The already implemented scheme would be effective against that.  3 corruptions out of 5 seems highly unlikely, but best to verify empirically.

So nothing changes...

**Comment by KevinOConnor** [comment]
Okay, thanks.  The results (from @derdigge, @Alexdad76, and my tests) seem to show that the problem goes away with the mcu median filter.  So, I went ahead and merged the work-lpc176x-median-20190112 branch.

@derdigge - I don't have the SKR board, but my experience with these type of boards is that they mix the 5V USB power with the onboard 5V regulator.  So, the mcu is powered from both motor power and usb power.  Thus, the rpi_usb will not work in that situation.  The default restart method is "command" and that should work fine.  If you're having an issue with that mechanism, go ahead and open a github issue for it.

@derdigge - could you comment on PR #1111 for the SKR board?

@mattthebaker - interesting.  Thanks.  The results do look promising on the 5 entry median filter and it's not expensive to use it, so lets see what the results are with a wider audience of users.

-Kevin

**Comment by derdigge** [comment]
@KevinOConnor Thanks for the merge. The board has a jumper for being powered ofer usb. As mentioned above, If i Power the usb hub down Boards leds deactive and its being reset. See:

`#!/bin/sh

echo '1-1' |sudo tee /sys/bus/usb/drivers/usb/unbind
#sleep 1
echo '1-1' |sudo tee /sys/bus/usb/drivers/usb/bind
`

As those resets are (maybe) an individual thing and not all people using pis, i had the idea of a fourth reset method. Theres today command/Arduino/rpi_usb. What about adding a fourth called "script" and klippy calls a local script(python?shell?) at given path and users can do what ever they want it to do. This could be a future proof for other individual methods to come. 

What do you think?

**Pull request closed without merging**
