### PR TITLE
New target STM32F0

### PR DESCRIPTION
**Pull request by Delsian**
UPD: This PR mostly the same as #1383, but have tons of changes due to mainline code changes.
Have sense to make new PR instead patching old one to avoid merging bugs.

The main goal of porting Klipper firmware to tiny Cortex-M0 chips is creation of distributed controller architecture.
Possible to use nanoboards with, for example, one ADC and two power switches to create multi-head printers. Each print head requires only 4 wire (power and signal) and can control heater and fan individually.
Additionally - CAN bus looks better in intermodule communication than USB (and takes less space)
To work with CAN please use additional HW and SW as it described in the documentation section.

Current state: few boards with STM32F042 working together over CAN and serial, GPIO/ADC/SPI works fine, i2c not tested yet.

Board schematics and PCBs will be available soon on circuitmaker.com portal. For debug/testing possible to use NUCLEO-F042K6 board https://www.st.com/en/evaluation-tools/nucleo-f042k6.html , current Makefile version supports flashing and debugiing with on-board programmer.

### CODE REVIEW

**Comment by Delsian** [comment]
After merging #1437 I'll update this PR with SPI initialization fix

**Comment by KevinOConnor** [comment]
Thanks.  Were you able to review my comments at: https://github.com/KevinOConnor/klipper/pull/1383#issuecomment-473675849 ?

-Kevin

**Comment by Delsian** [comment]
Hi Kevin,
Sorry, I lost your comment in my previous PR. Now it fixed:
* Readme - done
* Existing CMSIS doesn't contain Cortex-M0 files
* The same reason - my first version I tried to use your timer_irq.c, but it suitable only for M3/M4 cores.
* Done. Due to some lack of debugging functionality in Cortex-M0 it's necessary to add sw workarounds.

Current state - everything works on my debug board. I didn't check step rate yet as I have no suitable setup and (probably) this check has no sense. I see the main role of this target as heater/fan/temperature control, where clocks and speed not important.
Probably next version will control stepper in direct extruder, but it's plan for future.

**Comment by KevinOConnor** [comment]
Thanks.  I merged this code in with a couple of minor changes:
- the lib/core-cmsis/ files should come from the main ARM cmsis source (described in lib/README)
- there were some spurious executable flags added to some non-executable files

One thing I noted during the merge is that src/stm32f0/log.c does not have a copyright notice.  I would prefer for all code files (.py and .c files) to have a copyright.  Please create a pull request adding a copyright to that file.

A couple of high level comments:
- It should be possible to compile the code with -fwhole-compile.  Any failure is almost certainly the result of a __visible tag missing on a C function that is called from outside the C code.  I'll try to take a look.
- The generic/armcm_timer.c code is specific to cortex-M3/M4 cores, but the generic/timer_irq.c code is not.  In particular, the SAMD21 code (arm-cm0+) and PRU code use timer_irq.c.  Take a look at src/atsamd/timer.c for an example.

-Kevin

**Comment by KevinOConnor** [comment]
Also, it would be good to run the benchmark tests described in docs/Debugging.md.  I understand that driving a stepper isn't the goal of the board, but the benchmarks are primarily designed for comparison purposes - determining if a code change improves/hurts the scheduler, and for determining relative processing power of different boards/software platforms.

On all the boards, we just choose dummy pins.  The goal isn't to actually drive a stepper motor, but to determine how fast the code can respond to requests.

-Kevin

**Pull request closed without merging**
