### PR TITLE
config: Add example configuration for Creality Ender 3 V2

### PR DESCRIPTION
**Pull request by Jimmacle**
This is an example config for the stock Creality Ender 3 V2 that includes special instructions regarding communication port selection and firmware flashing.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  The convention of the "printer" config files is to place a year in the file name.  So, something like "printer-creality-ender3-v2-2020.cfg".  Otherwise, looks good to me.

-Kevin

**Comment by Jimmacle** [comment]
Should be all set now; I can squash everything into one commit if you prefer.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by mikeyman77** [comment]
I used the instruction in the cfg file in order to compile and flash my Ender 3 V2. I set it up to use USB for communication, however when I connect my printer to the RPi4, it shows the usb device, but times out when trying to connect. Is there something that I am missing?

**Comment by Jimmacle** [comment]
Just to confirm, you selected USART1 in the menu? The Creality board's USB port is connected to that port via a dedicated USB to serial converter. This is the firmware configuration I'm currently using to control my Ender 3 V2 via the USB port: Image

**Comment by mikeyman77** [comment]
Ok, that makes sense now, I did not see the Serial Port because I had "Use USB for communication" and I did not have "Enable extra low-level config options". Does the display work with Klipper?

**Comment by Jimmacle** [comment]
The display does not work. I may pursue adding compatibility for it in the future but I don't currently have enough knowledge of the Klipper codebase to do so.

**Comment by KevinOConnor** [comment]
FYI, I made a couple of minor changes to the config and added it to the printers test case (commit 68e9a495).

-Kevin

**Comment by yiyoMX** [comment]
Hi @Jimmacle I recently purchased an Ender 3 V2 and Im interested in flashing it with klipper, do you have any updates in the stability of this config file? have you printed something yet?

**Comment by Jimmacle** [comment]
I've done several prints and the config seems stable, however I highly recommend configuring pressure advance as described in the Klipper docs.

**Comment by mikeyman77** [comment]
What value did you get for PA? I got almost 1.0.

**Comment by Jimmacle** [comment]
It will depend on the nozzle temperature and filament type/color which is why I didn't include any value for it in the config. I ended up with 0.566 for Creality's black PLA at 185C and haven't calibrated it for my other filaments yet.

**Comment by yiyoMX** [comment]
How is it compared to stock Marlin?, I mean, the printer out of the box has
great print quality. Is there a way to go back to stock?

**Comment by mikeyman77** [comment]
To go back to stock just put the stock .bin on the as card, turn off the
printer and turn it back on. It should flash the firmware on boot.

**Comment by yiyoMX** [comment]
Awesome!, I just flashed klipper and Im printing a calibration cube, thanks.

**Comment by thywolf** [comment]
Sorry for asking here, but any problems with extruder skipping/clicking on Ender 3 V2 during printing of a tuning tower with this config and default tuning instructions? Does it go away after PA is set? I abandoned the PA tuning for now as I feared I'll break something... and though I'll consult with someone who did that already. I think I might have sliced it too fast (100mm/s everywhere) for E3v2

**Pull request merged**
