### PR TITLE
Automatic retry for QUAD_GANTRY_LEVEL and Z_TILT_ADJUST

### PR DESCRIPTION
**Pull request by fessyfoo**
Support retrying QUAD_GANTRY_LEVEL and Z_TILT_ADJUST a configurable number of times to a configurable tolerance both in the config or as parameters. 

By default keeps original behavior of no retries.

Adds parameters RETRIES and RETRY_TOLERANCE to Z_TILT_ADJUST and QUAD_GANTRY_LEVEL gcode. 
Adds config options retries and retry_tolerance to `[z_tilt]` and `[quad_gantry_level]`
Issues an error if we are getting worse intead of approaching tolerance
Issues an error if retries were requested but we did not reach the tolerance in the specified number of retries

### CODE REVIEW

**Comment by Maglin** [comment]
I've tested this modification out on Quad Gantry Level and it works as expected.  Can't comment on Z Tilt but I would think it would work just the same.

**Comment by VoronDesign** [comment]
Can’t find seal emoji. 

Using 🦝 of approval instead.

**Comment by andylsun** [comment]
It works for z_tilt as long as PR:1652 is included as well (that reduced the z-tilt probe number from 3 to 2)

```
Send: G28
Recv: ok
Send: z_tilt_adjust
Recv: // probe at 0.000,80.000 is z=5.110000
Recv: // probe at 200.000,80.000 is z=3.640000
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.800553
Recv: // stepper_z1 = 1.610258
Recv: // z_adjust = 0.318641
Recv: // Retries: 0/6 Probed points range: 1.470000 tolerance: 0.015000
Recv: // probe at 0.000,80.000 is z=4.511617
Recv: // probe at 200.000,80.000 is z=4.441617
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.214469
Recv: // stepper_z1 = -0.099651
Recv: // z_adjust = 0.000175
Recv: // Retries: 1/6 Probed points range: 0.070000 tolerance: 0.015000
Recv: // probe at 0.000,80.000 is z=4.340174
Recv: // probe at 200.000,80.000 is z=4.330174
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.008642
Recv: // stepper_z1 = 0.007747
Recv: // z_adjust = 0.013897
Recv: // Retries: 2/6 Probed points range: 0.010000 tolerance: 0.015000
Recv: ok
```

**Comment by KevinOConnor** [comment]
Thanks.  As a low-level comment, I fear that retries.py is too generic a name for klippy/extras/ - I'd place the code into z_tilt.py and just `import z_tilt` in quad_gantry_level.py.  If you feel another module is necessary, then a copyright statement must be added to the top of that code file.  (Use one of the other .py files for the template.)

As a high-level comment, I'm not sure I understand how this retry mechanism works.  I'll try to take a closer look, but if you can provide a high-level description of what RetryHelper and RetryRun do that would probably help.

-Kevin

**Comment by fessyfoo** [comment]
- refactored to put RetryHelper and RetryRun classes in quad_gantry_level  import them in from there for z_tilt. 
- added comments to attempt to document them. 

Let me know if the documentation makes sense.  or if you want it refactored to some other style. 

it's possible i could eliminate the RetryHelper intermediary for just functions, I didn't think about that till now trying to describe why it exists.   it's also possible I could plum a return code from probe helpers invocation of probe_finalize method.  and eliminate the need for RetryRuns check method to be called I got stuck on that. 

open to any feedback.

**Comment by KevinOConnor** [comment]
Thanks.

There's one issue I see that I think would need to be fixed before merging - the z_tilt.py code directly accesses the quad_gantry_level:RetryHelper() member variables.  As mentioned in docs/Code_Overview.md - we want to avoid doing that as it makes it harder to do long term maintenance.

As a high-level comment, though, I do think some refactoring would help.  One issue I see is that ProbePointsHelper:start_probe() becomes reentrant.  If 10 retries are implemented then a stack trace would become very long (it would contain 10 start_probe() calls).  That could become quiet confusing.  One solution would be to signal a retry to ProbePointsHelper and do the retry looping there.

FWIW, I think refactoring the low-level z stepper adjustments between z_tilt and quad_gantry_level would be useful.  (That code is very low-level and it would be preferable to have only one copy of it to maintain.)

I put together some demo code of a possible alternative code flow on the work-probe-20190523 branch.  This code is entirely untested, but hopefully gives some clarity to my comments above.  The first commit (7e250d59) adds retry support to ProbePointsHelper, a ZAdjustHelper class is added (commit d05ddd5b and 4595227d) and then that class could (in theory) also be used for common retry logic (commit 59dac3eb).

Thanks again,
-Kevin

**Comment by fessyfoo** [comment]
thanks. that's good feedback.

**Comment by fessyfoo** [comment]
sry I haven't updated this yet.  I still intend to.  life getting in the way.

**Comment by KevinOConnor** [comment]
Okay, thanks for the update.  FYI, I rebased the work-probe-20190623 demo branch on top of PR #1698.

-Kevin

**Comment by fessyfoo** [comment]
only fixed the direct property access so far
merged in latest master, and resolved conflicts. 
next is to integrate the  probe helper retry support. 

commits will require rebase before merge,

**Comment by fessyfoo** [comment]
Ok, now using the probe helper retry support. 

Note I want to use the probe points range as the retry trigger instead of the z adjustments.   the later would mean the tolerance varied with the angle and distance of the points to the z motors and can be larger than a single step as well as not an even multiple of a step.    the former is more intuitive as the minimum range is a single step.   As such I didn't need to integrate the shared z_adjust mechanism.   However I'm willing to pursue that next as a separate PR. 

looking for feedback.  good to merge code wise? 

before merge needs:
- testing of z_tilt_adjust  ( @andylsun  )  
- rebase  for sane commits

**Comment by fessyfoo** [comment]
@andylsun tested z-tilt. Gave the ok.

**Comment by fessyfoo** [comment]
restructured commits.   this is now good to merge from my perspective. 

Any further feedback?

**Comment by KevinOConnor** [comment]
Thanks.  As a purely mechanical comment, Python does "weird things" if two modules import each other.  So, RetryHelper would need to be in z_tilt.py.

Unfortunately, I'm struggling to understand the retry code, so I'm not able to provide a meaningful review.

Would it be possible to simplify it a bit - maybe something like the following?
```diff
--- a/klippy/extras/quad_gantry_level.py
+++ b/klippy/extras/quad_gantry_level.py
@@ -16,6 +16,7 @@ class QuadGantryLevel:
             raise config.error(
                 "Need exactly 4 probe points for quad_gantry_level")
         self.z_helper = z_tilt.ZAdjustHelper(config, 4)
+        self.retry_helper = z_tilt.RetryHelper(config)
         gantry_corners = config.get('gantry_corners').split('\n')
         try:
             gantry_corners = [line.split(',', 1)
@@ -36,6 +37,7 @@ class QuadGantryLevel:
     cmd_QUAD_GANTRY_LEVEL_help = (
         "Conform a moving, twistable gantry to the shape of a stationary bed")
     def cmd_QUAD_GANTRY_LEVEL(self, params):
+        self.retry_helper.start()
         self.probe_helper.start_probe(params)
     def probe_finalize(self, offsets, positions):
         # Mirror our perspective so the adjustments make sense
@@ -89,6 +91,7 @@ class QuadGantryLevel:
 
         speed = self.probe_helper.get_lift_speed()
         self.z_helper.adjust_steppers(z_adjust, speed)
+        return self.retry_helper.check_retry(positions)
     def linefit(self,p1,p2):
         if p1[1] == p2[1]:
             # Straight line
diff --git a/klippy/extras/z_tilt.py b/klippy/extras/z_tilt.py
index 5d984004..9a4f22d0 100644
--- a/klippy/extras/z_tilt.py
+++ b/klippy/extras/z_tilt.py
@@ -61,6 +61,27 @@ class ZAdjustHelper:
         toolhead.set_position(curpos)
         gcode.reset_last_position()
 
+# Helper code to determine when a Z adjustment pass should be retried
+class RetryHelper:
+    def __init__(self, config):
+        self.printer = config.get_printer()
+        self.max_retries = config.getint("retries", 0, minval=0)
+        self.retry_tolerance = config.getfloat("retry_tolerance", 0., above=0.)
+        self.current_retry = 0
+    def start(self):
+        self.current_retry = 0
+    def check_retry(self, positions):
+        z_positions = [p[2] for p in positions]
+        error = max(z_positions) - min(z_positions)
+        if not self.max_retries or error < self.retry_tolerance:
+            # Retries disabled or latest run within tolerance
+            return "done"
+        self.current_retry += 1
+        if self.current_retry > self.max_retries:
+            raise self.printer.command_error("Too many retries - aborting")
+        # Request ProbePointsHelper to perform a retry
+        return "retry"
+
 class ZTilt:
     def __init__(self, config):
         self.printer = config.get_printer()
@@ -76,12 +97,14 @@ class ZTilt:
         self.probe_helper = probe.ProbePointsHelper(config, self.probe_finalize)
         self.probe_helper.minimum_points(2)
         self.z_helper = ZAdjustHelper(config, len(self.z_positions))
+        self.retry_helper = RetryHelper(config)
         # Register Z_TILT_ADJUST command
         self.gcode = self.printer.lookup_object('gcode')
         self.gcode.register_command('Z_TILT_ADJUST', self.cmd_Z_TILT_ADJUST,
                                     desc=self.cmd_Z_TILT_ADJUST_help)
     cmd_Z_TILT_ADJUST_help = "Adjust the Z tilt"
     def cmd_Z_TILT_ADJUST(self, params):
+        self.retry_helper.start()
         self.probe_helper.start_probe(params)
     def probe_finalize(self, offsets, positions):
         # Setup for coordinate descent analysis
@@ -110,6 +133,7 @@ class ZTilt:
         adjustments = [x*x_adjust + y*y_adjust + z_adjust
                        for x, y in self.z_positions]
         self.z_helper.adjust_steppers(adjustments, speed)
+        return self.retry_helper.check_retry(positions)
 
 def load_config(config):
     return ZTilt(config)
```

-Kevin

**Comment by fessyfoo** [comment]
Pull in latest master and resolved conflicts. 
dealt with module import loop. 
refactored out the no longer needed retry_function bit,  (because probe helper support) 

Oddly,  I didn't read your comment from three hours ago, and I think I've done most of  what you asked anyhow. :) 

let me morph it the rest of the way.

**Comment by fessyfoo** [comment]
updated to try to match above simpler style.  hopefully clearer now.   however:
- kept error check for diverging from tolerance instead of converging. 
- kept ability to  override config file values as gcode parameters. 
- kept progress info messages.  
- still error with gcode error instead of raising exception.   seems nicer. 

if that's still to complex, lmk. 

still trying to figure out how I broke the test.

**Comment by fessyfoo** [comment]
cool. test caught a definite bug.  go tests. :)   fixed.

**Comment by KevinOConnor** [comment]
Thanks.  I can either squash these into one commit and merge, or if you prefer, you can add your signed-off-by line to the "z_tilt: Add RetryHelper" commit and rebase, and then I will merge all four commits as is.

-Kevin

**Comment by fessyfoo** [comment]
Updated missing signed-off-by line.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
