### PR TITLE
Added Anet E16 to configs

### PR DESCRIPTION
**Pull request by dstack**
It do what it says on the tin.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In order for me to merge directly, commits need to have a signed-off-by line (see https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).  I can commit a basic config file using my signed-off-by line if that's an issue though.

-Kevin

**Comment by dstack** [comment]
@KevinOConnor Thank you.  I added a Sign-off line, and made a small adjustment to the print volume for this printer specifically.

**Comment by KevinOConnor** [comment]
Thanks, but the signed-off-by line should be in the git commit message (or here in the PR comments).  The signed-off-by line should not be in the config file.  See https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by KevinOConnor** [comment]
Thanks - I added this example config file (in commit c3b97331).

-Kevin

**Comment by dstack** [comment]
@KevinOConnor I apologize, I completely missed this.  Work has kept me extremely busy recently.  Thank you for adding the config.

**Pull request closed without merging**
