### PR TITLE
Display: add support for M73 R parameter

### PR DESCRIPTION
**Pull request by ld3300**
Adds the ability to include the R parameter with M73.  Requires an integer representing the number of minutes remaining in the print. Compatible with octoprint M73 plugin.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  FWIW, the M73 command does not appear to be a "widely used g-code command"; it's not widely produced nor widely supported.  As near as I can tell, the R parameter is even more scarce.  I wonder if it would be better to let individuals customize their config file if they wish to use a plugin that provides M73 with R.  (They should be able to provide their own M73 that sets a remaining variable and then override the display to show that variable.)

Cheers,
-Kevin

**Comment by ld3300** [comment]
Hi Kevin,
I thought it was a bit more common than that.  There are a few Octoprint plugins that inject it.  PrusaSlicer can export it with the gcode.  I don't know about the other slicers.  But I think I see what you mean.  If the change is made at the user end in the menu structure than no code changes are needed.
Reading through the example_extras.cfg for display_data and display_template leaves me with a couple of questions.  Maybe I should test these and figure it out, but my printer is a little active right now.  If I make a [display_data my_group_name my_data_name] does it overwrite the default entirely, or just the position specified?  It looks like I would need to pair the display_data render command with a delayed_gcode.  Does that sound right?

**Comment by KevinOConnor** [comment]
It shouldn't be necessary to use a delayed_gcode section.  One should be able to override M73 and just store the R value in a gcode variable.  To override the display section, one could define `[display_data _default_16x4 printing_time]` and set the `text` option to the desired value.

Given that the current "remaining" time display isn't very accurate, maybe we should just remove it from the default display in general.  Now that the display is configurable, users that wish to show it can do so via their own config settings.

-Kevin

**Comment by ld3300** [comment]
That would also be an easy change to implement.  I can revert and remove the remaining time completely.

**Comment by ld3300** [comment]
@KevinOConnor here is the branch with all remaining times removed

**Comment by KevinOConnor** [comment]
I'm not sure what went wrong, but this branch is showing lots of extraneous changes - perhaps a bad merge of some kind.  It probably needs to be rebased to master.

Thanks.
-Kevin

**Comment by ld3300** [comment]
okay, sounds like I did something silly somewhere

**Comment by KevinOConnor** [comment]
FYI, commit 2a66286d removes the "print time remaining" field from the default LCD display.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I think we can close this.

-Kevin

**Pull request closed without merging**
