### PR TITLE
DISPLAY: Menu control from gcode macros

### PR DESCRIPTION
**Pull request by ld3300**
Add G-Code commands that allow setting the display to a specific list or moving cursor to specific item in a list to allow for anticipated user interaction.  Ability to disable menu timeout included to make it possible to await for user interaction.

The GOTO_MENU command clears the stack so the [..] back will return to main screen.  If called without any parameters it will return straight to the main screen

The DISPLAY_TIMEOUT command stores the value initially read from the config file and will restore it when timeout is re-enabled.  A "TIME" parameter is also available to set a value other than that in config.

I know menu changes are coming.  In that branch right now it looks like the methods this relies on have changed a little, but not so excessively as to not be possible to bring over.  Let me know your thoughts about committing this to the current master with the expectation that I would adapt it to work with the future menu system as well.

Signed-off-by: David O Smith <davidosmith@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  FWIW, I'm leery of changing the menu while it's in flux.  I fear it will lead to conflicts later on.

-Kevin

**Comment by ld3300** [comment]
I believe you are probably right, so maybe this is just helpful in case anyone wants to pull it into their instance for the temporary ability.  What is the state of the new menu?  Is there a branch or pull request to follow?

**Comment by ManIkWeet** [comment]
Any update on this? Sounds very useful for filament changing

**Comment by ld3300** [comment]
I would like this feature, but won't be able to try and look at it for a little while.  I'll keep it on the list.

**Pull request closed without merging**
