### PR TITLE
MKS Robin Nano and TT Sapphire Pro cfg

### PR DESCRIPTION
**Pull request by thucar**

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In order for me to directly commit the commit should have a signed-off-by line (see https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).  However, for a config file I can commit using my signed-off-by line if you prefer.

What year is the Sapphire printer from?  The current standard is to place a year in the printer file names.  Is it necessary to place the nano board version in the filename (are there known to be other incompatible boards that are incompatible with the config)?

Thanks again,
-Kevin

**Comment by thucar** [comment]
If you could use your sign-off-by, it would be great. I'm not too good friends with Git, so expect me to take three days and add loads of unwanted clutter in process, should I try it.

I do not know of any config differences between board versions. There are things like extra always-on fan pins, etc. I'm not aware of any component or pinout changes.

The printer is from 2020. Late 2019 versions had some mechanical differences.

**Comment by KevinOConnor** [comment]
Looks like the stepper_y endstop pin should be PA12.  Also, is it intentional that the generic-mks-robin-nano config uses "Robin_nano.bin" while the Sapphire uses "Robin_nano35.bin"?

-Kevin

**Comment by thucar** [comment]
Seems like the bootloaders differ on these boards. On some late 2019 machines the file needed to be Robin_nano.bin On current versions it needs to be Robin_nano35.bin where 35 seems to refer to the 3.5” TFT used on the machine. Since there are more TFT sizes that could be used with this board, I suspect there could be bootloaders that look for Robin_nano24.bin or something similar.

And indeed, PE12 is correct for Y endstop. My bad.

**Comment by KevinOConnor** [comment]
Okay - I added the config files (commit cb414ae9 and 8f8cf7ef).

Thanks,
-Kevin

**Comment by Inserer-Pseudo** [comment]
@thucar @KevinOConnor 

Hello there ! I know that I'm a bit late but I need your help please.
I'm a beginner in firmware modification and Klipper.
I was wondering if you could give me the steps to follow in order to get klipper working with my robin nano 1.2.
I've followed this thread, but now I'm lost.
My printer is also a sapphire plus.

Thank you and have a nice day

**Comment by thucar** [comment]
Hello @Inserer-Pseudo 

What part is causing you problems? Did you follow the guide in the beginning of the Robin Nano config example file?

**Comment by Inserer-Pseudo** [comment]
It says that I have to compile this file.
Should I compile it in VScode or running the script and putting the out/robin_nano file on the SD is enough ?
And were can I find this file ?

**Comment by thucar** [comment]
You need to run the code in the Klipper directory as described in the installation document: https://www.klipper3d.org/Installation.html
```

cd ~/klipper/
make menuconfig
```

then for instance for my TwoTrees Sapphire Pro:

```
# When running "make menuconfig" you have to:
# - enable "extra low-level configuration setup",
# - select the 28KiB bootloader,
# - select serial (on USART3 PB11/PB10) communication
# - set "GPIO pins to set at micro-controller startup" to "!PC6,!PD13"

# Note that the "make flash" command does not work with the Sapphire
# Pro. After running "make", run the following command:
#   ./scripts/update_mks_robin.py out/klipper.bin out/Robin_nano35.bin
# Copy the file out/Robin_nano35.bin to an SD card and then restart the
# printer with that SD card.
```

**Comment by Inserer-Pseudo** [comment]
Yes I did that but where is  "out/robin_nano35.bin" ? On my SD card on the rpi ?

**Comment by thucar** [comment]
The out/robin_nano35.bin is relative to your current folder where you run the Make command.

**Comment by Inserer-Pseudo** [comment]
Okay I did it and now it may have flashed my MC but my screen is stuck at "TFT updating 100%"

**Comment by thucar** [comment]
Then some of the options in the "make menuconfig" part were not correct. Double check that you select all of the options I quoted above.

**Comment by Inserer-Pseudo** [comment]
Capture du 2021-04-07 14-03-51

**Comment by thucar** [comment]
That looks to be correct. Is your Nano version 1.2_400 ?

**Comment by Inserer-Pseudo** [comment]
It's only mentionned " Robin nano V1.2"

**Comment by Inserer-Pseudo** [comment]
@thucar 
I managed to deal with it and I followed the rest of the installation until I have to use a config file.
Which one should I use ?

**Comment by Inserer-Pseudo** [comment]
@thucar 
It almost work ! Klipper says it's ready but my screen is black, is it fixable ?
If not that's fine because I can plug a touchscreen on the RPI and use it as an interface, right ?

**Comment by tjengbudi** [comment]
@Inserer-Pseudo connect the mks robin mini must use uart cable from mks to rpi gpio? or can use usb while setting use uart?
sorry for dump question

**Comment by Inserer-Pseudo** [comment]
> @Inserer-Pseudo connect the mks robin mini must use uart cable from mks to rpi gpio? or can use usb while setting use uart?
> sorry for dump question

Connecting it with the USB works just fine

**Pull request closed without merging**
