### PR TITLE
Updates to stm32 CAN code

### PR DESCRIPTION
**Pull request by KevinOConnor**
I noticed a couple of errors in the stm32 can.c code.  Specifically:
1. There are some cases where C read+write modify accesses were made in an unsafe way.  (For example, the `IER |= CAN_IER_TMEIE` in serial_enable_tx_irq() could race with a CAN irq; the `RF0R |= CAN_RF0R_FOVR0` in CAN_IRQHandler() could race with a new received packet.)
2. The CAN irq handler could perform blocking actions (waiting for space in the tx queue) that could potentially last over a millisecond.  That much of a delay would cause the main timer dispatch code to miss its schedule.

This PR modifies the can.c code to fix the above issues.  To reduce IRQ latency, the new CAN irq just activates a low-priority task to handle the CAN traffic.  This ensures the main Klipper timer dispatch code is given the highest scheduling priority.  This PR also makes a few minor (non-critical) code layout changes.

@Delsian and @bondus - FYI.

-Kevin

### CODE REVIEW

**Comment by Delsian** [comment]
LGTM, +1

**Comment by bondus** [comment]
The tx irq handler was actually designed to not block. Deferred handling in user mode like this change does it is a better solution.

Good catches or races and cleanup of the rest.

**Comment by bondus** [comment]
There is one tiny flaw in can_dispatch_task(), the last line 
`can_transmit_mbox(MyCanId+1, mbox, i, databuf)`; 
will send data on CANID 1, that no one listens to, until the board has a CANID assigned.

`        if(MyCanId) can_transmit_mbox(MyCanId+1, mbox, i, databuf);`
will fix that.

**Comment by KevinOConnor** [comment]
Thanks.

I added a new patch to this series - it splits the high-level CAN message processing into a new C file (src/generic/canbus.c) that is separate from the low-level board specific CAN code (src/stm32/can.c).  My hope is that this will make it easier to maintain the high-level code (which doesn't need to worry about low-level register details).  This new code also removes the dependency on serial_irq.c , and is slightly more efficient as it uses more optimized buffer updating.

-Kevin

**Pull request merged**
