### PR TITLE
HD44780: fix initialization, configure delay

### PR DESCRIPTION
**Pull request by andryblack**
Correct initialization sequence, allow fine-tune commands delay.

On linux mcu with some frequency deviation my display dnt work properly with default commands delay. Increase delay get stable work.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, I suspect the root of the timing issue is the mcu implementation on Linux (as discussed briefly in https://github.com/KevinOConnor/klipper/pull/2815#issuecomment-623007745 ).  It shouldn't be necessary to configure custom delays, as the hardware really should be okay with the existing 40us delay.

Can you further explain the init sequence change?  I'm not sure why that would be needed.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by andryblack** [comment]
for now it is worked solution for my setup, but #2915 look like more correct. I will check this soon.

**Comment by andryblack** [comment]
#2915 fixes timing issue, init sequence change unimportant

**Pull request closed without merging**
