### PR TITLE
hall based filament width sensor  

### PR DESCRIPTION
**Pull request by test3210-d**
module: hall_filament_width_sensor

Signed-off-by: Denis Ignatenko <deniss979@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks good to me.

The Signed-off-by line needs to contain your real name as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .  It means you are agreeing to: https://github.com/KevinOConnor/klipper/blob/master/docs/developer-certificate-of-origin

-Kevin

**Comment by test3210-d** [comment]
Now all right ?

**Comment by KevinOConnor** [comment]
The Signed-off-by line needs to have your full real name.  If you place your copyright in the new file, then it too must contain your full real name.

If you have a concern with this and wish to discuss off-line, feel free to email me at kevin@koconnor.net.

-Kevin

**Comment by test3210-d** [comment]
module: hall_filament_width_sensor

Signed-off-by: Denis Ignatenko <deniss979@gmail.com>

**Comment by KevinOConnor** [comment]
Thanks.  I merged this (commit 9a65a456).  I did make a couple of minor changes during commit.  I did not commit the changes to the display code as the display code is currently in a bit of flux and I'm leery of making changes until we can get the display code settled.

Thanks again,
-Kevin

**Pull request closed without merging**
