### PR TITLE
Report additional information via get_status

### PR DESCRIPTION
**Pull request by Arksine**
This reports the following additional information via calls `get_status`:
- toolhead: `max_velocity`, `max_accel`, `max_accel_to_decel`, `square_corner_velocity`
- filament_switch_sensor:  `enabled`
- temperature_sensor:  ` measured_min_temp`, `measured_max_temp`

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  The first two commits look fine to me.  What's the use case for the min/max temperature?

-Kevin

**Comment by Arksine** [comment]
It was a request from @meteyou, he displays in in Mainsail:
image

I could implement this tracking in Moonraker if you prefer to keep it out of Klipper.

**Comment by KevinOConnor** [comment]
Thanks.  I would have thought users would prefer "max in last 24 hours" or similar.  That is, if the printer is up for 30 days, not sure what the min/max would be used for.  That said, when I originally reviewed this, I missed that it only applies to custom `[temperature_sensor]` config sections.  (I thought it was a generic temperature tracking change.)  As such, I'm fine with the change as you have it now.

Separately, what's your plans for short-term temperature tracking?  That is, keeping the log of the last ~2 hours of temperatures so that the website can immediately render the temperature graph.  Just curious.

-Kevin

**Comment by Arksine** [comment]
Hi Kevin, Moonraker has a "plugin" that handles this.  Currently it stores 20 minutes of data for each configured temperature sensor at 1 second intervals.  My thought is that it is unlikely that a client will have a temperature graph that plots more than 20 minutes of data, but if a client developer requests it I can increase the amount stored.

Soon I will PR the moonraker.py "extras" module which provides configuration for the server and handles status requests/subscriptions.  With that Klipper master will have everything necessary to connect to Moonraker. 😃

**Comment by KevinOConnor** [comment]
Great!  Thanks.

-Kevin

**Pull request merged**
