### PR TITLE
Add virtual stepper motor to avrsim

### PR DESCRIPTION
**Pull request by kargeor**
Signed-off-by: Georgios Karnas <kargeor@gmail.com>

### CODE REVIEW

**Comment by kargeor** [comment]
This is still work-in-progress. I'm going to implement end-stops and heaters so we can have a full virtual 3d-printer.

**Comment by KevinOConnor** [comment]
Seems interesting.

Just as an FYI, there is a separate simulator in the src/simulator/ directory.

-Kevin

**Comment by kargeor** [comment]
I played with the current code and I am constantly getting `MCU 'mcu' shutdown: Timer too close`.
This happens even if I remove the motor sim code and just use the code from master. I tried different avr clock rates and baud rates. Any ideas?

Also, I looked at the simulator code. It currently does not simulate motors but I can move the logic from this pull-request there and avoid using avrsim.

**Comment by KevinOConnor** [comment]
The klipper log file would be needed to determine what the cause of a "Timer too close" error is.  That said, the simulavr code doesn't run at a 1 to 1 timing, which can confuse the host code.  On my desktop, I tend to run the code with the `-r .2` to try keeping a steady execution rate.

-Kevin

**Comment by kargeor** [comment]
> The klipper log file would be needed to determine what the cause of a "Timer too close" error is. That said, the simulavr code doesn't run at a 1 to 1 timing, which can confuse the host code. On my desktop, I tend to run the code with the `-r .2` to try keeping a steady execution rate.
> 
> -Kevin

Thanks. This solved my timing issues! (should the docs be updated?)
Another issue I noticed was with tty on mac, sometimes causing the connection to timeout. I updated the code based on unix man pages to setup a raw tty [here](https://github.com/KevinOConnor/klipper/pull/2343/files)

Also happy 2020!

**Comment by kargeor** [comment]
I'm giving up on this. Probably does not add big value.

**Pull request closed without merging**
