### PR TITLE
Filament Jam Sensor

### PR DESCRIPTION
**Pull request by WindoC**
module: filament jam sensor.py

I add Filament Jam Sensor base on an on/off or encoder(use only 1 wire/pin) and monitor the filament usage during each on/off cycle of the monitor pin.

It can detect two situations, 
1. filament did not extrude as fast as expected
2. filament jam or run out

Signed-off-by: Antonio Cheong

### CODE REVIEW

**Comment by WindoC** [comment]
I have a question, what is the different of toolhead.get_position() & toolhead.get_kinematics().get_steppers() ? Are they provide the same result?

**Comment by KevinOConnor** [comment]
Thanks.  It's not clear to me what this code does.  How does it differ from the existing code in klippy/extras/filament_switch_sensor.py?  Could that file be used instead and/or could updates to that code be made instead?

The signed-off-by line (as well as any copyrights added) must contain a real name as well as a valid email address - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by WindoC** [comment]
filament_switch_sensor can only detect filament runout but this one can detect both runout and jam.

The hardware using for filament_switch_sensor is an endstop. 
(something like this https://www.thingiverse.com/thing:2845176 )

And the hardware using for filament_jam_sensor is an encoder or something like this. https://www.thingiverse.com/thing:3067904

**Comment by SrGeek** [comment]
@WindoC.  Will you be checking the enable pin pulses from the boards and compare them to the RPM of the encoder basically creating a closed loop system for the extruder motor?

**Comment by WindoC** [comment]
> @WindoC. Will you be checking the enable pin pulses from the boards and compare them to the RPM of the encoder basically creating a closed loop system for the extruder motor?

I use toolhead.get_position() to get the E-axis usage (in mm) and there is a bit different to the actual usage of the filament. After some test, I have already given up the function "1. filament did not extrude as fast as expected". Just implement the filament jam and run out detect.

To close loop the E-axis filament & motor request more precise monitor and faster react. And the design of this module did not fulfill the requirement of it.

**Comment by KevinOConnor** [comment]
What's the status of this PR?  Is there further feedback on my comments at https://github.com/KevinOConnor/klipper/pull/1544#issuecomment-484919212 ?

-Kevin

**Comment by WindoC** [comment]
Correct the sign.
Also, I make some change for the logic for bug fixing and better user exp.

**Comment by SrGeek** [comment]
How do I upload this feature.  I downloaded WindoAC filament sensor from thingiverse and I am anxious to try it.

**Comment by WindoC** [comment]
> How do I upload this feature. I downloaded WindoAC filament sensor from thingiverse and I am anxious to try it.

Copy https://github.com/WindoC/klipper/blob/filament_jam_sensor/klippy/extras/filament_jam_sensor.py to your installation folder. 

Add the config listed in https://github.com/WindoC/klipper/blob/filament_jam_sensor/config/example-filament_jam_sensor.cfg to your printer.cfg file. (Of cause, modify the setting for your case)

See https://github.com/WindoC/klipper/blob/filament_jam_sensor/docs/Filament_Jam_Sensor.md for how to use.

**Comment by KevinOConnor** [comment]
I'm not sure what the current state of this PR is.  At a high-level, in order to merge this to the master Klipper repo, it would require a signed-off-by line using a real name (as mentioned above).  Some additional feedback: the filament_switch_sensor.py code was intended to provide a "base class" for this type of functionality and it would be preferable to use it for features like pause integration; unfortunately there isn't a good way to get the current real-time E position in Klipper right now - calling toolhead.get_position() is often out of sync with real-time by a couple of seconds (it is the last position added to the look-ahead queue - not the real-time position); the indentation style used in this code is unlike normal Python formatting and that makes it harder to review/share the code.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin

**Pull request closed without merging**
