### PR TITLE
Add overclocking feature to samd51 based MCU's

### PR DESCRIPTION
**Pull request by popshansen**
module: atsamd

Added the same overclocking choices (150MHz, 180MHz and 200MHz) as in Arduino IDE for Adafruit (SAMD51) boards like the Grand Central. If encounter any problems it is possible to overclock at lower freq. or just use the default 120MHz.

Performance result at 200MHz as I can measure:
samd51 : ticks

1 stepper : 841
2 stepper : 835
3 stepper : 835
4 stepper : 838
1 stepper (no delay) : 40
3 stepper (no delay) : 195

Signed-off-by: Lars R. Hansen popshansen@hotmail.com

### CODE REVIEW

**Comment by popshansen** [comment]
Whant to redo the pull request

**Comment by KevinOConnor** [comment]
Interesting!  Thanks.  Out of curiosity, why is this limited to "CLOCK_REF_INTERNAL"?

-Kevin

**Comment by popshansen** [comment]
The short answer is that I don't know if it posible to overclock while running on external clock (32.768Khz crystal).
Thats why I add the CLOCK_REF_INTERNAL limit in order to not interfere with external clock.

But when I looked at the code again after your question I can see a problem in the clock_init_32k of the samd51_clock.c.
It use the FREQ_MAIN, but what is FREQ_MAIN at that stage. I had some code that should prevent that, but I removed that during test cleanup.
I'll fix that when I get home from work today.

/Lars

**Comment by KevinOConnor** [comment]
Ah, okay.  I tested it on my "Adafruit Feather M4" and it works fine (both with the crystal and without the crystal).  I made a couple of minor changes to Kconfig and committed this (commit 524ebbc7).

Thanks.
-Kevin

**Comment by popshansen** [comment]
Super, then I won't try to fix something there is not anymore :-)

Surprisely the SAMD51 stays cool, I was suspecting it a bit warmer during the performance test at 200 MHz, but it was still cold, that's positive.

/Lars

**Comment by jalanjarosz** [comment]
Ladyada notes in one of my Klipper/GC support tickets that Adafruit overclocks tbr GrandCentral all the time with no problems.  

Looking forward to this addition. 

Thanks @popshansen for this enhancement.

**Comment by KevinOConnor** [comment]
Lets close this as it's been merged with commit 524ebbc.

-Kevin

**Pull request closed without merging**
