### PR TITLE
Tmc5160 write to gconf register

### PR DESCRIPTION
**Pull request by yhaiovyi**
Fix an issue when user can't configure important writable register. I'm also planning to take care of other tmc5160 issues like that later. [Datasheet for reference](https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5160A_Datasheet_Rev1.13.pdf) navigate to page 32

### CODE REVIEW

**Comment by yhaiovyi** [comment]
I realize that you likely don't want `en_pwm_mode`,  `diag1_stall`, and such to be accessible directly. But there're also quite a few registers that are potentially interesting. Please let me know what you think.

**Comment by yhaiovyi** [comment]
Also currently I set `en_pwm_mode` to `1`, and `TPWMTHRS` to 0, which allows me to use stealthchop only. There's no nice way to do that with current configuration options. So I's like to be able to set those params manually. Anyway if you set them, you likely know what you're doing.

**Comment by KevinOConnor** [comment]
Thanks, but I don't think it is worthwhile to add additional configuration complexity for most of these parameters.  (I didn't check them all, but many of them would just cause incorrect operation if a user were to set them.)  If you want to modify them for debugging purpose (or for your own custom setup) then you can use the SET_TMC_FIELD command (see docs/G-Codes.md) to set these fields.

-Kevin

**Comment by Coffee0297** [comment]
@KevinOConnor this is stuff that us that optimice the driver would like to have access to at firmware level, it's really useful parameters. and if they are set to default in the config_extra.cfg it should not be a problem.

**Comment by yhaiovyi** [comment]
@Coffee0297 that's exactly my point, why restrict low level configuration. An average user would not use them anyway, yet they are pretty useful for an advanced one.

**Comment by yhaiovyi** [comment]
@KevinOConnor there's also another issue/feature with registers that I ran into. I'd expect klipper to clear driver error flags on init, which it doesn't do at the moment. Will you be interested in that PR?

**Comment by Coffee0297** [comment]
Please do... And maybe get klipper to reconice a error from the driver... Rn klipper don't care about the errors comming from the drivers, even tho they are avalible

**Comment by KevinOConnor** [comment]
The error flag clearing was raised in PR #2243 .  It certainly seems like a useful feature.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I'm going to close this as it looks like the conversation has concluded.  If there is some field that can be meaningfully exported to the config file then that is great.  However, if a field can not be set from the config file (because any user setting would just cause internal errors) then I think it should not be in the config file.

-Kevin

**Pull request closed without merging**
