### PR TITLE
stm32: Initial support for stm32f2 in general and STM32F207 in partic…

### PR DESCRIPTION
**Pull request by combolek**
…ular

Boots up and communicates on STM32F207VC.

Signed-off-by: Boleslaw Ciesielski <combolek@users.noreply.github.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me.  What does work and what doesn't currently work on the chip?

Out of curiosity, are there any important changes between stm32f4.c and stm32f2.c - or could potentially stm32f4.c be used on the f2?

-Kevin

**Comment by combolek** [comment]
Currently only the most very basic stuff works (or rather has been tested, who knows what works). The board that I am using is not a full 3D printer board, it's only usable as an extender. I tested UART and some GPIO (connected a filament sensor and it worked :-)). I could not test USB because there is only an USB-A connector which is normally intended for flash drives. I think it may be possible to use it for communication with the host but I have not figured out how to safely wire it up. So for now I am using UART3 to communicate with the host.
My board does not have an external crystal, so I only tested the HSI->PLL clock. I don't know if the external clock setup is correct.
Also, I could not figure out how to get klipper to coexist with the stock bootloader, so I am just using it without bootloader for now.
Regarding stm32f4.c vs stm32f2.c, they are indeed very similar right now. Just about the only thing different is the clock configuration but that is already in separate functions. So I think these two files could be combined, I just don't know if there won't be other differences later. But I guess they can always be split later.
Would you like me to combine stm32f4.c and stm32f2.c and resubmit? Should it be renamed or  leave it as stm32f4.c? 
One other question I have is that in some places a runtime check is used where an ifdef could work, e.g.:
```
static void
clock_setup(void)
{
    // Configure and enable PLL
    if (CONFIG_MACH_STM32F405 || CONFIG_MACH_STM32F407)
        enable_clock_stm32f40x();
    else
        enable_clock_stm32f446();
```
I guess the compiler will optimize the if anyway so it's more of style issue. I assume that I should just follow along for consistency?

Thanks

**Comment by KevinOConnor** [comment]
Okay, thanks.  I'm fine with merging, so if there are no further comments I'll do that in a few days.

> Would you like me to combine stm32f4.c and stm32f2.c and resubmit? Should it be renamed or leave it as stm32f4.c?

I'm fine with either merging or not merging.  We can always refactor in the future.  If merging, I'd be fine with leaving it as stm32f4.c but I don't have a strong preference.

> One other question I have is that in some places a runtime check is used where an ifdef could work, 

Yes, it's mostly style, but the "runtime style" is strongly preferred.  The compiler does a better job of checking for errors when using that style.

Cheers,
-Kevin

**Comment by combolek** [comment]
OK, I combined the two files and left the name as stm32f4.c
Thanks

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by inks007** [comment]
@combolek Did you manage to get USB serial working? The STM32F2's have USB OTG, so it should be able to act as a USB device.

Does your device have a bootloader, or did you flash directly to 0x08000000?

I have a Particle Photon (STM32F205) which has a USB micro-B port. I've managed to flash it with Klipper and got it to communicate via USART1, but not USB serial. [Planning to build a toolboard shield with an ADXL345]

**Comment by combolek** [comment]
I do not use a bootloader, I could not figure out how to get this to work. Also, I do not have a USB serial working, I am just using UART3 (see my post above).

**Pull request merged**
