### PR TITLE
Add  pid temp controlled fan

### PR DESCRIPTION
**Pull request by wizhippo**
Perhaps we could unify the temperature controlled fans and add more `control`s to support other scenarios?

This acts like a heater but in reverse adding more fan when cooling is needed.  Two modes are available `BangBang` and `Pid`. 

`min_speed` refers to the minimum speed the fan can spin when on as many fans will not spin unless sufficient power is applied.

Thought? Suggestions to improve?

Signed-off-by Douglas Hammond  <wizhippo@gmail.com>

### CODE REVIEW

**Comment by wizhippo** [comment]
I have tested the pid and it is working well.  I have a fan and a thermister on my tmc2130's and it keeps them at a consistent 50 deg C.

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.  It would probably be good to see if we can refactor the PID and Watermark control classes so that the same code can be reused for both heaters and fans, but that's something that can be done after merging.

@w1ebr / @bmc0 - do you have any comments on this change?

**Comment by w1ebr** [comment]
I think it is a good extension as long as it is optional, but I would also merge the existing [fan] code into it as well. This should allow a fan to be associated with a heater or a temperature sensor and allow bangbang, pid or no feedback for fan speed control.

**Comment by KevinOConnor** [comment]
On Tue, May 15, 2018 at 04:59:51PM +0000, w1ebr wrote:
> I think it is a good extension as long as it is optional, but I would also merge the existing [fan] code into it as well. This should allow a fan to be associated with a heater or a temperature sensor and allow bangbang, pid or no feedback for fan speed control.

I don't think it would make sense to merge [fan] or [heater_fan] with
a pid controlled [temperature_fan] - [fan] is controlled via M106 and
we really shouldn't change the speed except from g-code, and
[heater_fan] should always be fully on when the heater is enabled (or
otherwise, it can cause disturbances to the heater pid).

-Kevin

**Pull request merged**
