### PR TITLE
Add bootloader option for stm32f070 (malyan) boards

### PR DESCRIPTION
**Pull request by clearchris**
Signed-off-by: Chris Lombardi <clearchris@hotmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
How does this work without a VTOR register to specify the vector table?

I would have thought that Klipper would need to place the VectorTable at the beginning of ram and then use the stm32f0 remap system to point address 0x00000000 to ram.

-Kevin

**Comment by KevinOConnor** [comment]
Any updates on this?

-Kevin

**Comment by xC0000005** [comment]
Yeah, you need some code to copy over the vector array to a RAM section and then set the mapping table (you can copy it from my malyan variant in stm32duino), and you need to euthanize all ISR/timers/etc while you do the ram copy, otherwise you'll trigger the one that's watching the shared memory section Malyan's bootloader sets up, and the printer will crash during that very first copy of all the globals. It's likely something similar is what's hosing Chitu as well, but we'll see.

**Comment by KevinOConnor** [comment]
I believe @clearchris had better luck with some code I put up at:
https://github.com/KevinOConnor/klipper/tree/work-stm32f0-bootloader-20191209
However, I think it was still showing some issues.

The code on the branch above does do the memory copy of the vector table.  I'm not sure what you mean by "watching the shared memory section", but I guessing that bootloader isn't designed to run arbitrary code.

-Kevin

**Comment by xC0000005** [comment]
Yes, that should work. Malyan (like MKS Robin, Chitu, and a few others)
have a section of ram that contains variables "shared" between the
bootloader and the app. Writing values to these often triggers stuff during
systick and so on. For the M200 and M300s, I had to do two things: 1. Load
the SP always, since the bootloader might not, and 2, disable
interrupts/faults until everything was cleared and re-intialized. I never
bothered figuring out if it was the systick or some other running timer,
but once all the interrupts are reset and so on, it should be good. Do you
have any idea why the startup code writes the VTOR to 0x8000000 and then
whatever the right value is?

**Comment by KevinOConnor** [comment]
> For the M200 and M300s, I had to do two things: 1. Load
the SP always, since the bootloader might not, and 2, disable
interrupts/faults until everything was cleared and re-intialized.

Ah, okay.  The Klipper code on that branch doesn't do these things.

> Do you have any idea why the startup code writes the VTOR to 0x8000000 and then
whatever the right value is?

Not sure what you mean here.  The stm32f0 doesn't have a VTOR register so there shouldn't be any references to it.  If you're referring to the stm32f1 and stm32f4 code, then I don't know why the STM provided code overwrites the VTOR register; Klipper restores it because it's simpler to do that then to keep modified versions of the STM provided code.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by xC0000005** [comment]
I don't know. I think Chris was going to fix the RO data copy so it's not
overwriting the vector segment, and so globals actually get initialized but
I didn't see anything after that.

**Comment by KevinOConnor** [comment]
@clearchris do you think I should commit 2d36d1a to the master branch?

Otherwise, I don't think we need to track this as an open PR in Klipper.

-Kevin

**Comment by clearchris** [comment]
No, please do not commit.

I have a patch coming, it's currently working with openblt bootloader, but needs further work to be compatible with the malyan bootloader.  I will open a new ticket when it's ready, you can close out this one.  I'm hoping to have it ready this weekend, but we'll see.

C

________________________________

**Comment by clearchris** [comment]
Closing and resumbitted as:
https://github.com/KevinOConnor/klipper/pull/2526

**Pull request closed without merging**
