### PR TITLE
Add travis continuous integration for src/

### PR DESCRIPTION
**Pull request by archi**
This PR adds Travis-CI for the MCU code.

The CI builds targets atmega2560, atmega328, hostsimulator, linuxprocess and sam3x8e (all 250000bps and default clocks)
I put their respective configuration files into 'test/configs/', more variants could be added.

Since Travis uses Ubuntu 14.04 and their arm-none-eabi-gcc is virtually broken (no nano.specs), I added a mechanism to pull in an external GCC packages. Not nice, but does the job (I tried installing the correct gcc from a semi-official PPA, but that then conflicts with avr-gcc since both try to install a libcc; installing packages per-target is only possible via a hack, but then additional sourcelines/ppas are ignored; so I gave up and decided this to be most "clean" approach until the Travis people bump their Ubuntu version to something more recent).
On the bright side, this hack allows to add a pru-gcc and also built for beaglebone. I just don't want to build one now and figure out where to put it.

Results look a lot like this:
https://travis-ci.org/archi/klipper/builds/336354417

The fail for linuxprocess is caused by the linking klipper.elf step: Having -lutil before the actual object files causes the linker to discard the symbol `openpty`, which is later needed for linking. I didn't fix that for this PR since that's not the scope of the PR (hope that's okay?).

Future work:
1. Add beaglebone (need to prebuild and put pru-gcc somewhere)
2. Test the python stuff (I'm not a python dev, so maybe someone else should to do that?)
3. Export build artifacts somewhere (where?) so people can just download them instead of having to build from source :)

### CODE REVIEW

**Comment by archi** [comment]
Oh, didn't know PRs track changes to the originating branch. Okay, now this PR also fixes the parameter order. CI says that doesn't affect the other targets: https://travis-ci.org/archi/klipper/builds/336360179

**Comment by archi** [comment]
Travis-ci is free for open source projects, so you can just use it after registering at their site (uses your github login, so no new user/password). If you want to, I can link you to a tutorial later today ;)

**Comment by archi** [comment]
Regarding the build fix: However you like, it's trivial anyways.

**Comment by archi** [comment]
This is their beginners site: https://docs.travis-ci.com/user/for-beginners/
And a 5 minute video: https://www.youtube.com/watch?v=FEXY1ZP-sBs (and the .travis.yml is already there, so it's even less work).

They offer really good github integration: You register on their site and then select for which of your projects to enable their continuous integration service. Since travis uses the github account, the necessary hooks are automatically set and enabled in for your repository. And because Klipper is open source this comes entirely for free :)

Integrating python test cases should be possible, too. I think worst case I'll figure out how to hack that into a few simple bash or perl scripts and just run it for every target (or add a special magic target).

Especially in case you're getting more PRs this should help a lot, since those are tested, too - and the test results are visible in the PR on github. See for example https://github.com/archi/wzet/pull/16, there should be a "1 check passed" info and a button "View details".

**Comment by KevinOConnor** [comment]
Thanks.  This looks like a really good idea.  I need a few more days to look at it before committing, but I agree we should do this.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks!  I committed this change.  (I made a minor change to the build to use "make olddefconfig" so that it wouldn't fail with recent Kconfig changes.)

**Pull request closed without merging**
