### PR TITLE
virtual_sdcard: Calculate progress from first gcode (byte)

### PR DESCRIPTION
**Pull request by jordanruthe**
Calculate progress off of the byte position of the first gcode. This provides a more accurate progress percentage for smaller prints as it ignores the beginning slicer metadata.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks, but there is a general preference to not put print time heuristics into virtual_sdcard.py - the goal of that code is just to support printing.  The print_stats.py module has some heuristics for facilitating better estimates, but it may be better to look at something like [moonraker](https://github.com/Arksine/moonraker) which already has several mechanisms for calculating improved print estimates.

-Kevin

**Comment by jordanruthe** [comment]
I personally don't believe this would be print time heuristics, it's just making the progress percentage be as accurate as possible. When building clients based off moonraker, the developer can adjust the percentage by calculating it properly, but then the percentage value will vary between the client and Klipper, resulting in a confusing experience for the user. Having the progress percentage be calculated off the byte location of the first gcode would make a consistent experience across klipper and the clients. 

I don't think print_stats would be the place to alter the percentage value as it doesn't have access to the file to find the first gcode byte position, and I also don't think print stats should be accessing the file to find that out.

If you don't agree with the above, feel free to close this PR.

**Comment by cadriel** [comment]
I think the end result we're after here is consistency between a klipper configured LCD and any client, be it web or otherwise.

Currently there's disparity between them - which as mentioned above causes confusion.

If we're happy to move forward knowing that, that's okay too - and I can update Fluidd to match what the other clients are doing.

@Arksine @KevinOConnor

**Comment by Arksine** [comment]
One option here is to add a Moonraker plugin similar to Octoprint's `M73 Progress`.  The plugin could do the progress calculation and send M73 to Klipper on a timer.  Clients can request a list of enabled plugins in Moonraker, if they see the progress plugin enabled they could report value from `display_status.progress`.  Otherwise they can calculate progress however they prefer.

**Comment by cadriel** [comment]
That may be a fair compromise.. I wonder if that wouldn't also be a good way to provide common time estimates for all clients too? I.e., you end up with;

1. Duration only (as per current klipper lcd).
2. Slicer Estimates (total estimated time and M73 progress).
3. File estimated time (moonraker plugin estimates the total and sends M73 progress).
4. Something else.. ?

I feel like overall this deserves some thought if we end up going down the plugin route.

Thoughts?

**Comment by KevinOConnor** [comment]
> I think the end result we're after here is consistency between a klipper configured LCD and any client, be it web or otherwise.

I agree Klipper could be better at that.

I'm not sure what the best solution is.  Any advanced print time estimate will need to scan the file in advance and database the results - so I think klippy is probably not the best place for that.  That said, we do want to be able to have a consistent estimate across all the displays.  I do wonder if an external program that scanned the "virtual sdcard directory", analyzed new files, and provided the results to all the clients via the Klipper API server would be a scalable solution.  (Or use the moonraker API to accomplish the same result.)

-Kevin

**Comment by KevinOConnor** [comment]
BTW, I know Marlin has some ability to write out firmware files to the SD card.  Unfortunately, I don't know the details.  I wonder if it would be possible to detect if Marlin is running and use that method for the first Klipper install.  May not be worth the effort though.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as I don't think this is a good candidate for the Klipper master branch - I don't think we want to add this logic to virtual_sdcard.py .

-Kevin

**Pull request closed without merging**
