### PR TITLE
MMU2 Firmware Support

### PR DESCRIPTION
**Pull request by trevjonez**
Squashed signed off of #1044

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

I fear the changes to avr/gpio.c would be a maintenance burden.  That gpio code is a part of the "fast path" and is used on dozens of different boards.  I'm leery of adding complexity there to support one (atypical) board.

I'd like to give some advice on alternative approaches, but I don't have a good feel for the mmu2 mechanics.  Can you provide some high level guidance on what the ultimate support will look like (what klipper g-code commands will be added, what will the ultimate config file settings looks like)?  When a filament change occurs, what types of motions will the mmu2 steppers be required to make?

-Kevin

**Comment by trevjonez** [comment]
so currently as far as I can tell the MMU2 just requires T commands in order to trigger a tool change.

so T?, T0, T1 ... TN etc. as well as homing support. the mmu2 also makes use of an inductive prob to detect load/unload/runout but I figured I would put that bit off to last as it seems other people are working on filament sensor support etc...

One main issue that I hit when trying to follow our original discussion is that the existing stepper code depends on firmware level direction pin control which is on the shift register. initial attempts at support I was able to add the ability to flash lights etc by using many set digital calls but it was painfully slow compared to doing it direct on the mcu. and I was never able to get stepper motion figured out when going with that approach.

at least for me a goal with this is to get the MMU2 to work as is. all while keeping the filament control split out enough that anyone could print the parts and command it via 2560/ramps or duex5 ports etc.

as far as the kinematics go it is 3 stepper motors. two control which filament is being fed (selector/idler) and the other is an extruder (pulley).

for config I think what I want to do is add a property to printer, such as:

```
[printer]
kinematics: cartesian
filament: ips
(...)
```

which then causes up the IPS stepper config options to work similar to the way the cartesian argument does. filament would default to None which would mean business as usual.

from there I think an IPS config section or something similar to define a required set of gcode macros for the required motion and we would be set. 

Things that would get more interesting would be like when rebooting with filament already loaded you can't home the S axis due to the filament being a physical obstruction so further work would be required there to get an elegant user experience. although it should be achievable with further gcode commands to tell the system where the head is located based on known locations. IE ask the user where the head is `tool A - F?`

as far as the maintenance to GPIO goes I struggle to see a better option. But really this is why I opened the PR was to get feedback started as this is really only the next tiny step in the long road ahead.

**Comment by KevinOConnor** [comment]
Okay, thanks.

> at least for me a goal with this is to get the MMU2 to work as is. all while keeping the filament control split out enough that anyone could print the parts and command it via 2560/ramps or duex5 ports etc.

That sounds like a good idea.

At a high level then, I think you should be able to go forward with development using your current code.  We can always resolve the "shift register" implementation later.

> initial attempts at support I was able to add the ability to flash lights etc by using many set digital calls but it was painfully slow compared to doing it direct on the mcu.

If you use "update_digital_out" instead of "schedule_digital_out", you should be able to blast out the shift register updates from the host and have them execute in about a millisecond.  Take a look at klippy/extras/display/uc1701.py for an example of using that command.

> as far as the maintenance to GPIO goes I struggle to see a better option.

It's certainly possible to extend the mcu code if necessary.  If I understand correctly though, you're not really interested in the Klipper "kinematics" system - that is, you don't need to synchronize simultaneous stepper movements.  It sounds like the mmu2 would always have just one stepper moving at a time (and during these moves, the main printer toolhead would not be moving either).  In that case, the force_move module could handle these mmu2 stepper movements.  (Perhaps not the force_move.py code as it is today, but the mmu2 code could use that as a base for manually commanding steppers to move.)  In such a system, the mmu2 abstraction could be at the host "stepper move" level instead of at the mcu "stepper oid" level.  For example, the mmu2 code could implement a move_stepper() method that checked if the requested move is in a different direction from the last move and then blasts out the shift register updates prior to the movement in that case.  A different (simpler) move_stepper() method could be used on a ramps based mmu2 implementation that doesn't need special direction handling.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this pull request?

-Kevin

**Comment by trevjonez** [comment]
I think what I want to do with this is actually take the mmu2 board and do a whole split config for it specifically so it has its own gpio files. thus we can run klipper firmware on the board without muddying up the main AVR sources. that seem like a reasonable solution?

Sorry I have left this stuff setting for so long. work and life have been eating my free time the last few weeks.

**Comment by KevinOConnor** [comment]
My recommendation would be to implement the mmu2 support entirely in the host software and try to avoid making any micro-controller code changes.

The work-manual-stepper-20190208 branch that I uploaded has demo code for manually controlling a stepper (see https://github.com/KevinOConnor/klipper/issues/1180#issuecomment-462001267 ).  It should be possible to do something similar for the mmu2 board by having the host bitbang out the direction step changes if the high-level code detects that a move request is in a different direction from the last movement request.

-Kevin

**Comment by trevjonez** [comment]
I worry that host driven bit banging will not be robust enough. and how would the existing mcu stepper code deal with not having a dir change pin? feels dirty to me to let a gpio abstraction drive overhead all over through the host code. also can the existing step compress and message que work accurately with something else sending pin updates that need to be precisely at the right point in the precalculated move?

**Comment by KevinOConnor** [comment]
> I worry that host driven bit banging will not be robust enough

I don't think this board will ever be "robust".  It's a quirky board.  It's designed entirely to control an mmu2.  It's really only capable of driving an mmu2.

> how would the existing mcu stepper code deal with not having a dir change pin?

Use the normal config_stepper command and assign a dummy pin (eg, PF0) to the dir_pin.  A hack for a hacky board.

> feels dirty to me to let a gpio abstraction drive overhead all over through the host code.

That's actually my point.  As I see it, this board is exclusively for use with an mmu2.  Thus, it should ultimately be controlled entirely from a klippy/extras/mmu2.py module.  That module can independently schedule the direction changes on every direction update.  No need for any code changes outside of mmu2.py; no changes to the host kinematics code and no changes to the micro-controller code.  As near as I can tell, direction changes on an mmu2 will occur a handful of times per second which is well within the capability of the host code to generate and synchronize.

-Kevin

**Comment by trevjonez** [comment]
I suppose I don't disagree with this thing being quarky but a huge part of my motivation for any of this work is to bury the overhead as tightly and far away from anything else important. I will close this for now. Once I get the overall functionality working I can circle back on the shift reg headache and see what it will take to deal with it 100% in the host as well as have a way to test the GPIO implementation.

**Pull request closed without merging**
