### PR TITLE
print_stats: add `cancelled` when `CANCEL_PRINT` used

### PR DESCRIPTION
**Pull request by ayufan**
Before this change, a `CANCEL_PRINT` would set a `print_stats` to `paused`
that would later be workaround-ed with `moonraker`/`fluidd`/`mainsail` to re-define
`CANCEL_PRINT` to transition to `standby` and forcefully unload file.

This adds a proper `canceled` state. This additonally closes a file
from a `virtual_sdcard` context for `canceled`/`error`, as such state is no longer
resumable from this point.

This removes workarounds needed by `fluidd`/`mainsail` as previously they would ask to:
- https://docs.fluidd.xyz/configuration/initial_setup#cancel_print
- https://docs.mainsail.xyz/necessary-configuration#for-pause--resume--cancel-functionality
- https://github.com/Arksine/moonraker/blob/master/moonraker/components/history.py#L191
- manually call `CLEAR_PAUSE` to mark `pause_resume` as not paused before the call to `SDCARD_RESET_FILE`
- manually call `SDCARD_RESET_FILE` to reset `print_stats` to `standby` and close file in `virtual_sdcard` context
- used a workaround to discover `canceled` state by looking at `print_stats` transition from `paused/printing` to `standby`

This removes all the above workarounds, as either generic `CANCEL_PRINT` can be used, or can be extended with `TURN_OFF_HEATERS`.

This connected with https://github.com/KevinOConnor/klipper/pull/4364/files, does provide a clear distinction about `virtual_sdcard` holding information of currently loaded file, `print_state` holding information about the most recent print result.

Related:
- https://github.com/Arksine/moonraker/pull/176

Signed-off-by: Kamil Trzcinski <ayufan@ayufan.eu>

### CODE REVIEW

**Comment by ayufan** [comment]
cc @Arksine @cadriel @meteyou

**Comment by KevinOConnor** [comment]
Okay, a change here is fine with me, but I would need feedback from the frontend developers.

Also, if we're changing this area of the code, it's worth mentioning that #3666 and #3895 are also pending.

-Kevin

**Comment by zellneralex** [comment]
Hello Kevin,

for me #3666 is a general problem and should not be mix'ed with a user forced CANCEL_PRINT. At the moment any error during a print using the virtual_sd will not stop the print and/or switch of the heater. E.g. a QGL fail in your PRINT_START will exit your PRINT_START but the print of the virtual_sd card will continue. Maybe there is a need of an "general error handler" while printing from the virtual_sd.

**Comment by meteyou** [comment]
i still have to test it, but from a purely visual point of view, i see the modification as a good idea. it makes it easier to separate user forced cancellations and klipper errors, and it also makes it possible to display them differently/seperate in the gui (reprints after canceling for example)

**Comment by ayufan** [comment]
@zellneralex 

Likely this can be solved by a sane defaults: on error or cancel always do `TURN_OFF_HEATERS` as this is a security feature.

**Comment by zellneralex** [comment]
@ayufan but that solve only part of the problem I would expect the print to error and stop if e.g a QGL fails as this means the gantry is not leveled and has a potential risk of a nozzle crash. That's the point why I suggest a more generally look in an error handling when using the virtual_sd

**Comment by ayufan** [comment]
@zellneralex 

> potential risk of a nozzle crash

We have no clue how to move gantry. What we can do, is to offer a way to allow you to hook on error. This could be achieved with:

```
[print_stats] or [pause_resume] or [something_else]
on_complete_gcode: ...
on_cancel_gcode: ...
on_error_gcode: ...
```

**Comment by zellneralex** [comment]
@ayufan btw the CLEAR_PAUSE is in the macro as the proposed flow is: PAUSE -> CANCEL_PRINT or RESUME. Later that was changed that you can also use CANCEL_PRINT direct in both FE.
The CLEAR_PAUSE simply avoids that message 'Print already paused' if you want to avoud it in both cases https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/pause_resume.py#L91 would need to change to  `if not self.is_paused:
    self.cmd_PAUSE(gcmd)`

**Comment by ayufan** [comment]
@zellneralex Good point. I think `cmd_PAUSE` was retained, to ensure that we set a proper state, but you are right, this can be avoided.

**Comment by zellneralex** [comment]
> @zellneralex
> 
> > potential risk of a nozzle crash
> 
> We have no clue how to move gantry. What we can do, is to offer a way to allow you to hook on error. This could be achieved with:
> 
> ```
> [print_stats] or [pause_resume] or [something_else]
> on_complete_gcode: ...
> on_cancel_gcode: ...
> on_error_gcode: ...
> ```

That's my point I expect klipper to handle it thats the reason I say that should been mixed with the PR here. There are errors where it is simple enough to been reported but there are others that need to at least stop the print. As Kevin mentioned in the past octoprint handles most of them by simply sending a M112. So as more and more users switching away from octo and therfore use the virtual_sd for there printing task's it might be time to get that better sorted

**Comment by zellneralex** [comment]
I will check your changes against the proposed FE macros later today as both FE uses currently macros I did.

**Comment by ayufan** [comment]
> That's my point I expect klipper to handle it thats the reason I say that should been mixed with the PR here

We can solve that, but I would not bundle too many things at once, as they might require more discussion. This PR acknowledges a missing state, and does not truly change status-quo that was present.

I'm happy tho to follow-up, but to keep things easy to discuss I would focus on one thing at a time, it makes it easier to reason about problems :)

**Comment by ayufan** [comment]
> I will check your changes against the proposed FE macros later today as both FE uses currently macros I did.

Thanks. My current macro is:

```ini
[gcode_macro CANCEL_PRINT]
rename_existing: BASE_CANCEL_PRINT
gcode:
    PRESENT_PRINT
    BASE_CANCEL_PRINT

[gcode_macro PRESENT_PRINT]
gcode:
  SAVE_GCODE_STATE NAME=PRESENT_PRINT_state
  M83 ; extruder relative mode
  {% if printer.extruder.temperature > 175 %} G1 E-10 F500 {% endif %} ; Retract a bit
  TURN_OFF_HEATERS ; turn off extruder & heatbed
  M107 ; turn off fan
  {% if printer.toolhead.homed_axes == "xyz" %} G1 X0 Y200 F3000 {% endif %} ; home X axis
  RESTORE_GCODE_STATE NAME=PRESENT_PRINT_state
```

It works fine with latest frontend, even though it does not show `cancelled` as expected. With Moonraker change mentioned, it does track in history cancelled properly. This change should also be backwards compatible for products that use `printing/paused > standy` flow.

**Comment by zellneralex** [comment]
For me it is more important that the work backwards so I will check it against the current proposal in FluiddPi and MainsailOS. We do not want all people coming to the discord asking why there macros do not work anymore. Of coarse I will do also modified version that would fully use your changes

**Comment by ayufan** [comment]
> For me it is more important that the work backwards so I will check it against the current proposal in FluiddPi and MainsailOS

Thank you. I agree with this being important.

**Comment by cadriel** [comment]
I've taken a look, and I think this change is good. It'll remove some unnecessary logic client side, and helps better demarcate these states.

I have not tested this yet - and I would like to prior to merge. I'm not sure what impact a change like this is going to have on the current releases in circulation, and I think we may need to consider in what order, and how we release this - if it does require client updates.

@ayufan Have you tested the clients with it in place, any concerns?

A couple of things;

**Comment by ayufan** [comment]
@cadriel 

I tested:
- Moonraker history plugin breaks without `cancelled`
- Fluidd appears to work fine with `cancelled` and non-cancelled
- I did not yet test Mainsail, but will try
-

**Comment by ayufan** [comment]
I tested the following:

## With patch (with default `CANCEL_PRINT`)

```ini
[gcode_macro CANCEL_PRINT]
rename_existing: BASE_CANCEL_PRINT
gcode:
    BASE_CANCEL_PRINT
```

```
17:03:40 $ SDCARD_PRINT_FILE FILENAME="wait_print.gcode"
17:03:40 File opened:wait_print.gcode Size:450
17:03:40 File selected
17:03:46 $ CANCEL_PRINT
```

Screen Shot 2021-06-09 at 16 46 53
Screen Shot 2021-06-09 at 16 47 02

## With patch with old `CANCEL_PRINT`

```ini
[gcode_macro CANCEL_PRINT]
rename_existing: BASE_CANCEL_PRINT
gcode:
    CLEAR_PAUSE
    SDCARD_RESET_FILE
    BASE_CANCEL_PRINT
```

```
17:07:35 $ SDCARD_PRINT_FILE FILENAME="wait_print.gcode"
17:07:35 File opened:wait_print.gcode Size:450
17:07:35 File selected
17:07:40 $ CANCEL_PRINT
17:07:41 // action:cancel
```

- The `action:cancel` appear here due to `CLEAR_PAUSE`, `SDCARD_RESET_FILE` resetting active virtual sdcard context, and `BASE_CANCEL_PRINT` => this is harmless

Screen Shot 2021-06-09 at 16 49 15
Screen Shot 2021-06-09 at 16 49 20

## Summary

All appears to work fine. The Moonraker patch is required for History component: https://github.com/Arksine/moonraker/blob/master/moonraker/components/history.py#L191

**Comment by KevinOConnor** [comment]
> That's my point I expect klipper to handle it thats the reason I say that shouldn't been mixed with the PR here.

Just to be clear, my goal with mentioning #3666 and #3895 was to raise awareness of two other pending issues.  I'm not suggesting that this PR should fix them.

Cheers,
-Kevin

**Comment by zellneralex** [comment]
Did a few test on mainsail and fluidd
1) no CLEAR_PAUSE AND SDCARD_RESET_FILE -> works status cancel file still shows as loaded
2) current FE macros (CLEAR_PAUSE AND SDCARD_RESET_FILE) -> works status standby file unloaded
3) only CLEAR_PAUSE -> print can not been canceled until you run SDCARD_RESET_FILE manual
4) only SDCARD_RESET_FILE same as 2) but message already paused

used FE macro 
```
[gcode_macro CANCEL_PRINT]
rename_existing: CANCEL_PRINT_BASE
gcode:    
  TURN_OFF_HEATERS
  CLEAR_PAUSE    
  SDCARD_RESET_FILE    
  CANCEL_PRINT_BASE
```

Chase 3 is what worries me

**Comment by ayufan** [comment]
@zellneralex

Do you mean `CLEAR_PAUSE` being run alone? 

I didn't see a usage of `CLEAR_PAUSE` alone. This is based on a fact that `print_stats` is connected with `virtual_sdcard` and cannot be used outside of this context for other purposes.

I would aim to ensure that we can maintain backward compatibility with what is running for majority and a new preferred one.

**Comment by zellneralex** [comment]
Chase 3 means 
```
[gcode_macro CANCEL_PRINT]
rename_existing: CANCEL_PRINT_BASE
gcode:    
  TURN_OFF_HEATERS
  CLEAR_PAUSE    
  CANCEL_PRINT_BASE
``` as said this is used to avoid the message already in PAUSE when using the FE macro out of a paused stare

**Comment by ayufan** [comment]
Did you test latest commit? This should not be needed :)

**Comment by zellneralex** [comment]
Oh no I prepared at 12h ago

**Comment by zellneralex** [comment]
So need to redo it with the last changes

**Comment by zellneralex** [comment]
Already integrated you last changes, started the next test cycle. I will redo all 4 chases

**Comment by zellneralex** [comment]
redone all 4 cases again. I can confirm there are working now.

I will update the Mainsail docu and MainsailOS macros as soon that is merged and @cadriel can than take them from mainsailOS. The change will require no change it both FE

**Comment by ayufan** [comment]
Thank you @zellneralex !

**Comment by cadriel** [comment]
Thank you all, given this isn't breaking at all then I think its good from my side.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
