### PR TITLE
Support customizing the main lcd display via Jinja2 templates

### PR DESCRIPTION
**Pull request by KevinOConnor**
This PR adds support for customizing the content and layout of the main lcd screen.  It introduces two new config sections (`[display_data]` and `[display_template]`) to specify the content.  The default screen layout is unchanged from the previous hard-coded layout (see the new file klippy/extras/display/display.cfg for the Jinja2 config sections used to recreate the current layout).  So, almost all existing users should not notice a change.  However, it is hoped this new capability will make it easier for users to add new display information going forward.

As part of this process, the existing menu based display customization (via menu "deck" and "card" items) was disabled.  Any users using that system will need to convert to the new system implemented here.

@mcmatrix , @Arksine - FYI.

-Kevin

### CODE REVIEW

**Comment by Arksine** [comment]
Hi Kevin, looks great!  I think to support multiple displays we would only need to make a small change, and that is it instantiate "DisplayStatus" in the load_config() method of __init__.py and add it as a printer object.  Then each individual display could look up the "display_status" object and assign its get_status() method.

Since each display no longer stores its own message state this change would remove the ability to add a SET_MESSAGE muxed gcode, however that is likely no longer necessary as users can now customize each display.  

I'll pull this and test it against multiple displays, then report back with results.

**Comment by KevinOConnor** [comment]
> I think to support multiple displays we would only need to make a small change, and that is it instantiate "DisplayStatus" in the load_config() method of __init__.py and add it as a printer object. Then each individual display could look up the "display_status" object and assign its get_status() method.

Thanks - that's a good idea.  I went ahead and updated this branch to do something similar.  I made the status.py module its own independent display_status.py "extras" module.  That way the display.cfg can access the single global `printer.display_status.xxx` information irrespective of the display.

-Kevin

**Comment by Arksine** [comment]
Ok, looks good.  I went ahead and added a PR against this branch so you could see what the commits look like to add multi display support.

One thing I did notice is that the progress bar isn't rendering correctly on the UC1701/SSD1306.  I was able to correct it by modifying display.cfg by changing the this:
```
[display_data _default_16x4 row2col0]
position: 2, 0
text:
  {% if 'extruder1' in printer %}
    { render("_heater_temperature", param_heater_name="heater_bed") }
  {% else %}
    {% set progress = printer.display_status.progress %}
    { draw_progress_bar(2, 0, 10, progress) }
    { "{:^10.0%}".format(progress) }
  {% endif %}
```
to:
```
[display_data _default_16x4 row2col0]
position: 2, 0
text:
  {% if 'extruder1' in printer %}
    { render("_heater_temperature", param_heater_name="heater_bed") }
  {% else %}
    {% set progress = printer.display_status.progress %}
    { draw_progress_bar(2, 0, 10, progress) }
  {% endif %}

[display_data _default_16x4 progress_text]
position: 2, 0
text: 
  {% if 'extruder1' not in printer %}
    {% set progress = printer.display_status.progress %}
	{ '{:^10.0%}'.format(progress) }
  {% endif %}

```

I assume that change would also need to be made for the progress bar when extruder1 is enabled.  I checked against a ST7920 and it renders correctly both with the original version and the updated version.  I didn't add this to the multi-display PR in case you wanted to resolve it differently.

**Comment by KevinOConnor** [comment]
> One thing I did notice is that the progress bar isn't rendering correctly on the UC1701/SSD1306.

Oops - I think we can fix it by writing the text prior to drawing the progress bar.  (That's how the old hardcoded system did it - I missed that.)  I rebased and pushed again - hopefully it's fixed now.

Thanks!
-Kevin

**Comment by KevinOConnor** [comment]
Actually, on second thought - that probably isn't going to work.  I have an ssd1306 here - I'll hook it up and test locally.  I think you're right though - adding a new block is probably the simplest solution.

Thanks.
-Kevin

**Comment by KevinOConnor** [comment]
FYI, I rebased again with a new fix and tested it on the st7920 and ssd1306.  I added a new display_data block for the progress bar with its display position set to 3,16 to make sure it would be rendered after all the text is shown.  A bit of a hack, but should be okay for now.

-Kevin

**Comment by Arksine** [comment]
Just tested on every display I have, works great!

**Comment by mcmatrix** [comment]
Hi Kevin, nice work!
It will simplify the menu system, this way custom displays and menus are kept separately.
I keep this in mind and try to rework the menu code accordingly.

**Pull request merged**
