### PR TITLE
linux: change clock frequency

### PR DESCRIPTION
**Pull request by andryblack**
Allow configure timer resolution for linux mcu.
With gpio implementation need more precise timings for some hardware.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
The default of 20000000 enables a scheduling precision of 50ns.  What task were you doing that required greater scheduling precision?  What value did you ultimately need?

I'd prefer not to add Kconfig settings if there is an alternative - it leads to confusion for many users and it increases the testing burden for developers.

-Kevin

**Comment by andryblack** [comment]
I need value greater 47MHz for bypass [https://github.com/KevinOConnor/klipper/blob/master/src/lcd_hd44780.c#L35](this) check.

**Comment by KevinOConnor** [comment]
Ah, okay.  Lets just unconditionally move the Linux value to 50Mhz.

Separately, the lcd_hd44780.c (and similarly the lcd_st7920.c) code wont work reliably on the Linux mcu.  The `command_config_hd44780()` function times a transmission and subtracts that time from the requested delay - that logic is based on the premise that the micro-controller has constant timing.  However, the linux mcu code will not have constant timing and thus this assumption is not valid.  It's probably possible for that code to disable that timing optimization on the linux mcu.

-Kevin

**Comment by andryblack** [comment]
> Ah, okay. Lets just unconditionally move the Linux value to 50Mhz.

Ok, I use 50Mhz for my setup already. Another issue PWM (soft) used for screen backlight on 20Mhz has strange artefacts: looks like it’s freezing or change duty cycle every 1second. On 50Mhz this effect invisible.

**Comment by KevinOConnor** [comment]
Thanks.

I'm not sure why the soft pwm code would care about the precision.  Maybe it resonated with something.

FWIW, I suspect timing wont be great on the linux mcu.  It might be possible to improve the timing a little by moving the code from a polling solution to one based on unix signals.  But, even then it wont be great.

-Kevin

**Pull request merged**
