### PR TITLE
Allow manual_stepper to run in parallel than an other stepper

### PR DESCRIPTION
**Pull request by kakou-fr**
Based on the previous patch in issue #897.

Signed-off-by: Jeremy Briffaut <kakou@kakou.org>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  At a high-level it looks like good.  As a minor comment, I don't think the "sync" state should be stored between commands.  I think it would be preferable for every manual_stepper move that does not require synchronization to explicitly state SYNC=0.  I think it would be preferable for the sync parameter to be explicitly passed to `do_move()`.

-Kevin

**Comment by kakou-fr** [comment]
better like this ?

**Comment by KevinOConnor** [comment]
Yes, thanks.  I made some minor changes (mostly to the G-Codes.md description) and committed this (commit 6be552f6).

-Kevin

**Comment by kakou-fr** [comment]
thks

**Pull request closed without merging**
