### PR TITLE
Speed icon

### PR DESCRIPTION
**Pull request by jameswood**
LCD: "Feed Rate" text changed to a speedometer icon to sit better with the other icons. After 2 years I thought it was time 🤣

### CODE REVIEW

**Comment by jameswood** [comment]
Preview: https://i.imgur.com/Mm6O6CZ.jpg

**Comment by JohnEdwa** [comment]
Feedrate is one of those annoyingly hard things to iconify as it is a speed multiplier, and not actually speed itself. 
If something like this is done, I think it should also come with the re-branding of "Feed Rate" to actually just be "Speed Multiplier" or something like this. Klipper is already the breaker of standards and inventor of new things, so why not.
Maybe it could eventually finally get other people (Marlin) to hop on board too and end the needless Feed/Flow confusion.

**Comment by jameswood** [comment]
> Feedrate is one of those annoyingly hard things to iconify as it is a speed multiplier, and not actually speed itself.
> If something like this is done, I think it should also come with the re-branding of "Feed Rate" to actually just be "Speed Multiplier" or something like this. Klipper is already the breaker of standards and inventor of new things, so why not.
> Maybe it could eventually finally get other people (Marlin) to hop on board too and end the needless Feed/Flow confusion.

What do you think about just calling it "Speed," given that it's always displayed as percentage?

**Comment by LazaroFilm** [comment]
This is great! Love the idea! Can't wait to see in the main branch!

**Comment by KevinOConnor** [comment]
Thanks.  FYI, I don't personally have a preference on display icons.  As some high-level feedback, I agree the new icon looks neat, but I'm not sure a new user will understand what it means.  I'm therefore not sure it is a good idea to change it to the default, as I would not want it to raise support questions.  The "feedrate" icon isn't pretty, but I think it does a good job at being unambiguous. 

Cheers,
-Kevin

**Comment by jameswood** [comment]
@KevinOConnor I agree about the need to limit support requests and agree that my previous (*ahem* extremely pretty!!) icon says "feed rate" more clearly than this one does.

From here it's all my opinion, but I think I make at least one good point, and hopefully it comes across in the respectful way it's intended!

I don't agree with the term itself. I think "feed rate" is a poor name for the setting. We do not use "feed" anywhere else, so it's not inherently clear what it is that we're setting the rate *of*. The amount of feed of filament? The movement of the head? It's both of these things, as we know, but this is not explicit from the name. So already, "feed rate" assumes some prior knowledge; the name "speed" is, I think, instantly clear, and if anything, less cryptic for new users. With that in mind, I think this icon strongly sugggests "speed" to both new and experienced users.

The value can't be edited here, just displayed - so the user will have to have to set it somewhere else before the number appears here, making it pretty clear to them what is being displayed. I would also argue that "feed rate" should be renamed "speed" in the menus but that's beyond this scope ("Speed multiplier" is perhaps a better name, but the % symbol makes the word "multiplier" redundant and I'd argue that "speed" is plenty).

I understand that "Feed Rate" has become the accepted name across the industry. I do not agree with the industry 🤣 (background for those who don't know: the name "feed rate" came from CNC machining land, where the movement of the tool relative to the workpiece (the "feed") is independent of, say, the rotational "speed" of the spindle ("feeds and speeds" go hand in hand)).

OK, that's the end of Opinion Corner!

I am happy to defer to your experience in writing and supporting widely-used software. This change could be considered mostly decorative, and if you think it will make the overall experience worse as a default, then that's cool by me (fwiw 😆)

Do you have any advice about how it would work as an optional feature? Would users ideally enable it in printer.cfg under `[display]`, for example?

**Comment by KevinOConnor** [comment]
Thanks.  Some random thoughts:
1. I agree that "feed rate" is not a great name.  However, a user can do a web search for it and get some basic results.
2. I think the speedometer is neat.  I'm not sure every user will immediately "see" the speedometer and associate it with "speed" though.
3. "Speed" could be reasonably confused with the G1 F parameter (ie, the move speed parameter).
4. I'm not sure we need to show the "speed factor override percentage" on the default screen at all.  (To the best of my knowledge, it's a value that is rarely changed.)  I suspect it's on the default screen because there was "space to fill".

I don't want to be critical - I think the picture is great.  I am a little leery of changing one icon that can cause some confusion for another icon that can cause a "different set of confusion" though.  Beyond that, I don't personally have a preference for the display icons.

For users that want to change the icon (or any icon), they can place the new `
[display_glyph feedrate]` definition in the printer.cfg file.  Any definition in printer.cfg will override a definition in display.cfg.

Cheers,
-Kevin

**Comment by jameswood** [comment]
Hey Kevin,

Thanks so much for your patience, encouragement and explanation, I get it now. I'll cancel this pull request and send a different one - I've put this icon (and a few others to make it worthwhile!) into a `sample-glyphs.cfg` file inside  `/config`

**Pull request closed without merging**
