### PR TITLE
Creality Ender 3 v4.2.7 configuration file

### PR DESCRIPTION
**Pull request by Feche**
Fully working Creality Ender 3 configuration for Creality v4.2.7 newest silent motherboard, it includes LCD display too.
Tested and fully working!

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In order for me to commit directly, a commit must have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .  That said, I can usually commit a config file under my signed-off-by line if you prefer.

How does this config differ from the existing config/printer-creality-ender3-v2-2020.cfg file?  Is it for an ender3-v4 or is just the board different?  What year (roughly) is this printer from?

-Kevin

**Comment by Feche** [comment]
> Thanks. In order for me to commit directly, a commit must have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md . That said, I can usually commit a config file under my signed-off-by line if you prefer.
> 
> How does this config differ from the existing config/printer-creality-ender3-v2-2020.cfg file? Is it for an ender3-v4 or is just the board different? What year (roughly) is this printer from?
> 
> -Kevin

Hello, you can use your signed off if you want!

Ender 3 V2 has motherboard v4.2.2, this config is for motherboard v4.2.7 (silent, with TMC2225 drivers)

The step_pin and dir_pin pins are inverted in v4.2.7, and I also added LCD support for st7920.

In my case, I have a Ender 3 with v1.1.4 and replaced with v4.2.7, so this config file makes Klipper work correctly with LCD support.

**Comment by zellneralex** [comment]
Feche, Kevin can not use his sign of for that. Please read:

It is important to have a "Signed-off-by" line on each commit - it certifies that you agree to the developer certificate of origin. It must contain your real name (sorry, no pseudonyms or anonymous contributions) and contain a current email address.

It is like you signing a contract. Without that line it will never be merged in

**Comment by KevinOConnor** [comment]
Thanks.  I added a generic-creality-v4.2.7.cfg example config file (commit 0bf0cb5b).

-Kevin

**Pull request closed without merging**
