### PR TITLE
Add CNC type commands

### PR DESCRIPTION
**Pull request by nytowl**
CNC machines use G0[0-9] for rep-rap type commands G[0-9]. Parse the CNC
style as well.

Is this all thats need or are there more spots to change this?

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, my high-level feedback is that this can already be done without code changes by adding `[gcode_macro G01]` type config sections to the printer.cfg file.  So, I'd be inclined not to make this code change.

-Kevin

**Comment by grigi** [comment]
Is the point not also to have good defaults? Could this then not be included as a standard macro, just so that people don't end up with lots of boilerplate in their config file?

**Comment by KevinOConnor** [comment]
> Is the point not also to have good defaults?

FWIW, I prefer to target "slicer support" and not "gcode support".  If we can identify a commonly used program that produces a particular gcode dialect (in its default configuration), then it might be worth looking at adding support for that particular program.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as I don't currently think it is a good candidate for the master Klipper branch.

-Kevin

**Pull request closed without merging**
