### PR TITLE
Improved CAN support for STM32

### PR DESCRIPTION
**Pull request by bondus**
A major rewrite and update to the CAN support for STM32 MCUs. 
It is more portable and should work on F0, F1 and F4 MCUs, F042 and F103 are tested.

(It my git history is cluttering yours I can make a cleaner pull request)

### CODE REVIEW

**Comment by Delsian** [comment]
We discussed it with @bondus  in private chat early.
Reviewed and looks good for me. Thanks

**Comment by KevinOConnor** [comment]
Okay, thanks.  At this point, I'm just looking for the signed-off-by line (as described at https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).

-Kevin

**Comment by bondus** [comment]
Signed-off-by: Pontus Borg <glpontus@gmail.com>

**Comment by bondus** [comment]
I'll do it properly next time. I plan to integrate CAN into klippy too, to avoid the external serial emulation program.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by bondus** [comment]
I saw the recent STM32F2 port, it looks very similar to F4 and a few #ifdef changes should make the CAN bus work fine.

**Pull request merged**
