### PR TITLE
TMC5160 diag0 support

### LINKED ISSUE #3150: FYSETC TMC5160 v1.2 - diag0_stall homing
Kevin: 

I've just been updating one of my machines to use some new drivers and the latest klipper code.
What I am finding is that the default of using diag1_stall is not appropriate for these step sticks.

I've been able to workaround by modifying [this line](https://github.com/KevinOConnor/klipper/blob/68e9a495dd49dc46f984858a45102925eef1e274/klippy/extras/tmc.py#L231) to reference "diag0_stall" instead.

Would you be open to a pull request that exposes a configuration option to customize which register to use?  It seems only the 2130 and 5160 could be impacted by such a change. Though I am doubtful any 2130 driver layout would need this change or you would have likely seen this issue before.

Or is the timing of homing override gcode timing appropriate that I could use a `SET_TMC_FIELD` to set the value immediately preceding a `G28` command? Skimming the extras files made it seem like any value I set would be overridden by `handle_homing_move_begin`

https://wiki.fysetc.com/S5160_V1.2/
https://github.com/FYSETC/TMC-Stepstick-Divers/blob/master/hardware/S5160/V1.2%203020/FYS_TMC5160_V1.2.pdf

Notes for SEO:

Similar to other 5160 stepsticks in order to get sensorless homing to function some modifications to the driver need to be made.
The FYSETC 5160 v1.2 driver exposes the CLK pin via pin3 on connector P2. For sensorless homing to work you need to remove that pin and connect it to ground (pin 1 on connector P6). Additionally you will need to add a pin to the board on pin 2 of connector P1 in order to connect the diag0 signal to the MCU.

All done, it looks like this:
00100lrPORTRAIT_00100_BURST20200803093630154_COVER

### PR DESCRIPTION
**Pull request by trevjonez**
Follow up to and closes #3150 

Here is my first pass at it. I figured pushing the diag_pin lookup into the tmc_spi is a reasonable place to limit duplication and minimize impact on the 2209/uart code.

I wasn't sure what the best place to document was so I just added that small note to the sensorless homing page. If the
 assumption holds, that the diag0 only hardware is uncommon I don't expect much more would be necessary?

~My machine with with the 5160's just finished as I was typing this PR up, so I am headed to test it now.~
One silly mistake on my part and it seems to be working as expected.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  As high-level feedback, we really don't want to add this to the mcu_tmc classes, as those classes are already very complex.  I would perform the pin selection and pin configuration within TMCVirtualPinHelper - something like:

```python
class TMCVirtualPinHelper:
    def __init__(self, config, mcu_tmc):
        self.printer = config.get_printer()
        self.mcu_tmc = mcu_tmc
        self.fields = mcu_tmc.get_fields()
        if self.fields.lookup_register('diag0_stall') is not None:
            if config.get('diag0_pin', None) is not None:
                self.diag_pin = config.get('diag0_pin')
                self.diag_pin_field = `diag0_stall'
            else:
                self.diag_pin = config.get('diag1_pin', None)
                self.diag_pin_field = `diag1_stall'
        else:
            self.diag_pin = config.get('diag_pin', None)
            self.diag_pin_field = None
        ...
```

-Kevin

**Comment by trevjonez** [comment]
@KevinOConnor thank you! I do like that better, it didn't occur to me to use the field lookup to differentiate. I will make this adjustment and retest. 

One less critical question:

Should I keep the assertion for only having one of the two pins? I assume if not the result would be the unused value raising an error later in the configuration phase.

I do not know what your preferred style for this type of thing is, but I'd like to try and follow suite. I tend towards throw as early and specific as possible.

**Comment by KevinOConnor** [comment]
> I do not know what your preferred style for this type of thing is, but I'd like to try and follow suite. I tend towards throw as early and specific as possible.

FWIW, my general preference is to make sure the user gets an error, but otherwise try to keep the code simple.  As an example, if the user were to do something silly like defining both diag0_pin and diag1_pin then the code above would provide _an_ error.

That said, I don't have a strong preference - I recognize that everyone has their own coding style and no one style is "the best".

Cheers,
-Kevin

**Comment by trevjonez** [comment]
Ok change made, basically verbatim as your suggestion above. Working as expected.

If both pins are specified the `check_unused_options` picks it up as expected.
```
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 143, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 140, in _read_config
    pconfig.check_unused_options(config)
  File "/home/pi/klipper/klippy/configfile.py", line 248, in check_unused_options
    option, section))
Error: Option 'diag1_pin' is not valid in section 'tmc5160 stepper_x'
```
Not quite as specific but still straight to the cause of the issue, worst case a quick search in github should land them on the sensorless homing notes or this pull request.

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.  Would be great to also update config/example-extras.cfg as well.

-Kevin

**Comment by trevjonez** [comment]
Side thought: what if the extras had a markdown document and the `.cfg` for it was embedded in a code block so the viewing experience was super rich and I would assume then easily made available via klipper3d.org? plus then you would get "free" linking to and from existing docs for the more detailed things like the sensorless homing.

Obviously the real machine specific example configurations would want to be kept in the existing format, but for documenting how to use all the extras and organizing it, it could be a nice experience

**Comment by KevinOConnor** [comment]
Thanks.

> what if the extras had a markdown document and the .cfg for it was embedded in a code block so the viewing experience was super rich and I would assume then easily made available via klipper3d.org

FWIW, my experience with auto-generated documentation has not been positive.  They aren't significantly less work for developers and the resulting documents are often of poor quality.  That said, if someone wants to experiment, I'm open to reviewing the results.

-Kevin

**Pull request merged**
