### PR TITLE
Add STM32F407 port

### PR DESCRIPTION
**Pull request by ssolodskih**
Add STM32F4 port, based on current STM32F1 port, currently tested on 
STM32F407VET6 "Black Pill" board. The maximum possible step rate
is around 650K steps per second.

This uses stm32flash to burn the firmware. The bootloader needs to be started
by setting BOOT0 to 1 and resetting the MCU. There is no automatic bootloader,
unlike on Arduino.

Signed-off-by: Sergei Solodskikh <s.solodskih@gmail.com>

### CODE REVIEW

**Comment by mattthebaker** [comment]
It should be possible to activate the ST ROM bootloader without manipulating the boot pins. There is a register SYSCFG_MEMRMP that gets set from the boot pin state, but can be overridden by the firmware. We would have to set the register and then jump to the reset vector address.

I wanted to look at a 407/F4series port too, I'll get this built up soon to help test. I have an F407 dev board, and a pick and place machine with F407.

**Comment by KevinOConnor** [comment]
Thanks.  In order for this to be merged the build checks would need to successfully pass.  (Looks like there are mostly just white space issues.)

Some additional comments:
- One of the files in the commit (stm32f4.ld - included in two locations) explicitly states that distribution is not permitted - that makes it incompatible with the GPL license and thus we would not be able to commit it to Klipper.
- Has this code been tested on a real board?  If so, which board does it work on?
- There seems to be a bit of similarity between the f4 code and the f1 code.  Is it feasible to have just one directory and use some compile time checks to select between the two?  If separate files are required, then the new code should not leave the old code commented out (commenting out old code tends to cause confusion).
- It would be a good idea to add a test/configs/stm32f0.config so that a compile time check is performed during the regression tests.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by KevinOConnor** [comment]
Okay - I'm going to close this pending a response to the above comments.

-Kevin

**Pull request closed without merging**
