### PR TITLE
Changed config for TAZ 6; LCD UI improvements

### PR DESCRIPTION
**Pull request by marcio-ao**
- Added LCD to TAZ 6 configuration file
- The heat waves on the bed now only show up when the heater is on, otherwise a bare bed is shown.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I pulled this in to the work-lcd-20180115 branch.  I modified the heat wave change - the current code locally blanks the screen at the start of each screen update (self.lcd_chip.clear() ), so it isn't necessary to explicitly blank any icons, text, or graphics during the update.  If it doesn't get drawn during the update, it's erased from the screen during the self.lcd_chip.flush() call.

The flush() call checks between the current screen and the last sent screen, so if parts of the screen are redrawn the same way then those changes aren't resent.

**Comment by marcio-ao** [comment]
I just checked in another mod but I got a conflict. I think I resolved it.

**Comment by KevinOConnor** [comment]
On Tue, Feb 20, 2018 at 06:38:44PM +0000, Marcio Teixeira wrote:
> I just checked in another mod but I got a conflict. I think I resolved it.

Okay, sorry about that.  I'll hold off on merging while you work, so
you don't get further conflicts.

-Kevin

**Comment by marcio-ao** [comment]
@KevinOConnor : Um, I'm not sure what state this is in. The latest commit is this one. Pretty simple:

https://github.com/KevinOConnor/klipper/pull/184/commits/679cc1b1f2905f9bfa4388ae947dcc620d87384f

**Comment by marcio-ao** [comment]
@KevinOConnor : I admit GIT confuses the heck out of me sometimes. I'm done with the edits for today. If you want to make sure everything gets merged, I can review tomorrow and make sure nothing got missed.

**Comment by marcio-ao** [comment]
BTW, one other though I had is that the screen with a blank hole where the progress bar used to be looks bad. How about printing just the frame of the progress bar with the words "No SD" or "No card"?

**Comment by KevinOConnor** [comment]
Okay - I wonder if we could avoid nested functions as they can be confusing.  I committed a demo of how it could be done without the nesting.

Also, my 20x04 display doesn't like the \x1A (it just shows as a blank).  How is that supposed to look?

We don't need to keep the 2004 and 12864 code together - it just made testing a little easier.

**Comment by marcio-ao** [comment]
@KevinOConnor : To nest or not to nest -- I don't have a preference either way. Feel free to un-nest if you prefer. The "\x1A" is supposed to look like an arrow:

img_3861

I didn't realize the code was shared between the two displays. I wonder if it would be possible to pick an equivalent looking character and selectively apply it based on the display? Anyhow, the idea is that if the current temperature is not near the target, it shows an arrow indicating that the temperature is changing. It helps to de-clutter the display.

**Comment by marcio-ao** [comment]
According to [this datasheet](https://www.sparkfun.com/datasheets/LCD/HD44780.pdf), there are in fact arrow characters, but to make things interesting it varies based on the version of the chip. ROM Code A00 has an arrow as 0b01111110, while ROM Code A02 has it as 0b00011010 ... On the other hand, it looks like the HD44780 has some CGRAM with up to eight custom characters. I suppose you could use that for special symbols if you want to get fancy.

**Comment by KevinOConnor** [comment]
On Tue, Feb 20, 2018 at 06:48:48PM +0000, Marcio Teixeira wrote:
> BTW, one other though I had is that the screen with a blank hole where the progress bar used to be looks bad. How about printing just the frame of the progress bar with the words "No SD" or "No card"?

That's easy enough to do.  Or, the printer status (printing, ready,
idle, etc.) could be moved up to the sdcard space and the position
always drawn.

On Tue, Feb 20, 2018 at 11:31:15AM -0800, Marcio Teixeira wrote:
> @KevinOConnor : To nest or not to nest -- I don't have a preference either way. Feel free to un-nest if you prefer. The "\x1A" is supposed to look like an arrow:
> 
> img_3861
> 
> I didn't realize the code was shared between the two displays. I wonder if it would be possible to pick an equivalent looking character and selectively apply it based on the display? Anyhow, the idea is that if the current temperature is not near the target, it shows an arrow indicating that the temperature is changing. It helps to de-clutter the display.

Yeah, it's '\x7e'.  Oddly, the hd44780 apparently has another chip
with a different text rom that does put it at '\x1a'.  Hard to tell if
all the chips are the same.  However, I'm pretty sure this lcd doesn't
have a chip manufactured by hitachi, so they probably all have the
same clone.

It should be pretty simple to choose between the glyphs - something
like:

class HD44780:
    char_right_arrow = '\x7e'
...
class ST7920:
    char_right_arrow = '\x1a'
...
    "%3d%s%3d" % (temperature, self.lcd_chip.char_right_arrow, target)

-Kevin

**Comment by marcio-ao** [comment]
@KevinOConnor : It's actually more complicated than that. It appears as if there are different variants of the Hitachi chip. You appear to have ROM code A00 (Japanse), but if you had a ROM code A02 (European), then the arrow would be at \x1a just like in the ST7920. Maybe there needs to be a config  for the ROM code?

**Comment by KevinOConnor** [comment]
Github emails appear to be slow today - looks like our messages crossed.  I also noticed the two different chips.  According to the wikipedia article, the hd44780 was introduced in 1987.  I'm pretty sure I don't have an actual hitachi chip - it's likely some clone.  There's a good chance that all the clones emulate the same 00 rom.  I'd go with the simple solution first - the HD44780 class can load a custom font and point char_right_arrow to it, if it turns out that is needed.

**Comment by marcio-ao** [comment]
> That's easy enough to do.  Or, the printer status (printing, ready,
> idle, etc.) could be moved up to the sdcard space and the position
> always drawn.

The challenge comes when supporting dual extruders. Here is a comparison of the layouts I am using on our printers:

single_nozzle
dual_nozzle

Even without the progress bar, cramming in the status message becomes difficult on the dual-nozzle rig. BTW, the first figure shows a scrolling status message. This is something I still need to backport to Klipper.

**Comment by marcio-ao** [comment]
This is what the Marlin screen looks like on the hd44780, BTW:

https://user-images.githubusercontent.com/698003/36394228-df948318-1578-11e8-81f2-06d5c406bed1.png

It may make sense to implement that layout, as they seem to be packing quite a bit of info in limited space.

**Comment by marcio-ao** [comment]
@KevinOConnor : I added some code to scroll particularly large status messages into view. However, it would be nice if the scrolling reset each time a new message was displayed. I'm not sure how you want to do this.

**Comment by marcio-ao** [comment]
I still occasionally get garbage in the graphics buffer. What is strange is that it only happens at the end of the lines:

corrupted_lines

Any ideas as to what might be causing this? Could it have anything to do with how you are updating the graphics framebuffer?

**Comment by marcio-ao** [comment]
@KevinOConnor : I've having some difficulties understanding your framebuffer code, but I'm going to take a wild guess as to what the cause is. You appear to be grouping writes into contiguous chunks and then writing an address followed by a sequence of bytes. The problem, however, is that on the ST7920, writing past the end of a row causes the address pointer to reset to the beginning of a row -- it will not continue onto the next row as you might expect. I can't really understand your code well enough to see whether you are taking that into account.

**Comment by marcio-ao** [comment]
@KevinOConnor : I put in some debug statements to convince myself that you were not taking this into account. I see several writes which are splitting over across different row. The following info from the datasheet might help:

> The address counter(AC)of graphic RAM(GRAM) only increment after write for horizontal address. After horizontal address
> =0FH it will automatically back to 00H. However, the vertical address will not increase as the result of the same action.

**Comment by KevinOConnor** [comment]
On Tue, Feb 20, 2018 at 10:05:43PM +0000, Marcio Teixeira wrote:
> I still occasionally get garbage in the graphics buffer. What is strange is that it only happens at the end of the lines:

That is strange.  Does moving the location of the nops help?  (The
eight bit may not have been getting the proper delay.)  I just pushed
that as commit 3d27690f.

-Kevin

**Comment by KevinOConnor** [comment]
On Tue, Feb 20, 2018 at 02:43:45PM -0800, Marcio Teixeira wrote:
> @KevinOConnor : I've having some difficulties understanding your framebuffer code, but I'm going to take a wild guess as to what the cause is. You appear to be grouping writes into contiguous chunks and then writing an address followed by a sequence of bytes. The problem, however, is that on the ST7920, writing past the end of a row causes the address pointer to reset to the beginning of a row -- it will not continue onto the next row as you might expect. I can't really understand your code well enough to see whether you are taking that into account.

The code creates 34 framebuffers for the st7920 which should match the
hardware itself.  There is one text framebuffer, one cgram
framebuffer, and 32 graphics framebuffers (32 bytes each - one for
each row in the hardware - which is two lines on the display).

The flush() call walks through each of the 34 framebuffers, creates a
list of every byte that is different [(pos, 1), ...], then compresses
this into a list of updates [(pos, count)], and then walks through
this list of [(pos, count)] updates.  It then sends the command to set
the given position and then sends count bytes of data to update the
data at that position.

On Tue, Feb 20, 2018 at 11:03:43PM +0000, Marcio Teixeira wrote:
> @KevinOConnor : I put in some debug statements to convince myself that you were not taking this into account. I see several writes which are splitting over across different row. The following info from the datasheet might help:
> 
> > The address counter(AC)of graphic RAM(GRAM) only increment after write for horizontal address. After horizontal address
> > =0FH it will automatically back to 00H. However, the vertical address will not increase as the result of the same action.

Right - 0x0f in the hardware is byte 30 in the given framebuffer.  So,
it should work..

-Kevin

**Comment by KevinOConnor** [comment]
On Tue, Feb 20, 2018 at 08:36:47PM +0000, Marcio Teixeira wrote:
> This is what the Marlin screen looks like on the hd44780, BTW:
> 
> https://user-images.githubusercontent.com/698003/36394228-df948318-1578-11e8-81f2-06d5c406bed1.png
> 
> It may make sense to implement that layout, as they seem to be packing quite a bit of info in limited space.

Thanks.  That is interesting - it has similar information but a
slightly different layout.

I wonder if we should rework the code so that we figure out where
everything should be on the screen at startup, and then just call a
bunch of screen drawing functions with (x, y, width) parameters.
Something like:

def init(self):
    ...
    self.update_functions = [
        # (function, x, y, width, addtional parameters...)
        (self.show_temperature, 0, 0, 10, self.extruder0),
        (self.show_temperature, 1, 0, 10, self.extruder1),
        (self.show_fan, 10, 0, 6),
        ...
    ]
...
def work_event(self, eventtime):
    self.lcd_chip.clear()
    for update in self.update_functions:
        update[0](eventtime, *update[1:])
    self.lcd_chip.flush()
    return eventtime + 0.500
...
def show_fan(self, eventtime, x, y, width):
    self.lcd_chip.write_text(x, y, ...)

That way, we could change the layout for the 20x04 display during the
init, and most of the other code wouldn't care.  Also, the layout when
there are two extruders could be figured out just once in the init.

-Kevin

**Comment by marcio-ao** [comment]
Closing this pull request since all the work has either been incorporated, or moved to new pull requests.

**Comment by marcio-ao** [comment]
> I wonder if we should rework the code so that we figure out where
> everything should be on the screen at startup, and then just call a
> bunch of screen drawing functions with (x, y, width) parameters.

Yes, that would work, except that we would need to weigh the added complexity of this vs. just making ST7920 and HD44780 entirely independent classes with their own independent layout code.

**Comment by lbibass** [comment]
I've been having issues with klipper on my taz 6. Namely, the auto bed leveling doesn't work. the head doesn't go to the right spot, and it tries to send the head of the printer straight through the bed.

**Comment by marcio-ao** [comment]
@lbibass: As far as I recall, auto-leveling wasn't something that was implemented at the time of my original experimentation with klipper. Since we aren't working on klipper anymore, someone else would need to step up and get that working.

**Pull request closed without merging**
