### PR TITLE
Update RPi_microcontroller.md

### PR DESCRIPTION
**Pull request by DavoudTaghawiNejad**
Make flash sometimes fails. As documented here (https://github.com/KevinOConnor/klipper/issues/473), make clean solves this problem. Recommends to run make clean if make flash fails.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line in order for me to commit directly - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by KevinOConnor** [comment]
FYI, with recent build changes, a `make flash` should no longer be needed when changing architectures (commit 85300a4a).

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as running an explicit "make flash" should no longer be needed.

-Kevin

**Comment by bruce356** [comment]
Just received my Fysetc S6 board and am having the same problem. The first firmware make and upload worked as expected. On the second attempt after "make clean"
make: *** No rule to make target 'scripts/buildcommands.py', needed by 'out/compile_time_request.o'.  Stop.
The same error comes up when attempting to "make flash FLASH_DEVICE=/dev/ttyACM0" with a backup copy placed into the "out" folder.
After re-installing Klipper it works for the first firmware upload but not the second attempt.
Thanks regards - Bruce

**Pull request closed without merging**
