### PR TITLE
Fix G4 not working issue

### PR DESCRIPTION
**Pull request by WindoC**
module: Capitalized, fix cmd_G4 var "delay" not defined

Signed-off-by: WindoAC <windo.ac@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I don't see what this fixes (delay is defined) - if you've encountered a problem please attach the klipper log file from the event.

-Kevin

**Comment by WindoC** [comment]
No log can be provided since I have already fixed the problem on my machine.

My device is Due + RAMPS-FD + RepRapDiscount 2004 Smart Controller(the beeper)

I try the setup M300 for a short beep sound but it not work.

Below is the related config.
```
[output_pin BEEPER_pin]
pin: ar37

[gcode_macro M300]
default_parameter_S=1
default_parameter_P=100
#   Allows for a default 10ms duration is P is omitted
gcode:  SET_PIN PIN=BEEPER_pin VALUE={S}
        G4 P{P}
        SET_PIN PIN=BEEPER_pin VALUE=0
```


The existing cmd_G4 seem missing define delay outside the if/else block so the value of delay will become null when calling the function _self.toolhead.dwell(delay)_
```
    def cmd_G4(self, params):
        # Dwell
        if 'S' in params:
            delay = self.get_float('S', params, minval=0.)
        else:
            delay = self.get_float('P', params, 0., minval=0.) / 1000.
        self.toolhead.dwell(delay)
```

**Comment by WindoC** [comment]
No log can be provided since I have already fixed the problem on my machine.

My device is Due + RAMPS-FD + RepRapDiscount 2004 Smart Controller(the beeper)

I try the setup M300 for a short beep sound but it not work.

Below is the related config.
```
[output_pin BEEPER_pin]
pin: ar37

[gcode_macro M300]
default_parameter_S=1
default_parameter_P=100
#   Allows for a default 10ms duration is P is omitted
gcode:  SET_PIN PIN=BEEPER_pin VALUE={S}
        G4 P{P}
        SET_PIN PIN=BEEPER_pin VALUE=0
```


The existing cmd_G4 seem missing define delay outside the if/else block so the value of delay will become null when calling the function _self.toolhead.dwell(delay)_
```
    def cmd_G4(self, params):
        # Dwell
        if 'S' in params:
            delay = self.get_float('S', params, minval=0.)
        else:
            delay = self.get_float('P', params, 0., minval=0.) / 1000.
        self.toolhead.dwell(delay)
```

**Comment by FHeilmann** [comment]
Your macro should always pass a value for P or S so at least one branch of the if clause will always be evaluated. Hence delay will always have a value. If you're running into an issue then your macro definition probably has an issue somewhere.

**Comment by WindoC** [comment]
Ok I am wrong. Seem python not request to define variable outside the if/else block but will work as programmer expected. But that confused me. I will cancel this "pull request"

```
class TheTest:
    def __init__(self):
        self.delay = 0.0;

    def cmd_G4(self, params):
        # Dwell
        if 'S' in params:
            delay = 1.0
        else:
            delay = 0.0
        self.toolhead_dwell(delay)
        
    def toolhead_dwell(self, delay):
        print "Debug - delay = %s" % (delay)

thetest1 = TheTest()
thetest1.cmd_G4(['S'])
thetest1.cmd_G4(['P'])
thetest1.cmd_G4(['T'])
```

```
$ python ./test.py
Debug - delay = 1.0
Debug - delay = 0.0
Debug - delay = 0.0

```

**Pull request closed without merging**
