### PR TITLE
toogle_digital_output support - allow user to add changeable GPIO via g-code

### PR DESCRIPTION
**Pull request by dragonnn**
User can now create a section in config:

`[toogle_digital_output my_toogle_pins]`
`pins: ar63`

This add pin ar63 so it state can be switched with a g-code command:
`SET_DIGITAL TOOGLE=my_toogle_pins PIN=ar63 STATE=1`

### CODE REVIEW

**Comment by lenne0815** [comment]
What is the syntax to set it via gcode console ?

**Comment by dragonnn** [comment]
Hmmm it is this SET_DIGITAL TOOGLE=my_toogle_pins PIN=ar63 STATE=1 
Where my_toogle_pins is the name of config section, ar63 is the name of the PIN, you can define more by separating it whit comma. 1 set the state (1 - on, 0 - off).

**Comment by dragonnn** [comment]
Hmmm strange, I am new to git. I had think when I create a pull requests it add only commits at the time when it was created. Well those can be merged too :D.

**Comment by KevinOConnor** [comment]
Thanks.  It looks like you've found the correct way to implement this feature.

I have some changes planned to how gcode.py handles extended g-code commands, so I'm not looking to add this feature to the main Klipper code right now - I'll look again in a couple of weeks.

**Comment by hg42** [comment]
I think, if the pins are listed in printer.cfg, then they should get a name and the gcode command should use the symbolical name instead.
Also, I would consider future extensions.
Example:

```
[digital_output NAME1]
pin = ar61

[digital_pwm NAME2]
pin = ar62

[digital_input NAME3]
pin = ar63

[analog_input NAME4]
pin = ar64
min=...
max=...
offset=...
```
and
```
GPIO_SET PIN=NAME1 VALUE=1
GPIO_SET PIN=NAME2 VALUE=128
GPIO_GET PIN=NAME3
  -> NAME3=1
GPIO_GET PIN=NAME4
  -> NAME4=25.6
```

For debugging purposes, it would also be nice to use pins directly, but I think then they should be also configurable by the command (pinMode etc.).

Intentions:

If we replace one of the MCUs, the configuration should allow to hide hardware dependencies (e.g. pins that are free, or that can do PWM etc.). The usage from outside should stay the same.

I see the configuration as a kind of hardware abstraction layer. So everything should be abstract when used outside.

**Pull request closed without merging**
