### PR TITLE
accelerometer frequency response graphing

### PR DESCRIPTION
**Pull request by KevinOConnor**
@dmbutyugin - I'm finding it useful to compare the "power spectral density" between multiple raw data captures.  I find it helpful to analyze different test runs.  To help with this, I updated the `./scripts/graph_accelerometer.py` script with your frequency calculation code.

Let me know if you're okay with me committing this to the master branch.

Thanks,
-Kevin

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@dmbutyugin - What is the reasoning for smoothing the data before running the FFT?  I'm guessing it is a high-pass filter to remove uninteresting high-frequencies.  If so, though, wouldn't it be simpler to just not graph those high frequencies?  In my tests the smoothing is noticeably reducing the magnitude of frequencies above ~60hz and I'm not sure if that's intentional.

Also, I noticed the post fft smoothing code is doing `* (1./.3)` (or multiply by 3.33333) - surely that should be `* (1./3.)`?

Using of the maximum found frequency of the whole time-series seems a bit extreme.  (I fear it will exasperate noise.) However, I don't have a good alternative.

Cheers,
-Kevin

**Comment by dmbutyugin** [comment]
@KevinOConnor 
> Let me know if you're okay with me committing this to the master branch.

I do not mind that, but it would be great to not duplicate the code between the script and (which I hope to commit in the future) `shaper_calibrate.py` (especially now when it is still WIP, and there is a chance some of the fixes/improvements get committed only into one part of the code, but no the other one). We can, of course, refactor it later, just wanted to know your opinion about this.



> @dmbutyugin - What is the reasoning for smoothing the data before running the FFT? I'm guessing it is a high-pass filter to remove uninteresting high-frequencies. If so, though, wouldn't it be simpler to just not graph those high frequencies?

It is a bit not that simple - Input Shaper autotuning may pick up high-frequency "resonances", e.g. from the stepper motors, but it is not helpful at all to reduce those. In principle, there is already some limit in place for shaper tuning via
```
        psd = psd[freq_bins <= MAX_FREQ]
        freq_bins = freq_bins[freq_bins <= MAX_FREQ]
```
but I am not sure if there could be some strong vibrations from the stepper motors right below that cutoff frequency (depending on the microstepping, for instance).

> In my tests the smoothing is noticeably reducing the magnitude of frequencies above ~60hz and I'm not sure if that's intentional.

As you can see
```
        # 1.75 constant is just some guess for blackman window smoothing
        smooth_window = int(1.75 * SAMPLING_FREQ / MAX_FREQ)
```
maybe this 1.75 needs to be adjusted (made smaller). You can see if, say, 1.5 or 1. improves the behavior you observe.

Theoretically, FFT is not really sensitive to the noise. But I think it may improve the robustness of the algorithm overall if some smoothing is still there (because the data, unfortunately, is very noisy). But feel free to test the algorithm without the smoothing, or with less aggressive smoothing.


> Also, I noticed the post fft smoothing code is doing `* (1./.3)` (or multiply by 3.33333) - surely that should be `* (1./3.)`?

Yes, oops, that's, of course, a typo. However, this (1./3.) is done just to re-scale back to the original scale - input shaping tuning, for example, does not depend on this.

> Using of the maximum found frequency of the whole time-series seems a bit extreme. (I fear it will exasperate noise.) However, I don't have a good alternative.

Yes, an alternative could be to use an average (`.mean(axis=1)`) or some quantile (e.g. `.quantile(0.95, axis=1)`). TBH, I did not explore it too much, but this was the reason I added an averaging between 3 consecutive windows to smooth out the noise a bit. Though I did not observe significant changes - so FFT seems to be pretty stable over the noisy (but smoothed) data.

**Comment by KevinOConnor** [comment]
> I do not mind that, but it would be great to not duplicate the code between the script and (which I hope to commit in the future) shaper_calibrate.py (especially now when it is still WIP, and there is a chance some of the fixes/improvements get committed only into one part of the code, but no the other one). We can, of course, refactor it later, just wanted to know your opinion about this.

Agreed.  I've been running experiments with trying to tune spreadcycle using the adxl345, and it is useful to be able to graph the raw data though.

FWIW, having klippy directly perform analysis and graphing doesn't fit well in my workflow.  It's easier for me to copy the raw data to my desktop and perform the analysis there.  It's a lot faster and it allows me to use matplotlib's interactive graphs.  It also easier to try different analysis and to compare old runs to new runs.

> Yes, an alternative could be to use an average (.mean(axis=1)) or some quantile (e.g. .quantile(0.95, axis=1)).

FWIW, I was just playing with that.  I'm seeing interesting results by removing all the smoothing and just using averaging at the end.  For example, here's a graph I posted yesterday (using the original smoothing code):
g1
And here it is with just averaging at the end:
g1-avg

I do see that if pre-fft smoothing is removed it can really emphasize higher frequencies (possibly due to noise that the later max() pass is picking up).  But, if pre-fft smoothing is removed and averaging is done at the end, it mostly negates this effect.  The resulting analysis does show slightly more magnitude on higher frequencies, but I think this may be more correct.

Code change:
```diff
--- a/scripts/graph_accelerometer.py
+++ b/scripts/graph_accelerometer.py
@@ -69,27 +69,16 @@ def _most_significant_bit(N):
         res <<= 1
     return res
 
-def _smooth(x, N):
-    s = np.r_[x[N-1:0:-1], x, x[-2:-N-1:-1]]
-    w = np.blackman(N)
-    return np.convolve(w / w.sum(), s, mode='valid')
-
 def calc_freq_response(data, max_freq):
     N = data.shape[0]
     T = data[-1,0] - data[0,0]
     SAMPLING_FREQ = N / T
     # Round up to the nearest power of 2 for faster FFT
     M = _most_significant_bit(2 * int(SAMPLING_FREQ * WINDOW_T_SEC - 1))
-    # 1.75 constant is just some guess for blackman window smoothing
-    smooth_window = int(1.75 * SAMPLING_FREQ / max_freq)
-    if N <= M or N <= smooth_window:
-        return None
 
-    # Interpolate input data to fixed sampling rate and smooth it
-    t = np.linspace(data[0,0], data[-1,0], N)
-    ax = _smooth(np.interp(t, data[:,0], data[:,1]), smooth_window)
-    ay = _smooth(np.interp(t, data[:,0], data[:,2]), smooth_window)
-    az = _smooth(np.interp(t, data[:,0], data[:,3]), smooth_window)
+    ax = data[:,1]
+    ay = data[:,2]
+    az = data[:,3]
 
     mlab = matplotlib.mlab
     # Calculate PSD (power spectral density) of vibrations per window per
@@ -101,15 +90,12 @@ def calc_freq_response(data, max_freq):
     pz, fz, _ = mlab.specgram(az, Fs=SAMPLING_FREQ, NFFT=M, noverlap=M//2,
                               window=np.blackman(M), detrend='mean', mode='psd')
 
-    # Pre-smooth PSD between consecutive windows
-    px_avg = (px[:,:-2] + px[:,1:-1] + px[:,2:]) * (1./.3)
-    py_avg = (py[:,:-2] + py[:,1:-1] + py[:,2:]) * (1./.3)
-    pz_avg = (pz[:,:-2] + pz[:,1:-1] + pz[:,2:]) * (1./.3)
-    psd = (px_avg + py_avg + pz_avg).max(axis=1)
-    px_max = px_avg.max(axis=1)
-    py_max = py_avg.max(axis=1)
-    pz_max = pz_avg.max(axis=1)
-    return CalibrationData(fx, psd, px_max, py_max, pz_max)
+    # Report average of PSD for each FFT
+    psd = np.average(px + py + pz, axis=1)
+    px_avg = np.average(px, axis=1)
+    py_avg = np.average(py, axis=1)
+    pz_avg = np.average(pz, axis=1)
+    return CalibrationData(fx, psd, px_avg, py_avg, pz_avg)
 
 def plot_frequency(data, logname, max_freq):
     calibration_data = calc_freq_response(np.array(data), max_freq)
```

-Kevin

**Comment by dmbutyugin** [comment]
FWIW, I think averaging does not do a really good job, I would suggest to use `np.quantile(px, 0.99, axis=1)` and so forth. The point is, depending on `hz_per_sec` value, the averaging results may differ, and similarly if `min_freq` / `max_freq` is adjusted, while `max` or `quantile` should produce more comparable results if that happens.

Then, since the timings are not precisely stable (I believe?), at least this part is better to keep:
```
    t = np.linspace(data[0,0], data[-1,0], N)
    ax = np.interp(t, data[:,0], data[:,1])
    ........
```

**Comment by dmbutyugin** [comment]
> I do see that if pre-fft smoothing is removed it can really emphasize higher frequencies (possibly due to noise that the later max() pass is picking up). But, if pre-fft smoothing is removed and averaging is done at the end, it mostly negates this effect.

Well, I still do see some elevated level of vibrations at the end vs the original code, and I am not 100% sure if that's real, or it is just some vibrations from the steppers being picked up (though they, in general, tend to have higher frequency vibrations than 200 Hz).

BTW, I committed a change to reduce the averaging window coefficient form 1.75 to 1.25 for now, and I also fixed that 1/3 coefficient.

**Comment by KevinOConnor** [comment]
> FWIW, I think averaging does not do a really good job, I would suggest to use np.quantile(px, 0.99, axis=1) and so forth. The point is, depending on hz_per_sec value, the averaging results may differ, and similarly if min_freq / max_freq is adjusted, while max or quantile should produce more comparable results if that happens.

FWIW, if I graph the raw data for every FFT of a single axis for a single capture, I do see a lot of interesting data.  There's a lot of overlap at the "trouble frequencies".  A max() or quantile() will discard a lot of this info, and that seems unfortunate.

I didn't immediately see a problem when running the analysis on some of my older captures with different hz_per_sec and different min/max_freq, but my sample size is pretty small.  It does seem to modify the magnitude a bit, but I haven't seen a case where it changed the frequency peaks.

> Then, since the timings are not precisely stable (I believe?), at least this part is better to keep:
    ax = np.interp(t, data[:,0], data[:,1])

Unless I'm missed something, that shouldn't make a difference with the adxl345 capture code.  The capture code itself produces the timestamps by dividing the total elapsed time by the total number of samples.

Interpolating would be useful in the rare case that there was a communication drop between mcu and host (ie, `drops=xxx`), but in that case the linear interpolation isn't really what we'd want.  (We'd really want to interpolate just the gaps and not reinterpolate the whole data range.)

Cheers,
-Kevin

**Comment by dmbutyugin** [comment]
> FWIW, if I graph the raw data for every FFT of a single axis for a single capture, I do see a lot of interesting data. There's a lot of overlap at the "trouble frequencies". A max() or quantile() will discard a lot of this info, and that seems unfortunate.

BTW, you can get a pretty interesting view of the data if you put the following snippet into calc_freq_response code:
```
        matplotlib.pyplot.specgram(
                ax, Fs=SAMPLING_FREQ, NFFT=M, noverlap=M//2,
                window=np.blackman(M), detrend='mean', mode='psd')
        matplotlib.pyplot.show()
```
(or choose which axis you want to see by replacing `ax`). Note the `10 * log10` scale of the chart (you can also see the 'linear' scale by adding `scale='linear'` argument). The Y axis is frequency, X axis is FFT window (so essentially, time), and the color is magnitude of the response. I do not think it is worth plotting it for, sort of, everyday use, but it is generally interesting to see those harmonics.

> I didn't immediately see a problem when running the analysis on some of my older captures with different hz_per_sec and different min/max_freq, but my sample size is pretty small. It does seem to modify the magnitude a bit, but I haven't seen a case where it changed the frequency peaks.

I suppose it depends on what kind of meaning we want to put (if at all) into the values of the chart. I guess the rescaling of the chart as a whole doesn't make much of a difference for practical purposes, but rescaling different bins on the chart may have some impact on the shaper calibration. Generally, `max` or `quantile(0.99)` answers the question: how bad this particular frequency can be? while `mean` tells how bad _on average_ a respective frequency can be. And another question is: what does power spectral density for a given _window_ in the output of `specgram` mean? When the current vibration frequency matches the resonance frequency - then it's the response to that resonance, but otherwise? From that 'specgram' it would appear that this can be a second-, third-, etc. order harmonic, but how should we account for it, if at all?

> > Then, since the timings are not precisely stable (I believe?), at least this part is better to keep:
> > ax = np.interp(t, data[:,0], data[:,1])
> 
> Unless I'm missed something, that shouldn't make a difference with the adxl345 capture code. The capture code itself produces the timestamps by dividing the total elapsed time by the total number of samples.

Right, it was actually me who apparently lost track of how the timestamps are generated (I was under the wrong impression that we used the timestamps of when we read the data from FIFO as a reference (and we still do, but only for beginning and the end of the sequence)). So indeed, that shouldn't be needed.

**Comment by KevinOConnor** [comment]
> BTW, you can get a pretty interesting view of the data if you put the following snippet into calc_freq_response code:

Thanks!  That is useful.  Right away I can see some interesting quirks comparing stealthchop to spreadcycle with that view.  I'll add that graph as an option to graph_accelerometer.py.

> I suppose it depends on what kind of meaning we want to put (if at all) into the values of the chart.

Very true.  FWIW, my recent focus has been on looking to see if one could tune the stepper settings using the adxl345.  So, it's a bit of a different use case than input shaper.  In particular, I was looking more at the higher frequencies.

> I guess the rescaling of the chart as a whole doesn't make much of a difference for practical purposes, but rescaling different bins on the chart may have some impact on the shaper calibration. Generally, max or quantile(0.99) answers the question: how bad this particular frequency can be? while mean tells how bad on average a respective frequency can be.

That makes sense.  However, to look at it from a different perspective, if we request the toolhead to move back and forth 50 times a second, do we really care if there is a 50hz signal?  In contrast, if we request motion at 30 times a second and observe a 50hz response, request motion at 40hz and see a 50hz response, and request motion at 60hz and see a 50hz response - then that is an interesting result.  It indicates 50hz is a "trouble frequency".

I guess that's why I thought average might be more useful.  It will highlight those frequencies that continue to occur over a wide variety of motion requests.

> When the current vibration frequency matches the resonance frequency - then it's the response to that resonance, but otherwise?

I guess it would say that the axis has a tendency to resonate at a particular frequency regardless of the requested motion.

> From that 'specgram' it would appear that this can be a second-, third-, etc. order harmonic, but how should we account for it, if at all?

Agreed, but hopefully those harmonics fall out in the average..

As a random idea, perhaps we could do something like: drop the top 1/3rd, drop the bottom 1/3rd, and average the remaining 1/3rd..

> we used the timestamps of when we read the data from FIFO as a reference (and we still do, but only for beginning and the end of the sequence)

FYI, the final code actually uses the timestamp of the start measurement request (POWER_CTL=0x8) and the timestamp of the end measurements request (POWER_CTL=0) to improve the time accuracy.  Not related to this discussion, but I'm hoping to see if I can use this timing precision during analysis.  If I get a chance, I'd like to try and line up the time of each step pulse with the accelerometer data.  The high level idea is to move the stepper at constant velocity, and then graph the acceleration during each stepper phase - to check for cases where the stepper phases aren't smooth..

-Kevin

**Comment by dmbutyugin** [comment]
> Very true. FWIW, my recent focus has been on looking to see if one could tune the stepper settings using the adxl345. So, it's a bit of a different use case than input shaper. In particular, I was looking more at the higher frequencies.

Fair enough. Then my thoughts are that the script and the shaper calibration code could, in general, be somewhat different. So, let's commit the script and see what makes more sense for input shaper calibration (and have potentially different code there).

>  However, to look at it from a different perspective, if we request the toolhead to move back and forth 50 times a second, do we really care if there is a 50hz signal? In contrast, if we request motion at 30 times a second and observe a 50hz response ...

The way it usually goes then is, we request the toolhead to move 50 times a second with a certain amplitude, and it moves but with the amplitude, say, 10x. That is also very troublesome. Of course, in practice it is rarely the case like that, but more like - it is easier to detect the resonances when we look at the frequency response near the resonance frequency (that's why we try all in a certain range). Also, it seems that the frequency of 40 Hz does not really excite 50 Hz resonances that much, but 80 Hz, 120 Hz and so forth.

> I guess it would say that the axis has a tendency to resonate at a particular frequency regardless of the requested motion.

It depends. If this a step function or something like it - then most likely yes. If the exciting signal is periodic (sinusoidal, oscillating step function, etc.) - then it will actually oscillate at the requested frequency (+ some harmonics), because the transient solution with the own resonance frequency exponentially [decays](https://en.wikipedia.org/wiki/Harmonic_oscillator#Transient_solution).

> Agreed, but hopefully those harmonics fall out in the average..

Well, if we start with low frequency (and we should) then no, the higher harmonics can also be quite noticeable:
specgram
Here the 3rd harmonic of the ~18 Hz main signal is actually stronger than the 18 Hz signal itself.

TBH, the current input shaper tuning does not necessarily minimize some physically sound function, so overall I am open to other ideas. However, it would seem that max or 99-th percentile is not very prone to noise (together with FFT): they give fairly repeatable results; also they probably give more meaningful values for shaper tuning, so I am more inclined to use them for now.

But I also want to try another idea: try to just generate the 'perfect' readings how they would look like if the toolhead followed the commands from the test exactly, run those readings through the specgram and see how the frequency response looks like. Perhaps this could give some more ideas (and also provide some baseline for comparison).

**Comment by dmbutyugin** [comment]
@KevinOConnor  BTW, the averaging between windows is actually a [Welch's algorithm](https://en.wikipedia.org/wiki/Welch%27s_method).

**Comment by KevinOConnor** [comment]
> BTW, the averaging between windows is actually a Welch's algorithm.

Thanks!  That is helpful.  Looking a little closer now, I suspect matplotlib.pyplot.psd() would directly generate these graphs (though it seems to plot in logarithm scale).

> So, let's commit the script and see what makes more sense for input shaper calibration (and have potentially different code there).

I agree it's fine to have different code for input_shaping vs general analysis.  That said, I wouldn't want to introduce confusion with a new chart that is "very similar but slightly different" than the main charts currently in use.  I'll leave the code on this branch for now.  No rush to merge.

> Well, if we start with low frequency (and we should) then no, the higher harmonics can also be quite noticeable:

Yes - I get similar results on my spectograms.  I'd be curious how much the two "psd" charts differ for that data though.  I updated the code on this branch - you can create a psd chart with `~/klippy-env/bin/python ./scripts/graph_accelerometer.py mydata.csv`.

In particular, your spectogram shows an interesting signal at 80hz and I wonder how the two methods will handle that (my steppers don't show purely horizontal lines like that).

Separately, the graph_accelerometer.py code can now also chart a spectogram - for example: `~/klippy-env/bin/python ./scripts/graph_accelerometer.py mydata.csv -s -a x`

Cheers,
-Kevin

**Comment by dmbutyugin** [comment]
> In particular, your spectogram shows an interesting signal at 80hz and I wonder how the two methods will handle that (my steppers don't show purely horizontal lines like that).

That's an interesting case, but I do not think these are steppers (that wouldn't make sense, especially on a delta printer). Also this signal is _very_ weak, and is only visible because the color chart is in a log scale. Perhaps, an accelerometer picks up some faint vibrations from another source - e.g. PSU or the motherboard fan (one of them is noticeably loud). Out of curiosity, I measured the ambient noise when the printer is powered on (but is not moving, and steppers are disabled) using my phone (Spectroid app) - I just put it on the bed:
Screenshot_20200918-003656

And here is the specgram from another test:
specgram
Here you can (barely) see two lines: one at 80 Hz, and one at ~70 Hz (repeating, or resembling, the results from the phone). And you can probably also notice the ~70 Hz line in the specgram I posted earlier.

BTW, the spectrogram plotting needs to be slightly fixed to show the correct frequencies:
```diff
--- a/scripts/graph_accelerometer.py
+++ b/scripts/graph_accelerometer.py
@@ -55,8 +55,9 @@ def plot_accel(data, logname):
 WINDOW_T_SEC = 0.5
 
 class CalibrationData:
-    def __init__(self, freq_bins, px, py, pz):
+    def __init__(self, freq_bins, times, px, py, pz):
         self.freq_bins = freq_bins
+        self.times = times
         self.px, self.py, self.pz = px, py, pz
         self.pall = px + py + pz
         avgs = [np.average(d, axis=1) for d in [self.pall, px, py, pz]]
@@ -77,13 +78,13 @@ def calc_freq_response(data, max_freq):
     # Calculate PSD (power spectral density) of vibrations per window per
     # frequency bins (the same bins for X, Y, and Z)
     specgram = matplotlib.mlab.specgram
-    px, fx, _ = specgram(data[:,1], Fs=SAMPLING_FREQ, NFFT=M, noverlap=M//2,
-                         window=np.blackman(M), detrend='mean', mode='psd')
+    px, fx, times = specgram(data[:,1], Fs=SAMPLING_FREQ, NFFT=M, noverlap=M//2,
+                             window=np.blackman(M), detrend='mean', mode='psd')
     py, fy, _ = specgram(data[:,2], Fs=SAMPLING_FREQ, NFFT=M, noverlap=M//2,
                          window=np.blackman(M), detrend='mean', mode='psd')
     pz, fz, _ = specgram(data[:,3], Fs=SAMPLING_FREQ, NFFT=M, noverlap=M//2,
                          window=np.blackman(M), detrend='mean', mode='psd')
-    return CalibrationData(fx, px, py, pz)
+    return CalibrationData(fx, times, px, py, pz)
 
 def plot_frequency(data, logname, max_freq):
     calibration_data = calc_freq_response(data, max_freq)
@@ -138,10 +139,12 @@ def plot_compare_frequency(datas, lognames, max_freq):
 def plot_specgram(data, logname, max_freq, axis):
     calibration_data = calc_freq_response(data, max_freq)
     pdata = calibration_data.get_psd_axis(axis)
+    t = calibration_data.times
+    bins = calibration_data.freq_bins
 
     fig, ax = matplotlib.pyplot.subplots()
     ax.set_title("Spectogram %s (%s)" % (axis, logname))
-    ax.pcolormesh(pdata, norm=matplotlib.colors.LogNorm())
+    ax.pcolormesh(t, bins, pdata, norm=matplotlib.colors.LogNorm())
     ax.set_ylim([0., max_freq])
     ax.set_ylabel('frequency (hz)')
     ax.set_xlabel('Time')
```

**Comment by KevinOConnor** [comment]
> That's an interesting case, but I do not think these are steppers 

Okay.

> BTW, the spectrogram plotting needs to be slightly fixed to show the correct frequencies:

Thanks!

-Kevin

**Comment by dmbutyugin** [comment]
Well, I found it really interesting - that the accelerometer can, apparently, find traces of such a small vibrations - from a 3d printer fan. Of course, in the real input_shaper calibration these will be lost, as they will be 'overriden' by a more powerful toolhead vibrations, but this noise can still be found on the specgram.

BTW, as I mentioned in another FR #3027, I have made a change to the input_shaper calibration code to divide the calcuated PSD by the frequency of a specific bin. Later I plan to experiment further if it makes sense to completely remove smoothing and/or switch to Welch's method to calculate the frequency response.

**Comment by KevinOConnor** [comment]
I'm closing this PR becaues it was superseded by #3381 .

-Kevin

**Pull request closed without merging**
