### PR TITLE
menu conversion to jinja template (wip)

### PR DESCRIPTION
**Pull request by mcmatrix**
Signed-off-by: Janar Sööt <janar.soot@gmail.com>

### CODE REVIEW

**Comment by mcmatrix** [comment]
@KevinOConnor I started menu conversion to jinja2.
It's still very raw and wip.

What you think about my changes in `gcode_macro`?
I created additional filters and interpolate (fit) function.
Also changed the way how additional context is handled in render.
This way additional filters and func are available for all.
Is it okay for you? If you want something changed or different way 
then let me know.

Should I keep menu compatiblity with older way?
I really dont want to, managing future changes this way will be quite painful.
My idea is only support new jinja2 way, 
Probably some additional document is needed, for example how to migrate
from old to new.

**Comment by KevinOConnor** [comment]
Hi.

> What do you think about my changes in gcode_macro?
I created additional filters and interpolate (fit) function.

I'm not sure I understand the changes.

FWIW, I think the jinja2 syntax is a bit goofy.  I'd start with just exporting some regular functions (instead of filters) via the render() context parameter.

> Should I keep menu compatibility with older way?

I don't think that is necessary.  I'd update the default menu, and we can then warn users that local menu modifications aren't currently stable and any customizations will need to be updated on each upgrade.

-Kevin

**Comment by mcmatrix** [comment]
Made huge progress supporting jinja2 in menu system.
At the same time, I made some other improvements.
Updated latest work here.
The menu configuration is not compatible with the previous configuration.
It's not yet ready for merge.
I'll continue posting for further tests and changes

**Comment by mcmatrix** [comment]
Added a few improvements.
Still WIP

**Comment by KevinOConnor** [comment]
Thanks!  In general I think this is a great improvement.  Some high-level comments:

* I'd like to better understand the changes to gcode_macro.py.  In general, I'd prefer not to customize the jinja2 language.  Some observations:
  * The "___" shouldn't be needed as callers can do something like `status["output_pin caselight"].value` to get the same effect.
  * Do we need specific expression handling?  To test a boolean, could we just do something like `xyz.render() not in ("0", "0.0", "False", "None", '""')`.
  * Instead of introducing '%% xyz()' syntax, can we just have the templates do `{% xyz() %}`?
  * The only users of the bool() method could be replaced with something like: `{ "ON" if my_test else "OFF"}`
* I have a rough plan to replace "status" with "printer" in gcode_macro.  I'd then like to add methods to the get_status() result dictionaries.  A prime candidate for a method would be `printer.gcode.action_respond_info("abc")`.  This mechanism will hopefully allow each printer object to define their own actions that macros can directly invoke.  I think a number of the menu specific commands could then be moved into `printer.menu.action_xyz()` methods.
* I'm confused on what `items` is used for on cards.  Couldn't the code just directly render a series of templates at various x,y screen locations?

-Kevin

**Comment by mcmatrix** [comment]
Thank you for feedback.

> I have a rough plan to replace "status" with "printer" in gcode_macro. I'd then like to add methods to the get_status() result dictionaries.

I think it would be a good idea.

I have removed "___", `bool`, '%% xyz()' syntax and also an expression handling from the `gcode_macro.py`.
Now all attributes in the menu are using templates. I'll try to keep a consistent line.
I'll review the code and try to refactor the menu card conversion.

**Comment by mcmatrix** [comment]
Hopefully, during next week I'm able to update this PR.

**Comment by mcmatrix** [comment]
Update to the latest dev version.
I'll wait till #1689 is merged. 
Then I'll update this according to the latest changes,

**Comment by KevinOConnor** [comment]
Thanks.  I extracted out the get_status() commits and went ahead and committed them.

Some comments:
* It's best if each individual commit is self sufficient.  (For example, changing the callers of MenuManager in one commit and then making the corresponding changes to MenuManager in a different commit doesn't work well.)  Otherwise, it breaks "git bisect" which is a very useful tool for finding regressions.
* I went ahead and added the `__contains__` call to the gcode_macro.py code.  I don't understand the other changes to gcode_macro - can you elaborate on what they're needed for?  In general, I'd prefer to avoid any elaborate use of Jinja2 syntax as I think its syntax is already too goofy.
* I'm not sure I understand the changes to display.py:draw_text() - can you elaborate on that?
* We can make the changes to toolhead.get_status() if that helps merging, but it would need to be short term - the values used in toolhead.get_status() should be replaced with other information.  The printing state should come from `printer.idle_timeout.state` (the toolhead doesn't track an accurate state). The 'is_printing' boolean can be replaced with `printer.idle_timeout.state == "Printing"`.  The 'xpos' can be replaced with `printer.toolhead.position.x` (and the same should be done for `printer.gcode.gcode_position`).
* FWIW, lerp() can be replaced with a multiply in all users of lerp().

-Kevin

**Comment by mcmatrix** [comment]
Thank you.

> We can make the changes to toolhead.get_status() if that helps merging, but it would need to be short term - the values used in toolhead.get_status() should be replaced with other information. The printing state should come from printer.idle_timeout.state (the toolhead doesn't track an accurate state). The 'is_printing' boolean can be replaced with printer.idle_timeout.state == "Printing". The 'xpos' can be replaced with printer.toolhead.position.x (and the same should be done for printer.gcode.gcode_position).

I'll update my code according to the new changes. No problem with that.

> FWIW, lerp() can be replaced with a multiply in all users of lerp().

I already noticed that :) Will do needed changes in the config and drop unnecessary things from code.

> I'm not sure I understand the changes to display.py:draw_text() - can you elaborate on that?

The old splitter had a problem with a single ~ character. 
By chance ~ (0x7e) is "right arrow" mark in hd44780
The new regex based splitter handles it better.

**Comment by mcmatrix** [comment]
> It's best if each individual commit is self sufficient. (For example, changing the callers of MenuManager in one commit and then making the corresponding changes to MenuManager in a different commit doesn't work well.) Otherwise, it breaks "git bisect" which is a very useful tool for finding regressions.

Sorry, I'm not familiar with that `git bisect` tool. 
Did I understand it correctly by "self sufficient" you mean that interdependent changes must be in the same commit.

I'll review my code and try to group my changes in the correct way.

**Comment by KevinOConnor** [comment]
> Did I understand it correctly by "self sufficient" you mean that interdependent changes must be in the same commit.

Yes, doing that helps a lot with `git bisect`.

Thanks,
-Kevin

**Comment by KevinOConnor** [comment]
Hi.  What's the status of the Jinja2 menu support?

FWIW, I have some high-level goals that I think would be great to see added to Klipper menus:
* Converting the menu to use Jinja2 templates.
* Converting the display code to use Jinja2 templates.  Either by removing the current display.py code and using menu "cards", or by removing the generic menu card support and enhancing the display.py code to specify the content via templates.
* Support for adding new menus in "extras" modules without modification to the main menu code/config.  Ideally PRs #1392, #1517, and #741 could then be merged without menu code changes.

I'm willing to help with the above, but I don't want to conflict with code you are working on.

Cheers,
-Kevin

**Comment by mcmatrix** [comment]
During this week I hope to update this PR according to the latest master branch changes.
It's a good idea to unify the display & menu. 
Hopefully, the menu & card/deck will fit for you.
Let's agree that I'll finish this PR and then we'll see what else is needed to achieve goals.
Thank you for your patience.

**Comment by mcmatrix** [comment]
Back from vacation. Trying to update it tomorrow.

**Comment by mcmatrix** [comment]
I updated the code according to the latest master branch.
Most of the changes have been made in `menu.py`.
This includes all that is needed for jinja2 and also a lot of other improvements.
I added changes that allow injecting menu items from other modules.
This makes possible for  #1392, #1517, to keep menu code in their modules.
Functionality to support #741 is also included in the menu system.
I know that it's not good practice to have a lot of different changes in one commit.
But in this stage, it's very hard (practically impossible) for me to separate these changes in menu.py.

I haven't had time to fully test the menu code from every angle. I did a quick usage test and it didn't crash.
I'll plan to test it next week.

> Converting the menu to use Jinja2 templates.

This is done.

> Converting the display code to use Jinja2 templates. Either by removing the current display.py code and using menu "cards", or by removing the generic menu card support and enhancing the display.py code to specify the content via templates.

More or less it can be used already now.
Just use 
`menu_root: __screen1604_static`
or 
`menu_root: __screen2004_static`


> Support for adding new menus in "extras" modules without modification to the main menu code/config. Ideally, PRs #1392, #1517, and #741 could then be merged without menu code changes.

Theoretically, the menu code is supporting it. But I need to build a test case.
I'll remove `'vsdcard': MenuVSDCard,` from the menu system and try to 
add menu injection part into the vsdcard module.

I'm glad to answer questions about the changes I have made.
Looking forward to your feedback.

-Janar

**Comment by mcmatrix** [comment]
I was able to remove `vsdcard` from the default menu and then inject sdcard menu items from 
`virtual_sdcard` module to the main menu.
I had to change menu functionality a bit, my original idea was not good.
Will do a few more tests and try to find the best functionality 
to support this kind of menu injection.

**Comment by mcmatrix** [comment]
Short update.
I found a nice way for the menu injection by utilizing the event system.
I'll update soon.

**Comment by mcmatrix** [comment]
Updated latest work code to pr.
Still needs a few test rounds.

Btw using this menu code it very easy for other modules to extend existing default menu
and inject their own menu items.
Short example.
`klipper/klippy/extras/virtual_sdcard.cfg`
```ini
### menu virtual sdcard ###
[menu __sdcard]
type: list
name: SD Card
items:
    .__start
    .__resume
    .__pause

[menu __sdcard __start]
type: command
enable: {not printer.idle_timeout.state == "Printing"}
name: Start printing
gcode: M24

[menu __sdcard __resume]
type: command
enable: {printer.idle_timeout.state == "Printing"}
name: Resume printing
gcode: M24

[menu __sdcard __pause]
type: command
enable: {printer.idle_timeout.state == "Printing"}
name: Pause printing
gcode: M25
```

In VirtualSD `__init__`
```py
...
# menu
printer.register_event_handler("menu:init", self.handle_menu_init)
printer.register_event_handler("menu:item:__main:populate", self.handle_main_populate)
...
```
```py
def handle_menu_init(self, manager):
    manager.load_config(os.path.dirname(__file__), 'virtual_sdcard.cfg')
```
```py
  def handle_main_populate(self, item):
        sdmenu = item.manager.lookup_menuitem('__sdcard', None)
        if sdmenu is not None:
            item.insert_item(sdmenu, 2)
            files = self.get_file_list()
            for fname, fsize in files:
                gcode = [
                    'M23 /%s' % str(fname)
                ]
                sdfile = item.manager.menuitem_from_config({
                    'type': 'command',
                    'name': repr('%s' % str(fname)),
                    'cursor': '+',
                    'gcode': "\n".join(gcode),
                    'scroll': True
                })
                sdmenu.insert_item(sdfile)
```

And that's it. Loose reference via events.

**Comment by KevinOConnor** [comment]
Thanks.  This change is a bit too large for me to review.  I guess that's fine for the menu code.  I'd like to better understand the changes to gcode_macro.py though.  I don't think there should be a setitem call (it's would not be valid to add items to the "printer" wrapper), and I don't understand what the find_variables call is used for.  Can you elaborate on what these changes do?  FWIW, I find the Jinja2 syntax to be rather "funky", and I don't think it is a good idea to implement syntax tricks with it.

-Kevin

**Comment by mcmatrix** [comment]
Thank you for feedback.

>  I'd like to better understand the changes to gcode_macro.py though. I don't think there should be a setitem call (it's would not be valid to add items to the "printer" wrapper), and I don't understand what the find_variables call is used for. Can you elaborate on what these changes do?

The wrapper `__setitem__` is used in menu `update_parameters` code.
The menu system allows registering (register_object, unregister_object) a module that
is not in printer global objects lists.
During each update, the menu is calling `get_status` from these objects and setting result dict to the current wrapper instance.
It can be some menu extension module, that is not registered in the printer objs.

Of course, if all the loaded modules must register in the printer list then this part is not needed.

The `find_variables` is used for menu card named/inline items.
```ini
[menu __testcard_static]
type: card
name: Test Card
content_a: "~extruder~{__card_hotend0_current}~degrees~"
...
content_d: "{items.0}"
items:
    __card_msg
```

The menu card must know the full list of used items when populating items.
In this example, the `{__card_hotend0_current}` menu item is referenced directly by name and inside a template.
The item `__card_msg` is added in config items
and can be referenced in the template via index as `{items.0}`

As I know the only way to achieve it this way in jinja2 is to look thru all variables used in a template
and if the variable name is in global loaded menu items list then later set that variable as menu-item rendered content and in `populate_items` append it to card items.
Internally the final items for this card will be 
```ini
items:
    __card_msg
    __card_hotend0_current
``` 
I also added logging for undefined variables.
In case you make a mistake in the inline menu-item name. The variable name used is not in the global menu-items list and nor it's a context variable then it'll be logged as an undefined variable.

I hope it explained a little these changes in `gcode_macro`

**Comment by KevinOConnor** [comment]
> It can be some menu extension module, that is not registered in the printer objs.

Thanks.  My feedback would be that if a module wishes to be callable from the `printer` interface then it should register with the printer class via `self.printer.add_object(self)`.  Otherwise it is confusing to have two different views of printer objects.

> In this example, the {__card_hotend0_current} menu item is referenced directly by name and inside a template.

Unfortunately, I don't understand how that works.  My feedback would be that the "card system" isn't frequently used.  I wonder if we'd be better off disabling this support, merging in the basic Jinja2 menu support, and then work towards a general replacement for the current display system.

Beyond the difficulty with reviewing the card system, I fear the unusual syntax interaction will be difficult for users as well.

-Kevin

**Comment by mcmatrix** [comment]
> Thanks. My feedback would be that if a module wishes to be callable from the printer interface then it should register with the printer class via self.printer.add_object(self). Otherwise it is confusing to have two different views of printer objects.

This is clear, I'll remove that part from menu code.

> Unfortunately, I don't understand how that works. My feedback would be that the "card system" isn't frequently used. I wonder if we'd be better off disabling this support, merging in the basic Jinja2 menu support, and then work towards a general replacement for the current display system.

The menu card/deck system is very powerful,  I really hope that we'll not drop it and then start again implementing the advanced screen functionality. The display part should be adjusted a little (maybe menu also) to make this as the main screen functionality. This can be done after this pr.
We can decide what will be the default screen for end-user. But the end-user has always an option to implement his own screen, maybe even more than one and switch between these screens.

The deck and card system make possible to implement different functional screens.
It can be read-only or some items can be editable on screen.

It's actually already in Klipper, I'm just converting it to jinja2 templates.
Yes, it's a little bit more complex than building a normal menu but after understanding the basic concept
it shouldn't be impossible. For the majority of users, there'll be a default menu deck with one card defined.

I'll try to explain the deck/card system.
When menu item like the `list` is for the conventional menu.
From top to bottom list type of menu.

Then deck and card are for custom pages or screens.
The main item is a deck. The deck can contain one or more card(s).
A card has all the visual stuff that should be rendered on the LCD. The card can include
text, variables and items. Items on the card can be functional (command, input).
Then you're able to move between items on the screen (selection is shown by blinking).

For example, I'm using this deck as my default screen. My Klippers starts with this screen. 
I hope there are more advanced users who like the flexibility of this deck/card system.

```ini
[menu __screen2004_static]
type: deck
name: Deck (static)
longpress_menu: __main
items: __card2004_static

[menu __card2004_static]
type: card
name: Card 20x04
content_a: "~extruder~{__card_hotend0_current}~degrees~~right_arrow~{__card_hotend0_target}~degrees~   {__card_zpos}"
content_b: "~bed~{__card_hotbed_current}~degrees~~right_arrow~{__card_hotbed_target}~degrees~   \xa5{__card_status}"
content_c: "~fan~{__card_fnspeed}  ~feedrate~{__card_frpeed} {items.0}"
content_d: "{items.1}"
items:
    5,__card_prt_time_hm|__card_prt_time_ms, __card_usb_progress, __card_sdcard_progress
    __card_msg,__card_xpos|__card_ypos|__card_epos
```
This is how it looks like.
screen1

All the cycler and concat functionality used were already in Klipper.
Here some menu item names are directly inserted to the template like 
`__card_hotend0_current`, `__card_hotend0_target`, `__card_hotbed_current` etc
and 2 more complex (with cycler and merge/concat) are added to items and in template used as `items.x`.
This is the way how it can be done in jinja2 template.

I find it very convenient to use items directly in a template via name.
Of course, item name must follow python variable name rules.

It is also already in Klipper, just this is the way how it can be implemented in jinja2.

If you still don't like this approach then I can remove inline/named item support.
So that all menu items used in the card must be in config `items:` attribute and
inside the template, the rendered item content is accessible via `items.xx` variable.

The default menu is accessible from this screen via a long press.
menu1

I have to go for now but we can arrange a skype or some chat
and I can go thru the deck/card capabilities.

-Janar

**Comment by mcmatrix** [comment]
Finishing changes from your last feedback (removing `setitems` related functionality).

Btw when going to the unified screen and menu then the current menu system is
already capable of taking over the hard written display.
In config, there is just a need to add options for the user
```ini
# use for 16x4 display
#menu_root: __screen1604_static
# use for 20x4 display
#menu_root: __screen2004_static 
```
If you decide to follow the menu way then we need to discuss what should be on the screen.
I can explain what it has at the moment (the pr version).

The 16 and 20 cols screens are a little bit different.

Here is 20x4 screen
image
It has one card, icons are not animated.
`Section 1` has extruder0 and hotbed info.
`Section 2` has a fan & feed-rate percentage
`Section 3` has M117 message and X, Y, E coordinates. It's static cycler and message has priority over merged coordinates. When the message is empty then the coordinates are shown.
`Section 4` has Z coordinates and printer state shown.
`Section 5` has print time and print progress info. It's a 5sec cycler. Time is shown in format `00m00s`
when hour part is 0 and when hour part is >0 then in format `00h00m`. During printing, a print progress percentage and time are cycled in 5sec. Depending on where you are printing (from USB or VCD) different icon and variable are shown. If progress is 0 then only time is shown.

The layout is debatable. We can remove progress info from S.5 and add it to the printer state in S.4
So that time is always shown in S.5
On S.4 when not printing `Idle` will be shown and when printing then only progress is shown instead of the printer state.

The current system allows doing all this only by using the config. No programming in the module is needed.

I'll also add 16x4 display explanation.

**Comment by KevinOConnor** [comment]
> The menu card/deck system is very powerful, I really hope that we'll not drop it and then start again develop of the advanced screen functionality.

That wasn't the intent of my suggestion.  My suggestion is to temporarily disable that code so we can merge the menu system updates to Jinja2 templates.  After that is merged I feel it would be much easier to discuss and merge display updates.  To the best of my knowledge, the card/deck system isn't frequently used (and any changes to it would break current users anyway).

> I'll try to explain the deck/card system.

Thanks.  I do understand the end result of the deck/card system.  What I don't understand is the config syntax for declaring cards/decks.  I suspect regular users would also not understand it.

As a high-level comment, for the menu/display I'd prefer simplicity over features.  There's a lot of powerful features in the current code, but I fear most users aren't utilizing it (or even some simple features) due to configuration complexity.

> If you decide to follow the menu way then we need to discuss what should be on the screen.

My primary feedback is that I'm struggling to review the changes as is and I fear adding additional features will make that worse.  If we can break up the changes into smaller units I'm hopeful that will help us get these changes merged.

Thanks.
-Kevin

**Comment by mcmatrix** [comment]
Thank you for feedback.
Okay, let's do it this way. 
I'll start with small steps in menu code.
First I'll only include changes that are needed to convert a current menu to jinja2.
Then later, with different PR-s, I'll add more features.
Hopefully, this will help to make reviewing simpler.

Br,
- Janar

**Comment by mcmatrix** [comment]
This has been outdated.
I'll close this and start from a clean sheet.

**Comment by mcmatrix** [comment]
@KevinOConnor Just wanted to let know that I'm working on
the new version of the jinja2 menu. 
It's in the alpha testing phase. 
I'll post PR when it's ready for the 1st review.

**Pull request closed without merging**
