### PR TITLE
"PROBE_ACCURACY" to measure the maximum, minimum, average, median and standard deviation.

### PR DESCRIPTION
**Pull request by rmcbc**
"PROBE_ACCURACY" to measure the maximum, minimum, average and standard deviation.

Signed-off by: Rui Caridade (rui.mcbc@gmail.com)

### CODE REVIEW

**Comment by rmcbc** [comment]
It works ok with my BL Touch. Should work with any kind of sensor.

**Comment by KevinOConnor** [comment]
Thanks.  At a high level the functionality seems useful.  Some feedback:
- Please don't mix whitespace changes with functional changes (it makes the patches harder to review and causes havoc with merges).
- The code should not call gcode.move_with_transform() and it should not manually invoke the low-level homing code.  Instead, the code should just be able to do `for i in range(count): self.cmd_PROBE({}) ; probes.append(toolhead.get_position()[2])`.

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor 

I need you help to move Z to position 10 before probe (you said not to use "gcode.move_with_transform", so I can I do it?
Need to replace:

        # Move Z to start reading position
        pos[2] = z_start_position
        self.gcode.move_with_transform(pos, self.speed)

For something like (but I don't know how to pass the "Z10" parameter to G1):

           self.cmd_G1({})

The code is currently:

    def cmd_PROBE_ACCURACY(self, params):
        toolhead = self.printer.lookup_object('toolhead')
        homing_state = homing.Homing(self.printer)
        pos = toolhead.get_position()
        endstops = [(self.mcu_probe, "probe")]
        probes = []

        number_of_reads = 10
        z_start_position = 10

        # Move Z to start reading position
        pos[2] = z_start_position
        self.gcode.move_with_transform(pos, self.speed)
        
        self.gcode.respond_info("probe accuracy at %.3f,%.3f" % (pos[0], pos[1]))

        # Probe bed "number_of_reads" times
        sum_reads = 0

        for i in range(number_of_reads):
            
            self.cmd_PROBE({})
            
            # Get Z value, accumulate value to calculate average and save it to calculate standard deviation
            pos_read = toolhead.get_position()
            sum_reads += pos_read[2]
            probes.append(pos_read[2])
            
            # Show current Z read value
            self.gcode.respond_info(" - read nr. %d/%d is z=%.6f" % (
                i+1, number_of_reads, probes[i]))
            
            # Move Z to start reading position
            pos[2] = z_start_position
            self.gcode.move_with_transform(pos, self.speed)

        # Calculate maximum, minimum and average values
        max_value = max(probes)
        min_value = min(probes)
        avg_value = sum(probes) / len(probes)

        # calculate the standard deviation
        deviation_sum = 0
        for i in range(number_of_reads):
            deviation_sum += pow(probes[i] - avg_value, 2)

        sigma = (deviation_sum / number_of_reads)**0.5

        # Show information
        self.gcode.respond_info("probe accuracy results: maximum %.6f, minimum %.6f, average %.6f, standard deviation %.6f" % (
            max_value, min_value, avg_value, sigma))

**Comment by lorf** [comment]
Great! Would be nice to have a parameters to specify the number of probes and Z retract (or Z start position) after each probe IMO.

**Comment by KevinOConnor** [comment]
I'd use the toolhead.move() method to request a move.  Take a look at how ProbePointsHelper._lift_z() implements it.

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor now I follow your tips and add several parameters.

**Comment by rmcbc** [comment]
@KevinOConnor I think now it's complete. Implemented all tips and request that I received.
So it's ready for your review.

**Comment by KevinOConnor** [comment]
Thanks.  The update still has whitespace changes throughout the file.  Also, when modifying an existing file it's necessary to follow the style of that file (specifically, code should be wrapped to 80 columns in probe.py and G-Codes.md).

As some minor comments:
- the error checking in cmd_PROBE_ACCURACY doesn't look correct to me - the self._probe() method doesn't throw an EndstopError.  The self._move_position() code can throw that error - but the error description doesn't match that error case.  I recommend moving the try/except clause into self._move_position() and it should then no longer be necessary to catch errors in cmd_PROBE_ACCURACY().
- I think it would be preferable for the error check parameters of self.gcode.get_int()/get_float() to be explicit (eg, minval=4, maxval=50).

Otherwise, the code looks fine to me.

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor code review sugestions implemented.

**Comment by KevinOConnor** [comment]
Thanks.  I fixed the G-Codes.md indentation, corrected the error handling in _move_position(), and committed this (276d5a14).

-Kevin

**Pull request closed without merging**
