### PR TITLE
correct pins for ender3max display

### PR DESCRIPTION
**Pull request by shawnifoley**
knob/clicker doesnt work with current values. Switching to values from printer-creality-ender3pro-2020.cfg work as expected. 

Signed-off-by: Shawn Foley shawnifoley@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@ChadDevOps - do you have any comments on this change?

-Kevin

**Comment by ChadDevOps** [comment]
@KevinOConnor @shawnifoley I'm no longer running klipper on my Ender 3 Max. I have no objections to the change if it's working on stock with the new values.

**Comment by shawnifoley** [comment]
Ill just keep both values and a person can uncomment out based on there board

**Comment by KevinOConnor** [comment]
Okay, thanks.  However, I don't understand the new comments that were added - the entire config is only valid for a 32bit board.  If the pins were incorrect before, then best to just correct them.

-Kevin

**Comment by shawnifoley** [comment]
Corrected

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
