### PR TITLE
Add Safe Z Homing extra

### PR DESCRIPTION
**Pull request by FHeilmann**
As discussed, here is a simple extra that allows to specify a safe z homing location. This is meant to easily replicate safe z homing features in other firmwares, by allowing the user to specify a coordinate at which the Z homing should be performed, as well a ZHop to lift the Z axis prior to homing.

This is a first draft, comments are welcome. Especially the zhop is something that can warrant discussion. As of now, the zhop is performed regardless of which axis is supposed to be homed. This is useful if you want to avoid dragging your nozzle through the bed whilst homing the X and Y axis, but I could also make this configurable to either zhop everytime, or only if the Z axis is involved in the homing procedure.

Also I'm not sure how this interacts with kinematics such as delta, polar etc. that have special axis setups. Maybe the comments should be extended to reflect that. 

Bests,
Florian

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  As we discussed off-line, I think this approach could be useful.  Some notes:
* We should probably document this in the example-extras.cfg above homing_override so users see this first.  (Under the assumption that most people that currently use homing_override could instead use safe_z_home.)
* The code should probably check that the user hasn't defined both safe_z_home and homing_override.
* The current code would break if the printer was in g-code relative mode when running G28.  The move should probably be done via toolhead.move() so as to avoid any of the many g-code axis transformation from corrupting the move.
* With this code, if the user first requested a `G28 X0`, it would raise the Z axis by z_hop and then consider the Z axis homed.  That's not desirable.  Instead, either an error should be returned or the Z axis should be homed as well.

-Kevin

**Comment by FHeilmann** [comment]
> Thanks. As we discussed off-line, I think this approach could be useful. Some notes:
> 
> * We should probably document this in the example-extras.cfg above homing_override so users see this first.  (Under the assumption that most people that currently use homing_override could instead use safe_z_home.)
done
> * The code should probably check that the user hasn't defined both safe_z_home and homing_override.
done
> * The current code would break if the printer was in g-code relative mode when running G28.  The move should probably be done via toolhead.move() so as to avoid any of the many g-code axis transformation from corrupting the move.
done
> * With this code, if the user first requested a `G28 X0`, it would raise the Z axis by z_hop and then consider the Z axis homed.  That's not desirable.  Instead, either an error should be returned or the Z axis should be homed as well.
I changed the way the extra behaves by adding the z move to the move_queue directly. While this allows the Z axis to move, it does not change the homed state of the Z axis during the ZHop.

**Comment by KevinOConnor** [comment]
It's not valid for an extras module to peak into another module's member variables.  (The code becomes unmaintainable otherwise.)  Also, it would not be valid to bypass the check_move() method of the kinematics - some kinematics (eg, delta) need to validate/modify moves before they are added to the lookahead queue.

Taking a step back - as a high-level comment - I think safe_z_home would only be interesting as a mechanism to make the homing mechanism more robust.  That is, I suspect the majority of homing_override users are only using it to perform a z home at a particular position, and if they could use a less generic homing tool then we could potentially make it easier for the majority of those users to deploy a "best practices" homing procedure.

However, if the goal is to make homing more "convenient", then I don't think it's worth our time.  The "homing" code has many subtle intricacies - the goal is to get bed Z position to within a few microns and to enable important boundary safety checks - and unfortunately seemingly every other printer uses subtly different hardware.  I've personally spent dozens of hours tracking down print problems that were ultimately the result of poor homing (z offset errors).  I fear efforts to be more "convenient" have missed "the big picture" - homing is critical and only high precision is important.

So, that said, if you're trying to code up the possibility to "home without homing", then I don't it's worthwhile.  If the user needs to move Z as part of homing XY then in my opinion it only makes sense to either home Z as part of that process or to verify that Z has already been homed.

Cheers,
-Kevin

**Comment by FHeilmann** [comment]
Thanks for the feedback. Given the restrictions you mentioned, I don't think the desired behavior can be implemented this way. I am therefore closing the PR.

Bests,
Florian

**Pull request closed without merging**
