### PR TITLE
Probe & manual_probe: add ability to save babystepping

### PR DESCRIPTION
**Pull request by shiftingtech**
Created two new extended gcodes: PROBE_UPDATE_OFFSET, and Z_ENDSTOP_UPDATE_POSITION
These use the z gcode offset to revise the probe offset, or z endstop position
allowing users to make a frequently used babystepping value permanent without
manual config editing.

Signed-off-by: Ben Eastep <shifting@shifting.ca>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  At a high-level it looks fine to me.  Some minor notes:
1. The convention in Klipper is for code to not peek at member variables of other classes.  So, the code should call gcode_move.get_status() and not directly access `gcode_move.base_position`.
2. I'm not sure about the new command names.  Although I'm not sure I have any suggestions either.  I'll give it some more thought.

-Kevin

**Comment by shiftingtech** [comment]
APPLY_Z_OFFSET/APPLY_PROBE_OFFSET or COMMIT_Z_OFFSET/COMMIT_PROBE_OFFSET have been suggested as other possible names.

**Comment by shiftingtech** [comment]
I've opted for Meteyou's suggestion of 

z_offset_apply_endstop
z_offset_apply_probe

seems clear, and not overly wordy

**Comment by shiftingtech** [comment]
@KevinOConnor   you do you feel about the names I chose here?  Would you rather go a different direction with it?

**Comment by KevinOConnor** [comment]
Thanks, and sorry for the delay.

-Kevin

**Comment by zellneralex** [comment]
@KevinOConnor Extended GCODE names are wrong G-Codes.md. How we should solve this? 
Do we need a new PR to correct that

**Comment by KevinOConnor** [comment]
Ah - I missed that the documentation had not been updated.  We'll need to fix the documentation.

-Kevin

**Comment by shiftingtech** [comment]
I completely forgot I hadn't done that yet: I'll fix it tonight

**Pull request merged**
