### PR TITLE
Added a lift speed parameter to mesh probing.

### PR DESCRIPTION
**Pull request by JohnEdwa**
Currently Klipper uses the probe speed or mesh movement speed, whichever is slower, to do the mesh/probe z-hop which with a BLtouch, for example, is usually painfully slow.  This would add a new parameter "lift_speed" which is used instead if provided.  
It doesn't have that much of an impact, but for bigger grids, it can shave a minute or two off the probing duration.

This can be treated more of as a feature request than a pull request, as I don't really have a clue as to what I'm doing or if this should be done some other way. It works, though.

Signed-off-by: Jonne Kuusela <johnedwa@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  It looks fine to me.  However, if we add a new config option, it would need to be documented in docs/example-extras.cfg (otherwise, users wont know about it).

-Kevin

**Comment by JohnEdwa** [comment]
Tried my best - for the [Probe] the actual probing `speed` is used when lifting to take another sample, but "...when lifting the probe after finishing probing but not between the samples taken according to the `samples`` parameter below" kinda felt like too much. But maybe it should be added so it's accurate?

And as for the [bed_mesh], the default `lift_speed` uses `speed`, it's the speed of `horizontal_move_z`, and it uses the smaller of the two lift speeds if the probing is "automatic" and not "manual", which is a confusion state to explain.    

In any case, someone who 1) knows the Klipper documentation better and 2) is actually a native English speaker should probably rewrite those, but now they at least exist.

**Comment by KevinOConnor** [comment]
Thanks.  I think that the new lift_speed parameter should only be added to the probe class (not to the ProbePointsHelper class) as I don't think it adds any value to ProbePointsHelper.  Sorry for missing that during the initial review.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  Alas, the latest code doesn't actually change the lift speed - it would need to be used in `run_probe()` in probe.py.

-Kevin

**Comment by JohnEdwa** [comment]
It does for the part I meant it to, which is when performing BED_PROBE_CALIBRATE and lifting Z to the [bed_mesh] `horizontal_move_z` height with a BLtouch, which is why I originally put it to both the probe and the helper.    

Actually, wouldn't it currently do the Z-moves for manual mesh levelling using that [bed_mesh] `speed` parameter? At least my Ender 3 is not capable of moving the Z-axis anywhere near at the same speed as the X an Y and would, therefore, need a `lift_speed` parameter for the [bed_mesh] too.

**Comment by JohnEdwa** [comment]
Okay, so I went through the config examples looking for things that have to do with probing and such.
[safe_z_homing] is the only one to specify a lift speed with `z_hop_speed: 20.0`. All the others ([probe], [bltouch], [bed_mesh], [bed_screws], [screws_tilt_adjust] and [z_tilt]) either specify a *horizontal* speed which defaults to 50mm/s, or a probing speed which is then used in all moves when lifting the probe as well.  

As it is possible to use some of them (bed_mesh) without a probe defined at all, I feel that they should have a `lift_speed` parameter of their own - 50mm/s is slow for horizontal speeds but way too fast for vertical ones.

So I propose the following:

* [probe]/[bltouch]: adding `lift_speed`, a parameter that is used between `samples` probes. Defaults to the probe/bltouch `speed` (which preferably would be renamed `probing_speed`). Not really that important.

* [bed_mesh]: adding `z_hop_speed`, used when lifting to `horizontal_move_z` from one probe location to the other, or when using manual probing.
* [bed_screws], [screws_tilt_adjust], [z_tilt] and others I've missed: also adding `z_hop_speed`, if they can't inherit it from [bed_mesh].


Thoughts?

**Comment by KevinOConnor** [comment]
I'm not sure I understand.  The probe/bltouch sections could use a lift_speed that so that the lift after an automatic probe can go faster than the descent speed.  This could be useful on probes that need a very slow descent speed, but can be raised much faster.  The other sections (bed_mesh, bed_tilt, z_tilt, etc.) can all use the probe's lift_speed when an automatic probe is in use.  For manual probing, I don't see any value in a separate lift speed (what's the value in lifting slower than descending when manual probing?).

-Kevin

**Comment by JohnEdwa** [comment]
>what's the value in lifting slower than descending when manual probing?

Nothing. But as manual probing has no actual "probe" configured, so doesn't the current code use the bed_mesh 'speed' for both horizontal and vertical moves? If I set that to 175mm/s, does Klipper try to lift my z-axis at that speed? (I guess capped by the printer max z speed value).

And when you do have a probe, there are two different lifts, the one that happens between probe samples which should be slow for accuracy, and the one bed_mesh uses for moving to next point, which should be fast. I can't think of a way to set both to different values without having one be a parameter of the probe, and the other be a parameter of bed_mesh.

**Comment by JohnEdwa** [comment]
Well, the build failing doesn't matter as that line was left as an open issue anyway. I think simply removing it is fine?

---

In quick video form, [this is Klipper currently](https://youtu.be/gREPEIwDwd8?t=3), and [this is it with the changes](https://youtu.be/5YLNKNhFtzM?t=4) - it moves up after the probing is done faster. Not a huge difference, but it obviously compounds the more points you have and the bigger the difference between probing and z-hop speed.

I added it to [bed_mesh], [bed_tilt], [bed_screws], [screws_tilt_adjust] and [z_tilt] because if I understood correctly, they all would inherit it from the probe helper anyway. I was able to test them with all except [z_tilt] as it doesn't work with my printer.   
[quad_gantry_level] would maybe also use/inherit it, but I definitely can't test that.

**Comment by KevinOConnor** [comment]
Thanks.  I'm confused by z_hop_speed.  Your videos show a slight time improvement with z_hop_speed - wouldn't increasing the lift speed between probe samples have a dramatic time improvement?

My high-level feedback would be for us to add lift_speed to the probe (which would change the lift speed during multi-sample probes and change the lift speed to ProbePointsHelper).  If an additional z_hop_speed parameter is needed then do I'd recommend a separate PR.

Separately, given the holidays, I'd prefer to treat the repo in a "soft freeze".  So, this is something I'd look to merge in early January.

Thanks again,
-Kevin

**Comment by JohnEdwa** [comment]
This is supposed to be that additional PR.

In the video example, the difference for a single mesh point is moving roughly 8mm (probe retract to 10mm zhop height) with either 5mm/s or 25mm/s, which (ignoring acceleration) takes 1.6 seconds or 0.32 seconds respectively, which while on a 3x3 grid only saves 12 seconds, on a 6x6 grid saves 46 seconds.   
If the values were 2mm/s probing and 50mm/s lifting, then it would be a difference of 4s vs 0.16s per point, and on a 6x6 grid it would save 128 seconds, and so on.

And that probe stuff is going to be much better implemented (eventually) from the BLtouch fast mode changes discussed in #2267. If a prob_lift_speed is going to be added as a parameter, merging it with that one would make more sense IMHO.


>Separately, given the holidays, I'd prefer to treat the repo in a "soft freeze". So, this is something I'd look to merge in early January.

Perfectly understandable, and this PR is not a priority whatsoever in the first place.

**Comment by KevinOConnor** [comment]
FYI, I implemented a LIFT_SPEED parameter to probe and ProbePointsHelper (commit c36fe76d6).

Is there additional features that are needed?

-Kevin

**Comment by KevinOConnor** [comment]
Okay, lets close this as it looks like lift_speed is generally working.

-Kevin

**Pull request closed without merging**
