### PR TITLE
Updated src folder structure to reflect genericness of source files, make samd21 makefiles and kconfig more generic

### PR DESCRIPTION
**Pull request by FHeilmann**
As per the discussion in #1093 here is my suggestion for the src folder restructure. I took the opportunity to make the samd21 kconfigs and makefiles less specific (like you have done for the SAM3/SAM4) so other samd21 derivatives and (in the future) samd51 devices can be added.

### CODE REVIEW

**Comment by FHeilmann** [comment]
I accidentally included the whitespace fixes in the wrong commit, I'll fix it once you agree with the changes. If you'd prefer another organization for the commits or want me to squash some of them let me know.

**Comment by KevinOConnor** [comment]
Thanks.  FYI, if the directory renames are done separately from the Makefile fixes, then it'll break "git bisect" (as git bisect wants to be able to successfully build each commit).  I can squash and merge all of these into one commit though.

If there's no further comment, I'll commit in the next few days.

-Kevin

**Comment by FHeilmann** [comment]
I see, feel free to squash as you see fit!

**Comment by KevinOConnor** [comment]
Thanks.

BTW, are you working on the samd51 chips?  I'm curious what the performance would be, so I placed an ordered for an Adafruit ItsyBitsy M4.  I don't have any timeframe to look at it though.

-Kevin

**Comment by FHeilmann** [comment]
Same here. I have a board on the way based on the samd51. I have not done any work yet though

**Pull request merged**
