### PR TITLE
config: Generic and TMC2208 UART configuration for BIGTREETECH SKR V1.3 board

### PR DESCRIPTION
**Pull request by alekssobolewski**
Signed-off by: Aleksander Sobolewski <aleks.sobolewski@outlook.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Were you able to test this on an SKR v1.3?  (I didn't think they were shipping yet.)

I think there should be just one config file added (generic-bigtreetech-skr-v1.3.cfg).  If there is a desire to document additional capabilities, the comments should describe that and there can be commented out config sections as examples.

-Kevin

**Comment by alekssobolewski** [comment]
Thanks for valuable tip! :smiley:
I deleted the file entirely dedicated to TMC2208 UART config, and merged it into generic one.

Also, as you have thought, I haven't been able to test out this configuration on a real board (more on that in file itself).

_Please forgive me so many commits, I'm still learning Git :relieved:_

**Comment by KevinOConnor** [comment]
Thanks.  Lets leave this open until we can confirm it working on the board.  Hopefully that should be possible in a little over a week.

-Kevin

**Comment by KevinOConnor** [comment]
Now that the board is shipping, has anyone been able to confirm this config?

-Kevin

**Comment by alekssobolewski** [comment]
I'm still waiting.

**Comment by maker3dpl** [comment]
I have actually this board and puttin now klipper, but some problems.. with make

**Comment by bbd10000** [comment]
Hi all. I hope this helps..  I have this board up and running on a Tronxy X5S with five TMC2208's communicating over UART. All five drivers respond to the DUMP_TMC STEPPER request. I've found a few mistakes with the config file. the uart pin for stepper z should be P1.10 also the extruder 'step' and 'dir' pins are also transposed.

I haven't used git other than for downloads but I'll try to put in a change request to add the second extruder driver pins (I'm actually using it for a 2nd z motor) and add the dedicated 'servo' pin for use with a BLTouch.   

PS Thanks to Kevin and all of his helpers for the great work you've done. The documentation and work flow for preparing a new setup are fantastic, much quicker and easier than Marlin 2.0.

**Comment by pulsar256** [comment]
Got my SKR1.3 board as well. Cannot comment on TMC2208 configuration yet but what I have tested are HD44780 and ST7920 displays. 

## HD44780

working fine:

```
[display]
lcd_type: hd44780
rs_pin: P1.19
e_pin: P1.18
d4_pin: P1.20
d5_pin: P1.21
d6_pin: P1.22
d7_pin: P1.23
encoder_pins: ^P3.26, ^P3.25
click_pin: ^!P0.28
```

## ST7920 

Does not work. Tripplechecked the pinout against https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/hardware/SKR-V1.3-PIN.pdf which is syntactically correct:

```
[display]
lcd_type: st7920
cs_pin: P1.19
sclk_pin: P1.20
sid_pin: P0.18
encoder_pins: ^P3.26, ^P3.25
click_pin: ^!P0.28
```

When only looking at the SPI bus to the display (via EXP1), one potential problem might be the Display SPI CLK signal which has been moved from P0.15 (SKR1.1) to P1.20 (SKR1.3). My understanding is that this is not part of any valid µC SPI configuration and needs to be bitbanged. I have verified the display to be working fine with SKR 1.1 and/or generic Ramps boards. 

I guess one could rewire the board to move the SPI CLK signal from EXP2 Pin2 over to EXP1 Pin5. That would either require cutting of the P1.20 -> EXP1 Pin5 trace or (if possible) setting the P1.20 GPIO to HighZ and bodging a bridge between  EXP1 Pin5 <-> EXP2 Pin2

**Comment by jakep82** [comment]
One of the st7920 pins is incorrect.  See the correct sid_pin below.  I've confirmed with the schematic and the pins file from Marlin.

~~~
[display]
lcd_type: st7920
cs_pin: P1.19
sclk_pin: P1.20
sid_pin: P1.18
encoder_pins: ^P3.26, ^P3.25
click_pin: ^!P0.28
~~~

**Comment by pulsar256** [comment]
@jakep82 CS and CLK were indeed swapped. Thanks! I also presumed that the display driver is using SPI - it is not. The source says otherwise, should have check that one first.

**Comment by StealthNinja1O1** [comment]
I can make the firmware, but if I upload it to the sd and boot it, the board does nothing. Anyone else this problem? Or can someone send their settings?

**Comment by alekssobolewski** [comment]
@StealthNinja101 Read the docs 😉 You need to change filename from klipper.bin to firmware.bin

**Comment by StealthNinja1O1** [comment]
I did that, and it won't get detected as a USB device anymore. The screen also doesn't show anything.

**Comment by alekssobolewski** [comment]
@KevinOConnor I think we have a new, working config :smiley: 
@pulsar256 @jakep82 Thanks for correct pinout for display, I have added it as well.

**Comment by KevinOConnor** [comment]
@StealthNinja1O1 - your screenshot of "make menuconfig" shows usb as disabled.  Obviously, that needs to be enabled in order to use USB.

-Kevin

**Comment by KevinOConnor** [comment]
@alekssobolewski - thanks.  Some minor comments:
- The "make flash" command should now work on the lpc176x boards.  Can you retest with "make flash"?
- I think it would be preferable to comment out the [tmc2208] config sections and add a comment describing the steps needed to enable the tmc2208 (uncomment config, appropriate board jumper settings, etc.).
- Similarly, I think it would be preferable if the [display] section was commented out.  (See config/generic-ramps.cfg for an example of this.)
- If the hd44780 config has been verified, it would be good to also add a commented out config section for that.  (See also config/generic-ramps.cfg for an example.)
- this commit is adding a spurious  test/klippy/printers.test.orig file.

-Kevin

**Comment by pulsar256** [comment]
I would also recommend adding a commented out "buzzer silencer configuration" section for RRD GLCD

```
[output_pin BEEPER_pin]
pin: P1.30
```

or at least

```
[static_digital_output silence_beeper]
pins: !P1.30
```

if the buzzer is not configured, it will make a continuous squeaking sound.

**Comment by alekssobolewski** [comment]
@pulsar256 Which display do you use? I have the RepRapDiscount Smart Controller (st7920) connected and working fine, without any problems with the buzzer.
Nevertheless, I have added a section below display configuration to mention that problem together with your solution.

**Comment by pulsar256** [comment]
@alekssobolewski tested with these:

image

Only the rather old (~4y) Big Tree Tech RRD GLCD had issues with the buzzer, the 2004 / hd44780 stays silent.

**Comment by alekssobolewski** [comment]
@KevinOConnor I have tested out "make flash" command, and it works flawlessly! :smiley:
I took your corrections into account (3b1e8810284500b5839d000db27610cea65d22a9), could you please review the code again? Thanks

**Comment by pulsar256** [comment]
@alekssobolewski @KevinOConnor 

make flash does not work for me. Am I missing something? 

```
> make flash FLASH_DEVICE=/dev/ttyACM0                                                                                                                                                                                              
  Flashing out/klipper.bin to /dev/ttyACM0
Entering bootloader on /dev/ttyACM0
Device reconnect on /sys/devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-7/1-7:1.0
sudo dfu-util -p 1-7 -D out/klipper.bin

dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available

Failed to flash to /dev/ttyACM0: Error running dfu-util

If flashing Klipper to a Smoothieboard for the first time it may be
necessary to manually place the board into "bootloader mode" - press
and hold the "Play button" and then press and release the "Reset
button".

When a Smoothieboard is in bootloader mode it can be flashed with the
following command:
  make flash FLASH_DEVICE=1d50:6015

Alternatively, one can flash a Smoothieboard via SD card - copy the
"out/klipper.bin" file to a file named "firmware.bin" on an SD card
and then restart the Smoothieboard with that SD card.

make: *** [src/lpc176x/Makefile:49: flash] Fehler 255
```

```
> lsusb                                                                                                                                                                                                                            
(...)
Bus 001 Device 035: ID 2341:abcd Arduino SA 
(...)
```

```
kernel: usb 1-7: new full-speed USB device number 39 using xhci_hcd
kernel: usb 1-7: New USB device found, idVendor=2341, idProduct=abcd, bcdDevice= 1.00
kernel: usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
kernel: usb 1-7: Product: Klipper firmware
kernel: usb 1-7: Manufacturer: Klipper
kernel: usb 1-7: SerialNumber: 12345
kernel: cdc_acm 1-7:1.0: ttyACM0: USB ACM device
mtp-probe[19568]: checking bus 1, device 39: "/sys/devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-7"
mtp-probe[19568]: bus: 1, device: 39 was not an MTP device
mtp-probe[19583]: checking bus 1, device 39: "/sys/devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-7"
mtp-probe[19583]: bus: 1, device: 39 was not an MTP device
```

**Comment by KevinOConnor** [comment]
@alekssobolewski - okay, I'll take another look.  It doesn't seem like the "make flash" comments have been updated though.
@pulsar256 - the existing Klipper micro-controller code on the board must be relatively recent (mid-January or later).  If it's an older revision, then use one of the manual flash methods to update the micro-controller code.  Future flashes should then work via "make flash".  (Also, for anyone else facing a similar problem, the OctoPi image must be based on v0.15.1 or later - older revisions report "dfu-util 0.8" which will not work correctly.)

**Comment by pulsar256** [comment]
@KevinOConnor the board was already running the most recent version of klipper based on the current master branch (c105adc80bbcdc7daf5c86ec7ec49511a36a3cbd).

**Comment by pulsar256** [comment]
@KevinOConnor I have been following up on the make flash issue and got it working. The USB device needs to be reset before (`USBDEVFS_RESET`) it gets re-recognized by the kernel as 1d50:6015 after putting it into the DFU mode via klipper firmware (pyusb can help here). Currently I am testing on my workstation which might behave differently to the ideal RPI target so more tests are required until a generic solution can be found.

Shall we take this into a separate issue and not pollute this PR any further?

**Comment by KevinOConnor** [comment]
Thanks.  I made some comment updates (make flash should now work, make comments more similar to other config files) and committed this config (commit ccc1107db).

-Kevin

**Comment by banolka** [comment]
Have anyone had luck with attaching Ender 3 lcd to skr 1.3?

**Comment by jwynn6** [comment]
> Have anyone had luck with attaching Ender 3 lcd to skr 1.3?

[display]
lcd_type: st7920
cs_pin: P1.22
sclk_pin: P1.21
sid_pin: P1.23
encoder_pins: ^P1.18, ^P1.20
click_pin: ^!P0.28

[static_digital_output silence_beeper]
pins: !P1:30

**Comment by Arksine** [comment]
For reference I thought it would be a good idea to add my experience with the SKR 1.3.  Around the end of March I order 2 for a Voron 2 build, and I just got around to getting them wired up and installed.  Initial setup went without a hitch, I was able to flash via SD card, get the config setup, and start Klipper.

I then proceeded to test flashing via DFU mode, and this is when things went sideways.  I searched though all of the related issues and information, including #1470.  I tried adding the reset routine found there, increasing the timeout for the related patch, and removing it all together.  Nothing worked, neither of the boards would go into DFU mode.

Finally I decided to try flashing the stock smoothieware bootloader via serial ISP.  That did it, after flashing the bootloader, then flashing Klipper via SD card, I was able to use `make flash` to get the boards into DFU mode and flash Klipper.  This suggests to me that its possible newer boards are shipping with an altered bootloader that breaks DFU.

**Comment by DeviousPenguin** [comment]
@Arksine thanks for sharing your findings, I have been experiencing something similar to you, I ordered 2 x SKR v1.3 boards, and one flashed OK using 'better bootloader', but the other one refuses to boot into DFU mode.

I'll see if I can flash the stock smoothieware bootloader via serial ISP and take it from there.

**Pull request closed without merging**
