### PR TITLE
stm32f4-usb:  Fix for the control transfer data stage

### PR DESCRIPTION
**Pull request by Arksine**
While attempting to get a bootloader working for the STM32F405/STM32F407 I noticed that the MCU was not resetting when flash_usb.py tries to enter the bootloader.  After debugging I determined that the line_coding struct was being filled with nonsense, thus the check against `line_coding.dwDTERate` always returned false in `check_bootloader()`.

It seems that the STM32F40x must NAK all OUT packets received over EP0 until the core signals that the setup stage is done.  The core will always receive and ACK setup packets, even when the EPENA bit is cleared and the NAK bit is set.

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Good catch.  Some high-level comments:

1. Setting SNAK on startup seems fine (`usb_init()`).
2. Waiting to return the setup packet after the "setup complete notifier" seems sane and makes sense.  (Note, that `setup_ret` will always be 8.)
3. I'm not sure about the change to when CNAK is set. My general understanding is that the host could end a USB read transaction at any time and thus the device should accept an OUT packet at any time (even before the first IN packet is received).  Thus I would think that the CNAK should be set as soon as the "setup complete notifier" is received.

I'll try to reproduce the problem on my local stm32f4 board (an stm32f446).

-Kevin

**Comment by Arksine** [comment]
I can remove setup_ret, adding it was more habit than anything.  

As for when to set CNAK, I'll experiment with it some more.  I tried several variations of the CNAK timing, however I might not have tried setting it after the setup stage is complete and popped of the queue.  I'll test it in the morning and see what happens.

I'm interested to see if you can reproduce on the STM32F446.   One would think that it would behave in a similar way to the 405/407.

**Comment by Arksine** [comment]
Hi Kevin,
Good call on enabling EPOUT 0 after the "setup complete" packet is popped, it works.  I went ahead and squashed everything into one commit since the change involved altering both of the previous commits.

I also removed setup_ret and just return the size of the setup buffer (8).

**Comment by KevinOConnor** [comment]
Thanks.  Unfortunately it would not boot on the stm32f446.  I think the f446 needs to have USB_OTG_DOEPINT_STUP cleared in order to get pktsts==4 notifications.  (The usbotg controller seems to be pretty flaky.)  I did break up the commit into two patches tracking this down - it's on the work-stm32f4usb-20200502 branch (commit cd807913 and a3e1a0c3).  Hopefully it also works on stm32f407.  Do they look okay to you?

-Kevin

**Comment by Arksine** [comment]
The otg controller is definitely flaky.  Is it possible that the STM32F446 requires STUPCNT to be reset in the DOEPTSIZ0 register after each SETUP is finished (in rx_enable_endpoint())?  The F407 reference says that you should set it to 3 before a SETUP packet is received, but it is essentially optional because it will keep sending setup packets regardless of what the STUPCNT is.

With regard to those commits, I will test them in a bit.  There are a couple of things that stand out to me:
- In `usb_read_ep0_setup()`:  When pktsts == 4 I suspect that we will need to pop off the "status complete" packet by reading out GRXSTSP.
- In `usb_read_ep0()`:  I'm not sure if we should enable the OUT endpoint after the read.  My understanding is that after the read, the application will send a zero length packet.  Then the Host will respond with a simple ACK and proceed with the next setup stage (if necessary).  It might work like this though.

I'll report back with results after testing your branch.

**Comment by Arksine** [comment]
Your branch works on both the STM32F405 and STM32F407(SKR Pro), so what do I know 😄

**Comment by KevinOConnor** [comment]
> Is it possible that the STM32F446 requires STUPCNT to be reset in the DOEPTSIZ0 register after each SETUP is finished (in rx_enable_endpoint())?

When I last looked at that, it didn't seem necessary.  The `EPOUT(0)->DOEPINT = USB_OTG_DOEPINT_STUP;` was needed though.

> The F407 reference says that you should set it to 3 before a SETUP packet is received, but it is essentially optional because it will keep sending setup packets regardless of what the STUPCNT is.

Right.

> In usb_read_ep0_setup(): When pktsts == 4 I suspect that we will need to pop off the "status complete" packet by reading out GRXSTSP.

For consistency, I thought it would be better to do this via `fifo_read_packet(NULL, 0);`.  That is, any time we pop the packet we should also read the contents, which is what fifo_read_packet() does.  There is no packet contents for pktsts==4, but it doesn't hurt to use fifo_read_packet().

> In usb_read_ep0(): I'm not sure if we should enable the OUT endpoint after the read. My understanding is that after the read, the application will send a zero length packet. Then the Host will respond with a simple ACK and proceed with the next setup stage (if necessary). It might work like this though.

In theory, the host might send multiple packets, which is why I think the code should reenable the endpoint.  In practice, there would probably never be multiple packets.  I don't think there's any harm in supporting multiple read packets though.

That said, I think it would be cleaner if `enable_rx_endpoint(0);` was called at the top of `usb_read_bulk_out()`, `usb_read_ep0()`, and `usb_send_ep0()` instead of at the bottom of `usb_read_bulk_out()`, `usb_read_ep0()`, and `usb_read_ep0_setup()`.  I can give that a try.

> Your branch works on both the STM32F405 and STM32F407(SKR Pro),

Great.

Thanks,
-Kevin

**Comment by KevinOConnor** [comment]
> That said, I think it would be cleaner if enable_rx_endpoint(0); was called at the top of usb_read_bulk_out(), usb_read_ep0(), and usb_send_ep0() instead of at the bottom of usb_read_bulk_out(), usb_read_ep0(), and usb_read_ep0_setup(). 

Turns out that isn't a good plan for bulk transfers - as it delays when the next bulk packet can be read.

However, it seems to work on the stm32f446 if it is done for setup transactions.  I put the test code up on the test branch (commit 0140545d).  Do you have a preference on approach?

-Kevin

**Comment by Arksine** [comment]
>For consistency, I thought it would be better to do this via fifo_read_packet(NULL, 0);. That is, any time we pop the packet we should also read the contents, which is what fifo_read_packet() does. There is no packet contents for pktsts==4, but it doesn't hurt to use fifo_read_packet().

Makes sense, I see what I was missing.  I didn't think it was being called when pktsts==4, but after a closer look I see that it is.

>However, it seems to work on the stm32f446 if it is done for setup transactions. I put the test code up on the test branch (commit 0140545). Do you have a preference on approach?

Nope, no preference here.  If you want I can close this PR and you can create one for your testing branch.  In the meantime I'll test your new patch and see how it behaves on the STM32405/7.

**Comment by KevinOConnor** [comment]
Thanks.  I went ahead and committed this (commit e93c1887 and f8649b4b).  I went with the original method, which basically amounts to "continue to enable reception after fifo_read_packet() except for pktsts=6", as that seems like the smaller change.

-Kevin

**Comment by Arksine** [comment]
Great, thanks!

**Pull request closed without merging**
