### PR TITLE
printrbot play V2 config

### PR DESCRIPTION
**Pull request by drphil3d**

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Also, the config files should end in a ".cfg" suffix.  It would be great if new config files were added to the test/klippy/printers.cfg test file.  What's the difference between this PR and #1274?

-Kevin

**Comment by drphil3d** [comment]
Noted.
 The play v2 and the simple pro have a few differences the y and x axis are different size, the z axis is not as long.

**Comment by KevinOConnor** [comment]
Will you be able to provide a Signed-off-by line to this PR and the other two?

Details are at https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .  It means you are agreeing to https://github.com/KevinOConnor/klipper/blob/master/docs/developer-certificate-of-origin .

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  The signed-off-by line does require your full name.  If there's a concern with the signed-off-by line, then let me know.  For simple config changes and fixes I can commit the work under my signed-off-by line (but I would then not be able to use the github pull request mechanism).

Separately, I have two other questions:
1. Is the printrbot play from 2019?  I thought printrbot closed down in 2018.
2. The simple pro has "einsy rambo" in the name.  Was this a customization of that printer or were there several version of the official printer that used different boards?

-Kevin

**Comment by drphil3d** [comment]
I'm still learning how github and git works my apologies.
The Simple Pro was released in 2016 using the G2 controller. I used the designation 2019 Einsy Rambo to avoid confusion with the two controllers because people including myself are building more of these machines with new controllers.

**Comment by KevinOConnor** [comment]
As a general rule, we only include configuration files for stock (unmodified) printers in the Klipper example config directory.

Is both the config in this PR and the config in PR #1274 both of customized printers?  (I'm not sure what a "G2" is.)

-Kevin

**Comment by KevinOConnor** [comment]
Any further comments on this?

-Kevin

**Comment by drphil3d** [comment]
yes its a customized config file for the simple pro, there are small differences between the play v2 and the simple pro so it can just go in a single file. G2 refers to the SAM3XC board which is known as the PrintrboardG2 it originally came with the Simple pro but people have been replacing the G2 with an Einsy Rambo.

**Comment by KevinOConnor** [comment]
Okay, thanks.  However, it looks like both this and #1247 are for customized printers.  Alas, I think there are too many customized printers for us to add example files in Klipper - my fear is that the example config directory would become too cluttered with all the options.  I think we should primarily focus on stock printer configurations in the Klipper config directory.

-Kevin

**Comment by drphil3d** [comment]
Maybe it would be a good idea to store customized profiles in another area
such as the documentation. It would really help the adaptation of the
firmware if there are customized configs available.
When I setup my printer I did a bunch of digging through old configs and
logs in the issues to see how other people had done things.
My printer worked running marlin so I didn’t have a lot of motivation to
switch, I saw it as having to spend a lot of time learning new firmware.

-- 

Philip Mally
3D Printing & Rapid Prototyping Services
530-205-3210
pmally@gmail.com

**Comment by KevinOConnor** [comment]
Alas, I'm not sure what would be a good location for custom printer locations.  I'm okay with adding the printer config for the G2 (we can add comments indicating it is still a work in progress).  Perhaps with that and with generic-einsy-rambo.cfg users would be able to put together a working config.

-Kevin

**Comment by drphil3d** [comment]
we got the thermistor table issue solved in marlin so it should work for
Klipper as well which was the very last problem I had.
-- 

Philip Mally
3D Printing & Rapid Prototyping Services
530-205-3210
pmally@gmail.com

**Comment by KevinOConnor** [comment]
Lets close this pull request - if you have a sample G2 config (even if it isn't yet complete) then lets add that one.

-Kevin

**Pull request closed without merging**
