### PR TITLE
Move config reference information to new Config_Reference.md document

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is a fairly large change to the Klipper documentation.  It replaces the documentation in config/example-extras.cfg with a new markdown document (docs/Config_Reference.md).

There are a couple of reasons to make this change:
* It makes it easier to obtain and share a URL to specific information on a particular config section.
* It's easier to link to the config reference from the other Klipper documents.  It's also easier to cite other Klipper documents from within the config reference.
* The raw example-extras.cfg file got so large that it became unwieldy to navigate.  Having a table-of-contents to config sections should help.
* It unites the reference information in examples.cfg, example-extras.cfg, example-menu.cfg, and other files into one document.
* I often see complaints that the "klipper documentation is scattered", which I suspect is primarily due to the config reference being in the config/ directory.

On the flip side, the new Config_Reference.md is quite large - it's large to the point that a new user may be overwhelmed finding information on the basic Klipper settings (eg, [printer]).

Comments?
-Kevin

### CODE REVIEW

**Comment by jakep82** [comment]
I like where this is headed, but I feel like a table of contents at the top of the page would be very helpful.  Something with links to the start of broad categories like kinematics, steppers, fans, heaters, displays, bed leveling, etc.  Otherwise you're still scrolling through a ton of stuff, or using Ctrl-F to search within the page which is not ideal.

**Comment by KevinOConnor** [comment]
> I feel like a table of contents at the top of the page would be very helpful.

Thanks for reviewing.  I agree.  At this point, my plan is to rely on www.klipper3d.org rendering to automatically add the table-of-contents.  (For an example of this, see: https://www.klipper3d.org/G-Codes.html vs https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md ).  Unfortunately, this wont provide a table-of-contents for viewers using the github version of the docs, but it is a lot simpler to rely on auto-generation of the table-of-contents then trying to maintain one by hand in the markdown documents.

Cheers,
-Kevin

**Comment by jakep82** [comment]
That makes sense.  Looking forward to being merged.

**Comment by LazaroFilm** [comment]
Suggestion: I spent quite a while looking for that config extra. Should we have a dummy config extra that lets people know it has now moved to the docs section?

**Comment by bung69** [comment]
I also spent ages the other day trying to work out what had happened to example config / config extra etc.

As @LazaroFilm suggested, i think examples.cfg, example-extras.cfg, example-menu.cfg should have place holders pointing to the new documents for a while until any old references and guides have had the chance to be updated.    

I ended up viewing the history in the end to find the old documents as i assumed they had mistakenly been deleted.

**Comment by KevinOConnor** [comment]
That makes sense - I created dummy example.cfg and example-extras.cfg files (commit 3d36ab68).

-Kevin

**Pull request merged**
