### PR TITLE
Add a bltouch "extras" module

### PR DESCRIPTION
**Pull request by KevinOConnor**
This change adds a new bltouch "extras" module and recommends its use instead of a "probe" config section with custom probe activate and deactivate sequences.  This new bltouch.py module has several useful features:
- It should be easier to configure for new users.
- It performs an internal test on the signal line prior to first use (which should help catch incorrect wiring or pin definitions).
- It provides more precise timing of bltouch actions.

Existing users would need to convert their configs to use the new bltouch module (the existing probe/servo config combo will continue to work but will not have the advantages described above).

-Kevin

### CODE REVIEW

**Comment by BlackStump** [comment]
@KevinOConnor  just tried this and with a genuine antclabs Bltouch is is working fine no probs at this stage.
a question is if I was at the commisioning stage and want to manually command the different angles
how would I do this?
ie 
pin down (10)
pin up (90)
self test (120)
reset (160)
query_probe ie M119 (60)

I changed to this code and the first thing I wanted to do before attempting a homing was to test the bltouch, the set_servo commands obviously dont work anymore.

**Comment by KevinOConnor** [comment]
It's possible to implement a "BLTOUCH_COMMAND" type of command, but I wasn't sure that was a good idea because it might leave the bltouch in a state that the new "self check" code would not like.

Hopefully the new code would require less manual testing as it should self check on each start.

-Kevin

**Comment by BlackStump** [comment]
fair enough, I am a person that likes to verify that endstops/probes work after a alteration before blindly issuing a homing command.
The other main reason for manual commands is to visually/physically test on commissioning
but I am gathering you have some checks in place that will issue a error if something is misconfigured so that is fine by me.
If a bltouch goes into a alarm state on boot is should reset without user intervention ?
I ask this because prior to this update if I booted the orangepi then the mcu it would on occassion go into alarm state so I just issue the reset command and everything is sweet. if I powered mcu first then powered orangepi I havent had a alarm state.
I will test the same boot sequence with this update.

**Comment by KevinOConnor** [comment]
Good questions.  Alas, I don't know - I don't actually own a bltouch.  I coded this up based on the spec and other's feedback.

The new code will leave the bltouch in "reset mode" normally.  On the first probe attempt (or any probe attempt with more than 5 minutes since the last probe attempt) the code will command the probe into "touch mode" while it is still raised and verify that the sensor pin shows as triggered.  It will then command the bltouch to "pin down" and it will verify that the sensor pin shows as non-triggered.  It is hoped that this command, verify sensor on, command, verify sensor off sequence will give confidence that the bltouch is operational.

Another change is that the bltouch pwm control line will not repeatedly send commands during normal printing - instead the pwm pin will be set to full off (no command sent).  It is hoped that this will reduce the chance that line noise impacts the bltouch.

-Kevin

**Comment by BlackStump** [comment]
well over the next few days I will test as is and if any issues arise I will let you know but sounds like you have a well thought out plan 👍

**Comment by KevinOConnor** [comment]
FYI, I've merged this code into the master branch.  I'm still interested in any feedback.

-Kevin

**Comment by jakep82** [comment]
I recently set up a BLTouch on my printer.  I'll update tonight and do some testing this weekend.

**Comment by jakep82** [comment]
I'm not sure if it's the new bltouch code, or some other change, but I'm getting a lot of errors on G28 after my update last night.  I'm currently running on a Raspberry Pi 3.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2636295/klippy.log)

**Comment by jakep82** [comment]
It homes X and Y 100% of the time, but after moving the head to the center of the bed, it gives me the error just before it deploys the bltouch probe.  It happens maybe 50% of the time.

**Comment by KevinOConnor** [comment]
Ugh.  I think I saw what went wrong.  Could you test the code on the work-bltouch-20181201 branch and see if it improves your results?

cd ~/klipper ; git fetch ; git checkout origin/work-bltouch-20181201 ; sudo service klipper restart

Thanks,
-Kevin

**Comment by jakep82** [comment]
I've homed my printer quite a few times since switching to this branch now, and I've not seen this issue again.  It seems to be solved.

**Comment by KevinOConnor** [comment]
Thanks.  I merged that fix.  I also put some new code up on the work-bltouch-20181201 branch that adds support for a new BLTOUCH_DEBUG command.  It would be great to verify everything still works on that branch and that the new BLTOUCH_DEBUG command works.

cd ~/klipper ; git fetch ; git checkout origin/work-bltouch-20181201 ; sudo service klipper restart

-Kevin

**Comment by jakep82** [comment]
All of the BLTOUCH_DEBUG commands seem to work, but I'm not sure the RESET is working entirely as desired.  If I run SELF_TEST, the RESET command works as expected.  If I use TOUCH_MODE and manually trigger the pin, the probe will show as triggered until I issue a PIN_DOWN or PIN_UP command.  Perhaps this is the desired behavior, but I would have expected a RESET to clear the trigger and show open.

**Comment by KevinOConnor** [comment]
Thanks.  I went ahead and merged the BLTOUCH_DEBUG stuff.  Odd on the "reset" command - it just sends the given command (2200us / S160) to the bltouch - not sure why it would respond that way.

-Kevin

**Comment by jakep82** [comment]
If you're using a BLTouch you don't need a probe section. Only the BLTouch section.

**Comment by RedlineGT** [comment]
> 
> 
> If you're using a BLTouch you don't need a probe section. Only the BLTouch section.

Thankyou so much for clarifying that! Do you have any hints for the the sensor_pin and control_pin?

**Comment by jakep82** [comment]
You would need to figure out the pins based on where you're connecting to the board. I don't have that printer so I'm not familiar.

**Comment by RedlineGT** [comment]
@KevinOConnor is it possible to document this somewhere for folks using the CR10s V2.0+ boards, the default bltouch config?
sensor_pin: ^ar18
# Z stop pin traditionally
control_pin: ar11
# the pin where you connect the brown wire
Not sure what "^" symbol signifies alongside the pin designation though.

**Comment by AxMod3DPrint** [comment]
"^" denotes a pin pull up, whereas "!" inverts the pin.

**Pull request closed without merging**
