### PR TITLE
add config options for pid settling parameters

### PR DESCRIPTION
**Pull request by hg42**
allow adjustments of these pid parameters, because my bed doesn't work convenient otherwise (fast heat up but very slow cool down, waiting for eternity).

### CODE REVIEW

**Comment by KevinOConnor** [comment]
This is fine for testing, but I don't think it will be useful for other users without documentation for the two new config options.  That said, I'd be more inclined to try to find a good default then to overwhelm the user with lots of config options.

I'm not sure I understand the issue you are seeing - if you're okay with significant overshoot on the bed, then why not use the "watermark" heater?

**Comment by hg42** [comment]
the whole thing with configuration is that not everyone has a printer like you.

There are quite unusual setups you will never think of while programming the firmware (or would you include printing houses or chocolate in your design?).
And the evolution of 3D printing is very fast paced.
I think making parameters available for tuning is a must.

My bed is not very usual but also not that special. It's just a 9mm aluminum plate which cools down slowly because of all that metal.
Additional I have a 2000W heater. It heats up fast because of the high wattage.
This should be common for bigger print platforms (mine is "only" 330x330). I know there are much bigger printers outside.

I definitely need PID because I want to keep the overshoot small, because this combination has a large delay and can easily overshoot 50%.
I can easily accept an overshoot of 5°C for my PETG but would want to stay blow within 2°C for PLA.

You cannot find an ideal value for both parameters for every heater.
E.g. all beds I have seen behave totally different than all my hotends. And I also had hotends that were totally different.

**Comment by KevinOConnor** [comment]
I guess I'm not understanding the problem you're seeing.  Perhaps you could take a snapshot of the temperature graph showing where klipper currently finishes the M190 and point out where you'd like it to finish.

To be clear, I don't like the behavior of M190/M109 either.  I'd like to have more flexibility so that homing, nozzle heating, and bed heating could be done more in parallel.  Perhaps there is a way we could do this outside the limitations of M190 (eg, WAIT_TEMP MIN_TEMP=190 SETTLE_TIME=0.5).

**Comment by LucaBertuolo** [comment]
@hg42 
Like you, also mine hot bed plate is a 300x300, but mine has got an heater of 700W...
If, like mine, also your hot bed is powered from 110/220v with a relay, your decision to use a PWM configuration for the bed, is not the correct choose...

If you use a relay or a solid state relay with a PWM wave, this is a very bad and dangerous choose because you will create a very tons of disturb on house electric power line...

**Comment by dragonnn** [comment]
I don't agree - if you use an SSR with zero cross detection and run it with PWM under ~50Hz (default Marlin is around ~8Hz) it work fine. https://www.youtube.com/watch?v=aU-ryPd78Gc this is how PWM works in Marlin with an SSR, you can even see when it goes on and off.

**Comment by hg42** [comment]
@LucaBertuolo my 2000W heater with a 8mm aluminum plate willl easily overshoot 30-50% of the desired temperature with simple bang bang.
Usually I use PID with a frequency of 10 Hz. The SSR switches only on zero crossing, so it doesn't disturb the power line.

With my changes it works perfectly.

5% overshoot is ok, that's why I want to enable this for PID (=max_diff).

The other problem is that the duration until it reaches standard max_deriv is much much much toooooo long.
That's totally unnecessary for the bed because there only matters if it is below max_diff.

Changing these values for the hotend would be wrong (because it is much faster in every aspect). So, as a conclusion, it is necessary to make it adjustable.

I am sure, anyone who thinks (s)he could find an ideal value for all situations, will certainly fail.
That's why Marlin etc. have so many values to configure. There are way too many printers out there that do not follow standards that you would expect.
And still being in a pioneer phase, innovation should not be stopped by such simplifications.

Just use good defaults, but allow to tweak each and every setting, if necessary. You need not document it, because only knowledgeable people will use them.
If it's changing the defaults then exactly these knowledgeable people will find the better values and the defaults will change.
Or for some special printer models the values will be communicated to normal users (via examples).

**Comment by hg42** [comment]
@KevinOConnor 
1. I know bang bang will not work (at least it doesn't in Marlin or Smoothieware, or did you implement it much differently?). The reason bang bang does not work is the very long delay in the loop. If the temperature is reached and the heater switched off, it still heats up to something up to 50% overshoot. That's why I need PID. Apart from that I always used PID for heated bed. All my beds had a longer delay than each of my hotends. So why should I use bang bang? Can someone give me some positive aspect of bang bang?
2. the overshoot for good PID parameters (= fast and stable) for PETG is near to 5% (which is ok for me), heat up to temperature is fast (<5miin), but the first cycle is very long (~30 min) because of a very slow cool down caused by a huge heat capacity of the heater and the 8mm plate and until the next iteration that could go below 2% it's another long cycle...all this is totally unnecessary because 5% is ok.
3. max_deriv is reached near to 30 minutes, while temperature is reached after <5 min. It's a long curve, that slowly moves down but is above max_deriv all the time (think of something more like a straight line)

Why is making this adjustable so difficult? As I said, just make it available and document existence for power users.  They will know what it is.

I am sure good defaults cannot be found for every occasion. Something good for my bed will not be good for others. And beds and hotends differ very much in principle, beds have much more material and much bigger time constants. You would like optimal temperature accuracy for hotends but it's much less important for beds.

**Comment by KevinOConnor** [comment]
Okay, I think I understand what you're seeing - you need the PID for stable bed temperatures.  However, the PID doesn't really work well for you as it overshoots and then takes an extended time to stabilize after overshooting.  It looks like you've found an acceptable workaround - to accept the inaccuracy of the overshoot to improve the print start time.

I've committed a change to heater.py (commit bba22ab7) to make it more clear what the check_busy() call is doing.  It seems you have an acceptable workaround.  I'd like to get more feedback from other users having problems with the PID before committing a config system to facilitate work arounds.

**Comment by hg42** [comment]
Nearly... :-)

I need PID because it overshoots very much without.
PID works very well, but with the fixed numbers it is heating up much slower than necessary (-> max_diff) and needs 30 min until the curve becomes flat enough (-> max_deriv).
Simply choosing higher values would not be good for hotends, which are much faster / fast enough for these values.

I even think, users have different strategies and strategies will also differ for different use cases.
Some want everything as fast as possible (e.g. more overshoot, e.g. when printing big parts) and others want it to be accurate (e.g. if printing small parts).
So adjusting such things is necessary. However, the default should fit say 90% of the use cases (or more if Klipper gets more "normal" users).

I also think, given the huge differences in use cases for such firmware (or 3D-printers, think of chocolate printers or printed houses etc., very small printers vs. very big printers) every constant should be adjustable, because nearly everything is related to physics. And Klipper will probably get the most attention from specialized projects, because these need more speed, more accuracy, more axes, more extruders etc., which are all fields where Klipper will collect credits.

**Comment by hg42** [comment]
I also thought about other possibilities.

There are several aspects:
1. code changes (like adding an adjustable value) should be as local as possible to the place where it is used
2. user changes should not be distributed over the source files (or better not located in source files at all)
3. defaults should be defined near to the algorithm (also to change only one place)

Adding constants in a source file (like you did with PID_SETTLE_DELTA, PID_SETTLE_SLOPE) fulfills 1+3, but not 2. User changes could be put in a central file, but then you need to implement a default+override mechanism.

Adding the constant with a config setting fulfills 1+2+3 instead. I would say this is ideal.

Additionally, if there is a kind of abstraction (= config object) this allows to add other things later, like making everything adjustable, savable, loadable, remotely controllable via gcode (or text commands) like RepRapFirmware, partly Smoothieware, Marlin (M500 etc.). 
It also allows hierarchical configurations like in Cura, where you can override settings depending on User, Printer, Material, Project, whatever.

**Comment by KevinOConnor** [comment]
On Wed, Jan 03, 2018 at 07:24:20PM +0000, Harald wrote:
> Nearly... :-)
> 
> I need PID because it overshoots very much without.
> PID works very well, but with the fixed numbers it is heating up much slower than necessary (-> max_diff) and needs 30 min until the curve becomes flat enough (-> max_deriv).

I don't understand.  The "max_diff" has no impact on the heating rate
at all - it can't impact "heating up much slower than necessary".  I'm
confused what the issue you're seeing is.

I think if would help if you sent me a screenshot of your temperature
graph and pointed out where Klipper finishes M190 and where you'd like
it to finish M190.

-Kevin

**Comment by hg42** [comment]
ok here it is:

pid

it's measured with my current PID tuning. This can be varied, though. So a current snapshot isn't representive for all possibilities.
I did not react to your former requests for a screenshot because it's not very interesting...

The target temperature is set to 65°C.
I want it to stay between 70°C (best adhesion with my bed and currently used filament) and 60°C (not critical, could even go down to 50°C, I think).
My current PID tuning heats up as fast as possible for a limit of not overshooting 70°C. The maximum is usually at about 69°C. At 50°C the SSR starts PWM, above 55°C it is nearly off. But the temperature increases steadily until it reaches it's maximum of about 69°C after about 10 min. Now the temperature decreases very similar to a straight line. 20 min after start it reaches about 68°C, as you see it would still take a while (may be 10-30 min?) until it may reach 65°C.

Ideally I could start printing at 60°C which is reached after about 4 min. I know the temperature will always stay between 60°C and 70°C after this point.

There are generally two variations for the PID tuning.
* with my current PID tuning the damping is high and oscillation is nearly prevented. I only need to increase PID_SETTLE_DELTA to allow the bigger overshoot. If I cannot do this, the 2% limit (66.3°C) will be reached after may be 30 min? With this variant decay is probably always below PID_SETTLE_SLOPE.
* if I use lesser damping I get more oscillation and the slope is above PID_SETTLE_SLOPE. Heat up is a little faster (though not enough to be of interest). In this case I need to change both PID_SETTLE_DELTA and ..._SLOPE

**Comment by hg42** [comment]
> "max_diff" has no impact on the heating rate at all

of course it has...
faster heat up = more overshoot
(assuming more overshoot is accceptable)
without max_diff Klipper would not accept this and wait another cycle (which is very very long in my case, so it's a deal breaker).

The usual way would be to tune PID to stay below 1 degree. This is very low overshoot for my bed and needs at least 10 min (time near the maximum).

May be I am wrong with PID_SETTLE_SLOPE, because this can also be true at the maximum, and only fails if the overshoot is higher than PID_SETTLE_DELTA.
But in my case I could also set PID_SETTLE_SLOPE very high and accept the rising edge when it comes near to the target temperature. That's why I also added it to the game.

I could also argue, PID does already manage overshoot, so check_busy could be a simple check if the temperature is reached (= inside a range, eventually asymmetric).
Checking the slope makes only sense if you overshoot more than you want to allow for printing, which means waiting for a later maximum (which I think is a good feature, but not the only way to go).

**Comment by hg42** [comment]
sorry, I shouldn't have merged directly on github...the merge is wrong

**Pull request closed without merging**
