### PR TITLE
docs: Input Shaper and Resonances docs improvements

### PR DESCRIPTION
**Pull request by dmbutyugin**
Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by dmbutyugin** [comment]
@KevinOConnor  A few notable points about the docs changes (following the feedback from #3025):

- Input Shaping is not longer experimental; I rewrote the introductory section a bit. I also noted that Input Shaping reduces vibrations of the printer in general, and it may improve the robustness of the stealthChop mode of TMC drivers. At least on my Ender 3 TMC5160 can work in stealthChop mode at 7000 mm/sec^2 and 200-250 mm/sec velocity (with stock steppers and motor current somewhat below the default current with original Creality board) without skipping steps. Without Input Shaping I experience skipped steps at around 4000-5000 mm/sec^2 even without stealthChop. But it's TMC5160, so they may work better in stealthChop mode in general.

- I tried to rewrite the instructions about using X and Y marks on the model. I *hope* it is less confusing now. Let me know if you think that's already better and less confusing than the previous version, or if you still think that renaming marks on the model would be less confusing.

The feedback on the documentation changes are very welcome from everyone. Any feedback: about the changes themselves, wording suggestions or proofreading.

**Comment by grigi** [comment]
:+1: If I had these docs I would have spent less time trying to understand it.
It still doesn't make clear that the  determine damping ratio is a property of the printer frame, and not something one can really tune. (If my understanding is right)

**Comment by dmbutyugin** [comment]
@grigi, Thanks!

> It still doesn't make clear that the determine damping ratio is a property of the printer frame, and not something one can really tune.

Of the printer in general (e.g. belts and some installed dampers may play a role too). Well, resonance frequency(-ies) is also a property of the printer, but it requires some measurements. I changed the wording slightly in Config_Reference.md to:

> In most circumstances this parameter requires no tuning and should not be changed.

**Comment by KevinOConnor** [comment]
Thanks!  Looks good to me.

One note is that `|:--:|:--:|` made the klipper3d.org rendering of the documentation ( https://www.klipper3d.org/Resonance_Compensation.html ) go haywire.  I had to pull it out in commit 6e48ee53 .  I know this is a compromise, but after a bunch of testing it was the only thing I could come up with.

-Kevin

**Comment by dmbutyugin** [comment]
> One note is that `|:--:|:--:|` made the klipper3d.org rendering of the documentation ( https://www.klipper3d.org/Resonance_Compensation.html ) go haywire. I had to pull it out in commit [6e48ee5](https://github.com/KevinOConnor/klipper/commit/6e48ee537f0503bc8d87e5387bd642a9b74df0b0) .

Ah, OK, makes sense. I didn't know about it and somehow thought I forgot to commit them last time :) But I should have checked my commit, of course. Anyway, made this particular change.

> I know this is a compromise, but after a bunch of testing it was the only thing I could come up with.

And I assume adding `| | |` as the next line after `|:--:|:--:|` doesn't help? Sorry, I didn't manage to run jekyll to get a preview.

**Comment by dmbutyugin** [comment]
BTW, I have added one more commit (separately for the ease of reviewing), where I reworked the Measuring resonances section of the doc following another [stream](https://www.youtube.com/watch?v=Q4OGfAHRnhY).

**Comment by KevinOConnor** [comment]
> Ah, OK, makes sense. I didn't know about it and somehow thought I forgot to commit them last time

My fault - I should have pinged you when I made the change.

> And I assume adding | | | as the next line after |:--:|:--:| doesn't help? Sorry, I didn't manage to run jekyll to get a preview.

If I recall correctly, it worked, but rendered goofy (it showed a blank row after the pictures).

FWIW, to test, I setup a dummy github repo ( https://github.com/KevinOConnor/github-pages-testing ), enabled "github pages" in the github settings, copied in some test files, and then viewed the results (eg, https://kevinoconnor.github.io/github-pages-testing/Resonance_Compensation.html ).  Most of the time the rendering is the same between github-pages and the github repo, so I'd say it is not worth spending much time on it.

-Kevin

**Comment by KevinOConnor** [comment]
> BTW, I have added one more commit (separately for the ease of reviewing), where I reworked the Measuring resonances section of the doc following another stream.

Thanks.  Looks good to me.  I'll commit when you are ready.

FWIW, I wonder if the guide could be simplified a little.  Some ideas:
1. Request the user install numpy, install matplotlib, and remove references in the main guide to running without them.  All in spec hardware can install numpy - if a user wants to go through the trouble of installing an adxl345 then I think it's reasonable to have them run on reasonable host hardware.
2. Recommend always running TEST_RESONANCES with `OUTPUT=resonaces,raw_data` (or change the default to that).  I can't see any reason not to also store the raw data.
3. Remove references to LibreOffice Calc and "offline processing" from the main guide.  Instead direct the user to always run the `calibrate_shaper.py` script.  A power user should be able to figure out the alternatives and I wonder if offering more options may confuse less savy users.

Just talking points.  I guess my high-level thinking is that the main guide may be easier to follow if there are less alternatives provided.  (Unless I'm missing something, the alternatives don't offer a notable difference in outcome.)  The thinking is that "power users" will be able to "read between the lines" anyway, while users that just want to obtain a "shaper_freq_x" would prefer concrete steps with less choices.  It's your call though.

Cheers,
-Kevin

**Comment by KevinOConnor** [comment]
Oh, as another minor thought, might be worthwhile to consider removing the shell prompt (`$`) from the example unix commands.  The other guides don't currently show the prompt for commands.

-Kevin

**Comment by dmbutyugin** [comment]
> Most of the time the rendering is the same between github-pages and the github repo, so I'd say it is not worth spending much time on it.

OK, thanks for the suggestion on how to test it, but I agree that it's not worth the trouble by now. So let's leave it as it is.


> Oh, as another minor thought, might be worthwhile to consider removing the shell prompt (`$`) from the example unix commands. The other guides don't currently show the prompt for commands.

Made this change. Then


> FWIW, I wonder if the guide could be simplified a little. Some ideas:
> 
>     1. Request the user install numpy, install matplotlib, and remove references in the main guide to running without them.  All in spec hardware can install numpy - if a user wants to go through the trouble of installing an adxl345 then I think it's reasonable to have them run on reasonable host hardware.

OK, that makes sense, and I made the suggested changes (more or less).

>     2. Recommend always running TEST_RESONANCES with `OUTPUT=resonaces,raw_data` (or change the default to that).  I can't see any reason not to also store the raw data.

Raw data could take a lot of space especially if the measurements are repeated several times, which may be generally not great if SD card is small or if /tmp is mounted to RAM. But I think with the changes to the test (mostly, duration optimization) this is no longer much of concern. Still, `SHAPER_CALIBRATE` does not support `OUTPUT` argument at all, and arguably this should be a command of choice for repeated calibrations. So I will leave things be for now. Besides, raw data is useful in case of advanced debugging, in which case it is always a possibility to ask a user to generate the raw output. Anyway, I'll be updating the docs for `max_smoothing`, and I will see how it fits into calibration process, so maybe I will reconsider generating raw data at that point.


>     3. Remove references to LibreOffice Calc and "offline processing" from the main guide.  Instead direct the user to always run the `calibrate_shaper.py` script.  A power user should be able to figure out the alternatives and I wonder if offering more options may confuse less savy users.

Done. For the power users, I left a section "Offline processing of the accelerometer data".
 
> Just talking points. I guess my high-level thinking is that the main guide may be easier to follow if there are less alternatives provided. (Unless I'm missing something, the alternatives don't offer a notable difference in outcome.) The thinking is that "power users" will be able to "read between the lines" anyway, while users that just want to obtain a "shaper_freq_x" would prefer concrete steps with less choices. It's your call though.

I agree about the power users. The thing is, the initial guide was written for the power users :) Now that there's more confidence in the approach in general and in auto-tuning algorithm in particular, the guide should probably be adjusted towards the regular users who just need a step-by-step guide.

> Thanks. Looks good to me. I'll commit when you are ready.

I made another relatively large change to the docs following the suggestions and discussion. However, if there are no further suggestions / comments, I think the changes can be committed (and max smoothing and further updates can follow afterwards).

**Comment by KevinOConnor** [comment]
Looks good to me!  I guess I'll give it a day or so for more comments and otherwise commit.

-Kevin

**Comment by dmbutyugin** [comment]
OK, sounds good.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Pull request merged**
