### PR TITLE
RFC: display: Add support for display graphics

### PR DESCRIPTION
**Pull request by FHeilmann**
This PR adds support to display graphics on the full graphic displays. I implemented the following restrictions:
- width and height must be multiples of 8
- width and height are not constrained, however the code will simply not render anything that goes beyond the display dimensions (this also applies if the user tries to render a large graphic starting in the lower right corner for example)
- the length of the first line dictates the length of all lines.

The formatting of this PR could probably use some work, staying below the 80 line limit was a bit tricky. I'll add the docs once we have ironed out the issues with the code.

Thanks
-Florian

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I wonder if it would be simpler to just add support for 8x16 icons to the existing display_glyph code.  For users that want more complex combinations, they could obtain that by stringing and overlapping multiple 8x16 glyphs.  It's a bit more work for the user, but I'd guess it's not a common enough task to worry about.

Cheers,
-Kevin

**Comment by FHeilmann** [comment]
I changed the code to remove the x8 lines requirement and make the line drawing more robust.

Unless you have strong reservations against this I'd favor being able to define the entire graphic than having to split it into multiple glyphs and ending up with a huge config file.

**Comment by FHeilmann** [comment]
So far I've used it to display full-screen splash screens at startup, but with the recently merged PRs for switching display groups I'd imagine that people could come up with all sorts of things, i.e. backgrounds for things like a mesh leveling visualizer, larger animated pictures for layouts that don't want to cram so much information onto one screen etc.

From another point of view, the 8x16 glyphs you propose, as well as the existing 16x16 glyphs are really just specific cases of this more generic use of `write_graphics()` so theoretically `display_graphics()` could become the only system (and thus take over the `~name~` format as well).

**Comment by KevinOConnor** [comment]
Could we make `[display_glyph abc]` more flexible and avoid adding a new config section?  I think we'll want to continue to have `~name~` support because some glyphs (eg, `~degrees~`) are actually used in a text context.  Could we continue to use `~my_graphic~` to show arbitrary images?

Separately, I just committed a cleanup patch to write_graphics() (commit 9465618a) which will conflict with this patch.

-Kevin

**Comment by FHeilmann** [comment]
@KevinOConnor im fine with putting this all into one system that can handle larger images. I Sony have a preference regarding what gets unified with what so long as larger glyphs can be displayed without having to split them into 32 smaller glyphs ☺️

**Comment by FHeilmann** [comment]
@KevinOConnor so, moving forward on this, what's your preference for this PR? Would you like me to fold the graphics functionality into the display glyphs? If so I could get on that soon. I'd then make display_glyph accept images which are multiples of the base-size of 8x16 if thats ok with you.

Florian

**Comment by KevinOConnor** [comment]
Thanks.  Reworking display_glyph so it can handle (N*8)x16 icons sounds good to me.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by FHeilmann** [comment]
Sorry I haven't gotten around to it yet. If you want I can close this pr and open a new one once I have everything ready.

**Comment by ETE-Design** [comment]
@FHeilmann  Does this mean that you can now make your own Start Up screen / logo on the 12864 Display? If so, how to do it easiest? Is it possible to do it like the Marlin Bitmap Converter?

**Comment by FHeilmann** [comment]
@ETE-Design that is definitely possible. I'll try to provide a writeup once I update this PR

**Comment by FHeilmann** [comment]
I'mc losing this due to lack of time for now. I'll revisit this at a later point.

**Pull request closed without merging**
