### PR TITLE
module: simple-pid implementation for PID heater control

### LINKED ISSUE #1167: Request - Set / Adjust PID parameters via gcode
Possibility for PID values be changed for different temperatures / materials using gcode macros?
In Marlin one can use in the slicer start script:-
M304 - Set Bed PID
M301 - Set Hotend PID
to change preset pids
thanks - bruce

### LINKED ISSUE #1215: hotend temperature become increasingly unstable despite auto pid tuned and low fan speed
image

i am using mks gen l as my controller board. as title, i have my hotend pid auto tuned at 215C with 50% fan speed for the part cooling fans.  i've installed a home made silicone sleeve for the heater block, i've the part cooling fans turned on at layer 2, only at 15% fan speed, which barely pushes any air but it is already enough to cause crazy fluctuations and it get worse as it goes on, at worse the temp will go up and down for +5/-5C

 it might be worth mentioning that i've tried setting up various conditions prior auto pid tuning, such as, sleeve on/off, various fan speed, various z height. however, nothing changes, the thermal instability kicks in as soon as there are slightest amount of breeze over the heater block. 

is there anything i can do to improve the temperature stability for my hotend?
[klippy.zip](https://github.com/KevinOConnor/klipper/files/2846388/klippy.zip)

### LINKED ISSUE #2324: [feature request] PID gain scheduling
It would be helpful to have the ability to change the PID gain values on a schedule.  Perhaps a command similar to loading and saving bed meshes that can be used for PIDs?  I'm not sure if something like this exists...

My use case would be using a different PID to get to temperature vs maintaining temperature, and perhaps a different PID for certain conditions such as cooling fan on/off.

The ability to schedule/modify PID gains on-the-fly would add a lot of flexibility and greater control over temperatures.

### LINKED ISSUE #2331: Feature Req: Set PID values per G-Codes or have different values for different set points
Hi,

I print with 190 C lowest and up to 260 C highest. PID values are different (significant) for these two set points. Right now I use one PID set which is measured at 210 C.

Yes, it is „ok“ but it would be better to be able to either set the PID values per G-Code (Macro) or have defined areas for PID values.

Let’s say something like that.

```
[PID-170-190]
P=xxx
I=xxx
D=xxx
[PID-190-220]
...
[PID-220-270]
...
```

### PR DESCRIPTION
**Pull request by bjones14**
replacing custom PID control algorithm in favor of simple-pid
library.  also adding additional extended gcode commands
for on-the-fly PID tuning and PID debugging.

Signed-off-by: Brandon Jones <bjones14@gmail.com>

---

These commands allow updating PID terms "on-the-fly".  This allows anyone to script different terms for different portions of their print.  It also allows for more advanced PID tuning for those of us interested in doing so.

Fixes #1167 
Fixes #2324 
Fixes #2331 
Fixes #1215

### CODE REVIEW

**Comment by FHeilmann** [comment]
Is there a specific reason you decided to replace the inbuilt PID with simple_pid?

**Comment by Coffee0297** [comment]
this is amazing for us that likes to do pid by yourself, the klipper one are just not the best.. 
did you manege to "fix" the sample time/call time of pid? when klipper are in printing mode i feel like the pid loop is not called fast/often enough.
in "standby" mode its fine and updates the pid loop as expected.
-Tonny

**Comment by bjones14** [comment]
@FHeilmann I decided to do so for a few reasons.  One of which is related to what @Coffee0297 pointed out.

1. Support for Proportional on Measurement control, in addition to traditional Proportional on Error control.  This control works much better on integrating processes such as temperature control.  [http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/](http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/)

2. The way the PID control is currently happening, I think, should be modified.  What happens now is that the PID only calculates a new value when there is a temperature update.  Sometimes a temperature update (at least on my hardware) can take over 1 second which is an incredibly large delay between PID calls for good control.  While this pull request does not address that specifically, it does make it easier to call the PID update independent of the temperature updates in the future.

3. Maybe this one is more of a personal opinion, and I will argue it, but I'm a strong proponent of code reuse and I would rather see a standard PID library being utilized instead of a custom one.

**Comment by bjones14** [comment]
> 
> 
> this is amazing for us that likes to do pid by yourself, the klipper one are just not the best..
> did you manege to "fix" the sample time/call time of pid? when klipper are in printing mode i feel like the pid loop is not called fast/often enough.
> in "standby" mode its fine and updates the pid loop as expected.
> -Tonny

I identified the cause of that but did not implement a fix.  The cause is that the PID is only calculated on temperature updates, not at a fixed rate.  I think you could launch a thread to call the PID at a constant rate independent of the temperature update rate, and just use whatever the most recent temperature value is.  Ideally if temperature acquisition rates could be improved then the PID would also drastically improve as-is.

**Comment by bjones14** [comment]
> 
> 
> Is there a specific reason you decided to replace the inbuilt PID with simple_pid?

@FHeilmann I decided to do so for a few reasons.  One of which is related to what @Coffee0297 pointed out.

1. Support for Proportional on Measurement control, in addition to traditional Proportional on Error control.  This control works much better on integrating processes such as temperature control.  [hhttp://brettbeauregard.com/blog/2017/06/introducing-proportional-on-measurement//](http://brettbeauregard.com/blog/2017/06/introducing-proportional-on-measurement/)

2. The way the PID control is currently happening, I think, should be modified.  What happens now is that the PID only calculates a new value when there is a temperature update.  Sometimes a temperature update (at least on my hardware) can take over 1 second which is an incredibly large delay between PID calls for good control.  While this pull request does not address that specifically, it does make it easier to call the PID update independent of the temperature updates in the future.

3. Maybe this one is more of a personal opinion, and I will argue it, but I'm a strong proponent of code reuse and I would rather see a standard PID library being utilized instead of a custom one.

**Comment by Coffee0297** [comment]
@bjones14 good to know, are you willing to make a change so we can specify if we want "old" update or a new fixd rate? I wuld greatly appreciate it, and if that's more stable at klipper auto tune pid maybe make that default?

-Tonny

**Comment by Coffee0297** [comment]
Or is a better solution to make the temprature update at a fixd rate to make the pid more responsive when printing? Ie. 0.5s?
 I know from automation we use interrups but I have no idea how the mcu and pi handles this.

-Tonny

**Comment by bjones14** [comment]
> 
> 
> Or is a better solution to make the temprature update at a fixd rate to make the pid more responsive when printing? Ie. 0.5s?
> I know from automation we use interrups but I have no idea how the mcu and pi handles this.
> 
> -Tonny

I believe the best thing to do for this would be to have a separate process run at a fixed rate that updates the PID, that way temperature doesn't impact the control rate.  Thinking more on it, I do believe this should also have those changes 

I'm not super familiar with the pull request process but I could add additional changesets with those updates as well.

**Comment by Coffee0297** [comment]
@bjones14 
that wuld be super usefull.. when we have a fixd temp "rate" we can controll the pid so much better, and prevent silly over/under shoot that are caused by this. 
thanks so much for this work.

-Tonny

**Comment by fiveNinePlusR** [comment]
I will say that the simple_pid code does nice things like clamping to avoid integral windup errors. Not sure how keving feels about adding a dependency though and this pull request would have to add to the requirements file to pull in that dependency when needed anyway.

on my 3d printer the default pid implementation seems to work ok.

**Comment by bjones14** [comment]
> 
> 
> @bjones14
> that wuld be super usefull.. when we have a fixd temp "rate" we can controll the pid so much better, and prevent silly over/under shoot that are caused by this.
> thanks so much for this work.
> 
> -Tonny

The more I think on this, the more I believe that the rate at which the PID is updated currently is the correct way (on every temperature update).

A PID loop is a loop - which is to say that each updated control output value should be processed on a unique process variable reading - make a change, observe the change, repeat.

The problem is that the dead time of the control loop (the time between it making an output change and that change being observed) is quite large.  At least in my setup, my temperature updates are 1 second or slower, which is quite a slow update.  I don't know if that is expected, or unique to my case perhaps...

So, the loop isn't effective if it continues to make changes while not knowing the impact of the first change

I did update the requirements document to include simple-pid as well

**Comment by Coffee0297** [comment]
yea i know, pid loop to be effective should be as quick as possible.in big systems you set the pid loop to update at a fixed rate by interrupts and just feed it values.
but in this instance it would not be good bc of how slow the temp are updating.

i wuld suggest to make the temp update much more frequent and then let the pid be as it is in this pr.

-Tonny

**Comment by bjones14** [comment]
> 
> 
> yea i know, pid loop to be effective should be as quick as possible.in big systems you set the pid loop to update at a fixed rate by interrupts and just feed it values.
> but in this instance it would not be good bc of how slow the temp are updating.
> 
> i wuld suggest to make the temp update much more frequent and then let the pid be as it is in this pr.
> 
> -Tonny

I'm not sure what makes the temperature update slow.  If I think about it, it does need to ask the printer board for temperature and stream that over serial, so I imagine most of the latency or slowness is related to that.  I guess I'm not sure how often a comparable Marlin system would be providing temperature updates (I don't have a system like that around anymore, just a single printer with Klipper for me)

Either way, I think that should be a separate issue, as it impacts a lot more than just the PID update frequency.  The only thing you really lose by performing slower PID updates is more accuracy on your I-term, as you are only taking the average error over that long period of time instead of breaking it up into multiple updates.  However, I imagine taking the average is just fine in most cases.  I would say in some instances it might even be better just because it would average out any noise spikes that occur - that is particularly good if you have a large D term because the slope on a noise spike is near infinite.

**Comment by KevinOConnor** [comment]
My high-level feedback is that I don't think it makes sense to use an external library for Klipper's PID update loop.  The update loop is one of the few "hard realtime" code paths in the host code (the host code must be able to respond to a temperature update within about 200ms or it can result in a failure).  Given the nature of the strict timing and the threading/locking implementation to facilitate it, I don't think bringing in external code (where we can no longer monitor/control those low level implementation details) is a good idea.

Separately, there were several inaccurate statements in this thread that I find a bit startling.  The Klipper PID loop updates ever 300ms and that update time (along with the resulting temperature update, if any) is implemented with great accuracy and precision.  Communication latency has no impact on the PID loop, as everything is calculated and executed on scheduled times; the host never uses time of receipt of a message in its calculations.  Klipper does implement limits on integral windup (see `pid_integral_max` in config/example.cfg).

-Kevin

**Comment by bjones14** [comment]
> 
> 
> My high-level feedback is that I don't think it makes sense to use an external library for Klipper's PID update loop. The update loop is one of the few "hard realtime" code paths in the host code (the host code must be able to respond to a temperature update within about 200ms or it can result in a failure). Given the nature of the strict timing and the threading/locking implementation to facilitate it, I don't think bringing in external code (where we can no longer monitor/control those low level implementation details) is a good idea.
> 
> Separately, there were several inaccurate statements in this thread that I find a bit startling. The Klipper PID loop updates ever 300ms and that update time (along with the resulting PWM update, if any) is implemented with great accuracy and precision. Communication latency has no impact on the PID loop, as everything is calculated and executed on scheduled times; the host never uses time of receipt of a message in its calculations. Klipper does implement limits on integral windup (see `pid_integral_max` in config/example.cfg).
> 
> -Kevin

Excellent points.  Primarily I pulled in simple-pid so that I could quickly test Proportional on Measurement control without having to manually implement it in the algorithm that was there.  So long as the algorithm Klipper uses supports the additional extended gcode commands that I added (or just dynamic updates in general), I would agree that it is probably best for the PID to remain internal, with the Proportional on Measurement support and additional commands being there as opt-in features that could be added.

I do apologize if I misspoke or inaccurately understood how the timing of the PID works.  I appreciate that clarification, and after thinking about it, there must be something else in my setup accounting for the latency that I was comparing it to.  I'm a big fan of Klipper and I'm just here to help out where I have the experience and ability to.

**Comment by KevinOConnor** [comment]
> If it's alright, I'd like to remove the simple-pid dependency and instead implement the required changes to the built-in algorithm and add those changes to this pull request (and rename it as well). That way the pull request is just focused on adding Proportional on Measurement control as well as the additional extended g-code commands for dynamic configuration.

Sounds good.  I'd add the command in a PR separately from the features.  Also, I recommend adding the command to klippy/heater.py (and not klippy/gcode.py).

Thanks,
-Kevin

**Comment by Coffee0297** [comment]
Any dev in this anymore? i think this will fix alot of stuff thats wrong with the pid loop..

**Comment by GarthSnyder** [comment]
I was curious about this PR as well. The existing PID system is workable--no worse than Marlin--but autotuning is hit or miss and even with hand tuning I still have small ripples and sags.

This is tangential to what @bjones14 was working on, but I can't help thinking that there's a gold mine of data in the work queue that could inform hotend temperature management. You know what the upcoming extrusion pattern is going to look like over the next couple of seconds, so you know in advance how much heat is going to be discharged from the system. It seems like the regulation system should be able use this foresight to stabilize the hotend temperature. I'm sure there's no closed-form solution, but a variety of ML approaches might work.

**Comment by KevinOConnor** [comment]
Okay, looks like this PR can be closed.

-Kevin

**Pull request closed without merging**
