### PR TITLE
Added TronXY X5SA support

### PR DESCRIPTION
**Pull request by cab404**
That includes config, Kconfig entry for its bootloader and encryption utility.
Directions for building and flashing are in the config file.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

FWIW, I'd prefer to use the term "encode" then the term "encrypt".  (These utilities aren't really encrypting.)  Also, probably best to remove the "bmg encoder" and "pressure advance" comments as it's difficult to make meaningful recommendations for either of them.

-Kevin

**Comment by cab404** [comment]
>  I'd prefer to use the term "encode" then the term "encrypt".

I sticked with original name used by script's author, so that's why it is "encryption". I can change that as well)



> Thanks. Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

> Also, probably best to remove the "bmg encoder" and "pressure advance" comments as it's difficult to make meaningful recommendations for either of them.

Will rebase in a minute)

**Comment by cab404** [comment]
Should I generally remove stuff that belongs to "Getting started" guide, like "Calibrate your probe"?

**Comment by cab404** [comment]
I would guess "Yes".

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me.  What year is this printer (roughly) from?  By convention, the printer config files all end in a year.

-Kevin

**Comment by cab404** [comment]
@KevinOConnor, done)

**Comment by KevinOConnor** [comment]
Thanks.  I committed this and made a couple of minor changes on top (commit 1d201c35 and 12529ef6).

-Kevin

**Pull request merged**
