### PR TITLE
LCD: FR icon changed to "Feed Rate"

### PR DESCRIPTION
**Pull request by jameswood**
LCD: To increase clarity, I've changed the FR icon to read "Feed Rate" on graphical LCDs.

### CODE REVIEW

**Comment by jameswood** [comment]
img_4765
It looks like this - I hope that submitting a PR for this change was the community-minded way to go, I hadn't realised there had already been discussion about this over in #652 (sorry!)

**Comment by alfsoft** [comment]
:thumbsup: way better than current icon!

**Comment by jameswood** [comment]
> 👍 way better than current icon!

Thanks @alfsoft - the old one didn't really fit with the awesome new ones you made. I did this for me, then thought I'd share it, not realising the backstory. LOVE your new hotend icon, and the others are brilliant too.

Your Feed Rate icons were cool too, but as you all discussed on the other thread, it's a tough one to illustrate unambiguously. And the word "speed" is juuuust too large to fit!

eg:
feed rate

**Comment by KevinOConnor** [comment]
I like it!

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
