### PR TITLE
Add support for the AD849x series of thermocouple amplifiers

### PR DESCRIPTION
**Pull request by RadicalZephyr**
I'm using these thermocouple amps on a personal project of mine and thought I'd contribute it to Klipper.

Let me know if you have any feedback on the code!

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Could these tables be added to the existing klippy/extras/adc_temperature.py file (next to the AD595 table)?

-Kevin

**Comment by RadicalZephyr** [comment]
Yeah for sure. Would you want to move the other code to that file too?

**Comment by RadicalZephyr** [comment]
Looking more closely, I'm realizing that I actually based my new `AD849x` class on the `PrinterADCToTemperature` and I could probably just make a thin wrapper on `LinearInterpolate` like `LinearVoltage` to add the behavior for falling back to the 5mV/°C transfer function and just directly use the `PrinterADCToTemperature` class.  I'll work on putting together that change but it probably won't be this week.

**Comment by KevinOConnor** [comment]
The current LinearInterpolate code will use the last "slope" (or first slope) for any value outside the range.  So, you should be able to just add a table without code changes.

-Kevin

**Comment by RadicalZephyr** [comment]
The current LinearVoltage isn't quite capable of fully supporting the AD849x chips since there is a possible voltage offset that needs to be accounted for.  I updated the PR to have the code and tables live in `adc_temperature.py` but I wrote a new `LinearVoltageWithOffset` class to handle the AD849x's voltage offset configuration.

@KevinOConnor let me know if this looks reasonable or you have any other changes you want made.

**Comment by KevinOConnor** [comment]
Thanks.  If there's need for a `voltage_offset` value then lets just add that to the existing LinearVoltage class.  I think that would be preferable to adding additional code and adding a new section to the example-extras.cfg file.

-Kevin

**Comment by RadicalZephyr** [comment]
That makes sense to me, I'll go ahead and make that change.

**Comment by RadicalZephyr** [comment]
That makes sense to me, I'll go ahead and make that change.  It seems to me that the new section in `example-extras.cfg` is still needed to illustrate the use of the voltage offset and document the existence of the new `ad849x` temperature sensor values.  If you think there's a more appropriate place or way to document those new values though let me know and I'll change it.

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me.  The commit will require a signed-off-by line though.

-Kevin

**Comment by RadicalZephyr** [comment]
Fixed!

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
