### PR TITLE
pause_resume: Use built in gcodes for saving and restoring state.

### PR DESCRIPTION
**Pull request by Arksine**
Use the new SAVE_GCODE_STATE and RESTORE_GCODE_STATE gcodes to move back to the correct position after resuming from a pause.  Also use Octoprint's "action:paused" and "action:resumed" action commands.  These commands prevent Octoprint from sending additional gcodes such as M0.

Signed-off-by: Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by Hywelmartin** [comment]
I updated this morning and when paused via PAUSE the state in octoprint doesn't go to paused.. same behavior when RESUME...
I previously used this in my pause/resume macros..
RESPOND TYPE=command MSG=action:paused
RESPOND TYPE=command MSG=action:resumed

**Comment by Arksine** [comment]
pause_resume sends those action commands for you. I will need a log of this behavior to see what is happening.

**Comment by Hywelmartin** [comment]
between row 2500-ish and row 8500-ish I'm running without my own 
```
RESPOND TYPE=command MSG=action:paused
RESPOND TYPE=command MSG=action:resumed
```
in the macros

/M
[pause_resume_klippy.zip](https://github.com/KevinOConnor/klipper/files/3269514/pause_resume_klippy.zip)

**Comment by Arksine** [comment]
It looks like you are printing from SD.  By design, pause_resume does not send octoprint action commands while printing from SD, it directly executes a pause from the sd card.

**Comment by Hywelmartin** [comment]
Yes I print from vSD and the whole idea with "paused" and "resumed" is to send them to octoprint imo.. The "paused" does not trigger anything more than that Octoprint state changes, likewise with "resumed".. If you sent a "pause" or "resume" then octo will make stuff.. I see only benefits to send these action commands to octoprint... I have been using the responds for a while..... with no issues.. and benefits like the Telegram plugin that tells me when a print is paused.. due to lack of filament or when the printer gone thru its start procedure and is ready for filament...

But thanks for the clarification...

**Comment by Arksine** [comment]
The pause_resume module will send the "paused" and "resumed" action commands to Octoprint if you are printing from Octoprint.  They aren't sent if your are printing from Virtual SD.  The module can't distinguish if you are monitoring your VSD print via Octoprint or using another source.  It may not be harmful to always send the action commands, but IMO that is probably something better done in a gcode macro as you were doing before.

**Pull request merged**
