### PR TITLE
Added axis homing order for X and Y in Safe Z Homing module

### PR DESCRIPTION
**Pull request by mental405**
Some printers have issues where X can't home before Y without a collision. 
This adds an option to specify the order in which the X and Y axes are homed
when Safe Z Homing is used.

Signed-off-by: Paul McGowan <mental405@gmail.com>

### CODE REVIEW

**Comment by FHeilmann** [comment]
Just playing the devil here, if someone passes something else except `XY` or `YX` this could result in all sorts of trouble.
I would suggest to limit what the user can actually provide here to welldefined inputs.
Here's an example how to do this:
<https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/tmc.py#L259>

**Comment by mental405** [comment]
Not saying it isn't a bad suggestion, just saying that if the inputs are invalid it will throw a "must home axis" error if it tries to move the XY to their Z safe position since the XY coordinate for safe_z_homing are required.

**Comment by FHeilmann** [comment]
I'm just giving suggestions to harden the code. If someone puts `X` or `Y` in that configuration parameter, the printer is unhomeable, since the printer will never attempt the other axis and always error out with an error message that does not directly point to this misconfiguration.

**Comment by mental405** [comment]
Oh yea, I agree. I am going to put it in, just saying it isn't going to cause crashes, just errors.

**Comment by mental405** [comment]
I added the getchoice option for the xy homing order. 

After using the module for a couple of days and testing it with a couple other people, the feedback was favorable to add a Parking Position parameter as well so that the tool can be parked after homing, like above a wipe/purge station for instance.

**Comment by mental405** [comment]
Closing this because I am bad at GitHub.

**Pull request closed without merging**
