### PR TITLE
printer: simplify module loading.

### PR DESCRIPTION
**Pull request by cruwaller**
Add 'extras' to search paths list and use try-except
         to catch an possible loading error. This allows to
         add multiple dirs to load e.g. modules.

Signed-off-by: cruwaller <cruwaller@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I'm concerned about doing a blink module load, because a user might do something like [pickle abc] and then it loads the system python pickle module.  Loading the module could have obscure side effects.  That's why I purposefully check for the file's existence and prepend the "extra." to the load request.

Are you planning something that the current system doesn't support?

**Comment by cruwaller** [comment]
By doing this klippy allows to load modules from different folders like; gcode.M666, drivers.tmc2130 etc which makes system flexible and you can keep structure nice and clean. Current implementation forces all files to 'extras' folder and e.g. fan is not an extra, imo :)

By doing this,  module has to contain correct attribute or it is skipped anyway. So, it would be hard to load wrong module.

Would it be better to use "path" as a config keyword? like 
[drivers.TMC2130 this_is_my_name]

**Comment by KevinOConnor** [comment]
If the "extras" directory gets too crowded, then sure, might as well introduce new directories.  I'm not sure the best way to do that.  My first reaction would be to do something like:

CONFIG_OBJECT_DIRS = ["extras", "drivers", "gcode"]

and then change _try_load_module() do do something like:
```
for obj_dir in CONFIG_OBJECT_DIRS:
    if os.path.exists(os.path.join(obj_dir, module_name)):
          ...
          mod = importlib.import_module(obj_dir + "." + module_name)
          break
```

**Comment by cruwaller** [comment]
skip this

**Pull request closed without merging**
