### PR TITLE
Fix typo in TMC2660 extra

### PR DESCRIPTION
**Pull request by FHeilmann**
Somehow a typo was left uncaught when I rebased the commit.
I'm sorry. This PR fixes it.

Bests,
Florian

Signed-off-by: Florian Heilmann <Florian.Heilmann@gmx.net>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  FYI, if you can put together a sample config that uses an sx1509 then we can add it to the automatic test cases.  All the printer configs are tested this way (see test/klippy/printers.test).  It's also possible to test specific commands (see test/klippy/z_virtual_endstop.test).

-Kevin

**Comment by FHeilmann** [comment]
Yes, absolutely, I was thinking about putting together a generic-duet config which will cover the tmc2660 and the sx1509

**Comment by FHeilmann** [comment]
@KevinOConnor can you toss me a command which I can use to perform the travis config test locally?

**Comment by KevinOConnor** [comment]
I run `../klippy-env/bin/python scripts/test_klippy.py -d local/ test/klippy/*.test`

But in order for that to work you need a collection of "data dictionary" files in the local/ directory. Unfortunately it's a bit of a pain to build the pru dictionary - I've attached my local set: 
[dictionaries.tar.gz](https://github.com/KevinOConnor/klipper/files/2527148/dictionaries.tar.gz)

-Kevin

**Pull request merged**
