### PR TITLE
stm32:  Add support for the HID Bootloader

### PR DESCRIPTION
**Pull request by Arksine**
This pull request adds support for the [STM32 HID Bootloader](https://github.com/Serasidis/STM32_HID_Bootloader) to the STM32F103, STM32F405, and STM32F407 configurations.  I created specific builds for the [SKR Mini E3 and SKR Pro](https://github.com/Arksine/STM32_HID_Bootloader/releases/tag/v0.5-beta), along with updated builds for maple mini and "blue pill" devices that contain some fixes for issues that are present in the upstream builds.

From my experience this bootloader works much better with the SKR Mini E3.  It handles the USB discovery pin so it isn't necessary to do so via "inital pins".  Firmware restarts are consistently successful.  Unlike the stm32duino bootloader you don't have a time limit to flash the device.  The only downside is that there is no flash verification, as the developers squeezed the bootloader into 2KiB.

For Klipper I added a customized version of the open source "hid-flash" tool used to flash the bootloaders.   I made some changes that allow it to work with flash_usb.py and also changed the Makefile so that it would warn the user that it requires libusb-1.0 rather than generate an error.  This way "make flash" doesn't error out for existing users that are flashing via dfu-util.

Signed-off-by: Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback is that this looks useful and would be good to add.  One minor comment though - I'd prefer for the content in the lib/ directory to document the source of that content in lib/README along with a list of changes (if any).

-Kevin

**Comment by Arksine** [comment]
Great!  I'll get the readme up with the source and changes.

**Comment by Arksine** [comment]
README file added with links to the original source and changes.  I copied the license from main.c and put it in LICENSE so its easily visible.

**Comment by KevinOConnor** [comment]
Thanks.  I don't see an update to the `lib/README` file though.  In general, I'd prefer to keep pristine upstream code in the lib/ directory where possible.  Where not possible, we've been including explicit `diff` files so users can recreate the pristine code from the lib directory code.  Are there significant changes to make the tool work with Klipper that need to be done to the tool itself?

-Kevin

**Comment by Arksine** [comment]
Oh, I added the README and just squashed it into the original hidflash commit.  I probably shouldn't have rebased before you saw it.   I just pushed a commit with a diff.  FWIW, the changes are also available at the fork I made to create the SKR Mini/Pro Bootloaders:

https://github.com/Arksine/STM32_HID_Bootloader

The biggest changes were to make the serial port "optional" so the tool doesn't attempt to connect and enter the bootloader, as flash_usb.py does that for us (and does it better than the original tool).  I also made a change for it to work correctly with the SKR Mini Bootloader binaries I created.  The Mini uses a "high density" variant of the STM32F103 with 2KiB flash pages.  While the upstream bootloader added support for high density devices it contains a bug that doesn't write the last page if it is 1024 bytes or less.

**Comment by KevinOConnor** [comment]
Thanks.  I also added an entry to `lib/README.md` with a pointer to your `lib/hidflash/README`.

-Kevin

**Pull request merged**
