### PR TITLE
[WIP] BTT MMU DIP board integration and HC595

### PR DESCRIPTION
**Pull request by kakou-fr**
This is the modifiication I made for supporting the STM32F030 and the HC595 (based on other PR).

It now work correctly with my setup and a MMU2+1S.

I am ready for your comment  / modification ask.

### CODE REVIEW

**Comment by Arksine** [comment]
Wait, BTT decided to clone the MMU2 board with an improved MCU and they kept the shift registers?  😕

**Comment by kakou-fr** [comment]
indeed ...

**Comment by KevinOConnor** [comment]
Thanks.  My main high-level feedback is that I don't think we should add micro-controller code for the hc595 chip.  It shouldn't be needed, because the host can instead configure a "software_spi" object.  Basically, the shift register protocol is compatible with spi.

Also, it would be preferable to separate out the stm32f030 changes into its own commit.  It's easier to review, and it makes it easier to revert later if a problem arises.

I'm not sure I fully understand the mmu.py changes - I'd need to review that further.  It would also be preferable to implement the hc595 host code in a separate commit from the mmu2 code.  (Unless I'm missing something, it may be generally useful to have a `[hc5959]` config section to add button support even separate from the mmu2.)

-Kevin

**Comment by kakou-fr** [comment]
I tried with SPI, but it doesn't works  with the klipper SPI implementation. i think the change are to quick and the HC595 cannot handle them. It's why i added some pause into the hc595.c file compared to the original FR.  On the host level, the HC595 only handle the HC595 and has is  own section i the config. the MMU uses an HC595 to handle the leds and the steppers (i will add the button support later).

I will separate the patch, but before i want just to  be sure that i could be integrated into klipper :)
- one for the STM32F030
- one for the HC595 
- one for the mmu

this is a example of the  current config  I use
```
########################################
#
# Configuration for a SKR MINI board with 3 TMC2208 UART
# and 2 1.7A stepper motor at 1/16
# current for a 24V power
#
########################################

[mcu mmu]
serial: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A400YNOC-if00-port0
restart_method: command

[respond]
default_type: command


[hc595 mmu]
mcu: mmu
data_pin: PB15
latch_pin: PB12
clock_pin: PB13

[mmu2]
mcu: mmu
gear_stepper: gear_stepper
#selector_stepper:
idler_stepper: idler_stepper

########################################
#  MMU2S 5mm road with the 5 gears
[tmc2208 manual_stepper gear_stepper]
uart_pin: mmu:PB1
microsteps: 16
run_current: 1.000
hold_current: 0.600
interpolate: True
sense_resistor: 0.110
#stealthchop_threshold: 200

[manual_stepper gear_stepper]
step_pin: mmu:PB4
dir_pin: mmu:PB9  # false pin, led2
# 140 : mk8 gear
step_distance: .007142
# 165 : fystec gear for mmu2s
#step_distance: .00606
velocity: 40
accel: 1500 # same value that your printer accel

########################################
# MMU2S idler with the 5 ball bearings
[tmc2209 manual_stepper idler_stepper]
uart_pin: mmu:PB10
microsteps: 16
run_current: 0.800
hold_current: 0.800
interpolate: True
sense_resistor: 0.110
stealthchop_threshold: 100
diag_pin: ^mmu:PB5 
driver_SGTHRS: 75

[manual_stepper idler_stepper]
step_pin: mmu:PA8
dir_pin: mmu:PB8 #false pin, led1
#enable_pin: mmu:
# 25 step/mm
step_distance: .04
velocity: 100
accel: 500
endstop_pin: tmc2209_idler_stepper:virtual_endstop
homing_retract_dist: 0



## IR extruder switch
[filament_switch_sensor ir_sensor]
pause_on_runout: False
switch_pin: ^P1.26 # E0 DET
event_delay:0.1
runout_gcode:
    M117 Filament not in extruder
insert_gcode:
    M117 Filament in extruder
````

**Comment by KevinOConnor** [comment]
> I tried with SPI, but it doesn't works with the klipper SPI implementation. i think the change are to quick and the HC595 cannot handle them.

The timing info on the TI spec for the hc595 indicates it should be more than fast enough for software spi.  (The stm32f030 isn't a particularly fast chip.)  What configuration/code did you try with software spi?

> I will separate the patch, but before i want just to be sure that i could be integrated into klipper

At a high-level, it seems like a useful feature to me.  So, I don't see a problem with merging once we complete a review.

-Kevin

**Comment by kakou-fr** [comment]
I tried with software and hardware spi. But each time the HC595 lost bit and be not synchronized with the value that i send. 
It only worked when i added some ndelay like this, especially without the ndelay(20000) the HC595 lost  the bit at 30%  : 

```
void hc595_write_bits(struct hc595 *shift_reg, uint8_t oid)
 {
 	//latch off, noop
 	gpio_out_write(shift_reg->latch_pin,0);
 	ndelay(200);
 	//for each bit in reverse
 	for (int ic = ARRAY_SIZE(shift_reg->val) - 1; ic >= 0; --ic)
 	{
 		for (int bit = 7; bit >= 0; --bit)
 		{
 			//set data
 			uint8_t mask = 1 << bit;
 			gpio_out_write(shift_reg->data_pin, (shift_reg->val[ic] & mask) == mask);
 			//clock pulse
 			ndelay(20000);
 			gpio_out_write(shift_reg->clock_pin,1);
 			ndelay(200);
 			gpio_out_write(shift_reg->clock_pin,0);
 			ndelay(200);
 		}
 	}
 	//latch on
 	gpio_out_write(shift_reg->latch_pin,1);
 	ndelay(200);
 	hc595_send_bits_to_host(shift_reg, oid);
 }
```

**Comment by KevinOConnor** [comment]
Okay, thanks.  I think it would be worthwhile to understand why it doesn't work with spi.  If necessary, we can add speed limiting to the software spi implementation.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like it has gone stale.

-Kevin

**Pull request closed without merging**
