### PR TITLE
CONFIG: ADIMlab Add support for LCD knob and caselight

### PR DESCRIPTION
**Pull request by jrahaim**
Added support for knob / Menus

Added support for the LED Case light. defaults on like the original firmware.

Also lowered the heated bed checking to be 1 deg every 2 minutes.

signed-off-by: Jason Rahaim <jason@jasonr.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  A couple of minor comments:
- I think it would be preferable to consistently use the ":" separate in the config file (ie, update output_pin to use that)
- We don't currently support a filament runout sensor.  If you want to document the pin, I think it would be preferable to document just that (ie, "# The filament sensor (pin ar24) is not currently supported").

Separately, there was a PR for the filament sensor (#545).  The primary thing pending with that is verification that octoprint does something sane on repeated filament sensor signals - it needs testing on what happens during a filament change when the sensor may toggle a few times.  If you're willing to do that testing (and everything works fine) then we can move forward on the PR.

-Kevin

**Comment by jrahaim** [comment]
@KevinOConnor Resolved.

**Comment by jrahaim** [comment]
I did some testing on #545  and had some weird behavior with the head bed I didn't have time to narrow down. I reverted any everything was fine. I will try to do some testing this weekend.

**Comment by KevinOConnor** [comment]
Thanks.  I made a slight change to the comment and committed this (commit c7f0d039).

-Kevin

**Pull request closed without merging**
