### PR TITLE
Helper tool for adjusting bed screws and associated documentation

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is a continuation of improvements to the bed levelling documentation.  It adds a document describing the Z_ENDSTOP_CALIBRATE command and the new BED_SCREWS_ADJUST command.  The main document is at: https://github.com/KevinOConnor/klipper/blob/work-bed-screws-20190214/docs/Manual_Level.md

### CODE REVIEW

**Comment by theopensourcerer** [comment]
This sounds like a good idea but I have a comment regarding the documentation of this. I'm a bit confused between the pros and cons, or specific uses of the alternatives such as Z_ENDSTOP_CALIBRATE, TESTZ, PROBE_CALIBRATE, TILT and MESH CALIBRATE. There seem to be several options now which aim to achieve the same ends, e.g. calibrate Z. Perhaps there is a correct order to run these?

Maybe it's just me but I am a bit confused...

**Comment by KevinOConnor** [comment]
Thanks for reviewing.

Simply put, different printers require different calibration tools.  My high level observation is that there are three main categories of bed levelling:
1. delta calibration
2. manual bed levelling (using z endstop switches and bed screws)
3. software bed levelling (using an automatic z height probe) with either bed mesh, bed tilt, or z stepper adjustments

I tried to describe this at https://github.com/KevinOConnor/klipper/blob/work-bed-screws-20190214/docs/Bed_Level.md#choose-the-appropriate-calibration-mechanism .  If you have a better way to word it, then let me know.  (The "software bed levelling" document still needs to be written.)

Things get even more complex, however, as some printers mix the above categories (eg, using bed screws on a delta, doing bed mesh on a delta, printers with both a Z probe and a Z endstop switch, performing one of the software mechanisms with manual "paper test" probing, etc.).  So, ultimately I think each calibration tool needs to have a unique name (ie, a global "G29" or "LEVEL_MY_BED" command is not a good solution).

-Kevin

**Comment by theopensourcerer** [comment]
Ahh - OK I think I'm getting there now then. Perhaps the description of mechanical/manual vs software could be made a bit clearer then. My main machine is a CoreXY with a probe (Piezo) AND an end stop on Z. From what you said above I probably don't really need to be bothered about the BED_SCREW_ADJUST at all then. I do use paper to get the thing pretty level when I have just changed a nozzle for example, but after that I'd simply be using MESH_BED_CALIBRATION and that was it. After reading about these new tools I started trying some of them and my 1st layer was getting worse lol.

**Comment by KevinOConnor** [comment]
FYI, I've merged this code into the master branch.

-Kevin

**Pull request closed without merging**
