### PR TITLE
docs: First version of documentation for Input Shaper tuning

### PR DESCRIPTION
**Pull request by dmbutyugin**
Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by dmbutyugin** [comment]
@KevinOConnor This summarizes the tuning instructions for input shapers.

@BlackStump At this point I put the test model I've created earlier, but you also had some good model. What do you suggest we use for now?

**Comment by BlackStump** [comment]
@dmbutyugin 
I would suggest using your model for consistency.

**Comment by LazaroFilm** [comment]
Spelling error: it should be "on the fly" instead of "on the flight" in the [FAQ about dual carriages. ](https://github.com/dmbutyugin/klipper/blob/56475050d2bb578748ab02ecaac49ee499fc06e9/docs/Ghosting_Compensation.md#is-dual-carriage-setup-supported-with-input-shapers)

**Comment by dmbutyugin** [comment]
@LazaroFilm Yes, thanks, fixed.

**Comment by KevinOConnor** [comment]
Thanks!  Looks great!

Some very minor comments (nothing that would hold up merging):
* What do you think about calling the document Input_Shaper.md ?
* I'd probably start by adding a link to Overview.md .  The link in Config_checks.md is also fine.
* Sometimes the document refers to the resonance as "ghosting" and sometimes as "ringing".  I'd recommend choosing one term and use that throughout the documentation.
* It would be nice to show a define "ghosting" and show a picture of it at the start of the document, just so new users understand what is being discussed.  I can do that though.
* Similarly, it would be nice to show a picture of "smoothing".  Similarly, I can take that on as well.
* The guide does a great job of listing out the steps, including setting max_accel=7000.  But, it doesn't explicitly say to return max_accel and max_accel_to_decel back to their original values.  Would be nice to make that clear up front, as regular printing at accel=7000 is likely to produce bad results.
* I noticed that the guide recommends looking for "corners of the test model still show 'bulges' from disabled pressure advance".  FYI, PA varies dramatically between printers and filament, so I'm not sure one can assume there will be "bulges" when PA is disabled.

Again, I think the new docs look great!

Cheers,
-Kevin

**Comment by dmbutyugin** [comment]
@KevinOConnor I agree with most of your comments and suggestions.

>     * What do you think about calling the document Input_Shaper.md ?

I was thinking that if we add more stuff later (like, adaptive acceleration, not sure if it happens though), then it wouldn't be just about input shapers anymore. Also, Input_Shaper might be too technical implementation detail, and those unfamiliar with input shaping techniques may get confused as to what this is all about. But maybe the current name is not good either, so I could rename it to Input_Shaper.md or something else if there are other suggestions.

 
>     * It would be nice to define "ghosting" and show a picture of it at the start of the document, just so new users understand what is being discussed.  I can do that though.

I can do it, I have some decent pictures. But of course, feel free to add more or replace if you have better examples.

>     * Similarly, it would be nice to show a picture of "smoothing".  Similarly, I can take that on as well.

I can do that too, I would need to print the updated model with more smoothing to show the effect better.

>     * The guide does a great job of listing out the steps, including setting max_accel=7000.  But, it doesn't explicitly say to return max_accel and max_accel_to_decel back to their original values.  Would be nice to make that clear up front, as regular printing at accel=7000 is likely to produce bad results.

This was mentioned once (in line 202 of the main doc file), but it's probably worth mentioning it a few more times - where I say about increasing it, to make sure people wouldn't miss it.


I'll make the proposed changes in the next couple of days.

**Comment by KevinOConnor** [comment]
> I was thinking that if we add more stuff later (like, adaptive acceleration, not sure if it happens though), then it wouldn't be just about input shapers anymore. Also, Input_Shaper might be too technical implementation detail, and those unfamiliar with input shaping techniques may get confused as to what this is all about. 

Okay.  How about Resonance_Tuning.md or Resonance_Compensation.md ?  I suspect most people will find the document from the Overview.md index, so I'm not too concerned about the filename one way or another.

Thinking about it a little more, I fear "ghost" may be a little culturally loaded, and I think maybe "ringing" would be preferable in the text.  Though the choice is yours.

Thanks,
-Kevin

**Comment by Sineos** [comment]
Lol, nice thinking about the word "ghost" @KevinOConnor but you are totally right. "ringing" would be more factual and neutral.

Though when I see my printer's behavior the word "daemon" might be fitting as well ...

**Comment by dmbutyugin** [comment]
@KevinOConnor 

I made pretty much all of the suggested changes. Let me know if you have further comments.

> Thinking about it a little more, I fear "ghost" may be a little culturally loaded, and I think maybe "ringing" would be preferable in the text. Though the choice is yours.

Yep, admittedly I'm not an expert on these things, so I'll trust your judgement. I only added a list of other names for this defect at the beginning of the doc, but I now consistently call it 'ringing' throughout the doc. Hope it's OK.

Separately,
> * It would be nice to define "ghosting" and show a picture of it at the start of the document, just so new users understand what is being discussed. I can do that though.

I realized that my pictures are, perhaps, not the best. Feel free to change them or add more (maybe after the docs are merged).

> * Similarly, it would be nice to show a picture of "smoothing". Similarly, I can take that on as well.

I actually realized that taking a good picture of this effect is quite difficult. Moreover, it is actually not very easy to make a sound judgement whether the smoothing is too much or not from the test print. I decided to modify the test print to have a small gap (0.1 mm in the model) like this:

smoothing-test

Hopefully, this will allow the user to more clearly see how the gap widens when the model is more 'smoothed' as the acceleration increases, for instance. I uploaded the updated model to this PR, and I will print it tomorrow to see if that really helps detecting smoothing. But I was also hoping to get some feedback if that makes sense or not. @BlackStump what do you think about this approach?

After we clear things out regarding smoothing, I think the docs can be merged.

**Comment by dmbutyugin** [comment]
@KevinOConnor I think that trick with the gap should work for checking the smoothing. I tested it on my printer and the results are pretty good in my opinion. So I updated the [selecting max_accel](https://github.com/dmbutyugin/klipper/blob/merge-shaper-docs/docs/Resonance_Compensation.md#selecting-max_accel) section to explain this technique instead.

Further feedback and additional testing for the smoothing is very welcome.

**Comment by KevinOConnor** [comment]
Thanks!  I went ahead and merged this.  I'll give the updated ringing test a try on my printer.

-Kevin

**Pull request merged**
