### PR TITLE
Add power% for M105 response

### PR DESCRIPTION
**Pull request by WindoC**
Some firmware M105 response provided the current power% of the heater.

Example:
ok T:201 /202 B:117 /120 B@:128 @:128
ok T:201 /202 T0:201 /210 B:117 /120 B@:128 @:128 @0:128

Signed-off-by: Antonio Cheong <windo.ac@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
The goal of the legacy g-code support in Klipper is to provide compatibility with popular 3rd party software in their default configuration.  Is there a 3rd party software that requires this output?

-Kevin

**Comment by WindoC** [comment]
This output refers to Repetier-FW. Below screenshot is the result show in Repetier-Server.
Annotation 2019-07-10 100521

**Comment by KevinOConnor** [comment]
Thanks.  It appears that output is specific to Repetier firmware and is not a common M105 response.  For example, it's not listed at all at https://reprap.org/wiki/G-code .  I'm leery of adding custom "enhancements" to legacy g-code commands.  So, I don't think it makes sense for the master Klipper repo to produce that in response to an M105 command.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I'm going to close this PR as it looks like it may not be a good match for the master Klipper repository.

-Kevin

**Pull request closed without merging**
