### PR TITLE
Print from sd card menu folder support

### PR DESCRIPTION
**Pull request by Linusoderlind**
Recursive go through the folders of the virtual SD-card and create a menu that maps to those folders.

Right now it does not do any filtering or sorting

signed off by: Linus Söderlind linus.soderlind@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
The code contained in a python file should not peek into the member variables of classes in other python files.  Otherwise, the code becomes too difficult to maintain.  (There's a blurb on this in the docs/Code_Overview.md file.)  So, I think we should avoid having the menu code directly accessing the file directories and whatnot.  I haven't looked at this in detail, but I'd suggest adding new methods to the virtual_sdcard code (eg, file_list_for_menu() ).

Thanks.
-Kevin

**Comment by Linusoderlind** [comment]
Ok, Thanks for the feedback. I'll look into that.

**Comment by KevinOConnor** [comment]
I'm marking this as inactive.

-Kevin

**Comment by manu7irl** [comment]
@Linusoderlind what about adding only the folder functionality for the lcd menu only?
Can you finish this please?

**Pull request closed without merging**
