### PR TITLE
Configuration for MKS Robin E3 / MKS Robin E3D

### PR DESCRIPTION
**Pull request by kianusch**
config: MKS Robin E3 / MKS Robin E3D

Generic configuration for MKS Robin E3 / MKS Robin E3D - tmc2209 setup.

Signed-off-by: Kianusch Sayah Karadji <kianusch@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Some comments:

If the file is for the robin e3, then I'd name it generic-mks-robin-e3.cfg.  (The comments can explain that it is also a useful starting point for the e3d; I don't think it's necessary to include e3d in the file name.)

All of the printer config files are added to the test cases (test/klippy/printers.test), but this config file would throw errors.

I'm not sure what the EXP3_x aliases are for - the reason for EXP1_ and EXP2_ aliases is to allow users to cut-and-paste an lcd section from config/sample-lcd.cfg, but that wouldn't be possible with EXP3_x aliases.  Also, FYI, the pin 9 of these headers should always be ground - if the board describes pin 2 as ground then it is the board using backwards numbering which should be avoided in our configs.  Similarly, I don't think generic-xxx.cfg files are a good place to describe an lcd display - if there is an "ender2 stock display" that should be described then I'd say use a separate PR to add it to config/sample-lcd.cfg.

Cheers,
-Kevin

**Comment by kianusch** [comment]
Hello,

The board has 10 pins for CR10/Ender3-displays.  The MKS calls it Ender3-EXP1.  And according to the PCB documentation GND is pin2 and 5V is pin1 - it is upside down.  But I'll removed the alias for "EXP3".

I removed/commented out some non-generic lines (position_max).

Thanx
 Kianusch

**Comment by thisiskeithb** [comment]
> And according to the PCB documentation GND is pin2 and 5V is pin1 - it is upside down.

MKS's boards & LCD EXP headers are commonly 180° out from "normal" EXP headers. They've even [created a tutorial](https://www.youtube.com/watch?v=k2Ms2Cl5JFQ) on how to solve the issue when using their LCDs on other boards.

**Comment by KevinOConnor** [comment]
Thanks.  I modified the config so it would pass the test cases and committed this (2ae6c220).  Feel free to submit the sample-lcd.cfg changes as a separate commit.

-Kevin

**Pull request closed without merging**
