### PR TITLE
Filament encoder

### PR DESCRIPTION
**Pull request by MikeTStromberg**
added a module for encoder based filament detection, explanation of differences between encoder and switch, example use in macros.

### CODE REVIEW

**Comment by MikeTStromberg** [comment]
This passes white_check.sh at the local level. not sure what it wants?

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

I also have some high-level comments:
1. There is a large number of whitespace changes to docs/G-Codes.md .  Those types of changes would need to be in a separate pull-request (they should not be mixed with changes that add/update functionality).  That said, in general, it's preferable not to make sweeping whitespace changes.
2. I don't think we should add filament sensor lines to the existing macros in sample-macro.cfg as I suspect the majority of users still do not have one of these devices.
3. It looks like klippy/extras/filament_switch_sensor.py was copied to klippy/extras/filament_encoder_sensor.py and then changes were made to that file.  The intent of filament_switch_sensor.py is that the RunoutHelper class would be reused in future modules.  For example, see how hall_filament_width_sensor.py does this.  I think we'd really want filament_encoder_sensor.py to define its equivalent of a SwitchSensor class (which determines if filament is present or not) and then reuse the existing RunoutHelper code.
4. On new modules, please format the copyright notice at the top of the file in the same layout as the existing modules (one line description, one blank line, one copyright line, one blank line, one license notice line, followed by one empty line).

-Kevin

**Comment by MikeTStromberg** [comment]
Thanks Kevin, I was trying to make it clear that I was riding someone else's coat tails. Good point on the class. I was originally thinking it would be one or the other, and then didn't consider the effect when I realized you would still need both. Changes to come.

**Comment by MikeTStromberg** [comment]
Filament_Encoder_Sensor.py: Allows use of encoder based filament detection.

The name of the class has been changed, and has not inherited the runout helper classs as it's been changed at every level. 
There is nothing left to use from it, hence the change of the class name.

Signed-off-by: Mike Stromberg mtstromberg@gmail.com

**Comment by KevinOConnor** [comment]
What's the status of this PR?  I didn't see a response to my comments at https://github.com/KevinOConnor/klipper/pull/3317#issuecomment-691691295

-Kevin

**Comment by MikeTStromberg** [comment]
All issues you described have been addressed. comments and corrections were 9 days ago.
do you need something else as well?

**Comment by MikeTStromberg** [comment]
_Looks like it's straightened out now._
Filament_Encoder_Sensor.py: Allows use of encoder based filament detection.

The name of the class has been changed, and has not inherited the runout helper classs as it's been changed at every level.
There is nothing left to use from it, hence the change of the class name.

Signed-off-by: Mike Stromberg mtstromberg@gmail.com

**Comment by KevinOConnor** [comment]
I'm not sure what the state of this PR is.  I don't see a response to my comments at https://github.com/KevinOConnor/klipper/pull/3317#issuecomment-691691295 (neither in future comments here nor in the files diff at: https://github.com/KevinOConnor/klipper/pull/3317/files ).

-Kevin

**Comment by MikeTStromberg** [comment]
> I'm not sure what the state of this PR is. I don't see a response to my comments at [#3317 (comment)](https://github.com/KevinOConnor/klipper/pull/3317#issuecomment-691691295) (neither in future comments here nor in the files diff at: https://github.com/KevinOConnor/klipper/pull/3317/files ).
> 
> -Kevin

I've responded often! and both of the last times I've commited, there were no conflicts, but later changes to klipper created new ones. Is this something I have to watch for as the PR ages? It should be good to go again. The sample-macros.cfg file was cleaned up too.

**Comment by KevinOConnor** [comment]
Hi Mike,

Sorry, I did not mean to imply you were not responding.  Just that I did not see an objection to my comments nor has the submitted code addressed them.

This is still the case right now.  Please double check this yourself prior to asking me to review again - you can find your submitted changes at: https://github.com/KevinOConnor/klipper/pull/3317/files and my comments at: https://github.com/KevinOConnor/klipper/pull/3317#issuecomment-691691295

Cheers,
-Kevin

**Comment by MikeTStromberg** [comment]
That's what's confusing me Kevin, There's no conflicts with the latest
commit I did, The white space changes in gcode_macros.cfg have been
removed, and the class name inside the module has also been changed. It's
been signed off as requested, and the attribution is also done as
requested, so I'm at a loss for what you need from me now. Those changes in
your referenced comment are all green now. Just let me know what you object
to and I'll take care of it.

**Comment by jtckendrick** [comment]
Mike,

Item 1: When I look at his comments and the diff on this pull, I see that gcode.md is polluted with whitespace edits.  He is asking not to do this on this pull.

Item 2: I just started using klipper yesterday so I am still reviewing the code.  So I can't offer any support or guidance here.

Item 3: You need to leave the Runout_Helper in the filament_switch_sensor.py and not just copy it.  Use import to gain access to the runout class in the filament_encoder_sensor_class.py.  He stated review the code for hall_filament_width_sensor.py that imports the runout_helper.

Item 4: 

My only other comment would be that instead of using time for an encoded sensor, I would think it would be better served to track filament usage and use the pulse from the encoder to update the distance.  The only thing that has to be monitored as well is retractions pulsing the signal.  Also if you use the pulse from the sensor lets say its 10mm of filament, the encoder versions work as well as a switch they just delay and as long as the distance from the sensor to the extruder gear is greater than the 10mm of length they handle both cases.  

I started looking into this item as I have my filament detection encoded as well.

Thanks for taking on the this task.

Jason

**Comment by jtckendrick** [comment]
Here is something like what I would think.  I will test this tomorrow on mine to see if it works but basically only need to create this file and update the example_extras.cfg as well.

One issue here that I will look into is that it would be more appropriate to also have the encoded length updated during extruder position value changes.  Beginning of print when length is set to 0.  May be other things as well.  I will know more when I try this tomorrow.  This is based on encoders that provide a pulse every so many mm of filament movement.

[filament_encoder_sensor.zip](https://github.com/KevinOConnor/klipper/files/5322689/filament_encoder_sensor.zip)

**Comment by jtckendrick** [comment]
So I tried what I posted and it worked other it triggered at the beginning of the print as I expected.  Tomorrow I will be back at the printer again and will update the code to handle start of print.  I tried both cut filament and jammed nozzle but disconnecting me extruded arm tension.  In both cases system paused accordingly.  When left alone completed a 3 hour print without false triggers.

Jason

**Comment by MikeTStromberg** [comment]
I just moved so I have no access to my pc for a while. If you think yours is better I'll take mine down,  no ego involved here. Works fine for me.  Now if only we could synch it with what klipper is doing, we could go back and pick up where the filament stopped 7mm ago. For the btt sensor that is.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WindoC** [comment]
If you are using a real encoder. Why not use both pin1 and pin2 to get the direction information of it. Just change to use register_rotary_encoder(pin1,pin2,cw_callback, ccw_callback) instead of register_buttons. So you can get the real usage of the filament and compare it to the usage get from toolhead.get_position() or extruder.stepper.get_commanded_position()

**Comment by jtckendrick** [comment]
The device Mike and I are using is single ended.  So it is just a single pin pulse. The device was meant to be able to connect to boards that only have a single input for extruded limit.  But yes if the device provided A/B outputs then definitely the way to go.

Jason

**Comment by MikeTStromberg** [comment]
The position of the extruder and the amount requested from the extruder
don't do any good. This is what *should* be happening, but is not a
reflection of what *is* happening, which is why we are using an encoder in
the first place. The resolution of the encoder dictates how soon we can
determine a problem, but only if we can synchronize with the currently
executing extruder requests at the MCU side. Then we can take the
resolution of the encoder (7mm in the case of the BTT encoder) and know
that if we have no signal when that much filament has been requested,
there's a problem. In a perfect world, we would then raise an event, and
when the print is resumed, go back in time that amount of filament (again
7mm in our ex.) and return the toolhead to that position and pick up where
we left off. None of this seems to be possible right now. Klipper doesn't
seem to have the tools we would need to do this.

That's why my PR includes a document explaining the limitations of such a
sensor and why it only has value to prevent the hotend from burning the
filament, NOT to save the print.

**Comment by jtckendrick** [comment]
In the event of a clogged nozzle the 7mm is lost because the print didn't actually print.  If filament just runs out then as long as the distance from the sensor to the extruder gear is greater than 7mm, the print is usable.  Some prints can be saved with a clogged nozzle, jammed spool, etc with 7mm of filament loss but that depends on so much more.  Plus pause printing finishes out the current path so 7mm to detect plus the usage to finish the current command.  My sensor is set 30mm above the extruder gear for that reason.  Then I have "buffered" filament available in the event of empty spool.

Jason

**Comment by MikeTStromberg** [comment]
Are you saying that it signals when the two rollers touch ie. no filament
in the sensor? I've never checked for that. If it doesn't, then it is
detected the same way a jam is, after an interval of time has passed.

**Comment by WindoC** [comment]
my solution:

[Filament Jam Sensor - Look](https://www.thingiverse.com/thing:3067904)
[filament_jam_sensor.py](https://github.com/WindoC/klipper/blob/ver-after-gcode.py-20200522/klippy/extras/filament_jam_sensor.py)

the main idea is same. But it will only fire the runout(/jam) alert/action when there are extruding actually.

Time = T+0
_timer_handler:
check the stepper position
  jam_triggered = true if the value(position) is not same as last time.

(Normal case)
Time = T+0~1S
_signal_handler: (detected encoder move)
  jam_triggered = false (reset the flag and not to trigger the alarm)

Time = T+1S
_timer_handler:
  found jam_triggered == false and continue the checking of T+0

(runout/jam case)
Time = T+0~1S
_signal_handler: not triggered

Time = T+1S
_timer_handler:
  found jam_triggered == true and execute the jam_gcode

My English isn't very good ...

**Comment by jtckendrick** [comment]
Mike,

The sensor is distance not time because that BTT smart sensor.  It works the same way regardless; however, if the sensor is above the extrusion gear by the sensor detection distance plus some extra length then a filament runout will be detected BEFORE reaching the extrusion gear.  So that means there is no print loss for filament runout.  In the case of blockage, spool stuck, jam of some type that is a loss of extrusion but detected before the whole print finishes.

Also I have tried the code using distance and it is working even at print start.  You don't need to activate it or deactivate in slicing or start / end of print.  You would only need to deactivate it if it fails.  I have tested the ON/OFF of the sensor as well.

Antonio,

Your english is fine.  I understand what you are saying for the case with a fully encoded sensor where there are 2 channels and we know filament direction with that as well sufficient resolution on the encoder to monitor then you decide on a following error and utilize that for filament / jam detection.  The sensor Mike and I are using is only single channel and pulses on 7mm of filament travel.  Depending on the extrusion speed, that length of time between pulses will vary.

Jason

**Comment by tbe** [comment]
Hey @jtckendrick , did you finish your work? I'm very interested in that feature. Any i think so are many others.

**Pull request closed without merging**
