### PR TITLE
lpc176x: New MCU

### PR DESCRIPTION
**Pull request by cruwaller**
Support for LPC176x processors.
  Note: USB stack has some issues and need to be
  solved before "real" use.

Signed-off-by: Petri Honkala <cruwaller@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!

Where did the code from the lib/ directory come from?  I'm not sure that the license on some of those files (eg, lpc17xx_systick.c) is compatible with the GPL.  I like to record the upstream location of the lib files in lib/README, and I'd also like to see if the upstream has any info on GPL compatibility.

I noticed some of the c files in the src/lpc176x/ lack a copyright notice.  Are you okay if I add your copyright and an explicit GPLv3 license statement to them?

**Comment by cruwaller** [comment]
Those /lib -files originally from NXP sample driver library for LPC17xx. Unfortunately original download link is unavailable but fortunately someone has uploaded it to github https://github.com/scottellis/lpc17xx.cmsis.driver.library. 

I am very ok, just go ahead and do what you need to do :)

**Comment by KevinOConnor** [comment]
Unfortunately, I wasn't able to get this to boot.  (I purchased an lpc1768 dev board - not a smoothieboard.)  There were some compile errors, but I think I was able to fix those.  I'm going to see if I can bring up a simple test case with just serial support.

-Kevin

**Comment by KevinOConnor** [comment]
I was able to bring up my LPC1768 test board with just a stripped down serial only setup.  I pushed this code to a new work-lpc176x-20180508 branch.

Some notes:
- for my setup I needed to make sure the linker script placed the image at address 0 (instead of at address 16K).  I'm not sure if this is because I have a test board, and if the real smoothieboards require a different start address.
- I just used the basic CMSIS definitions that I grabbed from the mbed github repo.
- I was able to bring up basic serial console support and toggle pins.  The stepper benchmarks are inline with the other ARM boards.

**Comment by KevinOConnor** [comment]
FYI, I've updated the work-lpc176x-20180508 branch to include serial over USB support.  The code's pretty rough, but basic support seems to work.

Cheers,
-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I've merged my work-lpc176x-20180508 to the master branch.

**Pull request closed without merging**
