### PR TITLE
Add STEPPER_DISABLE gcode command to disable individual steppers

### PR DESCRIPTION
**Pull request by ld3300**
STEPPER_DISABLE extended G-Code for individual stepper disabling

Using command `STEPPER_DISABLE STEPPER=<config_name>` individual steppers can be disabled

Signed-off-by: David Smith <davidosmith@gmail.com>

### CODE REVIEW

**Comment by ld3300** [comment]
Hang on, found a bug, breaks homing if you disable extuder.  Let me figure it out

**Comment by ld3300** [comment]
Okay, this works now, but the list of steppers that require homing is awkward, anyone see a better way to check if a config item needs homing?  Also uncertain how to remove just one motor from the homed list instead of removing them all.  Though that may be a rev2 kind of thing.

**Comment by KevinOConnor** [comment]
Thanks.  FWIW, my recommendation would be to document the command as a "diagnostic and debugging tool" and make no attempt to validate homing.  If a user disables a motor and it breaks something then they get to keep both parts..

-Kevin

**Comment by KevinOConnor** [comment]
Oh, I'd also recommend logging a message that the stepper was manually disabled.

-Kevin

**Comment by ld3300** [comment]
Not validating homing would definitely be easier and does make sense.  Thank you.  When I get a minute I will update that and make sure it is clear in the documentation.  

I'm a little uncertain about the purpose of the levels of logging.  Would this be logging info or logging debug?

**Comment by ld3300** [comment]
I believe that wraps it up

**Comment by ld3300** [comment]
Now I'm really happy with it, a typo or mistake in capitalization won't bring the whole thing to a screeching halt.

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks fine.  One thing I wanted to look at was the possibility of adding a `SET_STEPPER_ENABLE STEPPER=stepper_x ENABLE=[0|1]` type of command.  That is, a debugging command that can either turn on or off the stepper might be useful.  I was hoping to try and mock that up, but if you want to do that, then that's also fine.  Otherwise, I'll get back on this in a few days.

Cheers,
-Kevin

**Comment by ld3300** [comment]
I will see if I can figure that out.  It is interesting though, because giving a move command is all it takes to enable the motor, though I guess that doesn't help if you don't want it to move.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Comment by darrellenns** [comment]
I think there's something a bit weird with the logic. If I start with all steppers disabled, then this works fine:

`SET_STEPPER_ENABLE STEPPER=extruder ENABLE=1` (turns on the extruder motor)
`SET_STEPPER_ENABLE STEPPER=extruder ENABLE=0` (turns off the extruder motor)

However, it does not work if I home all and then try the same command to turn off the extruder motor. Klipper returns 'ok' to the command, but the motor stays on.

**Comment by ld3300** [comment]
Can you do it again and include your log file?

**Comment by darrellenns** [comment]
Here's the log file. Sorry for the delay, I was not able to test on my machine for a few days.

- G28 home all, which turned on the extruder stepper
- SET_STEPPER_ENABLE STEPPER=extruder ENABLE=0
- Observed that the extruder stepper was still holding
- M112 (Emergency Stop)
- Observed that the extruder stepper was no longer holding

[klipper.log](https://github.com/KevinOConnor/klipper/files/4212059/klipper.log)

**Comment by ld3300** [comment]
Can you include the whole log file so I can see your setup and version?  It did log the change, so I need to see what is different, since the same command order does disable for me, I can easily pull filament through.

**Comment by darrellenns** [comment]
[klipper.log](https://github.com/KevinOConnor/klipper/files/4221197/klipper.log)

Here's the full log. I testing using commit 9818055 on the master branch (latest commit at the time of the test).

**Comment by ld3300** [comment]
hmm, i don't see any reason it wouldn't work.  I am also uncertain if the extruder was enabled to begin with.  So when you pull on the filament after the enable=0 you get no give, but after the M112 it does?

**Comment by darrellenns** [comment]
Yes, that's correct. The extruder stepper is enabled (holding) as soon as I do G28. After that, it is not disabled when I do the enable=0 command. I can easily tell, as I have a creality extruder with a knob on the stepper. If I hold the extruder arm in, it releases the filament and I can directly spin the motor by hand. After enable=0, it's still holding solid. After M112, it spins freely.

If I don't home anything, I can turn the extruder stepper on/off with enable=1 and enable=0 as expected. This was confirmed by the same method of directly spinning the stepper by hand.

I do also find it odd that G28 enables the extruder stepper - I'm not sure what the reasoning behind that is. Maybe the homing logic just blindly turns on all steppers, without regard to their function?

Do you have a printer you can repeat the same test (G28 and then enable=0) on?

**Comment by ld3300** [comment]
Yes, I did test that the enable=0 worked after a G28, but I must admit I didn't check to see if the extruder was enabled during G28.  I heated up my hot end and extruded a little before running g28 to make sure it was enabled.  Maybe there is a clue there.

**Comment by ld3300** [comment]
I'm sorry, I have not been able to reproduce the problem.  Everything looks nearly the same between our configs.  My extruder doesn't engage on a G28, can't figure out why yours does, it should only engage motors that have an endstop declared.

**Comment by jayjohns0n** [comment]
You probably have a board where every stepper uses the same enable pin. I had the same problem you need a board where every stepper has his individual enable pin.

**Comment by ld3300** [comment]
> You probably have a board where every stepper uses the same enable pin. I had the same problem you need a board where every stepper has his individual enable pin.

Perhaps I should update the documentation to reflect that.  Are you suggesting a different option?

**Comment by jayjohns0n** [comment]
I don't have any suggestions but it's a good idea to mention it in the documentation.

**Comment by darrellenns** [comment]
FYI - my issue was indeed caused by shared enable lines. I forgot that my board shares X, Y, and E enables (I thought it was just X&Y). If I disable all of them, then the steppers do indeed disable. It might be good to mention in the docs that if steppers share a line, you must disable all the steppers for there to be any effect.

**Comment by ld3300** [comment]
That is interesting, I would have assumed that disabling any of them would have disabled all of them.  Thank you for the info.  I'll try to figure out how to word that.

**Comment by ClockeNessMnstr** [comment]
It looks like the homing update was a problem when the disable stepper commands were created. 

Is there a way to update "printer.toolhead.homed_axes" manually?

**Comment by ld3300** [comment]
@ClockeNessMnstr, are you looking to just tell the printer that it is homed, or manually define a homed positions?

**Comment by ClockeNessMnstr** [comment]
Just looking to tell it that a specific axis is no longer homed.

**Comment by ld3300** [comment]
Back when we implemented this command it was initially intended for the extruder motor, but we concluded that it might as well be applicable to any motor.  Originally considered removing the homing state of the disabled motor, but decided that it is up to the user to maintain homing state, as it is possible to disable and re-enable certain motor configurations without losing home state.  I am not sure what your use case is, but you could use gcode macros to set a homed state variable for x,y,z,etc., and clear that variable if you turn the motor off.  You could then check both the printer homed_axes state as well as your variable to determine if the motor is in a valid state.
You could try writing a value to printer.homed_axes to clear the homing of a motor, but I can't remember if that works.  Unfortunately I'm not in a situation to test it right now.

**Pull request merged**
