### PR TITLE
Add support for board specific pin aliases

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is a proposal to add a module for generic board specific pin aliases.  This also updates a few config files to use these aliases for defining the EXP1/EXP2 lcd display adapter plugs.

It's becoming increasingly difficult to track all the various LCD configurations.  It is hoped that adding aliases may make this a little easier.

@FHeilmann - FYI - this is very similar to your past PR #848.

Feedback welcome.
-Kevin

### CODE REVIEW

**Comment by FHeilmann** [comment]
I think this functionality will make a great addition to klipper.

The only comment I have is that I'm not sure how useful the 'EXP1_9 = <GND>' functionality is. Is there any usecase you intend for this other than having a 'complete' list? Otherwise this just adds more possibilities to screw up during config writing.

**Comment by KevinOConnor** [comment]
Thanks.

> The only comment I have is that I'm not sure how useful the 'EXP1_9 = ' functionality is. Is there any usecase you intend for this other than having a 'complete' list?

The reason I did that is because the EXP1/EXP2 plugs are chaos on a number of boards.  It's often unclear which plug is which and where pin 1 is on each plug.  It seems the only way to really know is to identify the GND/5V/Reset pins and then identify the remaining pins from there.  That's why I wanted to document those pins in the board list.  I couldn't think of a good way to document it so I came up with the <> hack.  I'm open to alternatives.

-Kevin

**Comment by FHeilmann** [comment]
Ok my comment got scrambled, what I meant is

The only comment I have is that I'm not sure how useful the 'EXP1_9 = <GND> ' functionality is.

I like the PR, I just think giving the user the ability to also specify the 5V and GND pins is unnecessary

**Comment by KevinOConnor** [comment]
> I like the PR, I just think giving the user the ability to also specify the 5V and GND pins is unnecessary, much like you wouldn't put the steppers you don't use in your config.

Thanks.  I agree it is unnecessary and I agree it could lead to confusion.  However, I was finding it helpful to document the reserved pins inline with the routed pins.  In particular, some boards (eg, Duet2 Maestro, MKS SBase) don't route all the pins on the EXP1 header, and on many boards it is unclear which pin of EXP1/2 is pin 1.  Providing the full list of pins (reserved and routed) made creating the mappings more obvious.

-Kevin

**Comment by KevinOConnor** [comment]
I went ahead and merged this support.  I agree there could be some confusion with the "reserved pin" declarations - lets see what happens though.

-Kevin

**Pull request merged**
