### PR TITLE
Change M112 to run immediately, also M206 or SET_GCODE_OFFSET with FORCE parameter

### PR DESCRIPTION
**Pull request by rmcbc**
After seen the issue #1037 I solve it with this changes in gcode.py
@pecirep this a new solution more logical for your problem let's wait for @KevinOConnor to review it.

M112 is executed immediately when received.

Also added new parameters to:

M206 [X<offset>] [Y<offset>] [Z<offset>] [FORCE]
SET_GCODE_OFFSET [X=<pos>|X_ADJUST=<adjust>]  [Y=<pos>|Y_ADJUST=<adjust>] [Z=<pos>|Z_ADJUST=<adjust>] [FORCE]

With "FORCE" these commands are also executed immediately.

Signed-off by: Rui Caridade (@rmcbc)

### CODE REVIEW

**Comment by dushyantahuja** [comment]
Like this idea a lot. Would help create proper babystep commands from Octoprint. Currently, the babystep does not work as designed if you don't have a display with buttons connected to the micro-controller.

**Comment by KevinOConnor** [comment]
Thanks.  However, I don't feel this is the right direction.  I think the code should execute commands in the order that they are received.  OctoPrint should be sending commands one at a time, and waiting for an "ok" response to each command.  So, there shouldn't be any gain to handling commands out of order.  (Handling commands out of order adds corner cases that are hard to test and can cause a lot of confusion.)  If OctoPrint isn't sending commands to Klipper one at a time, then I think we should fix that in OctoPrint.

-Kevin

**Comment by pecirep** [comment]
What about the emergency stop? Shouldn't that be executed instantly? Wouldn't be bad for cacelling heatup or cooldown commands either. Send the wrong M109/M190 and you'll have to restart the printer by unplugging it

**Comment by dushyantahuja** [comment]
I would agree with Rui here, commands like emergency stop, babystepping,
etc need to skip the queue. These are exceptions to the rule.

Babystepping commands currently add to the queue and get executed only
after the commands in the queue are emptied. This does not provide the
immediate feedback that you get in Marlin. I used to fine tune the Z height
using babysteps all the time.

I'm most cases, I would agree with Kevin, and as far as I know octoprint
issues commands one at a time only, so there is nothing that needs to
change there.

**Comment by jakep82** [comment]
M112 is already executed instantly. I use it all the time when I make a mistake and need to stop the printer from waiting to reach temp.

**Comment by rmcbc** [comment]
@jakep82 the system that I implemented is faster and more reliable because is execute before entering the cache, if you analyze the code you see that is implemented in the event where all commands are received.
If @KevinOConnor don't approve this change, no worries, I was only trying to help to solve the issue #1037.
I personally don't use baby steps.

**Comment by jakep82** [comment]
I don't use babsteps either.  I just wanted to make it clear that M112 as currently implemented will interrupt M109 and M190.

**Comment by timryder** [comment]
I feel it absolutely needs to be executed instantly. There are certain real-time commands which should act as interrupts and get immediate attention. This Babystep z is one of them.  I can imagine a scenario where you're in a long arc and the updated z offset command on que wouldn't get attention for some time... It should be a firmware level implemented feature.

**Comment by rmcbc** [comment]
My friends, I agree with all, but the last decision is from @KevinOConnor he is the owner of this excellent firmware/software.
So let's respect is decision.

**Comment by KevinOConnor** [comment]
Thanks.  There shouldn't be a g-code queue in practice, so skipping the g-code queue should not have any noticeable impact.  What users are likely seeing is a delay due to moves in the lookahead queue (found in toolhead.py).  However, no firmware (to my knowledge) skips the lookahead queue (nor the g-code queue) for these commands.  And, skipping the lookahead queue would dramatically increase code complexity.

To the best of my knowledge, the M112 command is executed immediately by Klipper.  This is easy to test - just type M112 in the OctoPrint terminal tab.  This is important functionality - we even advise users to run this test directly in the docs/Config_checks.md guide.  If anyone finds this functionality not working, then please open a github issue with the Klipper log file from the event.  @rmcbc - there are some checks on the M112 test in process_data() that are intended to avoid bad behaviour if a user dumps an entire file into /tmp/printer - I don't think these checks would impact the normal case where a user is using OctoPrint (or similar) to feed commands to Klipper.

Cheers,
-Kevin

**Comment by hevilp** [comment]
This feature would be nice.
(rrf handle the babysteps instant)

**Comment by JohnEdwa** [comment]
@KevinOConnor Marlin executes babystepping changes immediately* when you rotate the encoder skipping all buffers (even the 'lookahead' buffer) but they are coming from the LCD and run by the board firmware, not sent as G-code from octoprint. The M206 command itself gets added to the queue just like everything else.  
 
But as the functionality of babystepping is to fine-tune your first layer height in real time while it is being printed (for us without ABL), something in Klipper needs to be able to lift the Z with minimal delay.

* The command it runs is 'thermalManager.babystep_axis(Z_AXIS, babystep_increment);', thermalManager is as the name suggest, responsible for the PID loops for the temperature. So the next time it goes to check those, it notices the babystepping request and fires 'stepper.babystep((AxisEnum)axis, curTodo > 0);' for each axis, which in turn will immediately move the stepper if required.

**Comment by KevinOConnor** [comment]
@JohnEdwa - Okay, thanks for the additional information.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks everyone.  I'm going to close this pull request as I don't feel skipping the gcode queue makes sense (the gcode queue is not the source of the delay - the delay is in the lookahead queue).

-Kevin

**Pull request closed without merging**
