### PR TITLE
Add generic sensors

### PR DESCRIPTION
**Pull request by wizhippo**
This allows setting up sensor for monitor only.  min and max temps are respected and will mcu will go into shutdown if out of range.  This is part of the ADC code.

```
[sensor_generic mosfet_sensor]
# using T2 here so octoprint graphs it as a tool
gcode_id: T2
sensor_type: NTC 100K beta 3950
sensor_pin: analog15
min_temp: 0
max_temp: 80
# setting a target temp will show the desired temp for example in octoprint
target_temp: 60

```

Signed-off-by: Douglas Hammond [wizhippo@gmail.com](mailto:wizhippo@gmail.com)

### CODE REVIEW

**Comment by nettunoroberto** [comment]
I'm sorry, should I add this script to the heater.py file?

**Comment by KevinOConnor** [comment]
Thanks.  My high level comment is that I find the config a bit confusing.  It seems odd to define a "generic heater" that doesn't "heat".  I think things would be more clear if there were a "temperature fan" config section.  As for reducing code, I'd recommend importing modules in python and reusing class modules within the python code.

-Kevin

**Comment by wizhippo** [comment]
That  doesn’t seem right to me either as this case is not to control a fan either.   It is just to monitor a sensor.  I think we should have the ability to setup a sensor on its own.  I went this route though because heater seems to manage sensors along with providing temperature updates in gcode.  Maybe we should add a sensor or generic_sensor class?  Almost feels like we should refactor heater and separate sensors as they are used in many places now outside of heater.

**Comment by wizhippo** [comment]
Maybe break it out something like https://github.com/wizhippo/klipper/commit/40f4070b50e17aa9d00d6a64f020b1acda192bf6

**Comment by KevinOConnor** [comment]
Is the objective to be able to register arbitrary temperature sensors (like we can now register arbitrary heaters)?  If so, I'd add a get_all_sensors() call to heater.py:PrinterHeaters and just add the ability to register a generic sensor much like the existing code registers a generic heater.

-Kevin

**Comment by wizhippo** [comment]
@KevinOConnor That is correct.  Plus in gcode.py return them also in the `get_temp`

**Comment by KevinOConnor** [comment]
I'd say change get_temp() to call the new get_all_sensors() so that it gets all sensors (including ones attach to heaters).

-Kevin

**Comment by wizhippo** [comment]
Looking into adding `get_all_sensors()` there are a few issues:
- sensor does not have a `gcode_id`, This would be needed in `get_temp`
- int heater sensors is a list of factories not sensors
- all sensors would need to implement a `get_temp` and generic sensors would have to handle the `temperature_callback`

Ideas?  Refactor

**Comment by wizhippo** [comment]
Implementation may not be ideal but it is working.

**Comment by KevinOConnor** [comment]
Thanks.  Some high-level comments:
- I agree that renaming add_sensor() to add_sensor_factory() is a good idea.
- I don't understand what heater.py:Sensor() is trying to accomplish.  I suspect this code should be in sensor_generic.py:PrinterSensorGeneric() instead.
- There is no such thing as a "heater gcode id" - there is only a "sensor gcode id".  The gcode.py:set_temp() method should probably be changed to not use get_heater_by_gcode_id() and then neither get_heater_by_gcode_id() nor get_sensor_by_gcode_id() is needed.  (The set_temp() method can call self.heater.lookup_heater() instead.)
- PrinterHeaters.get_all_sensors() should return a list of 2-tuples of the form [(sensor, gcode_id), ...].  The gcode.py:get_temp() method must not peak into other classes member variables.  (This was an error I missed when reviewing commit f6c91503.)

Separately, it would be nice if this was broken up into separate commits as that makes reviewing easier.

-Kevin

**Comment by wizhippo** [comment]
> Thanks. Some high-level comments:
> 
> * I agree that renaming add_sensor() to add_sensor_factory() is a good idea.
> * I don't understand what heater.py:Sensor() is trying to accomplish.  I suspect this code should be in sensor_generic.py:PrinterSensorGeneric() instead.

This sensor code is the same for both generic and could also be used in heaters as they both do temperature smoothing.  I missed a push an maybe you can see the idea.  I have not yet replaced the shared code in heater itself as I was just trying to show the idea.  Let me know if you're ok with this,

> * There is no such thing as a "heater gcode id" - there is only a "sensor gcode id".  The gcode.py:set_temp() method should probably be changed to not use get_heater_by_gcode_id() and then neither get_heater_by_gcode_id() nor get_sensor_by_gcode_id() is needed.  (The set_temp() method can call self.heater.lookup_heater() instead.)

Without self.heater.get_sensor_by_gcode_id('T0') how will be be able to determine which heater the T0,T1 etc belong to?  Just convert to extruder0, extruder1 etc?  Whit if they are are not named extruder in the future and used to set temps on other devices?

> * PrinterHeaters.get_all_sensors() should return a list of 2-tuples of the form [(sensor, gcode_id), ...].  The gcode.py:get_temp() method must not peak into other classes member variables.  (This was an error I missed when reviewing commit [f6c9150](https://github.com/KevinOConnor/klipper/commit/f6c9150349d3ffb364a990132a16afa64c890b2e).)
> 

You mean should be sensor.get_gcode_id() instead of sensor.gcode_id?


> Separately, it would be nice if this was broken up into separate commits as that makes reviewing easier.

I will keep this in mind thanks.

> 
> -Kevin

**Comment by wizhippo** [comment]
> * I don't understand what heater.py:Sensor() is trying to accomplish.  I suspect this code should be in sensor_generic.py:PrinterSensorGeneric() instead.

A bit more clarification regarding the heater.py:Sensor. Sensors like the adc_temperature and others do not have a get_temp() so this has to be implemented somewhere.  Heaters implement this.  The heater.py:Sensor() wraps the sensor drivers to provide the needed get_temp() interface.  Heater could be refactored to use this too instead of duplication the code.

**Comment by wizhippo** [comment]
@KevinOConnor To implement this as you are suggesting with `heater.py:get_all_sensors()` the biggest issue is that a sensor does not have a `get_temp` method that is needed in `gcode.py :get_temp()`.  `get temp()` is implemented in `heater` and not the respective adc_tmperature, spi_temperature, etc..  We will need to wrap those sensors to provide a `get_temp()` or make those sensor provide the get_temp function.  They way the code works with callbacks I think the wrapper may be the better option as it can do smoothing to the temperature like heater does.  How would you like me to approach this?

**Comment by KevinOConnor** [comment]
Unfortunately, I haven't had time to look at this in depth.  My high level thinking was that one could register PrinterSensorGeneric() as the sensor and add the get_temp() method to it.  (Which would also have a temperature_callback() method that just does `self.last_temperature = temp`.)  Unless I'm missing something, a generic sensor would not have a target so just return 0.0?

Separately, due to issue #1288, I'll be looking at changing gcode.py:set_temp().

-Kevin

**Comment by wizhippo** [comment]
So you are thinking the `heater.py:setup_sensor()` would register the Heater, PrinterSensorGeneric, TemeprtureFan, etc as the sensor instead of the sensor driver?

We will have to change a few things such as Heater will have to be created first, then create a sensor, then assign the sensor to the heater.  Or separate `setup_sensor` and add a `register senso`r so `setup_sensor` works as is and `register_sensor` adds it to the list.

I have pushed an example using the second option to register a sensor

**Comment by wizhippo** [comment]
@KevinOConnor I believe it is now more inline with what you were thinking.

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks good to me.  There are a few minor things I noticed:
1. The stats() method is removed from temperature_fan.  I'm fine with removing the stats, but it's not related to this functionality and (if it is desired) should be done in a separate commit.
2. The error handling of set_temp() is not correct (if an invalid Tx parameter is passed it would result in an internal error report instead of an appropriate error).
3. The smoothing of the reported temperature in the heater class was implemented to work around hardware problems on the lpc176x chip.  Ultimately that workaround was insufficient and the root issue was solved with additional lpc176x micro-controller code.  I think it's probably better to remove smoothing than to spread it to other users.
4. The example extras documentation should be expanded.  I don't see a reason to configure a target_temp.

I'll try to separate out the sensor_factory and gcode changes so as to fix issue #1288.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, I committed a series of changes to try and address #1288.  I also did the sensor_factory rename.  Alas, that conflicts with this series, but hopefully it isn't too hard for you to rebase on top of the new changes.

-Kevin

**Comment by wizhippo** [comment]
@KevinOConnor much simpler now with your recent changes.

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks good.  The error handling in register_gcode_sensor() isn't quite right though (it should raise a printer.config_error).  Also, the generic_sensor.py needs a copyright, and I think it would be better named as temperature_sensor.py.

How about the code on the new work-temperature-20190226 branch?  This unifies the config reading of gcode_id and makes some minor changes to temperature_sensor.py.  Let me know if you are okay with the code and/or if you'd prefer your copyright on that file.

https://github.com/KevinOConnor/klipper/commits/work-temperature-20190226

-Kevin

**Comment by wizhippo** [comment]
@KevinOConnor Changes look good.  Go ahead and correct it how you wish.

**Comment by KevinOConnor** [comment]
Okay, thanks.  I merged that development branch into the master branch.

-Kevin

**Comment by wizhippo** [comment]
Thank you,  Sorry about so much back and forth.

**Comment by KevinOConnor** [comment]
Nothing to be sorry about - I appreciate your work on this.

-Kevin

**Pull request closed without merging**
