### PR TITLE
Add Install Script for Debian/Ubuntu Linux

### PR DESCRIPTION
**Pull request by AxMod3DPrint**
module: install-linux.sh

Install script for Debian/Ubuntu. Edited from install-octopi.sh. Added gcc-arm-none-eabi binutils-arm-none-eabi virtualenv buildessential to allow building on a standard debian based linux system 

Compile tested for all supported MCUs 

Signed-off-by: Ax Smith-Laffin - AxMod 3D Print <ax@darknetweb.co.uk>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I don't think we need to add a new script though.  Unless I've missed something, we can just add the additional dependencies to the existing install-octopi.sh script (commit c89983fd).

**Comment by AxMod3DPrint** [comment]
OK, no problem, just a few things I came across when trying to compile for the LPC chip on a fresh-ish system.

python-virtualenv doesn't supply the command virtualenv 
gcc-arm-none-eabi binutils-arm-none-eabi  - wouldn't compile the bin on the LPC without these
build-essential adds common libraries for compiling, not strictly needed, but it's better to have than not.  - note there's a typo in the script for build-essential, seems I missed the error.

 I'll close this off and merge into the octopi script and create another pull request.

**Comment by AxMod3DPrint** [comment]
Derped and closed this off - now merged into install-octopi-sh

**Comment by KevinOConnor** [comment]
FYI, I merged in the additional dependencies as part of my initial review of your pull request - it's in the master branch as commit c89983fd.

Thanks,
-Kevin

**Comment by AxMod3DPrint** [comment]
Ah missed that, all good then ;)

**Comment by hg42** [comment]
@KevinOConnor for some time now, I thought, install-debian.sh would be a better name to describe what it really does.
I guess it may be a question of what systems you want to support.
On the other hand I think it doesn't depend on octopi in any way. Instead it's based on standard debian mechanisms.
The only dependency on octopi seems to be through the versions of packages.

**Comment by AxMod3DPrint** [comment]
@hg42 - you're right there, the script is pretty much more debian based, however, it could cause confusion for people new to Klipper who want to install on a Pi. So I think it would probably be better as `install-debian-octopi.sh`

**Comment by hg42** [comment]
or we could use two scripts ...debian... and ...octopi... where octopi could be a link to debian as long as it is equal.

**Comment by AxMod3DPrint** [comment]
That is true, but adding a file linking to the other is unnecessary, really,  when just renaming the file will serve the same purpose. Less work, less bloat.

**Comment by hg42** [comment]
my main motivation for two scripts are the different target groups
* Octopi is mainly a octoprint distribution for beginners. Those may not even know that it contains Debian.under the hood. So they max need "their" script.
* Debian users may not expect, the more specific "octopi" script is meant for them, too (I noticed that already)

The second motivation is clearly distinguishing the target group from the implementation. It doesn't matter if both scripts are equal when the target groups are different. In case they would start to differ at some point in time, the users can still use "their" script whilr the implementation changes.

But you may be right, a debian script could be used and documenting it in the procedure might be enough.

**Pull request closed without merging**
