### PR TITLE
toolhead: Fixed reporting of the kinematic limits

### PR DESCRIPTION
**Pull request by dmbutyugin**
Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by dmbutyugin** [comment]
@KevinOConnor, moving the conversation from #3381 PR to a separate one. I think it is worth fixing the kinematics limits reporting because:

1. Currently Klipper reports back the parameters from the request, even if it didn't apply them. Then the message is not particularly helpful. I have seen quite some confusion from the users (myself included at first), who believed that their limit was applied. This can be especially problematic if the user wanted to, but forgot to change the limit in their config (or did that but forgot to run RESTART) - they will believe they are doing the right thing without a good way to detect their mistake. So I think it would be great to fix that.

2.  Resonance tester code issues a command to increase the maximum acceleration (and set accel-to-decel = max_accel); here arguably the user didn't request any limit change directly, so it is best to report the actually configured new limits. I was thinking that this can lead to some extra confusion if the user configured, say, max_accel = 5000 because they know this is how much their printer can handle, and then they'll see that max_accel was set to 9000 (which would be 75 * 120), and can freak out with 'My printer will fall apart from this!' thought.

Now why I made the change to `get_status` method: that method is used in logging, AFAICT. If it isn't updated, but this code is changed, this will lead to inconsistent messages in the logs. Please let me know how you think about updating just `SET_VELOCITY_LIMIT` and leaving `get_status` method be. @Arksine please also let me know if you have any additional concerns about changing `get_status` method.

> FWIW, I tend to think of "requested max accel to decel" to be the "real" value, and the internal "trimmed max accel to decel" to be an internal implementation detail. That is, if the requested accel to decel is greater than the max accel, then it doesn't actually impact the print, but it's still a "valid value".

Well, I can see why 'max accel to decel' can be in general viewed as an implementation detail. And TBH I do not have a very strong opinion about `max accel to decel' parameter specifically. However, even though one could use the same argument for the rest of the kinematics limits parameters, along the lines 'trimmed max_accel is an internal implementation detail...', I still think that if a user requested to change a certain parameter (e.g. max_accel, square_corner_velocity, etc.), they had a reason to do that, and if it is not possible to apply that value, it is a good idea to report that one way or the other. E.g. if a user tries to set too high temperature (above the configured limit), this operation will fail and the error message will be printed. Arguably, setting too high max_accel value (above the config) shouldn't be a fatal failure, but reporting the actually applied limit is a useful feedback for the user.

**Comment by KevinOConnor** [comment]
Thanks.  I agree that we should change the reported values to match the actual values for velocity, accel, and square_corner_velocity.  However, I'd say it's probably more clear to always report the requested max_accel_to_decel (and treat the internal value as an "implementation detail").

Note that get_status() is not used in logging.  It's used by the jinja2 templates (menus and macros) and the "webhooks" api server.

Separately, this change is something that I'd look to merge after the v0.9.0 release.

-Kevin

**Comment by dmbutyugin** [comment]
@KevinOConnor Thank, would you agree to merge just a part of the change prior to v0.9 release, specifically reverting the `get_status` part and, if you prefer, to keep logging `self.requested_accel_to_decel` instead of `self.max_accel_to_decel`? Basically, to commit only the following change:
```diff
         msg = ("max_velocity: %.6f\n"
                "max_accel: %.6f\n"
                "max_accel_to_decel: %.6f\n"
                "square_corner_velocity: %.6f"% (
-                   max_velocity, max_accel, self.requested_accel_to_decel,
-                   square_corner_velocity))
+                   self.max_velocity, self.max_accel, self.requested_accel_to_decel,
+                   self.square_corner_velocity))
```
I still think this particular change is very useful, and especially if [resonance_tester] is merged.

**Comment by dmbutyugin** [comment]
> If you wish, I think we could consider that a "bug fix" and merge it prior to the release. If so, please update the PR and I'll merge.

Sounds good, done.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
