### PR TITLE
Fixed build on OSX

### PR DESCRIPTION
**Pull request by lylecheatham**
Made the changes I outlined in #1432, tested the build on Linux and OSX

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Unfortunately, I'm not sure if this will work correctly.

The -T is currently needed, because if one compiles for "avr" then it will create the symbol link `board -> .../klipper/src/avr`.  Then if one changes to compile for "atsam" it wont change that link without the -T (instead it would incorrectly create a new link `board/atsam -> .../klipper/src/atsam`).

The change to check-gcc.sh is possible, however it would require the arm toolset to be installed even when compiling for AVR, PRU, linux, and/or the simulator builds.  Not sure that is desirable.

Not sure what the best way forward is.

-Kevin

**Comment by KevinOConnor** [comment]
Any further comments on this?

-Kevin

**Comment by lylecheatham** [comment]
Ah sorry, got busy with school.

Do you think we could `rm` the symlink (if it exists) before linking the board directory? If you think that would be a valid solution, I'll write it up and put it in this PR.

**Comment by lylecheatham** [comment]
Also an additional problem I spotted that's not related to building on OSX, but related to running on OSX: the `clear_hupcl(fd)` function on line 20 of `klippy/util.py` throws an error on OSX, I'm guessing it's just unsupported or something.

~~~~
Unhandled exception during connect
Traceback (most recent call last):
  File "./klippy/klippy.py", line 137, in _connect
    cb()
  File "/Users/Lyle/Documents/workspace/klipper/klippy/mcu.py", line 609, in _connect
    self._serial.connect()
  File "/Users/Lyle/Documents/workspace/klipper/klippy/serialhdl.py", line 69, in connect
    stk500v2_leave(self.ser, self.reactor)
  File "/Users/Lyle/Documents/workspace/klipper/klippy/serialhdl.py", line 269, in stk500v2_leave
    util.clear_hupcl(ser.fileno())
  File "/Users/Lyle/Documents/workspace/klipper/klippy/util.py", line 23, in clear_hupcl
    termios.tcsetattr(fd, termios.TCSADRAIN, attrs)
error: (22, 'Invalid argument')
~~~~

I did some reading and this seems to be a pretty esoteric feature of hardware serial ports that doesn't have much significance/ is unsupported by modern usb to serial chips, and that's not even counting the fact that many chips are just USB CDC and never even go to a hardware serial layer.

**Comment by KevinOConnor** [comment]
I think an "rm" prior to the "ln" would be okay.

I think it should be okay to catch an exception from clear_hupcl() and ignore it.

-Kevin

**Comment by lylecheatham** [comment]
Made both of those changes, used an `rm -f` so that if the link doesn't exist we don't throw an error. Additionally did a `chmod +x` on `klippy.py`, let me know if there's a reason it isn't that way, it just makes my testing a few keystrokes faster

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me except for the changes to check-gcc.sh (see my comments above).  If you want to separate that change out, I'll go ahead and commit the other changes.

-Kevin

**Comment by lylecheatham** [comment]
Undid those changes. Sorry for the latency, just started a new job!

**Comment by KevinOConnor** [comment]
Thanks.  I merged the commits and then broke them up into two commits (f7cb0875 and 1235972b).

-Kevin

**Pull request closed without merging**
