### PR TITLE
tmc2208: Decode register fields in DUMP_TMC

### PR DESCRIPTION
**Pull request by lorf**
Report decimal values for some of the TMC2208 register fields in
DUMP_TMC command if DECODE parameter is given. This helps in tuning and
diagnostics.

Sample output:
```
Send: DUMP_TMC STEPPER=stepper_a DECODE=1
Recv: // GCONF:          000001c4
Recv: // - I_scale_analog(ext VREF): 0
Recv: // - internal_Rsense:          0
Recv: // - en_spreadCycle:           1
Recv: // - shaft (inverse rot dir):  0
Recv: // - index_otpw:               0
Recv: // - index_step:               0
Recv: // - pdn_disable:              1
Recv: // - mstep_reg_select:         1
Recv: // - multistep_filt:           1
Recv: // - test_mode:                0
Recv: // GSTAT:          00000001
Recv: // - reset (driver was reset): 1
Recv: // - drv_err (error shutdown): 0
Recv: // - uv_cp (undervoltage):     0
Recv: // IFCNT:          00000066
Recv: // OTP_READ:       0000000d
Recv: // IOIN:           20000348
Recv: // - ENN pin:                  0
Recv: // - MS1 pin:                  0
Recv: // - MS2 pin:                  1
Recv: // - DIAG pin:                 0
Recv: // - PDN_UART pin:             1
Recv: // - STEP pin:                 0
Recv: // - SEL_A (driver type):      1 (TMC220x)
Recv: // - DIR pin:                  1
Recv: // - VERSION:                  0x20
Recv: // FACTORY_CONF:   0000000d
Recv: // - FCLKTRIM:                 13
Recv: // - OTTRIM (overtemp trim):   0 (OT=143C, OTPW=120C)
Recv: // TSTEP:          000fffff
Recv: // MSCNT:          0000038c
Recv: // - MSCNT A (position A):     908
Recv: // - MSCNT B (position B):     140
Recv: // MSCURACT:       00bb015f
Recv: // - CUR_A (current A):        -161
Recv: // - CUR_B (current B):        187
Recv: // CHOPCONF:       13030053
Recv: // - toff (slow decay time):   3 (108/fclk)
Recv: // - hstrt (start hysteresis): 5 (offset 3)
Recv: // - hend (end hysteresis):    0 (offset -3)
Recv: // - TBL (blank time):         2 (32/fclk)
Recv: // - vsense(high sensitivity): 1
Recv: // - MRES (microstep res):     3 (32 usteps/step)
Recv: // - intpol (interpolation):   1
Recv: // - dedge (double edge):      0
Recv: // - diss2g (short to GND protect off): 0
Recv: // - diss2vs (low side short protect off): 0
Recv: // DRV_STATUS:     80130080
Recv: // - otpw (overtemp warning):  0
Recv: // - ot (overtemperature):     0
Recv: // - s2ga (short to ground A): 0
Recv: // - s2gb (short to ground B): 0
Recv: // - s2vsa (low side short A): 0
Recv: // - s2vsb (low side short B): 0
Recv: // - ola (open load A):        0
Recv: // - olb (open load B):        1
Recv: // - t120 (120 C reached):     0
Recv: // - t143 (143 C reached):     0
Recv: // - t150 (150 C reached):     0
Recv: // - t157 (157 C reached):     0
Recv: // - CS_ACTUAL(current scale): 19
Recv: // - stealth (stealthChop):    0
Recv: // - stst (standstill):        1
Recv: // PWMCONF:        c80d0e24
Recv: // - PWM_OFS:                  36
Recv: // - PWM_GRAD:                 14
Recv: // - pwm_freq:                 1 (2/683 fclk)
Recv: // - pwm_autoscale:            1
Recv: // - pwm_autograd:             1
Recv: // - freewheel (brake mode):   0 (normal)
Recv: // - PWM_REG:                  8
Recv: // - PWM_LIM:                  12
Recv: // PWM_SCALE:      00000016
Recv: // - PWM_SCALE_SUM:            22
Recv: // - PWM_SCALE_AUTO:           0
Recv: // PWM_AUTO:       000e0024
Recv: // - PWM_OFS_AUTO:             36
Recv: // - PWM_GRAD_AUTO:            14
Recv: ok
```

Signed-off-by: Dmitry Frolov <dmitry.frolov@gmail.com>

### CODE REVIEW

**Comment by lorf** [comment]
Good idea! I'll try to modify the code to work that way, thanks.

**Comment by FHeilmann** [comment]
@KevinOConnor one thing we'll have to think about is what we do with registers that have multiple layouts. the TMC2660 has some registers that have different layouts depending on the values of some other bits. Also, there is one instance where the value of a parameter is split across two non-adjacant bitfields (see comment after [this line](https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/tmc2660.py#L112).

Otherwise I like this change a lot!

**Comment by KevinOConnor** [comment]
FYI, the tmc2208 has a similar overloading of register values for the IOIN field (the tmc2224 has a different layout than the tmc2208 for this register, and one can identify which layout is used by the "SEL_A" field).  One possible way to handle this would be to make "virtual" registers and have the high level code select the appropriate virtual register when necessary - for example: `if reg_name == 'IOIN' and tmc2130.get_field(Fields, "IOIN", "SEL_A", val) == 0: tmc2130.pretty_format(Fields, "IOIN#tmc2224", val)`

-Kevin

**Comment by lorf** [comment]
Based on Kevin's prototype I added field mappings for registers, added optional field descriptions and functions to get string representation of a field value. The IOIN register uses correct mapping based on driver type. Here is the sample DUMP_TMC output:

```
DUMP_TMC stepper_a
GCONF:          000001c4 I_scale_analog (current setting) = 0 (internal), internal_Rsense = 0, en_spreadCycle = 1, shaft (rotation direction) = 0 (normal), index_otpw = 0, index_step = 0, pdn_disable = 1, mstep_reg_select = 1, multistep_filt = 1, test_mode = 0
GSTAT:          00000001 reset = 1, drv_err = 0, uv_cp = 0
IFCNT:          00000036 IFCNT = 54
OTP_READ:       0000000d OTP_FCLKTRIM = 13, otp_OTTRIM = 0, otp_internalRsense = 0, otp_TBL = 0, OTP_PWM_GRAD = 0, otp_pwm_autograd = 0, OTP_TPWMTHRS = 0, otp_PWM_OFS = 0, otp_PWM_REG = 0, otp_PWM_FREQ = 0, OTP_IHOLDDELAY = 0, OTP_IHOLD = 0, otp_en_spreadCycle = 0
IOIN:           20000149 ENN = 1, MS1 = 0, MS2 = 1, DIAG = 0, PDN_UART = 1, STEP = 0, SEL_A (driver type) = 1 (TMC220x), DIR = 0, VERSION = 32 (0x20)
FACTORY_CONF:   0000000d FCLKTRIM = 13, OTTRIM (overtemp trim) = 0 (OT=143C, OTPW=120C)
TSTEP:          000fffff TSTEP = 1048575
MSCNT:          0000004c MSCNT = 76
MSCURACT:       00dc006f CUR_A = 111 (111), CUR_B = 220 (220)
CHOPCONF:       13030053 toff = 3, hstrt = 5, hend = 0, TBL = 2, vsense (sensitivity) = 1 (high), MRES = 3 (32 usteps/step), intpol (interpolation) = 1, dedge (double edge) = 0, diss2g (short to GND protect off) = 0, diss2vs (low side short protect off) = 0
DRV_STATUS:     80130000 otpw (overtemp warning) = 0, ot (overtemp error) = 0, s2ga (short to ground A) = 0, s2gb (short to ground B) = 0, s2vsa (low side short A) = 0, s2vsb (low side short B) = 0, ola (open load A) = 0, olb (open load B) = 0, t120 = 0, t143 = 0, t150 = 0, t157 = 0, CS_ACTUAL (current scale) = 19, stealth = 0, stst (standstill) = 1
PWMCONF:        c80d0e24 PWM_OFS = 36, PWM_GRAD = 14, pwm_freq = 1 (2/683 fclk), pwm_autoscale = 1, pwm_autograd = 1, freewheel (brake mode) = 0 (normal), PWM_REG = 8, PWM_LIM = 12
PWM_SCALE:      00000016 PWM_SCALE_SUM = 22, PWM_SCALE_AUTO = 0 (0)
PWM_AUTO:       000e0024 PWM_OFS_AUTO = 36, PWM_GRAD_AUTO = 14
```

I think it will be more accurate if fields will be on separate lines. Or I can make the output shorter and omit descriptions and string representations.

**Comment by lorf** [comment]
Also, is it worth to convert register to object? Maybe to be able to write `stepper.tmc.CHOPCONF.toff(3).hstrt(5).commit()` or `stepper.tmc.PWM_AUTO.read().PWM_GRAD_AUTO()`?

**Comment by KevinOConnor** [comment]
Thanks.  There's one error in the code that would need to be fixed before merging - the Fields global variable must not be modified (both because modifying global variables could break the RESTART command and because it's technically possible for a user to have both tmc2208 and tmc2224 drivers in the same machine).  My suggestion would be to perform the IOIN test within the loop in cmd_DUMP_TMC().

Separately, FWIW, it should be possible to avoid using collections.OrderedDict() - pretty_format can just sort the fields by bit mask.  That may make the fields tables a little more readable.  It's not something that would stop merging though.

In my opinion, object wrappers would add more complexity, so I suspect it would be a net loss.

-Kevin

**Comment by KevinOConnor** [comment]
> I think it will be more accurate if fields will be on separate lines. Or I can make the output shorter and omit descriptions and string representations.

FWIW, I'd say omit the field descriptions, don't bother printing fields if they are zero, and remove the spaces around the equal sign.

I think, in practice, one will need to have the tmc spec handy to gather any meaning from the fields so I'm not sure the descriptions (though nice) add much.

Again, though, this wouldn't stop merging.

-Kevin

**Comment by lorf** [comment]
OK, will follow your suggestions. Give me a couple of days.

**Comment by lorf** [comment]
Here it is with IOIN selection fixed and simplified as You suggested, ready to merge if there will be no objections.

```
DUMP_TMC stepper_a
GCONF:          000001c4 en_spreadCycle=1 pdn_disable=1 mstep_reg_select=1 multistep_filt=1
GSTAT:          00000001 reset=1
IFCNT:          00000006 IFCNT=6
OTP_READ:       0000000d OTP_FCLKTRIM=13
IOIN@TMC220x:   20000149 ENN=1 MS2=1 PDN_UART=1 SEL_A=1 VERSION=32
FACTORY_CONF:   0000000d FCLKTRIM=13
TSTEP:          000fffff TSTEP=1048575
MSCNT:          00000044 MSCNT=68
MSCURACT:       00e10064 CUR_A=100 CUR_B=225
CHOPCONF:       13030053 toff=3 hstrt=5 TBL=2 vsense=1 MRES=3 intpol=1
DRV_STATUS:     80130000 CS_ACTUAL=19 stst=1
PWMCONF:        c80d0e24 PWM_OFS=36 PWM_GRAD=14 pwm_freq=1 pwm_autoscale=1 pwm_autograd=1 PWM_REG=8 PWM_LIM=12
PWM_SCALE:      00000016 PWM_SCALE_SUM=22
PWM_AUTO:       000e0024 PWM_OFS_AUTO=36 PWM_GRAD_AUTO=14
```

**Comment by KevinOConnor** [comment]
Thanks!

Note that using "is" to compare a string in python isn't safe - depending on what the interpreter does, it may or may not work correctly.

Also, FWIW, I did think the value translations from your previous patch were useful (just the field descriptions seemed a bit verbose).  I think it might be possible to define all the value translations in a single table - I'll try to prototype something.

-Kevin

**Comment by KevinOConnor** [comment]
FYI - I pushed the idea I had for the value formatters up to the work-tmcfields-20190127 branch (commits cd916fa4 and 77e1899b).  Do you still have the code with the value formatters you previously wrote available?

-Kevin

**Comment by lorf** [comment]
Yes, old code is here https://github.com/lorf/klipper/tree/tmc2208-decode-old. I'll add the formatters based on your prototype. One note - in my opinion, the formatted value should not replace the numerical value, but be added to it to prevent confusion, e.g.:
```
MRES=3(32usteps)
```
but not
```
MRES=32
```

**Pull request merged**
