### PR TITLE
New target STM32F0

### PR DESCRIPTION
**Pull request by Delsian**
The main goal of porting Klipper firmware to tiny Cortex-M0 chips is creation of distributed controller architecture.
Possible to use nanoboards with, for example, one ADC and two power switches to create multi-head printers. Each print head requires only 4 wire (power and signal) and can control heater and fan individually.
Additionally - CAN bus looks better in intermodule communication than USB (and takes less space)

Current state: few boards with STM32F042 working together over CAN and serial, GPIO works, ADC in progress, SPI/I2C/HWPWM will be soon.

Board schematics and PCBs will be available soon on circuitmaker.com portal. For debug/testing possible to use NUCLEO-F042K6 board https://www.st.com/en/evaluation-tools/nucleo-f042k6.html , current Makefile version supports flashing and debugiing with on-board programmer.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!  It's going to take me a few days to look through this.  It's great to see support for it.

-Kevin

**Comment by Delsian** [comment]
Also, I'll be glad to get help with documentation from any people with native English, my English level pretty poor yet.

**Comment by Delsian** [comment]
Last commit contains some important fixes, now ADC working fine, so only SPI/PWM commits required

**Comment by Delsian** [comment]
Fixed rare race condition when CAN and USB boards working together.

**Comment by KevinOConnor** [comment]
Thanks.  I got a chance to look through this.  In general, it looks good.  I do have some comments:

- The lib/README file will require an update to document the source of the additional files in the lib/ directory.  It would be nice if one commit contained all the lib/ updates separate from the main Klipper code additions.
- It would be preferable to use the existing cmsis files in cmsis-core/ instead of adding an additional copy in cmsis-stm32f0/
- I think the timer code could be simplified quite a bit by using generic/timer_irq.c.  See src/atsamd/timer.c for an example (or take a look at any of the many example timers in the code tree at 55df8bf5).
- Can you provide some details on what the fault handler and logging stuff does?

Of the comments above, only the lib/README update is a prerequisite to merging (other comments can be addressed if needed after merging).

Separately, I may end up merging #1388 which will conflict with your pins.py changes.

-Kevin

**Comment by Delsian** [comment]
see PR #1422 for details

**Pull request closed without merging**
