### PR TITLE
Add Klipper architecture schematic

### PR DESCRIPTION
**Pull request by PRouzeau**
ADD KLIPPER ARCHITECTURE SCHEMATIC

Source file is in Libre Office Draw
PNG Images attached are the Libre Office output.

Signed-off by: Pierre ROUZEAU

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Very nice.  How did you see this fitting in with the rest of the Klipper documentation?

-Kevin

**Comment by PRouzeau** [comment]
This is a rework of what I have done for Duet/RRF and I initially created that for the main RRF presentation page on RepRap Wiki (this was done before manufacturer creates documentation on the DuetWiFi site), in first paragraph 'using firmware' as you can see here: http://reprap.org/wiki/RepRap_Firmware. Yet there is no 'operation' page in the Klipper doc so it can go in the Features pages but I think some description of operation is needed. 
I also  think a 'table of content' page shall be created linking to other pages/images, as there is no links in the doc. I know that GitHub have a wiki functionality which can be useful for documentation, but I have no idea how this work. 

Just a note, you have given a name 'Klippy' for the main python program which is nice, and I think giving another name to the board firmware part will help, better than a tag or referring to the 'MCU firmware part'. 

Did you have comment or is there any inaccuracy ? (I have not yet tested Klipper for miscellaneous reasons, so that was only theoretical analysis).

**Comment by KevinOConnor** [comment]
Thanks.  It looks nice and seems accurate to me.  My only comment would be that it may be trying to convey too much information in one picture.  For example, the information on the virtual_sdcard could be dropped to simplify things.

I too am unfamiliar with the mechanics of the github wiki system.  I'm leery of using a wiki though, as I've found them to not work well in other projects of similar size.  (Over time the content becomes stale, contradictory and misleading.)

I'm still trying to think of a good place to integrate the image.  I think the Features document would work if it was simplified a bit.

-Kevin

**Comment by PRouzeau** [comment]
Agree that it was a bit too much info in one drawing, so I divided in three different schematics
- Architecture2 
- Connectivity
- Virtual SD card

What I find very good in a wiki is the easiness of page creation and interlinking. Short page are better and a lot of interlinks allow reader to follow own mind path, not the one decided by the writer. Other tools than wiki can offer these functionalities. What is missing mostly in wiki is formal update and translation tool (translations are a nightmare to maintain when not linked to a formal update).
For the rest, I think update is mostly not related to the used tool but that it is difficult to constrain oneself to the tedious task of re-reading regularly docs. When maintaining a doc, you have to read it again and again.

**Comment by KevinOConnor** [comment]
Thanks, and sorry for the delay in responding. The pictures look nice, but I don't have a good idea for where to add them to the existing documentation.  I think there should be a reference to them from one of the markdown (.md) files before committing to the repo.  Also, the commit message should have a signed-off-by line (as described in https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).

**Comment by wesc23** [comment]
Please add this to the docs.   I spent a long time yesterday googling to find an overview of how everything is connected.   All this may be obvious to someone already using klipper, but for someone new to the project it would be of great help.

**Comment by KevinOConnor** [comment]
Thanks.  I'm going to close this as it looks like the conversation has concluded on it.

-Kevin

**Comment by PRouzeau** [comment]
And ? 
Were these images added to the docs, and if yes, where?
if no, why ?

**Comment by KevinOConnor** [comment]
I apologize, but no, they were not added.  I don't know of a good place to add them to the documentation.  I wanted to update the ticket though, as it's been in basically the same state for 2 years.

-Kevin

**Comment by PRouzeau** [comment]
wesc23 suggested to add it in the Readme. That could be the most synthetic presentation of what is Klipper, without diving in a text.

**Comment by KevinOConnor** [comment]
The documentation is now primarily hosted at https://www.klipper3d.org/ .  So, the images would need to be integrated into the documentation and style of that website.  It's not an easy task, but it's great if someone wishes to undertake that.  I'd suggest starting by proposing the page on the website and provide a mock up of what that page will look like.

I'll add the "inactive" label as I agree this ticket isn't really "closed".

-Kevin

**Comment by PRouzeau** [comment]
These images are entirely self-supporting:
- They have a title
- All explicative text is included in the image
You don't even need to add one line of text or any paragraph title, just create a page 'Klipper architecture', and add the three images (full screen width):
- Architecture 2
- Connectivity
- Virtual sd card 
one after the other with just a separating line between the images.

I really don't get the difficulty to incorporate a schematic in documentation when whole text is included in.

**Pull request closed without merging**
