### PR TITLE
skew_correction:  Software based printer skew compensation

### PR DESCRIPTION
**Pull request by Arksine**
This is a port of Marlin's skew correction algorithm.   It uses the stacked gcode transform implementation from #1243.  @KevinOConnor, if you prefer to merge that commit yourself, I can drop that commit from this pull and rebase on top of it.

Currently this module only supports cartesian and corexy kinematics.  I think that delta support is can be easily added in a separate pull request where those with delta printers can test it.   My current method for fetching the minimum and maximum reachable X,Y coordinates from the configuration is a workable temporary solution, but a more robust solution would be to have a function in the Kinematics class that returns those values for X, Y, and Z (although this module doesn't need Z).

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks good to me.  Some comments:
- I think the set_move_transform() call should be done in a "klippy:connect" handler.
- I'm not sure about the pictures in the docs - do we have permission to redistribute them?  I'm not sure we want to have large "Prusa" logos in the main Klipper docs.
- FWIW, the _check_pos_range() calls don't look correct to me.  It looks like they could cause discontinuous jumps in some outlier regions.  Which would certainly be startling, and If it occurred during a print it would almost certainly cause the print to be corrupted.)  Is this just a leftover from Marlin (which lacks the ability to move without transforms)?  I would have thought that always applying the transformation would be simpler and less error prone.

-Kevin

**Comment by Arksine** [comment]
I'll fix set_move_transform and change the pictures.  I'll try to find something open source with no branding and get permission from the author, or I'll just skip the visual examples and hope that the explanation is good enough.

The _check_pos_range is ported from Marlin.  I don't think the 1mm minimum offset is absolutely necessary, however I think a slightly modified object at the edge would be preferable to Klipper raising an error if the correction applied moves the tool out of bounds.

**Comment by Arksine** [comment]
I went ahead and removed the skew examples from skew_correction.md for now, if it seems necessary to add them back I'll just model something in Fusion myself for the example. 

I made the changes to skew_correction.py, including the removal of _check_pos_range().  I'll test it as soon as I get and chance, and if everything seems to work ok I'll squash the commits for merging.

**Comment by Arksine** [comment]
@KevinOConnor After initial testing I have discovered that by using the "klippy:connect" event handler in place of "handle:ready", the call to set_move_transform() returns None.  I presume this is because the gcode class doesn't assign its  toolhead attribute until "handle:ready" fires.  Would it be okay if I switched skew_correction's event back to handle_ready?

**Comment by KevinOConnor** [comment]
Oops.  Yes, sorry for the confusion.  (The gcode.py code probably should be looking up the toolhead from "klippy:connect", but that's a separate issue.)

-Kevin

**Comment by Arksine** [comment]
Okay, tested with and without bed_mesh enabled.  It works as it should, with the caveat that a correction can result an out of bounds error if the tool moves too close to an edge.  Any easy workaround for people with positive skew is to simply set position_min and position_endstop to a slightly negative value on X and/or Y.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Pull request merged**
