### PR TITLE
Adding folder support to the virtual SD card

### PR DESCRIPTION
**Pull request by Linusoderlind**
Adding folder support to the virtual SD card.

The files are just listed with the folder as a part of the name.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Does OctoPrint do the "right thing" with these files?  (I didn't think OctoPrint supported directories.)

-Kevin

**Comment by Linusoderlind** [comment]
I forgot to check Octoprint, 

I have checked printing from the Octoprint terminal and from the display.

I will check when I get back home.

/Linus

**Comment by Linusoderlind** [comment]
OctoPrint supports folders in it's upload folder without problems.

One thing that looks a bit odd is when starting a job the file name includes the folder name:
image
If I start the same file from OctoPrint the folder name is not included. But that's only cosmetic and I am sure that it can be changed. 

The Klipper display and menu supports it with this pull request but its not pretty.  
The files located in folders gets name like: folder\file.gcode that has to scroll if they are long.

I plan on adding proper folder support for the menu next. So that each folder gets its own sub menu.

**Comment by KevinOConnor** [comment]
Thanks.  I'm not sure about the changes to the M20 command.  The reprap documentation ( https://reprap.org/wiki/G-code#M20:_List_SD_card ) seems to indicate various firmware have different behaviour for directories.  As a high-level comment, I'm leery of chasing weird M314.15 type g-code functionality.  I'd prefer to implement the most basic g-code support and then use "extended commands" (eg, LIST_VIRTUAL_SD_FILES DIRECTORY=a/b ) for enhancements.

Separately, adding directory support to the internal menus is fine and would not be impacted by my observations above.

-Kevin

**Comment by Linusoderlind** [comment]
Ok. Thanks for the input!

My end goal is folder support for the menu and I do not need this to do that.

I will close this PR and open a new one with the menu changes.

**Pull request closed without merging**
