### PR TITLE
spi_temperature: fix MAX31865 temperature conversion

### PR DESCRIPTION
**Pull request by arkeet**
I was testing a MAX31865 chip with Klipper (on a breadboard setup to ensure it works first, config attached below) and noticed some weird measurements. I'm using a 430ohm reference resistor, and first I tested with a 216.5ohm (measured) resistor in place of a real PT100. Klipper was reporting 286.2C. which is inconsistent with a resistance table (which gives 313C for 216.64 ohms). I know the problem isn't the chip because the adc value was 33012 (and 33012/2^16 * 430 = 216.6). (For reference, here is my [printer.cfg](https://github.com/KevinOConnor/klipper/files/5159711/printer.cfg.txt))

As a "real world" test, I stuck a type K thermocouple together with a PT100 (thermocouple read by a Fluke 87V) attached to the MAX31865. In some hot water, the thermocouple reported 81.7, while Klipper said 78.8 at the same time. I also tried blowing hot air on them, and although there was a few degrees variation in the readings, with the thermocouple reading around 245-250 and Klipper reporting 225.

I narrowed down the problem to the adc-to-temp conversion code; specifically, VAL_B has the wrong sign compared to the MAX31865 datasheet (the rest of the code looks fine):
image
After flipping the sign of VAL_B, the reported temperature is correct and Klipper agrees with my thermocouple readings.

So unfortunately it seems that ever since MAX31865 support was added, everyone using it was reading low temperatures (the error is quadratic in the temperature, so negligible at room temp but about 20C low at typical printing temperatures). So this is somewhat of a breaking change (users will have to change their temperature calibration), and I feel that affected users should be notified of it. At least it will make actual temperatures *lower* so it shouldn't be *unsafe* in terms of burning things.

### CODE REVIEW

**Comment by randellhodges** [comment]
I'm guessing this would also impact a PT1000 hooked up to a MAX31865 that has the correct 4.3k reference resistor as well?

**Comment by KevinOConnor** [comment]
Eeks!  I agree that looks like a bug.  I agree we should fix it.  I think we can add a note to Config_Changes.md to help warn about it.

-Kevin

**Comment by KevinOConnor** [comment]
@cruwaller - FYI.

-Kevin

**Comment by arkeet** [comment]
Went ahead and added a note to Config_Changes.md

**Comment by arkeet** [comment]
> I'm guessing this would also impact a PT1000 hooked up to a MAX31865 that has the correct 4.3k reference resistor as well?

Yup, this affects any RTD, regardless of reference resistor.

**Comment by arkeet** [comment]
> I'm guessing this would also impact a PT1000 hooked up to a MAX31865 that has the correct 4.3k reference resistor as well?

@randellhodges Yup, this affects any RTD, regardless of reference resistor.

**Comment by KevinOConnor** [comment]
Thanks!  I committed this fix.  I also committed some simplification of the math on top (commit c69527e2).

-Kevin

**Comment by arkeet** [comment]
For reference, below is a conversion comparing the old erroneous readings to the correct ones. So, for example, if you calibrated your hotend temperature before the fix, you can see how your temperature setting should be adjusted to achieve the same actual temperature.

<details>
<summary>
Table
</summary>

| Old temperature | New temperature |
| ---: | ---: |
| 0 | 0.0 |
| 10 | 10.0 |
| 20 | 20.1 |
| 30 | 30.3 |
| 40 | 40.5 |
| 50 | 50.7 |
| 60 | 61.1 |
| 70 | 71.5 |
| 80 | 81.9 |
| 90 | 92.5 |
| 100 | 103.0 |
| 105 | 108.4 |
| 110 | 113.7 |
| 115 | 119.0 |
| 120 | 124.4 |
| 125 | 129.8 |
| 130 | 135.2 |
| 135 | 140.6 |
| 140 | 146.0 |
| 145 | 151.5 |
| 150 | 157.0 |
| 155 | 162.4 |
| 160 | 168.0 |
| 165 | 173.5 |
| 170 | 179.0 |
| 175 | 184.6 |
| 180 | 190.1 |
| 185 | 195.7 |
| 190 | 201.3 |
| 195 | 206.9 |
| 200 | 212.6 |
| 205 | 218.2 |
| 210 | 223.9 |
| 215 | 229.6 |
| 220 | 235.3 |
| 225 | 241.1 |
| 230 | 246.8 |
| 235 | 252.6 |
| 240 | 258.4 |
| 245 | 264.2 |
| 250 | 270.0 |
| 255 | 275.9 |
| 260 | 281.7 |
| 265 | 287.6 |
| 270 | 293.5 |
| 275 | 299.4 |
| 280 | 305.4 |
| 285 | 311.3 |
| 290 | 317.3 |
| 295 | 323.3 |
| 300 | 329.3 |
| 305 | 335.4 |
| 310 | 341.4 |
| 315 | 347.5 |
| 320 | 353.6 |
| 325 | 359.7 |
| 330 | 365.9 |
| 335 | 372.0 |
| 340 | 378.2 |
| 345 | 384.4 |
| 350 | 390.7 |
| 355 | 396.9 |
| 360 | 403.2 |
| 365 | 409.5 |
| 370 | 415.8 |
| 375 | 422.1 |
| 380 | 428.5 |
| 385 | 434.8 |
| 390 | 441.2 |
| 395 | 447.7 |
| 400 | 454.1 |
| 405 | 460.6 |
| 410 | 467.1 |
| 415 | 473.6 |
| 420 | 480.1 |
| 425 | 486.7 |
| 430 | 493.3 |
| 435 | 499.9 |
| 440 | 506.5 |
| 445 | 513.2 |
| 450 | 519.9 |
| 455 | 526.6 |
| 460 | 533.3 |
| 465 | 540.0 |
| 470 | 546.8 |
| 475 | 553.6 |
| 480 | 560.5 |
| 485 | 567.3 |
| 490 | 574.2 |
| 495 | 581.1 |
| 500 | 588.0 |
</details>

**Pull request merged**
