### PR TITLE
input_shaper: scripts to simulate shaper response and toolhead movement

### PR DESCRIPTION
**Pull request by dmbutyugin**
A couple of scripts that may be useful to simulate input shaper responses at different frequencies
and estimate their positional errors as well as how much they reduce vibrations.

Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by dmbutyugin** [comment]
@KevinOConnor I believe these scripts can be useful, but I'd need your feedback on them. For example, is it useful to have a step input simulation in graph_shaper.py, or does it not belong there? graph_motion.py script is pretty much copied over from your older #2030  pull request, with the supported input shapers added.

**Comment by KevinOConnor** [comment]
Thanks.  As high-level feedback, both scripts seem useful to me, but they appear to be "demo code".  That is, I get the impression that they would only be useful to a developer that is willing to modify the code.  I'm not sure there is much value in committing "demo code" to the master repo.  (As a developer knowledgeable enough to use the scripts could also likely find them on a dev branch.)

We could make the code more robust by making the common options selectable from the command-line.  Not sure if that's worth the effort or not.  How do you envision these scripts being used?

-Kevin

**Comment by Sineos** [comment]
Could these script be potentially extended, e.g. to load accelerometer measurements and simulate the output?

**Comment by dmbutyugin** [comment]
@KevinOConnor,
> As high-level feedback, both scripts seem useful to me, but they appear to be "demo code". That is, I get the impression that they would only be useful to a developer that is willing to modify the code.

Yes, I think your impression is correct. It is probably worth making changes to allow a user to configure the  parameters from the command line. This will also make the scripts more accessible to the users, as right now some things are "hidden" well inside the code.

> I'm not sure there is much value in committing "demo code" to the master repo. (As a developer knowledgeable enough to use the scripts could also likely find them on a dev branch.)

Well, now that we have input shapers integrated, I thought it would be more convenient to have the scripts in one place; similarly to an already existing scripts/graph_extruder.py. It would also be easier to link the script from the documentation.

>  How do you envision these scripts being used?

An experienced user could run them to figure out if the config they have created works for the resonance frequencies their printer has. Or they could use the script to optimize the parameters for the input shaper to cover the frequencies they need.

@Sineos 
> Could these script be potentially extended, e.g. to load accelerometer measurements and simulate the output?

I'm not sure we are quite at that stage. But honestly I hope that at some point we could have a command like

```
TUNE_INPUT_SHAPER AXIS=X RESONANCE_FREQS=35.7,47,52,66.1
```

**Comment by KevinOConnor** [comment]
Okay, I'm fine with merging this.  We can then work on adding command-line options afterwards.  If there are no further comments, I'll look to commit in a few days.

Thanks,
-Kevin

**Comment by dmbutyugin** [comment]
@KevinOConnor 
> We can then work on adding command-line options afterwards.

In principle, I do not mind either way, I was going to do this change soon anyway.

BTW, I've made an excerpt for input shaper documentation suitable to be integrated into Klipper, I'll send a pull request tomorrow probably. I was hoping maybe there will be some conclusion on the gaps that appear under some (still unknown?) conditions between the infill and the perimeters, but it looks like it'll probably take more time. So it is probably better to integrate the docs now, and expand them with the new findings later.

**Comment by KevinOConnor** [comment]
Okay, thanks.  I went ahead and merged.

Integrating the docs now and expanding them later sounds good to me.

-Kevin

**Pull request merged**
