### PR TITLE
Allow STM32F401 boards to use STM32 HID Bootloader

### PR DESCRIPTION
**Pull request by henkyprayoga**
W/o this patch, STM32F401 can't select bootloader offset. This is necessary for scripts/usb-flash.py use STM32 HID bootloader instead of DFU.

I use STM32F401CC board from WeAct Studio. It comes with preloaded HID bootloader. However, the preloaded bootloader is not compatible with HID Bootloader from Serasidis. If anyone else turns out at the same situation, I made some patch on WeAct bootloader so it compatible with klipper flashing mechanism. 

https://github.com/henkyprayoga/WeAct_HID_Bootloader_F4x1/releases/tag/v1.1-stm32-hid-bootloader

Just download the zip and flash it using DFU.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Change looks fine, but it needs a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md 

-Kevin

**Comment by henkyprayoga** [comment]
Done. Thank you.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by xromansx** [comment]
The device is not always detected as HID need multiple time to replug it. changed different cables same issue

**Comment by xromansx** [comment]
compiled the code and bootloader doesn't work led doesn't even light up.

**Pull request merged**
