### PR TITLE
tmc2130: add spi daisy chaining

### PR DESCRIPTION
**Pull request by sensille**
This patch adds the ability to daisy-chain multiple tmc2130 drivers. The
implementation is currently specific to tmc2130, mixing different drivers
in a chain is not possible and would require a higher-level code change.

This is a preliminary version as I'm unsure if my solution fits the overall
code structure and style.

Signed-off-by: Arne Jansen <arne@die-jansens.de>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  As the build tests report, changing bus.py would break other code.

Some high-level thoughts:
* If possible it would be preferable to explicitly list the options instead of parsing options.  So, I'd say avoid parameters like "1/2" - and instead add explicit options like "chain_length" and "chain_position".
* To avoid needing to modify bus.py, one possibility would be to add a "chain_length" parameter to the main tmc2130 instance (the one that defines cs_pin) and then define "main_chip" and "chain_position" parameters in all secondary instances (and if found, not check for cs_pin).  That way, the secondary classes can just lookup the primary tmc2130 class and use its spi class member to transmit messages.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by sensille** [comment]
Sorry, not yet. My other thought was to implement a [bus] section which defines the pins and reference that from all tmc configs, so i don't have a "master" tmc. This also would make it easier to mix different chips in a chain later on. It might take some time until I get to it again, though.

**Comment by KevinOConnor** [comment]
Okay, lets close this for now then.  I can reopen it when you're ready, or you can create a new PR.

Thanks,
-Kevin

**Pull request closed without merging**
