### PR TITLE
filament_switch_sensor:  misc fixes

### PR DESCRIPTION
**Pull request by Arksine**
This pr includes several small fixes to the filament_switch_sensor module:

- The first patch removes a stale toolhead attribute in the BaseSensor class.  Since the toolhead is no longer required by the BaseSensor, its entire handle_ready function could be removed.

- The second a patch appends M400 to the event gcode.  This keeps the BaseSensor's "event_running" attribute set to true until all moves are complete, preventing an additional event from triggering while the printer is responding to the previous event.

- The last patch adds a "TOGGLE_FILAMENT_SENSOR" gcode.  Some users prefer to unload/remove filament while the extruder gears are still moving.   To prevent a runout event from triggering it is necessary that the user manually toggle the sensor off at the  beginning of the unload macro, and back on at the end.

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I'm not sure I understand what the M400 does?  It seems odd to require a pause in the code.

Also, as a minor nit, the "TOGGLE_" prefix on the new command seems odd.  What about SET_FILAMENT_SENSOR?

-Kevin

**Comment by Arksine** [comment]
Hi Kevin.   I have gone ahead and renamed TOGGLE_FILAMENT_SENSOR to SET_FILAMENT_SENSOR.

As for M400, let me attempt to provide an example of current behavior, and why M400 is useful:  

Lets assume you have an unload_filament macro in your `runout_gcode` that retracts 1000mm, but you have an 800mm bowden.  Some users prefer to pull the filament out while the gears are still running.  When the filament passes though the switch it can cause it to bounce, triggering a secondary runout event.  Post-fixing M400 prevents this from happening, as it blocks exec_gcode() from returning until the all moves in the event script are finished.  This keeps the `event_running` attribute set to true, allowing the module to silently ignore all incoming events during that time.

Two alternatives:  

1) Have users add M400 to their scripts themselves, this is what I recommended as a workaround for users currently experiencing this issue.

 2) Increase the default event_delay to something large, like 60 seconds.  This might not be desirable as it would prevent an insert event if you attempt to insert filament within that delay time.

**Comment by KevinOConnor** [comment]
Thanks.

FWIW, I think there exists a third method - the code could note the print_time the script completes at and then reject any new requests that arrive prior to that time.  It's a convoluted method though.

-Kevin

**Comment by Arksine** [comment]
Thanks Kevin.  Actually I like that idea.  Right now the code notes the time the button event is received, then rejects any requests that fall within event_time+delay_time.  It should be simple to just update that variable with the print time after the gcode executes.  I'll play with the idea and do some testing.

**Pull request merged**
