### PR TITLE
add support for per-point z_offsets for gantry leveling with a biased probe

### PR DESCRIPTION
**Pull request by ObviousInRetrospect**
Some probes exhibit repeatable bias at certain bed points. This leads to a repeatable bed skew.
Currently the documentation says if your probe has bias you can't use it (https://github.com/KevinOConnor/klipper/blob/master/docs/Probe_Calibrate.md#location-bias-check).

This PR adds support to specify a per-point z offset to allow such a probe to be used. For example, my inductive probe is off by about 100-150 microns due to magnets in my build plate.

To use:
Determine probe offsets at each of your configured probe points (PROBE_CALIBRATE as described in the doc). Add the Z offset value that PROBE_CALIBRATE returns as a third coordinate to each configured probe point.
You need to do this for all configured probe points if you use the feature.

I also considered a delta at each point instead of an absolute offset but the sign was not intuitive. This approach allows the direct PROBE_CALIBRATE output to be used.

This was tested against 0.8.0 on a Voron 250mm in QUAD_GANTRY_LEVEL only. However, it should work with other leveling modes based on z_tilt.

I also very slightly increased the verbosity of quad_gantry_level to make it easier to copy/paste/run through analysis scripts. Most of the additional output is conditional on having configured per-point z_offsets.

### CODE REVIEW

**Comment by ObviousInRetrospect** [comment]
tests now passing, should look into getting them running locally.

**Comment by KevinOConnor** [comment]
Thanks.

Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

My high-level feedback is that this looks like a useful feature.  However, I think it would be worthwhile to do some "cleanup" before committing.  Specifically, I think the debug statements should be removed before commit.  I also think that it may be worthwhile to refactor the callers of ProbePointsHelper so that they get the final "cooked" value instead of the "value + global_probe_offset - this_probe_offset".  I can help with a refactoring if desired (but I'm not sure when I'll be able to get to it).

-Kevin

**Comment by ObviousInRetrospect** [comment]
I removed more debug output. While I can remove the rest of the new output this feature is only intended to be used when you are working around a particular class of mechanical problem that requires some fine tuning. The initial proposed algorithm in the docs got me from ~0.25mm of skew to about 0.08mm of skew. For me this was the thing that was otherwise going to make me go back to RRF on this printer. To get it down to 0.01 I found the more detailed messages useful to play with the constants.

To the extent that there are temperature effects I actually find it helpful to have the remaining messages that show the offset points both so I can sanity check if my offsets are pushing things in the right direction or not as well as to clearly see what it thinks it is doing and why. Given the level of verbosity in QGL already I think it's potentially worth leaving the parts I haven't removed but if there are specifics you think should go let me know. The moving to point X message is just generally useful when you are staring at it and trying to debug what it is doing.

Around a broader refactoring:
I'm not sure exactly what you are proposing. I thought I was already changing the points that went into result such that any callers would see only cooked points. That was why I did this in ProbePointsHelper instead of in QGL. The other approach I considered was to modify probe itself and to make this a generic probe-coordinate offset that applied to all uses of probe. The two reasons I took the current approach are to avoid the potential for the QGL points and the offset points to get out of sync as well as because I'm very new to this code base, don't yet have a sense of the quality of the test coverage or your patience/bandwidth with reviewing changes that touch more than they need to, and optimized for a change that would not have unintended consequences.

Re signed-off line, is  42229858+ObviousInRetrospect@users.noreply.github.com an acceptable email so I can re-point it in the future or were you looking for a non-github one? (which I don't object to but hadn't decided which one to link). I otherwise have no objection, own all copyrights to the work and for this sort of fairly trivial contribution am also happy to either public domain it or assign it you/the project to simplify licensing.

**Comment by KevinOConnor** [comment]
> Around a broader refactoring:
I'm not sure exactly what you are proposing.

Adding the global_z_offset and subtracting the point_z_offset on the assumption that the caller will add in the global_z_offset looks odd.  Refactoring the callers to make that relationship more clear may make sense (but I'm not sure what the best approach is).

> Re signed-off line,

I'm not sure if you are reporting that https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md is unclear or if you're uncomfortable agreeing to the terms at https://github.com/KevinOConnor/klipper/blob/master/docs/developer-certificate-of-origin .  If it's unclear, let me know what the confusion is.  If you're uncomfortable with the terms (in particular, providing your real name and agreeing to the terms using the convention described in the document) then let me know.  If you wish to discuss it off-line you can email me at kevin@koconnor.net .

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I'm going to close this as it looks like the conversation has concluded.

-Kevin

**Pull request closed without merging**
