### PR TITLE
module: host_temperature

### PR DESCRIPTION
**Pull request by shavrin777**
Replacing rpi_temperature by host_temperature with expanded functionality.
This makes possible to change the path to the temperature sensor.

Signed-off-by: Evgenii Shavrin shavrin0591@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Can you provide some additional information on how you plan to use this extended functionality?  What machine does this work on, and what are the paths a user may configure?

Separately, a non-backwards compatible change like this would require an entry in docs/Config_Changes.md .  If we were to change the name of the module, I would prefer temperature_host.py .

-Kevin

**Comment by shavrin777** [comment]
> Thanks. Can you provide some additional information on how you plan to use this extended functionality? What machine does this work on, and what are the paths a user may configure?
I use it to display CPU temperature. Klipper runs on old laptop based on Intel Atom N450. And default path for RPi doesn't work.
User can specify path to every file that contains temperature in format like "49000" for 49°C.

**Comment by KevinOConnor** [comment]
Thanks.  I made a couple of minor changes and committed this (3d35c003).

-Kevin

**Comment by theopensourcerer** [comment]
@shavrin777 See the discussion here: 

https://github.com/KevinOConnor/klipper/commit/3d35c003db3d4fd25a3cadde1e70373cf450e2f7

It looks like there might be an error in the pull request somewhere.

**Pull request closed without merging**
