### PR TITLE
Add installation script for CentOS

### PR DESCRIPTION
**Pull request by pyr0ball**
There's a few minor differences in the install script for CentOS, which I've included. I can't seem to find the right package names for any of the packages used in the ARM firmware compilers, so that's currently just commented out.

Tested on Centos 7

### CODE REVIEW

**Comment by pyr0ball** [comment]
ack missed a bit.

need to add redhat-lsb-core package

**Comment by pyr0ball** [comment]
aaaand none of the init functions are working still. I'll poke around and see what I can figure out

**Comment by pyr0ball** [comment]
Going to have to switch to systemd service instead of using init.d. CentOS doesn't have extensive lsb init-functions.

currently testing using this method, and will update when done

**Comment by pyr0ball** [comment]
success! Seems to work fine on my machine. Would appreciate someone double-checking for me

**Comment by KevinOConnor** [comment]
I'm fine with adding this script if you've determined that it works.  Some comments:
- In order for me to commit directly, the commit needs to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md
- The script needs some comment updates (it still refers to the raspberry pi) and removal of dead comments / dead code
- On fedora, the arm gcc packages are: arm-none-eabi-gcc-cs arm-none-eabi-newlib

-Kevin

**Comment by pyr0ball** [comment]
Okipokey I'll go make some edits

**Comment by KevinOConnor** [comment]
Thanks.

**Pull request merged**
