### PR TITLE
Added enhanced calibration spreadsheet  tool

### PR DESCRIPTION
**Pull request by vikbessems**
Enhanced calibration spreadsheet tool.

Added enhanced calibration google spreadsheets helper tool.
You can fill in your own measurements and it will auto-generate your terminal commands.
Nothing special but I found it handy for myself. If you find it useful you can add it in.

here is the link to the tool: [enhanced calibration tool](https://docs.google.com/spreadsheets/d/1_ROuHkXpktTF6SVirGQZenKYvMbJCKEZjVS0XCniAMk/edit?usp=sharing)

Signed-off-by: Vik Bessems <vik.bessems@outlook.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Looks nice.  I'm a little leery of having the official Klipper documentation link to an external website, but I do agree that Klipper could do better at obtaining this information from the user.

-Kevin

**Comment by vikbessems** [comment]
No problem, this spreadsheet tool can now be found on klipper.info!
[https://klipper.info/useful-code-links](https://klipper.info/useful-code-links)

**Comment by KevinOConnor** [comment]
Okay, it sounds like you've found a home for this info then.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I think we can close this.

-Kevin

**Pull request closed without merging**
