### PR TITLE
Replicape pru update start scripts

### PR DESCRIPTION
**Pull request by BlackStump**
Updates BBB/Replicape install scripts as it is known BBB kernels have a habit of breaking pru,s 
This update works with 4.14.108-ti kernel unfortunately the 4.19 kernels are broken and I don't know why.
This may help the redeem community changing to klipper.
First pull request so excuse me If I get it wrong

Signed-off-by: Trevor Wilson altocoey@hotmail.com

### CODE REVIEW

**Comment by ProfDrYoMan** [comment]
I can confirm this klipper-pru script works with kernel 4.14-ti in debian buster (10.x).

I did not test this install script, since a got a home grown Klipper install on BBB and buster.

Tried kernel 4.19-ti and even with a lot of investigating I did not get it to work. TI changed something in PRUs again. Seems to be a linkage issue with the PRU code.

Anyhow. This one looks good for me.

Did anybody tryout the install script.

**Comment by BlackStump** [comment]
I have used the install script multiple times, the main changes are in the klipper-pru-start.sh the install-debian.sh is a slight modification if the install-ubuntu-18.04.sh that uses systemd instead of init.d for klipper service
If I had the smarts I would use systemd for the pru,s as well

**Comment by KevinOConnor** [comment]
Thanks.  It looks fine to me.  Does the docs/beaglebone.md document need to be updated?

-Kevin

**Comment by BlackStump** [comment]
yes the docs probably do I have not tested that on earlier images so I would suggest using Stretch instead of Jessie

**Comment by KevinOConnor** [comment]
Okay, thanks.  After a user goes to https://beagleboard.org/latest-images , how will they know which image to download?  That is, how will they know which image contains a 4.14.x-ti kernel and not a 4.19 kernel?

-Kevin

**Comment by ProfDrYoMan** [comment]
Everything version 9.9 right now only uses 4.14 by default. I used the "Debian 9.9 2019-08-03 4GB SD IoT" as base install.

**Comment by BlackStump** [comment]
I agree Kevin that is another issue, There is a part of me that wants to say if you are going to use a Replicape then kernel numbers is something you need to learn, but I think the best option is use
the lastest version that is known to work and specify that image ie Debian 9.9 2019-08-03 4GB SD IoT

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by BlackStump** [comment]
@KevinOConnor  sorry but  install-debian.sh does not have the correct permissions, when executing you get permission denied.
can you fix please?  if fixed locally install comes up as dirty.

**Pull request merged**
