### PR TITLE
Add base ezboard config

### PR DESCRIPTION
**Pull request by th3fallen**
Display is not functional atm but this is enough to get motion and run headless

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks, but the config would need to be updated to match the style and formatting of the existing config.  I added some guidelines for the example configs at: https://www.klipper3d.org/Example_Configs.html

Separately, commits need to have a signed-off-by line for me to directly commit - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by th3fallen** [comment]
I'll fix the formatting in the am but the final commit in the stack is signed off do I need to squash them for you?

**Comment by KevinOConnor** [comment]
Ah - I missed the signed-off-by line in the final commit.  Squashing is always preferred, but otherwise it's fine.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by KevinOConnor** [comment]
It looks like this PR has gone stale.

-Kevin

**Comment by Apulo** [comment]
Can I reopen this PR or should I create a new one. I have the info to add LCD support for the stock Ender/CR-10 display.

**Comment by KevinOConnor** [comment]
Feel free to open a new PR.

-Kevin

**Pull request closed without merging**
