### PR TITLE
MAX6675 WORKING ON BEAGLEBONE AND REPLICAPE

### PR DESCRIPTION
**Pull request by ramezquitao**
MAX6675 WORKING ON BEAGLEBONE AND REPLICAPE

All the necesary code was added to be able to connect to thermocouples (MAX6675) to the SPI bus (in this case SPI1_0 and SPI1_2). The Replicape DTS file had to be modified in order to enable the bidirectional comunication and the 2 SPI ports used to comunicate the thermocouples.

Signed-off-by: Ricardo Amézquita <ramezquitao@cihologramas.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  FYI, it'll be a few days before I'll get a chance to look at this.

-Kevin

**Comment by KevinOConnor** [comment]
I went ahead and merged in your Linux SPI code along with the MAX6675 code (with some minor formatting changes).  Thanks!  These changes (along with the basic thermocouple support) are now on the master branch.  I need to take a closer look at the rest of the changes - I'll try to do that in the coming days.

-Kevin

**Comment by ramezquitao** [comment]
Great. I will install master and check. I'll let you know if I find issues

**Comment by KevinOConnor** [comment]
Any further updates on this?  As I understand it, the thermocouple support got merged, but there were other parts to this change.  My recollection is that there were OS script changes, and some config changes to allow the spi bus to be set.  However, it's not clear to me if those were general changes or something specific to your setup.

Thanks,
-Kevin

**Comment by ramezquitao** [comment]
Hi Kevin

I'm testing the master branch, and the spi temperature is not working in the beaglebone. There are a lot of changes in master compared to the work-thermocouple-20180521 branch. I'm checking what happened.

**Comment by KevinOConnor** [comment]
Okay, thanks.

As for setting the bus and bus speed, I'd suggest adding "bus" and "freq" parameters to the config.  Take a look at klippy/extras/tmc2660.py for an example.

I'm leery of adding DTS files to klipper, as I suspect different users will need to use different DTS files.

I did make changes to the spi_temperature.py code after merging in your changes.  I tried not to break anything - let me know if I messed something up.

Thanks again,
-Kevin

**Pull request closed without merging**
