### PR TITLE
added JSON based temperature sensor to heaters.py

### PR DESCRIPTION
**Pull request by br-edward**
Adds JSON based local file and remote (urllib) sensors to heaters.py

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, this code looks like it could cause internal errors - if the socket reading code were to block, it would cause internal errors in the Klipper host code.  That is, the "event reactor" that Klipper uses can't tolerate arbitrary delays.  In general, we want the host code to aggregate information from the micro-controller code - and do all the timing intensive work in the micro-controller code.

-Kevin

**Comment by br-edward** [comment]
> Thanks. However, this code looks like it could cause internal errors - if the socket reading code were to block, it would cause internal errors in the Klipper host code. That is, the "event reactor" that Klipper uses can't tolerate arbitrary delays. In general, we want the host code to aggregate information from the micro-controller code - and do all the timing intensive work in the micro-controller code.
> 
> -Kevin

Hello, Kevin.

Thanks for your answer, my initial thought was that reactor timers where async non-blocking queue objects. Nevertheless what is the max. execution time (delay) in millis you believe a sensor module is allowed to run for their respective sampling routines? I just now wrote a version where this is limited to 70ms, by timeout handling. Do you suggest a background threading model for the sampling routines instead? That would be easy to implement, as well.

Thanks!

**Comment by KevinOConnor** [comment]
The main host event code shouldn't block for more than a millisecond I'd say.

-Kevin

**Comment by br-edward** [comment]
> The main host event code shouldn't block for more than a millisecond I'd say.
> 
> -Kevin

Which function of the class  `Sensor_ANY` do you consider part of the "main host event code"? What about the reactor timer as queue objects?

**Comment by KevinOConnor** [comment]
All the Python code runs in the Klipper "reactor".  We don't do any blocking IO calls anywhere in the code.

-Kevin

**Comment by br-edward** [comment]
>  We don't do any blocking IO calls anywhere in the code.

Are your sure? I thought on Python2 file IOs are usually blocking calls. Here an example in the existing code: https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/temperature_host.py#L55

**Comment by KevinOConnor** [comment]
The temperature_host.py code is designed to read from a `/sys/` file with the understanding that the Linux kernel would never block on a simple read.

-Kevin

**Pull request closed without merging**
