### PR TITLE
Create printer-creality-cr6se-4-5-3.cfg

### PR DESCRIPTION
**Pull request by cbluoss**
New config for more fun with CR-6 SE and klipper

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Example configs in the Klipper repo should follow the guidelines described at: https://www.klipper3d.org/Example_Configs.html

Also, if you'd like to share a more custom config, we recently introduced a section to the Klipper Discourse server for that ( https://community.klipper3d.org/ ).

-Kevin

**Comment by cbluoss** [comment]
This is very much the 2020 config with updated heater pins for the rev 4.5.3 board (produced since late 2020)

Named the cfg 2021 as most units with this board should be sold since 2021.

**Comment by KevinOConnor** [comment]
Okay - the config is fine, but commits need to have a signed-off-by line for me to commit directly - see https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .

-Kevin

**Comment by cbluoss** [comment]
Any further changes needed?

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
