### PR TITLE
homing: allow to disable homing retract.

### PR DESCRIPTION
**Pull request by cruwaller**
Homing retract can be disabled by setting homing_retract_dist to 0.

Signed-off-by: cruwaller <cruwaller@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I think this is a good idea.  One question - instead of changing the three kinematics class, could we just change homing.py:home() to do something like: if second_home and forcepos==movepos: return

**Comment by cruwaller** [comment]
hmm, good point. I will recheck it.

**Comment by cruwaller** [comment]
I modified the code according to @KevinOConnor proposal.

**Comment by KevinOConnor** [comment]
Thanks.  Looks good.  In order for me to directly commit though, the signed-of-by line needs to have your real name.

**Comment by cruwaller** [comment]
signoff updated.
I removed also the initial commit and replaced by this one.

**Comment by KevinOConnor** [comment]
Thanks.  I committed this change.

**Pull request closed without merging**
