### PR TITLE
Add support base configuration file for MKS Robin Nano V2/Nano V3/SGEN_L V2 and support 48kbit bootloader offset for MKS Robin Nano V3

### PR DESCRIPTION
**Pull request by mks-viva**
Add support base configuration file and 48kbit bootloader offset for MKS motherboard
1. I has add base configuration file for MKS motherboard
generic-mks-robin-nano-v2.cfg for MKS Robin Nnao V2(STM32F103VTE6)
generic-mks-robin-nano-v3.cfg for MKS Robin Nano V3(STM32F407VGT6)
generic-mks-sgenl-v2.cfg for MKS SGEN_L V2(LPC1769)

2. Support 48kbit bootloader offset for MKS Robin Nano V3

3. Related information link
MKS Robin Nano V2: https://github.com/makerbase-mks/MKS-Robin-Nano-V2.X
MKS Robin Nnao V3: https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X
MKS SGEN_L V2: https://github.com/makerbase-mks/MKS-SGEN_L-V2

Signed-off-by: Qiuyanhua  1224833100@qq.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks fine to me, but commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by mks-viva** [comment]
Thank you! I will make adjustments.

**Comment by KevinOConnor** [comment]
Thanks.  Is "Qiuyanhua" your real name?  If you'd like to provide config files anonymously, I can usually implement config files with my signed-off-by line.  If so, let me know.

-Kevin

**Comment by mks-viva** [comment]
Thank you, i think use *mks-viva* is perfect.

**Comment by KevinOConnor** [comment]
Okay, thanks.  I committed the robin configs.  The sgenl config looks the same as the existing generic-mks-sgenl.cfg config, so I didn't commit that.

-Kevin

**Pull request closed without merging**
