### PR TITLE
Fix race condition of filament width sensor

### PR DESCRIPTION
**Pull request by Cirromulus**
I noticed that switching off the hall filament width sensor mid-print does not always switch off the active flow rate modifier.
With this fix, this problem did not occur to me again.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@test3210-d - Do you have any comments on this?

-Kevin

**Comment by test3210-d** [comment]
> 
> 
> @test3210-d - Do you have any comments on this?
> 
> -Kevin

No comments , this part of code from TSL1401CL_Filament_Width_Sensor, i think same problem have TSL1401CL Sensor module. Good solution i think

**Comment by Cirromulus** [comment]
I added the code to `tsl1401cl_filament_width_sensor.py` as well, but I can't test it there.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
