### PR TITLE
BLTOUCH: Add "probe in touch mode" option

### PR DESCRIPTION
**Pull request by FanDjango**
Solves #2321

Signed-off-by: Mike Stiemke fandjango@gmx.de

### CODE REVIEW

**Comment by fiferboy** [comment]
I did a quick check on my clone probe and touch mode is working as expected! I'll do some more testing tonight with some probe accuracy measurements and a 7x7 bed level. Thanks!

**Comment by fiferboy** [comment]
Probing is fast, reliable and seemingly accurate for me now. Hopefully added yet another BL Touch config option isn't deemed too excessive.

Here is the result of a 20 probe accuracy check for me. 20 probes previously would be extremely rare to have success in short succession and now it is repeatable every time.

```
Send: PROBE_ACCURACY SAMPLES=20
Recv: // PROBE_ACCURACY at X:155.000 Y:107.000 Z:20.060 (samples=20 retract=2.500 speed=5.0 lift_speed=10.0)
Recv: // probe at 155.000,107.000 is z=3.434839
Recv: // probe at 155.000,107.000 is z=3.453998
Recv: // probe at 155.000,107.000 is z=3.435672
Recv: // probe at 155.000,107.000 is z=3.436505
Recv: // probe at 155.000,107.000 is z=3.433173
Recv: // probe at 155.000,107.000 is z=3.455664
Recv: // probe at 155.000,107.000 is z=3.440670
Recv: // probe at 155.000,107.000 is z=3.432340
Recv: // probe at 155.000,107.000 is z=3.439837
Recv: // probe at 155.000,107.000 is z=3.438171
Recv: // probe at 155.000,107.000 is z=3.434006
Recv: // probe at 155.000,107.000 is z=3.436505
Recv: // probe at 155.000,107.000 is z=3.433173
Recv: // probe at 155.000,107.000 is z=3.440670
Recv: // probe at 155.000,107.000 is z=3.449000
Recv: // probe at 155.000,107.000 is z=3.438171
Recv: // probe at 155.000,107.000 is z=3.434006
Recv: // probe at 155.000,107.000 is z=3.438171
Recv: // probe at 155.000,107.000 is z=3.433173
Recv: // probe at 155.000,107.000 is z=3.447334
Recv: // probe accuracy results: maximum 3.455664, minimum 3.432340, range 0.023324, average 3.439254, median 3.437338, standard deviation 0.006768
Recv: ok
```

**Comment by KevinOConnor** [comment]
Thanks.  I'm fine with adding this config option.  However, note that the "manual timing optimization" in lower_probe() is not compatible with touch_mode.  I suspect the code should actually look something like:

```python
    if self.probe_touch_mode:
        self.send_cmd('pin_down', duration=self.pin_move_time)
        self.send_cmd('touch_mode')
    else:
        duration = max(MIN_CMD_TIME, self.pin_move_time - MIN_CMD_TIME)
        self.send_cmd('pin_down', duration=duration)
    self.send_cmd(None)
```

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I'm fine with adding this config option.  However, note that the "manual timing optimization" in lower_probe() is not compatible with touch_mode.  I suspect the code should actually look something like:

```python
    if self.probe_touch_mode:
        self.send_cmd('pin_down', duration=self.pin_move_time)
        self.send_cmd('touch_mode')
    else:
        duration = max(MIN_CMD_TIME, self.pin_move_time - MIN_CMD_TIME)
        self.send_cmd('pin_down', duration=duration)
    self.send_cmd(None)
```

-Kevin

**Comment by FanDjango** [comment]
Yes. My next PR would have added that and some "cleanup" in a next step, to get rid of the else.

Lemme see how I can sell you on that.

**Comment by FanDjango** [comment]
I can see a PR #2699 and I believe this PR here should be integrated right into that one.

I just put this out to help the one or two people with a CR capacitor problem.

**Pull request closed without merging**
