### PR TITLE
Fix ender 6 config

### PR DESCRIPTION
**Pull request by ben-kaye**
Corrected the offset direction, added screw levelling and fixed bed mesh limits to account for offset (this would otherwise cause an error when trying ABL)

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@smcgroty - do you have any comments on this?

Separately, I don't think it is a good idea to define a `[screws_tilt_adjust]` config section if the ender6 does not come with a probe by default.  A `[bed_screws]` section would be a better choice.

Finally, in order for me to commit directly, commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by ben-kaye** [comment]
Hi @KevinOConnor, should I redo the commit and resubmit the pull request, omitting the screw tilt adjust?

**Comment by ben-kaye** [comment]
@KevinOConnor fixed the commit messages and removed the screw section

**Comment by smcgroty** [comment]
I agree the default configuration should not become too highly specialized
toward a bed probe. My default config contained commented options for a
probe as a compromise because the latent hardware support suggested
Creality may realize that option. But it shouldn't be assumed everyone will
always add a probe to their Ender 6.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
