### PR TITLE
[WIP] Add samd51 pindefs and enable sercom advanced config support on atsamd

### PR DESCRIPTION
**Pull request by FHeilmann**
This PR is primarily for review purposes.
~~Sercom py extra still ToDo.~~

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks fine to me.  FWIW, I don't think the checking of ioset and i2c pins is necessary or worth the complexity.  The changes to gpio.h don't look correct - the only changes to that file should be the addition of the `void *sX` fields.

-Kevin

**Comment by FHeilmann** [comment]
the code from i2c.c and spi.c has to be able to call the sercom_* functions thats why I added them to gpio.h, should I rather add them somewhere else?
The reason I added the sercom_get_pclock function was because there is no other way to get to the pclocks from just the bus without duplicating information. 

I'll remove the extra information.

**Comment by FHeilmann** [comment]
Ready for another round of review.

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I squashed and merged these patches (commit c8d7e28a).

-Kevin

**Pull request merged**
