### PR TITLE
Adds a config for the Ultimachine Archim 2 printer controller 

### PR DESCRIPTION
**Pull request by mtw3d**
(My first github commit, pardon any mistakes!)

Signed-off-by: Mike Payson <mike@mtw3d.com>

### CODE REVIEW

**Comment by mtw3d** [comment]
I didn't realize that attached all files I've changed, I assumed it only pushed the specific file I did commit on. Anyway, the MTW Create config is also tested and working and will probably be useful to others. 

Is there a way to delete the third file from the pull request? It's not likely to be needed by anyone but me, so I don't want to clutter up the repo.

Thanks!

**Comment by KevinOConnor** [comment]
Thanks.  Some minor notes:

- It would be preferable to not cut-and-paste the documentation from example.cfg and example-extras.cfg to the sample config files.  From time to time we change the main documentation and it would be a maintenance burden to update all the sample configs.
- The sample configs should have the standard "See the example.cfg file for a description of available parameters." message.  (See the other sample configs for examples.)
- The blurb at the top of a sample config should specify what micro-controller to specify when running "make menuconfig".  (See the other sample configs for examples.)
- The sample configs for particular printers should have an approximate release year in the name of the file.
- It would be good to separate out the archim2 config from the other printer configs.

Thanks again,
-Kevin

**Comment by mtw3d** [comment]
Hi Kevin,

Ok, I can make these changes. Can you clarify exactly what you mean with this point? 

> It would be good to separate out the archim2 config from the other printer configs.

Archim is a controller, not a printer, and that is just a generic config that other people may find useful. I believe I used the same naming system as other controllers, but let me know if I should change anything.

Thanks,
Mike

**Comment by KevinOConnor** [comment]
> Ok, I can make these changes. Can you clarify exactly what you mean with this point?

> >  It would be good to separate out the archim2 config from the other printer configs.

Sorry, I was just agreeing that it would be better to submit those config files in a separate pull request.

I can help with the updates if you want.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by mtw3d** [comment]
Sorry, I've been busy and forgot all about it. I'm busy for the next several days, but I will try to get back to it soon.

**Comment by KevinOConnor** [comment]
FYI, I went ahead and added an Archim2 example config (commit fc6d045d).  Happy to add the mtw configs as well if you can provide approximate dates when the printers were released (the convention is to put a date in the name of printer config files).

-Kevin

**Comment by mtw3d** [comment]
Thanks Kevin. The MTW Create was released in 2015. You can delete mtw-create-xl400-se-einsy, that was included unintentionally.

**Comment by KevinOConnor** [comment]
Okay, I added that as well (commit 2b3ea29f).  If there are any errors or things that should be different then feel free to correct with a pull request.

Thanks,
-Kevin

**Comment by KevinOConnor** [comment]
Okay, I think this should be completed now then.

-Kevin

**Pull request closed without merging**
