### PR TITLE
avr: Add support for atmega32u4

### PR DESCRIPTION
**Pull request by trevjonez**
I am not sure how to further validate this is correct. It builds and flashing to my mmu2 board works and I can communicate with it via console.py but that is as far as I have gotten.  

All the step dir and LED's on the mmu are via two shift registers and it seems I will need some sort of extras in place before I can hit those pins correctly.

The pin maps are just a guess by me based on the similarity of a 328p via uno vs the 32u4 on Leonardo. The spec PDF is still pretty foreign language to me so any education there would be appreciated.

### CODE REVIEW

**Comment by npgoalkeeper** [comment]
How has your testing been so far? Does the MMUv2 kit work? Also if it helps you any, here's a link to the schematic for the MMUv2 if that helps:
https://github.com/prusa3d/MM-control-2.0/blob/master/rev.03/MM-control.pdf

**Comment by trevjonez** [comment]
still too early to know for sure but as far as I can tell there is no reason it shouldn't work. it supports multiple mcu connections so the host can directly manage both the printer and mmu directly via usb. by doing it that way no additional load will be put on the receiver printer. plus I suppose it will make the prusa mmu2 potentially usable on any other printer that klipper will run on? (dream big right?)

This pr represents my first step toward the goal of mmu2 via klipper, getting klipper firmware to run on the prusa board. next step is adding some sort of way to support the mmu2 boards shift registers so that I can correctly map the pins of the board.

**Comment by KevinOConnor** [comment]
Thanks.  I'm fine with committing this.

I don't have much insight on the mmu.  It's a shame they put the DIR pin behind the shift registers - that'll be a pain to use.  I guess you could use a dummy gpio pin for the direction pin and basically treat the stepper as only having a single direction from the kinematics code.  (You could still change directions as an external event from a high-level "extras" module.)

For an example of how to use a shift register, see klippy/extras/replicape.py - the replicape uses a shift register for the stepper enable pins.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, on a closer look, the alternative pin definitions in gpio.c don't look correct - most of the pins seem more similar to the at90usb1286 definitions then the atmega168 definitions.  Also, the OCR4A timer isn't 16bit on the atmega32u4 (that timer isn't similar to any timer on any other atmega board I've seen - simplest would be to just not support hardware pwm for it).

I have the spec handy, so I can put together the changes.

-Kevin

**Comment by KevinOConnor** [comment]
I pushed up what I think the pin changes should look like on the work-atmega32u4-20181119 branch (commit 54aa35bb).  Let me know if they look okay.

-Kevin

**Comment by KevinOConnor** [comment]
Hi,

> So comparing what you have vs what I did. in klippy/pins.py you specify port_pins(6) for the 32u4 where as I concluded it was 5 as in B,C,D,E,F. so what/where is port A?

In this case, we're just defining the internal mapping which is PA0-7 => 0-7, PB0-7 => 8-15, PC0-7 => 16-23, etc.  So, we need the PAx definitions just to complete the mapping.  This is a bit cryptic, and is something I'd like to improve after the next Klipper release.  (Specifically, I think we could extend the code to use the "static string" feature of the Klipper protocol to define the pin names solely in the mcu.)

> It also looks like you also added the 32u4 to the list of chips needing a prescaler clear.

Yeah, a lot of the USB bootloaders on AVR run at 8Mhz (I'm not sure why).  I thought it would be safest to enable it.

> I think the only other big question I have is what determines the order of the constants in gpio.c?

Yeah - it's all from the alternate pin mappings part of the spec.

If you can confirm the above boots okay on the atmega32u4 I'll go ahead and commit to the master branch.

-Kevin

**Comment by KevinOConnor** [comment]
> Then in the same file, do we need to specify an arduino_from_mcu for the 32u4?

The arduino mappings only apply if one uses the "pin_map: arduino" feature in their config.  Specifically it defines the aliases that the arduino project uses on their boards.  I don't think we need to bother with that as I don't think anyone is actually using a real arduino with this chip.  (It's generally preferable to avoid the arduino aliases and use the actual hardware names.)  We can always add the aliases later if we find someone does need them (I haven't checked, but I don't think they'll match any of the existing alias maps, so someone would need to track down the mapping and implement it.)

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I pushed up the changes.  I also reworked the hardware pwm pin table to try and make it a little more clear what's going on.

-Kevin

**Pull request closed without merging**
