### PR TITLE
Adding support for a homing_speed_slow parameter

### PR DESCRIPTION
**Pull request by pyjamasam**
Allows a second homing_speed_slow parameter to be defined in the config file so that the approach after initial endstop trigger can be slowed down more then the old default of homing_speed/2.0.

Code maintains the existing default if this new parameter is not configured in the config file.

Signed-off-by: Chris Whiteford <chris@chrisandtennille.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Can you provide additional information on the real-world usage for this option?  Under what circumstances would a general user want to set this value from something other than the default.  We'll need this (along with updates to example.cfg) to properly document any additional configuration option.

-Kevin

**Comment by pyjamasam** [comment]
In my case I have a delta with optical endstops.  I corse home quite fast (100mm/s) so the current code would then move off and then re-home at 50mm/s.

That's a little fast for my tastes for the final homing.  In my config I have 10mm/s for my homing_slow_speed.  This gives me the option to move quickly up to the endstops and then slowly creep away and back again to get a nice crisp final homing result.

I use this technique on a number of long axis machines that I have built.  It lets the homing process go as quickly as possible, but still results in high quality homing results.

I'd be glad to update documentation (I am assuming in should be in the example-extras.cfg file) if this is a change you'd like to consider merging.

chris.

**Comment by Flupke1979** [comment]
I also use the low speed homing by changing the divider in cartesian.py.
It is particularly handy in long axis machines.
Having it in the config would be nice.

Kim

**Comment by KevinOConnor** [comment]
Okay; in general, the code looks fine. There should be an addition to the example.cfg file describing the new parameter.  Also, I'm not sure about the "homing_speed_slow" name - how about "second_home_speed"?

-Kevin

**Comment by pyjamasam** [comment]
So the normal parameter is called homing_speed which was why I went with homeing_speed_slow, but I do see a valid point with NOT calling it _slow.

second_home_speed seams like its a departure from the other homing related parameters.  What about homing_speed_second.  Though as I type that I don't know if that's good either.  Sigh.

I'll make the changes and call things second_homing_speed.  If we want to change it from that just let me know.

chris.

**Comment by outlookhazy** [comment]
maybe homing_repeat_speed?

Another option would be to make the existing multiplier configurable, defaulted to the existing 0.5 - though that's a little more hassle for the user who might want a specific value to get the same result.

**Comment by KevinOConnor** [comment]
Thanks.

**Pull request merged**
