### PR TITLE
more info on Raspii and undervoltage

### PR DESCRIPTION
**Pull request by dothebart**
add howto see it in dmesg, tell its ok to increase the voltage a bit so dc/dc converters are able to keep up.

### CODE REVIEW

**Comment by dothebart** [comment]
oh how I hate that message. the raspii is really picky about its current.

**Comment by KevinOConnor** [comment]
Thanks.  How about a slightly different wording:

- If using a Raspberry Pi, make sure it has a stable power source. Use
  a good quality power supply for the Raspberry Pi and use a good
  quality USB cable to connect that power supply to the Pi. (If you
  get "under voltage" warnings from OctoPrint or the Unix command
  `dmesg -w` reports `Under-voltage detected!`, these are symptoms of
  voltage issues that need to be fixed.)

-Kevin

**Comment by dothebart** [comment]
the first link is the original raspii documentation about power requirements, the second one has more about bad cables etc. 
I'd like to let the DC/DC thing in, since if you run the raspii from the 12V PSU this may be a more common usecase when 3d printing then when using it as xbmc etc.

**Comment by dothebart** [comment]
Already inserted manually.

**Pull request closed without merging**
