### PR TITLE
fan: Scale fan speed between off_below and max_power

### PR DESCRIPTION
**Pull request by pfemiani**
New relative_power fan setting will allow the scaling of fan speed requests
between  off_below and max_power. For example, if off_below is .3 and
max_power is .9 and a fan speed of 20% is requested, then the fan power
will be set to 42%). 

With this setting enabled, once you have off_below and
max_power properly calibrated, it is much easier to request fan speeds
between 0% and 100% (or 0-255) via slicer for example and have the fan
behave as intended without having to be mindful of what speed the fan
will be under (ie not started) or over powered.

Signed-off-by: Peter Femiani <peter@femiani.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks, but see #2165 .  In that discussion it was raised that `off_below` should not be used for scaling.

-Kevin

**Comment by pfemiani** [comment]
Thank you @KevinOConnor, I did not see that issue and just read through the discussion. I have to admit I can't say I agree with the logic of the outcome, but I think the big difference in this implementation is that it doesn't change any existing behavior by default. One would have to opt-in to the lower-limit scaling, which was noted in #2165 as an acceptable option... "_In theory both settings could exist side by side -- I would not object if the existing behavior was preserved_". Interestingly, the requested power value is already being scaled to the max_power value, which seems no negate most of the arguments against a lower limit scaling made in that discussion.

This change is obviously a nice to have, I implemented it for my brother who's part cooling fans had a very high lower limit before they would turn on, and this change has made it much easier for him to work with fan speeds in his slicer, so i thought it was worth sharing. It is in no way critical or worth further debating. Feel free to evaluate and close the PR at your discretion. 

Thank you for everything you've done to make and support this amazing product!

**Comment by jakep82** [comment]
> IMHO this would be a very useful addition, e.g. for running 12V fans on a 24V line:
> PWM 0 - 255 --> Clamped to 0 - 127 --> Slicer control still 0% to 100%

This is not a proper way to wire a fan, and it will likely destroy the fan over time.  While the average voltage is 12V, the fan is still being pulsed with 24V.  You should never power a 12V device from a 24V supply even if it's PWM conrolled.  The proper way to do this is to use a buck converter to supply +12V, and use the ground side of the mosfet for PWM control.

**Comment by Sineos** [comment]
@jakep82 
Of course you are right. Although I have such a solution on one of my printers running for hundreds of hours now. The fan might not be happy to get blipped by 24V with a duty cycle of 50% but it does work. Poor man's solution (read: too lazy to install a DC-DC converter) after all.

**Comment by intelinc** [comment]
I'm dealing with this exact issue on a Taz 6 and slicing with Ideamaker -- a nice slicer in many respects, but one that has no setting for minimum fan speed, only maximum fan speed. As a result, it defaults to outputting M106 PWM values between 0 and whatever is set as the maximum fan speed. The result is an inability to manage cooling effectively on my Taz in Klipper.

While a min fan speed config setting in Ideamaker would be a solution, IMO it would be best to have this scaling handled by Klipper and not the slicer. My squirrel cage cooling fan won't reliably run below 20% PWM. Thus 20%-100% PWM duty cycle represents 0-100% of the _effective operable cooling range_ of the fan. This is a hardware-level idiosyncrasy that is best handled in Klipper, as opposed to having to uniquely configure (if possible) across every slicer that I use. The functional PWM range required to run the fan should be configured once, in Klipper, and then exposed as a consistent 0-100% cooling range that can be addressed via standard G-code consistently across any slicer. My 2C.

**Comment by grigi** [comment]
I have done some experiments with my squeaky 'ol 5015 cage fan, and it will reliably run at 20%, but won't start if it's lower than that.
If I set the PWM to 20% to ensure it starts smoothly, then  I can drop it to about 12% with no problems. Below that it loses speed and eventually stops.

So if we could have a `boost_below=0.2` parameter that would run at 20% PWM for a second or so before dropping below till 12% (e.g. `off_below=0.12`) could extend the usable range notably.

**Comment by intelinc** [comment]
> So if we could have a `boost_below=0.2` parameter that would run at 20% PWM for a second or so before dropping below till 12% (e.g. `off_below=0.12`) could extend the usable range notably.

@grigi: you should take a look at `kick_start_time` and `off_below` in the fan section of [example.cfg](https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg). The first turns the fan off below a certain speed, the second blips the fan at full duty cycle for a fraction of a second to get it going.

**Comment by grigi** [comment]
Thank you, I'll try that this weekend.

I feel like doing a documentation PR once I have a better idea of everything, as whilst everything is documented somewhere, just finding it isn't super easy.

I mean you find out that if you don't specify some sections in config then some features are disabled when reading the gcode documentation. It was unexpected to find it there.

On the other hand the setting up to get a basic working system and tune extrusion and motion is documented exceptionally.

**Comment by intelinc** [comment]
> I feel like doing a documentation PR once I have a better idea of everything, as whilst everything is documented somewhere, just finding it isn't super easy.

Absolutely agree. There is so much deep functional value that lies scattered across documentation, configs and code. But that’s also a good place to be; refactoring documentation and XD  based on great software is orders of magnitude better than the other way around. 😉

**Comment by towe96** [comment]
#3937 combines approaches from this and #2165 to integrate fan scaling without breaking existing configs or giving off_below multiple jobs.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like it has gone stale.

It may be worthwhile to add min/max scaling for the fan, however I think we'll need to find a way to do that which doesn't conflict with the off_below functionality.

-Kevin

**Pull request closed without merging**
