### PR TITLE
Config file for Anycubic i3 Mega

### PR DESCRIPTION
**Pull request by mjedlinski**
Config file for Anycubic i3 Mega v1 and Ultrabase
Signed-off-by: Marcin Jedliński <mjedlinski@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
In order for me to merge a pull request directly, it needs to have a signed-off-by line (as described in docs/CONTRIBUTING.md).  What year is this printer from - I'd like all the sample config files to contain an approximate year as printers have been known to change over time.

**Comment by mjedlinski** [comment]
Sorry for that. I updated config file, and add signed-off to Pr comment.

**Comment by KevinOConnor** [comment]
Would it be okay if I changed the leading comment to read as:
```
# This file contains pin mappings for the Anycubic i3 Mega with
# Ultrabase from 2017. (This config may work on an Anycubic i3 Mega v1
# prior to the Ultrabase if you comment out the definition of the
# endstop_pin in the stepper_z1 section.) To use this config, the
# firmware should be compiled for the AVR atmega2560.
```

**Comment by mjedlinski** [comment]
It's ok. Thanks.

**Comment by KevinOConnor** [comment]
Thanks.  I made some minor changes to the config to make it more similar to the other configs and committed it (a6025686).

**Pull request closed without merging**
