### PR TITLE
Correct support for OUT parameter in script to allow multiple config.

### PR DESCRIPTION
**Pull request by dianlight**
As discussed in #2781 this PR add Makefile modify to allow multiple mcu config in parallel. It is very usefull whan you have a secondary mcu in your config.

Edit: This PR fixes scripts to correctly handle the OUT parameter.

For example:
```
      make OUT=out3/ KCONFIG_CONFIG=$(pwd)/.config_2 menuconfig
      make OUT=out3/ KCONFIG_CONFIG=$(pwd)/.config_2
      make OUT=out3/ KCONFIG_CONFIG=$(pwd)/.config_2 flash
```

~For example the commands for the second mcu are:~
~make MCU=2 menuconfig
      make MCU=2
      make MCU=2 flash~

~Vote with a +1 if you are interested in this possibility because you are in a configuration with many mcu.~

Signed-off-by: Lucio Tarantino <lucio.tarantino@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback is that I think it's okay for users to run `make KCONFIG_CONFIG=config-mymcu OUT=out-mymcu/` instead of modifying the main makefile to infer these two parameters from a third parameter.

-Kevin

**Comment by KevinOConnor** [comment]
A `:=` is not needed to override a makefile variable.  Try it: `make OUT=~/testit/`

-Kevin

**Comment by dianlight** [comment]
It works  but it is quite uncomfortable. To have `OUT` and `KCONFIG` separate the user must launch a command like:
```
make OUT=out3/ KCONFIG_CONFIG=$(pwd)/.config_2 menuconfig
make OUT=out3/ KCONFIG_CONFIG=$(pwd)/.config_2 
make OUT=out3/ KCONFIG_CONFIG=$(pwd)/.config_2 flash
```

L.

**Comment by KevinOConnor** [comment]
Thanks.  I understand, but I'm still leery of adding additional complexity to the main Makefile.  I don't think this is something we want to add to the master branch.

-Kevin

**Pull request closed without merging**
