### PR TITLE
Fixing Quad Gantry logic to use probed Z values correctly

### PR DESCRIPTION
**Pull request by VoronDesign**
Signed-off-by: Maks Zolin <mzolin@vorondesign.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  What's the problem that is being corrected?  One thing that looks odd is the use of the horizontal_move_z in the stepper calculations - why would a constant offset impact the calculation?

-Kevin

**Comment by VoronDesign** [comment]
I'm using horizontal_move_z as a mirror plane to reflect the Z probe values onto (aka subtract them). There was a change in a way probe returns Z readings that broke my logic sometime after 0.7 release. It makes sense if you are probing for how far the bed is from the nozzle. What I'm interested in is how much the nozzle moved to get to the bed. That tells me how high that point on the gantry is from the bed and the math starts making sense.

**Comment by KevinOConnor** [comment]
Okay, thanks.  I will merge this if you wish.

I am confused, however.  I'm not aware of any changes to the probing or stepper code in this area of the code since v0.7.  I'm also confused how horizontal_move_z impacts the calculations.  I would have thought that any constant would work - in particular the constant of zero.

-Kevin

**Comment by VoronDesign** [comment]
Well ether the probe results coming back changed or my math was wrong from the start. I’m not implying I’m infallible. :) What I know is to do the calculations I need to know how far the probe had to travel before being triggered. What probe correctly gives me is the Z coordinate of that point in relation to Z0. 

I’m using horizonal_move_z because that’s effectively where the probe starts off before beginning the probe move. I could use some arbitrary value, I just figured it would be nice to have this be locked into an already configured variable. 

At the end, I’m averaging out the values to find a point on a plane that lies in between those point, and adjusting all corners to that plane.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
