### PR TITLE
Fix for z axis homing bug

### PR DESCRIPTION
**Pull request by ld3300**
Z axis was being marked as homed if G28 X or G28 Y were executed

If a Z hop value is specified in [safe_z_home] then the z axis would pick up its min and max limits and then evaluate as having homed.  This fix clears those limits back to un-homed state if the z-axis was not already homed prior to the issued command.

I believe this only applies to cartesian and coreXY kinematics, but please let me know if that is incorrect

Signed off by: David Smith <davidosmith@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@FHeilmann - fyi.

-Kevin

**Comment by FHeilmann** [comment]
@KevinOConnor LGTM, I'll leave it up to you if stubs for the other kinematics should be introduced. While I agree that safe_z_home is mostly used for cartesians and corexy's I'm not sure someone with a scara or polar machine might also use it.

**Comment by KevinOConnor** [comment]
The reset_limits() call would need to be added to all the other kinematics.  Alas, several of the kinematics don't have an easy way to correlate a particular cartesian axis with a stepper (eg, delta).

I think an alternate solution is to just document this - for example, something like:
```diff
--- a/config/example-extras.cfg
+++ b/config/example-extras.cfg
@@ -316,13 +316,15 @@
 #   Speed at which the toolhead is moved to the safe Z home coordinate.
 #   The default is 50 mm/s
 #z_hop: 0.0
-#   Lift the Z axis prior to homing. This is applied to any homing command,
-#   even if it doesn't home the Z axis. If the Z axis is already homed and
-#   the zhop would exceed the printer limits, the zhop is ignored. If a lift
-#   has already been performed or the Z axis is known to be equally or higher
-#   than this distance, the zhop is ignored. After homing Z completed, the
-#   printhead is lifted to zhop, respecting the probe's z_offset.
-#   The default is 0.0mm.
+#   Lift the Z axis prior to homing. This is applied to any homing
+#   command, even if it doesn't home the Z axis. If the Z axis is
+#   already homed and the current Z position is less than z_hop, then
+#   this will lift the head to a height of z_hop. If the Z axis is not
+#   already homed, then the Z axis boundary checks will be disabled
+#   and the head lifted by z_hop prior to any XY homing movement. If
+#   z_hop is specified, be sure to home the Z immediately after any XY
+#   home requests so that the Z boundary checks are accurate. The
+#   default is 0.0mm.
 #z_hop_speed: 20.0
 #   Speed at which the Z axis is lifted prior to homing. The default is 20mm/s.
 #move_to_previous: False
```

-Kevin

**Comment by ld3300** [comment]
Let me look into those, I can't see how adding it would hurt, just need to see the mechanism.

**Comment by ld3300** [comment]
I think that it is worth putting it in all the kinematics even if it has no effect.  Being able to have the printer.toolhead.homed_axes check be accurate might prevent issues like in #2479 where the issue first came up.  My latest push adds it to the other kinematics files.  I can't test on a polar printer, but it looks like identifying the z isn't a problem.  The delta printers wouldn't seem to apply so it would just return.  Would you consider this an acceptable solution?

**Comment by KevinOConnor** [comment]
While this is discussed, I've committed the change to the documentation (commit 049d8c2a).

-Kevin

**Comment by ld3300** [comment]
@KevinOConnor do you have any objections to having the reset_limits in the other kinematics files as I have submitted?  Currently the delta ones just return, but I could add the ability to reset the limits on those as well if it might be used by other features later on.  I would like to see this committed, but am happy to discuss if you see me steering off track.

**Comment by KevinOConnor** [comment]
Hi @ld3300 .  I don't know what the best approach is.  I suspect it might be best to continue to gather comments before deciding.

FWIW, my current high-level thoughts are:
1. I suspect it is not worthwhile to add additional complexity to al the kinematic classes.  The kinematic classes are already complex and I suspect adding additional complexity for this one corner case of safe_z_home is not a good trade-off.
2. I think it's fine to just document the current behaviour.  Fundamentally, z_hop requires turning off z boundary checks; so, just telling users that seems a workable approach.
3. It might also be possible to just "hack it".  For example, adding to safe_z_home.py something like `if hasattr(kin, "note_z_not_homed"): kin.note_z_not_homed()` and then populate `note_z_not_homed()` in all the kinematics that care with a comment that says "this is a helper for safe_z_home".

-Kevin

**Comment by ld3300** [comment]
oh interesting. I'm swamped for a bit, but that might be a good learning experience when i catch up.

**Comment by KevinOConnor** [comment]
Thanks.  It looks good to me.  Out of curiosity, though, is there a reason not to use the following in cartesian.py and corexy.py:
```python
    def note_z_not_homed(self):
        # Helper for Safe Z Home
        self.limits[2] = (1.0, -1.0)
```

-Kevin

**Comment by ld3300** [comment]
Yes, the main reason was I didn't stare at it long enough. Thanks for the catch.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by ld3300** [comment]
Kevin,

Thank you for the guidance and patience. I'm learning as I go and you have been incredible. It feels good to participate in a project where I can make a difference. Keep it up, this is clearly a project a lot of people love and are passionate about.

-David

**Comment by KevinOConnor** [comment]
Thanks David!  I appreciate your contributions!

-Kevin

**Pull request merged**
