### PR TITLE
Azteeg X5 mini config

### PR DESCRIPTION
**Pull request by AxMod3DPrint**
Tested as working

signed off - Ax Smith-Laffin (ax@darknetweb.co.uk)

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I noticed a couple odd things in the config - it looks like there is stepper_Z (instead of stepper_z) and there is a delta_calibrate section with cartesian kinematics.  Could you add this printer to test/klippy/printers.cfg as part of this commit?  That will enable the github build checks for the config.

-Kevin

**Comment by AxMod3DPrint** [comment]
Derp, pins were tested on a delta. Hence the delta section and the typo. I'll get that sorted later...

**Comment by AxMod3DPrint** [comment]
rebased and added config into printers.test

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Comment by AxMod3DPrint** [comment]
Welcome. that's all the boards I have now :P

**Pull request merged**
