### PR TITLE
Added ability to scroll long status messages

### PR DESCRIPTION
**Pull request by marcio-ao**
This will cause the status message to scroll if it does not fit the LCD display.

As a possible improvement, status_scroll_pos could be reset to zero every time a new message is displayed. However, I wasn't sure whether you wanted to do this by keeping a copy of the old string and doing a string compare each time, or whether you wanted something more efficient.

### CODE REVIEW

**Comment by marcio-ao** [comment]
module: Added ability to scroll long status messages

This will cause the status message to scroll if it does not fit the LCD display.

As a possible improvement, status_scroll_pos could be reset to zero every time a new message is displayed. However, I wasn't sure whether you wanted to do this by keeping a copy of the old string and doing a string compare each time, or whether you wanted something more efficient.

Signed-off-by: Marcio Teixeira <marcio@alephobjects.com>

**Comment by KevinOConnor** [comment]
Thanks.  I'm fine with this change, but there isn't a status message in the code today that is long enough to scroll.  Is there a plan to add that?

**Comment by marcio-ao** [comment]
Well, if someone issues M117 with a long message, it will need to scroll :)

**Comment by marcio-ao** [comment]
Incidentally, I'm not sure what the signed-off messages accomplish. They are redundant with respect to the author field, in that they both say I made the commit. If you want some sort of legal assurances that my company is releasing my work to your project, I will need to get you in contact with someone who has that sort of authority. As an employee, I can only certify that I wrote the code.

**Comment by KevinOConnor** [comment]
On Tue, Mar 06, 2018 at 07:44:02PM +0000, Marcio Teixeira wrote:
> Incidentally, I'm not sure what the signed-off messages accomplish. They are redundant with respect to the author field, in that they both say I made the commit. If you want some sort of legal assurances that my company is releasing my work to your project, I will need to get you in contact with someone who has that sort of authority. As an employee, I can only certify that I wrote the code.

It's an agreement of:

https://github.com/KevinOConnor/klipper/blob/master/docs/developer-certificate-of-origin

as described in:

https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

It's the same requirement as patches sent to the Linux Kernel (and a
bunch of other open source projects).  (Which is why "git commit -s"
will automatically add the signed-off-by line.)

-Kevin

**Comment by KevinOConnor** [comment]
On Tue, Mar 06, 2018 at 11:41:12AM -0800, Marcio Teixeira wrote:
> Well, if someone issues M117 with a long message, it will need to scroll :)

Well, M117 isn't implemented though.  :-)

-Kevin

**Comment by marcio-ao** [comment]
`It's the same requirement as patches sent to the Linux Kernel (and a
bunch of other open source projects).`

I've previously worked with projects that required a copyright assignment be done. I know that in that occasion I had to defer to my supervisor. AlephObjects is all about open-source (one of the reasons I chose to work here), so it's not a problem to get it if you need something more concrete than a signed-off by line with just my name on it.

`Well, M117 isn't implemented though.  :-)`

But once it is, thanks to this patch, long messages will work! It's future proofing :)

-- Marcio

**Comment by hg42** [comment]
I recently read, that the sign-off message is (probably) weak for legal issues. For example, the author might not have read the corresponding text (here CONTRIBUTING.md) and the message doesn't contain any link to it.
But it is kept for kernel development because it is useful to track the history of a piece of code. Especially because there are several other message lines like this. This seems to develop into something similar to mail headers.
But kernel development is an order of magnitude bigger than usual open source projects.
Looks a bit oversized to me.

**Comment by KevinOConnor** [comment]
Scrolling support would be useful, but we need M117 support first.  I think this branch looks stale, so I'm going to close this for now.

**Pull request closed without merging**
