### PR TITLE
Command M204 P???? Fail

### PR DESCRIPTION
**Pull request by WindoC**
module: toolhead.py, Command M204 P???? Fail

Fix the fail cause by M204 PXXXX and the system request S.

Signed-off-by: My Name 

============LOG=============
20:55:22.812: N36 M204 P500 ; set acceleration
20:57:54.704: !! Error on 'N36 M204 P500*85': missing S

### CODE REVIEW

**Comment by KevinOConnor** [comment]
This is by design.  I didn't want Klipper to silently ignore a request that it could not make.  The goal of the M204 command (as with all of the legacy g-code commands) is solely to be compatible with common 3rd party applications in their standard configurations (as described in docs/G-Codes.md).  If a 3rd party application generated this M204 command, then please let us know which application it was.  If this was a command manually generated then please use SET_VELOCITY_LIMIT instead.

-Kevin

**Comment by WindoC** [comment]
I know your point. I have changed the code to add current value as the default value so gcode "M204 PXXXX" will be no effect but not throw an error message to stop my print? Or leave info instead of error?

**Comment by Magoo0876** [comment]
I figured out also a Problem with M204:
Send: M204 T1400
Recv: !! Error on 'M204 T1400': missing S

I've tried many flavors in PrusaSlic3r 2.0.0, same result. Print fails.

**Comment by KevinOConnor** [comment]
Is there a widely used 3rd party application that generates this M204 command?  If not, I'd prefer to leave the code as it is.  I don't want Klipper to silently ignore a request it can not make.

-Kevin

**Comment by BlackStump** [comment]
can you not just disable Acceleration Control in the slicer ie PrusaSlic3r 2.0.0
M204
Maybe I am too simplistic but isn't Motion Planning best left to the firmware and slicing best left to the slicer?

**Comment by dragonnn** [comment]
Just select firmware flavor as RepRap/Sprinter and it will be gone.

**Comment by KevinOConnor** [comment]
I've made a similar change so that M204 will just warn on a missing parameter (commit f6e9db2d).

-Kevin

**Comment by WindoC** [comment]
Since it is fixed. I close this pull request.

**Pull request closed without merging**
