### PR TITLE
Config/anet e10 update

### PR DESCRIPTION
**Pull request by MrKekson**
tuned settings, and added verify_heater for extruder, bed

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.   I'm a little confused by the commit comments because the verify_heater section is enabled by default.  So, this config change doesn't enable verify_heater, it changes heating_gain from the default of 2 to 1.  Is this needed, or could we just stick with the defaults?

-Kevin

**Comment by MrKekson** [comment]
Right, i did not seen the first paragraph that it's an overwrite. Removed it. 

Letters confuses me sometimes :P

**Comment by MrKekson** [comment]
Not sure what happened with the CI build, some network error?

**Comment by MrKekson** [comment]
Re calibrated the steppes with multiple filament.

**Comment by KevinOConnor** [comment]
Hi.  I'm not sure what the state of this pull request is.  When I look at the final file differences between the master branch and this set of changes the only effective difference is max_z_accel goes from 100 to 1000.  (The min_extrude_temp defaults to 170, so it doesn't need to be set explicitly.)

**Comment by MrKekson** [comment]
Removed the default, but the text is not clear in the config. I tough it's not on by default, but for me the message suggested this temp as a default. 

The z acceleration is needed tho, because z hopping leave blobs everywhere on 100, since the head start moving slowly, leave. In fact there is an article somewhere in the marlin domian suggesting 1500 as a good value, but i could only set it to 1000.

**Comment by KevinOConnor** [comment]
Thanks.

**Pull request merged**
