### PR TITLE
Updates to allow stm32f0 to work with klipper and a bootloader.

### PR DESCRIPTION
**Pull request by clearchris**
Includes code by KevinOConnor.  Special thanks to JC Nelson for much
help.

Tested on Monoprice Mini Delta (malyan) stm32f070xb board.

Signed-off-by: Chris Lombardi <clearchris@hotmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  As a high-level comment, we don't want to add stm32f0 specific code to the generic armcm_boot mechanism.  Do you know what changes need to be implemented directly in the ResetHandler() code (eg, the stack pointer, the irq disable, etc.)?

-Kevin

**Comment by clearchris** [comment]
Specifically for the malyan loader, either the irq disable or the systick disable should happen quickly, and I'd definitely do it before messing with the vector table.  Either is sufficient for the malyan bootloader, doing both was just for completeness.  Depending on the bootloader code path, so long as we can make it to armcm_main() before SysTick_Handler is called, we should be ok.  But it does leave us open to crashes, I think.  What happens if SysTick_Handler on the original bootloader vector table is called while klipper is executing?  Probably nothing good.

Vector table copying could be moved into stm32f0.c.

I can test moving the setting of the stack pointer into stm32f0.c, but I'm thinking that calling a function without setting the stack pointer properly is probably a bad thing.

Watchdog feeding could probably be moved later, again, depending on bootloader code path.  It has already been started in the bootloader and can't be disabled.

________________________________

**Comment by xC0000005** [comment]
Every one of ST's startup files sets the stack pointer, so I'd say it's a good practice. I'm not sure how to handle specific "turn this off" needs without having some sort of function which can do the right thing based on whatever bootloader is running.

**Comment by KevinOConnor** [comment]
Well, it should be okay to disable SysTick and set the stack pointer on all armcm boards.  Something like the code up at: https://github.com/KevinOConnor/klipper/tree/work-stm32f0-bootloader-20191209

-Kevin

**Comment by KevinOConnor** [comment]
As we discussed offline, I merged the changes on the work-stm32f0-bootloader-20191209 branch.

Thanks.
-Kevin

**Pull request closed without merging**
