### PR TITLE
replicape: Correct spi bus designation for Replicape under 4.14 kernel

### PR DESCRIPTION
**Pull request by Wackerbarth**
Addresses issue #1778.

The appropriate bus is found by examining `/sys/devices/platform/ocp/481a0000.spi`

### CODE REVIEW

**Comment by Wackerbarth** [comment]
Test is failing because "Travis" is running on incompatible hardware. If you actually have a Replicape, it works just fine.

**Comment by KevinOConnor** [comment]
It's important that we be able to run the regression tests.  I'd prefer something like the below.

-Kevin

```diff
--- a/klippy/extras/replicape.py
+++ b/klippy/extras/replicape.py
@@ -3,11 +3,10 @@
 # Copyright (C) 2017,2018  Kevin O'Connor <kevin@koconnor.net>
 #
 # This file may be distributed under the terms of the GNU GPLv3 license.
-import logging
+import logging, os
 import pins, mcu, bus
 
 REPLICAPE_MAX_CURRENT = 3.84
-REPLICAPE_SHIFT_REGISTER_BUS = "spidev1.1"
 REPLICAPE_PCA9685_BUS = 2
 REPLICAPE_PCA9685_ADDRESS = 0x70
 REPLICAPE_PCA9685_CYCLE_TIME = .001
@@ -198,7 +197,11 @@ class Replicape:
             and self.stepper_dacs):
             shift_registers[4] &= ~1
         self.sr_enabled = list(reversed(shift_registers))
-        self.sr_spi = bus.MCU_SPI(self.host_mcu, REPLICAPE_SHIFT_REGISTER_BUS,
+        sr_spi_bus = "spidev1.1"
+        if not self.host_mcu.is_fileoutput() and os.path.exists(
+                '/sys/devices/platform/ocp/481a0000.spi/spi_master/spi2'):
+            sr_spi_bus = "spidev2.1"
+        self.sr_spi = bus.MCU_SPI(self.host_mcu, sr_spi_bus,
                                   None, 0, 50000000, self.sr_disabled)
         self.sr_spi.spi_send(self.sr_disabled)
     def note_pwm_start_value(self, channel, start_value, shutdown_value):
```

**Comment by KevinOConnor** [comment]
Okay, I committed a workaround for this issue (commit bc78bc48).  I'd prefer to go with the more minimal change as I'm leery of breaking any existing users (with unknown kernel settings) if we don't need to risk that.

-Kevin

**Comment by Wackerbarth** [comment]
For the same reasons that you prefer your approach, I prefer mine instead. Should something else change the kernel in the future, and the bus becomes "spi3" rather than "spi2", your approach will again break.

But, then, I guess that it's more important to utilize some kludge that works at the moment rather than having to maintain my own version of yet another file.

**Comment by KevinOConnor** [comment]
> Should something else change the kernel in the future, and the bus becomes "spi3" rather than "spi2", your approach will again break.

FWIW, the beaglebone cpu (AM335x) has exactly two hardware spi units, so I don't think it's an immediate threat.  That said, my experience tells me that future beaglebone Linux will break Klipper.  Alas, I'm quite confident it will break in a way we don't expect.  That's why I don't want to code for a possible future outcome - we'll never guess it right.

-Kevin

**Comment by KevinOConnor** [comment]
Okay - lets close this PR then.

-Kevin

**Pull request closed without merging**
