### PR TITLE
Removing obsolete STM32F0 folders

### PR DESCRIPTION
**Pull request by Delsian**
Sorry for delay with this task. Rewriting CAN from HAL to native took more time than I expect.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks for working on this!

In general, it looks good to me.  The commit will need a signed-off-by line (as described at https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).

FYI, I'm currently treating the repository in a "soft freeze" state for the holidays.  This is something I'll look to merge next week.

Happy Holidays!
-Kevin

**Comment by KevinOConnor** [comment]
Hi.  I think it would be good to merge this.  Will you be able to provide a signed-off-by line?

Thanks,
-Kevin

**Comment by Delsian** [comment]
@KevinOConnor Hi, sorry for delay with answer, it was holiday time :)

**Comment by KevinOConnor** [comment]
Thanks!  I made some minor modifications and pushed this to the master branch.  (Looks like some additional "project" files got pushed by mistake and some files mistakenly got set to executable - I fixed that on commit.)

I wasn't sure about the jlink/gdb changes so I held off on that commit for now.  I fear every developer will have their own flashing procedure, so documentation may be better than makefile rules.  FYI, there's a bunch of flashing documentation in docs/Bootloaders.md right now.

-Kevin

**Comment by Delsian** [comment]
@KevinOConnor Thanks. Unfortunately stm32f042 has not enough Flash to put bootloader inside, so external flasher required for FW update.
My old version did it with ST-Link, but currently it's possible to re-flash it to J-Link. 
I suppose "make jflash" should work as default upload command for tiny chips, not only for F042

**Comment by KevinOConnor** [comment]
Sorry for the delay in responding.

My high-level feedback is that I don't think we should add additional Makefile flash and gdb rules.  I fear there are too many different ways to flash and debug a board.  (I alone have 4 different debug/flashing methods for just stm32 chips!)  So, I think it's great to add info on how to flash and debug, but I think it should be in the docs/ directory - developers can then take that info and cut-and-paste the commands that they need.

Cheers,
-Kevin

**Comment by Delsian** [comment]
Ok, thanks, I'll update documentation section and then create new PR with my changes

**Pull request closed without merging**
