### PR TITLE
config: add config for Monoprice Select Mini v2 printer

### PR DESCRIPTION
**Pull request by 9R**
Adds config for the Monoprice Select Mini v2 cartesian printer. I have
successfully tested the configuration.

Signed-off-by: Kilian Neuner <github@9-r.net>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks good to me.  The example printer config files should have an approximate year of the printer in the file name though.  Also, "make menuconfig" changes from time to time (as it did in just the last few commits), so I'm not sure a copy-and-paste is a good plan.  Perhaps just describe the changes that need to be made.

-Kevin

**Comment by 9R** [comment]
Thank you for the quick response & feedback. I have applied your suggestions in the new commit.

**Comment by KevinOConnor** [comment]
Thanks.  I committed this and made a couple of minor changes on top (commit b24a547c).

Separately, was it intended for the file to use 2018 but the top comment to say 2019?  Also, was it intended for the stepper_x to use a step_distance of .01075 while stepper_y uses .010753?

-Kevin

**Comment by 9R** [comment]
Thanks for merging.

The different years resulted from me using a printer that I purchased in 2019 when i started writing the config and running some tests before submitting the PR on another one that was from 2018. 
The differing `step_distance` between X and Y is a mistake. I thought I corrected them all to six decimals before I submitted the config, but that one seems to have gotten through.

In b24a547 you removed `off_below` from `[heater_fan]`. On the printers I used for testing the fan stalled with a lower duty cycle, so I would suggest keeping this parameter.

**Comment by KevinOConnor** [comment]
A heater_fan doesn't use off_below - it always turns the fan full on or full off.  Perhaps I'm missing something though.

-Kevin

**Comment by 9R** [comment]
Ah, you are right. The fan on the Select Mini is a combined heater and part fan. While figuring out the config I first used it as part fan and the minimum duty cycle was required to not have it stall.
Finally I decided submitting a default config with heater_fan because without proper cooling the heatbreak & heatsink will get too hot.

**Pull request merged**
