### PR TITLE
Command / GCODE docs

### PR DESCRIPTION
**Pull request by mmone**
Hi Kevin,

I recently started using Klipper on a new CoreXY I build. Love the concept! Thank you for your work on this project!
I was looking for an overview of the available gcodes and commands so I created some documentation.

The text is based on the Marlin docs. Obviously everything needs to be reviewed by you. But some things were partially unclear to me.

**G28**
- What does the position parameter do? 
- What would be the result of e.g. "G28 X Y4 Z"?
	
**M206** 
- Is the description correct.
- When is the offset reset?

Hope you can use this. 

Martin

### CODE REVIEW

**Comment by KevinOConnor** [comment]
On Fri, Dec 22, 2017 at 01:38:35PM -0800, mmone wrote:
> Hi Kevin,
> 
> I recently started using Klipper on a new CoreXY I build. Love the concept! Thank you for your work on this project!
> I was looking for an overview of the available gcodes and commands so I created some documentation.
> 
> The text is based on the Marlin docs. Obviously everything needs to be reviewed by you. But some things were partially unclear to me.

Thanks.  I'm not sure if we can copy the Marlin docs.  I do like the
format and contents.  Any ideas how we can confirm that copying is
okay?

> **G28**
> - What does the position parameter do? 
> - What would be the result of e.g. "G28 X Y4 Z"?

I'm not sure what you mean by "position parameter".  The order of
parameters and the value of any parameters are ignored for g28 (and
Marlin too as I understand it).  So, "G28 Y4" is treated the same as
"G28 Y".

> **M206** 
> - Is the description correct.
> - When is the offset reset?

The M206 command should alter the interpretation of g-code coordinates
the same way Marlin does.  The offset is reset on a RESTART (or
similar) command, or a future M206 command.

Thanks again,
-Kevin

**Comment by mmone** [comment]
> Thanks.  I'm not sure if we can copy the Marlin docs.  I do like the
> format and contents.  Any ideas how we can confirm that copying is
> okay?

My thought was with both Klipper and Marlin being GPL licensed it would be OK to use the text. But you are right it would be nice to ask first.
I will follow up this comment with another one that describes the matter and @mentions the top three contributors to the marlin docs. That way they can tell us what kind of attribution, if any, they would like to see. If they don't respond I can figure out another way to contact them.

As for G28. I never used that command with any coordinates behind the axis identifier. My first thought was that it would set the home to the given coordinate. E.g G28 X Y4 would result in the home being at X0 Y4.
Then I [found documentation](https://www.cnccookbook.com/g28-g-code-cnc-return-reference-position/) that suggests it's a way to avoid head crashes by allowing more precise control over the path that the head takes toward zero. E.g. G91 G28 X0 Y0 Z4.0 would move Z up by 4 then move the head towards X0 Y0.

Martin

**Comment by mmone** [comment]
Hi @thinkyhead, @jbrazio,

I submitted this pull request to the newly developed GPL licensed 3D-printer firmware Klipper by @KevinOConnor. It uses text from the @MarlinFirmware gcode docs. Is this OK with you? If not what kind of attribution would you like to see?

Cheers Martin

**Comment by thinkyhead** [comment]
For my part, I think a simple attribution is fine. Above the documentation, it might just have a lead-in like this:
```
From the Marlin Firmware G-code documentation:
```
Or, below the documentation it could have a more formal credit line like this:
```
Contents (c) Marlin Firmware. All Rights Reserved.
```
🎄  Happy Holidays 🎄

**Comment by mmone** [comment]
As the texts are already partially changed and amended with things specific to Klipper, and will probably be much more so in the future, a copyright sounds a bit strong to me.

I would propose the following as a footer:

_Contains text from the Marlin firmware project documentation._

@KevinOConnor  if you're fine with this I will amend the pull request.

**Comment by jbrazio** [comment]
to: @mmone cc: @thinkyhead

Please feel free to use the documentation.
But you should keep the original copyright notice at the time of the fork.

A quick example from Marlin:
```
/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016, 2017 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
(...)
 */
```

You can see we kept a short Copyright claim from the original authors.

Using something like "Contains text from the Marlin firmware project documentation." means that you didn't fork the original project but heavily based your **new** work on something already existing.

So my suggestion would be a two liner:

```
Based on Marlin Firmware Documentation.
Copyright (C) 2016, 2017 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
```

I just noticed a bug, the [Marlin's copyright header](https://github.com/MarlinFirmware/MarlinDocumentation/blob/master/_includes/license.html) is being stripped from the website output files.

**Comment by cruwaller** [comment]
I think these docs are pretty useless anyway. Klipper files are installed on headless PC (mostly) so it is then a pretty hard to read these without making another clone on your daily PC or you anyway open a web browser. 
Nice G-code documentation can be found from reprap wiki (http://reprap.org/wiki/G-code).
I would rather extend reprap wiki and add klipper.

**Comment by mmone** [comment]
to: @jbrazio cc: @KevinOConnor 

I get your point and would be fine with having a header like the one you propose. Ultimately @KevinOConnor needs to decide what he thinks is feasible and how he can, if at all, accept the pull request.
I'm ready to modify it or drop it if necessary.

**Comment by KevinOConnor** [comment]
On Thu, Dec 28, 2017 at 01:39:39PM -0800, mmone wrote:
> to: @jbrazio cc: @KevinOConnor 
> 
> I get your point and would be fine with having a header like the one you propose. Ultimately @KevinOConnor needs to decide what he thinks is feasible and how he can, if at all, accept the pull request.
> I'm ready to modify it or drop it if necessary.

I'm not sure what is being proposed with the header.  If there is a
document for each g-code command and it is prefaced with a copyright
notice, I fear that will be cumbersome for readers.

I'm okay with including documentation on each supported g-code command
and I'm also okay with just having a link to a website with the
documentation (eg, Marlin's or Reprap's).  I would, however, like the
copyright ownership to be clear in the Klipper repo though.  If
there's consensus on how we can do that then great, otherwise it seems
like it's not really worth the pain - there's only about 8 or so
common g-code commands that would be worth copying.

-Kevin

**Comment by hg42** [comment]
>  there's only about 8 or so common g-code commands that would be worth copying.

and most commands will not be exactly the same.

Perhaps it would be best to extract the docs from the code, because if it is changed and forked the developers are visually reminded of adding and maintaining docs.
Otherwise I am sure, docs and code will drift apart very soon.

Also, there is (at least currently) no real standard klipper version, because there are many additions in forks. If someone uses a fork (s)he will probably wonder why the commands are undocumented or work different.

**Comment by hg42** [comment]
doc strings in the code can also be used to gather them and output them as help text. This shouldn't be duplicated. One must be the source and this can only be the code.

**Comment by hg42** [comment]
I forgot it's python, which has support for docstrings.
Basically you write something like:
```python
def cmd_M503():
    """shows all settings which are changeable via gcode
   this can be multiline
    """
    ...
```
then you can access these strings via cmd_M503.__doc__
The functions can be iterated and the docstrings processed to create whatever is necessary.

http://www.pythonforbeginners.com/basics/python-docstrings
https://en.wikipedia.org/wiki/Docstring

I would also suggest using decorators:
```python
@classmethod
@synchronized(lock)
def foo(cls):
    pass
```
which are invoked by python when reading the file.
In Python, ```@g @f def foo()``` translates to ```foo=g(f(foo))```, so you can do whatever you want with the function (or class etc.).

E.g. we could use something like:
```python
@alias("SHOW_CONFIG")
@gcode
def M503():
  ...
```
to automatically create the gcode list or dictionary and define aliases etc.
The implementation would be something like this (untested, see it as pseudo code, I am currently not familiar with python):
```python
def gcode(func):
  gcodes[func.__name__] = func
  gcodes_in_sequence.append(func.__name__)
  return func

def alias(name):
  def decorator(func):
    gcodes[name] = func
    aliases[func.__name__] += name
    aliases[name] += func.__name__
  return decorator
```
you can also use `cmd_M503` and use something like `func.__name__.replace("cmd_", "")` on it to strip the cmd.
I think, I would put each gcode in it's own file anyways.

Python syntax and semantics - Wikipedia  https://en.wikipedia.org/wiki/Python_syntax_and_semantics#Decorators

**Comment by mmone** [comment]
Hi @KevinOConnor,

I have updated the files with a header everyone should be able to live with.
Where it's completely original content I used the following:

> Copyright (C) 2016,2017  Kevin O'Connor <kevin@koconnor.net>
> 
> This file may be distributed under the terms of the GNU GPLv3 license.

Where it's based on Marlin docs I used: 

> Copyright (C) 2016,2017  Kevin O'Connor <kevin@koconnor.net>
> 
> This file may be distributed under the terms of the GNU GPLv3 license.
> 
> based on Marlin Firmware Documentation.
> Copyright (C) 2016, 2017 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]

If you don't want to use it like that please close the pull request. I don't mind.


Cheers

Martin

**Comment by mmone** [comment]
I close this for now.

**Comment by KevinOConnor** [comment]
@mmone - thanks for spending time on this.  Unfortunately, I haven't had a chance to look at it again.  I've added it to my list of things to review, but it's probably still a couple of weeks out before I'll start looking at g-code documentation.

**Comment by mmone** [comment]
I understand. And good to see that this project is gaining traction.

**Comment by KevinOConnor** [comment]
Hi Martin,

FYI, I decided to commit a very brief g-code document (commit 05ec7ca7) that just references the main reprap g-code documentation.  It's not really my goal to support lots of cryptic g-code commands, so I'm hoping we can rely on the reprap wiki for the traditional commands and focus our documentation efforts on the klipper specific "extended" commands.

Thanks,
-Kevin

**Comment by mmone** [comment]
Hi @KevinOConnor,

I started writing a [Klipper plugin for octoprint](https://github.com/mmone/OctoprintKlipperPlugin). Could be interesting to do a "live" docu that allows to test the commands right away, think swagger.io for Klipper. Just an idea.

**Pull request closed without merging**
