### PR TITLE
virtual_sdcard: pre-spooling gcode file

### PR DESCRIPTION
**Pull request by trevjonez**
This change helps make the input source of the gcode files both in path and medium less sensitive.

**Spooling behavior use case:**
In my home setup I have multiple machines running klipper on a typical raspbian 3b+ setup, each instance utilizes a virtual_sdcard path that is actually an NFS volume mount that is hosted from a separate file server. While this typically works well it introduces network as an element of the critical path. At times this prohibits me from doing server maintenance while prints are running. Additionally I believe a series of recent `no next step` failures are due to network or server issues of some sort (gcode file read stalling I am assuming).

**Select/Clear extraction use case:**
For the spooling work it allowed a bit less code duplication and separating the gcode param unpacking from the file operations.

It is also an enabler for improvements in the DWC2-for-klipper extra.
1. The DWC2-for-klipper extra has reimplemented a part of the `M23` logic [as part of its `M32` command](https://github.com/Stephan3/dwc2-for-klipper/blob/master/web_dwc2.py#L1074).  By extracting the select logic the integration can be improved in that module to allow virtual_sdcard.py to own the file operations, equally making DWC2-for-klipper not need to replicate the spooling behavior introduced here. 

2. Once a few small changes are made within the DWC2-for-klipper repo as well as a small adjustment to the sd card menu configuration in a users printer.cfg, DWC2-for-klipper can be made to gracefully handle the situation where a print is started via the printer LCD.

3. Due to the code duplication in DWC2-for-klipper file descriptors seemed to be leaked since clear logic was not executed when appropriate. Again having virtual_sdcard expose the select logic ensures files are closed with appropriate timing.

### CODE REVIEW

**Comment by rafaljot** [comment]
Do you mean "DWC2" or DWC2-for-Klipper ?  https://github.com/Stephan3/dwc2-for-klipper 

I made small improvement in dwc2-for-Klipper for printing both from LCD and web interface:
<------><------>klipper_sdpath = self.configfile.getsection("virtual_sdcard").get("path", None)
<------><------>self.sdpath = config.get("sd_path", klipper_sdpath)
<------><------>self.sdpath = os.path.normpath(os.path.expanduser(self.sdpath))

then I have additional parameter in config:
[virtual_sdcard]
path: /home/pi/sdcard/gcodes
[web_dwc2]
sd_path: /home/pi/sdcard

I think it is part of general topic -  How to build a communication interface with access to all Klipper functions, data etc to build better external UI

https://github.com/Stephan3/dwc2-for-klipper/issues/38

**Comment by trevjonez** [comment]
> Do you mean "DWC2" or DWC2-for-Klipper ? https://github.com/Stephan3/dwc2-for-klipper

you are correct, I am referring to Stephan3/dwc2-for-klipper. I will edit for clarity, conflation ends up being confusing without previously built up context.

> then I have additional parameter in config

That is something I am actively trying to avoid with this work. My thinking is that there is an existing convention for setting up `[web_dwc2]` so by adding a required field it is a breaking change for existing users doing the update. Which can be avoided by leaning on the existing convention.

> lot of annoying warnings

This pull request, plus the pull request on dwc2-for-klipper resolve the issue causing all of those errors.

**Comment by rafaljot** [comment]
It works. 
I can start printing both from LCD an DWC2 without any issue.

**Comment by trevjonez** [comment]
@rafaljot  I just rebased on master to resolve some conflicts. Depending on how you pulled in my proposed changes you may see odd conflicts once you go to update.

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback is that I'm not sure this is a good fit for the master Klipper branch.  The intent of virtual_sdcard is to point to a local directory.  I don't there will be a large enough audience of users doing something else to justify additional complexity in the master Klipper branch.

As for DWC2 - I'm not familiar with the issues you are referring to.  I can say that if there is interest in DWC2 support in the main Klipper repo, then the first step will be the code submission of DWC2 itself, followed by its review, etc.

-Kevin

**Comment by rafaljot** [comment]
What's wrong with adding DWC2_for_klipper to standard extensions?
The audience is small because now the installation is complicated.

I like this extension. I have workin Klipper with web interface on rPi ZeroW in delta. It works on one core without any issue. 

In my Prusa mk3s Banana Pi Zero and Klipper with web Interface start in less than 10 seconds.

**Comment by manu7irl** [comment]
Hi, I have myself been working on a big installer for klipper dwc2 and
octoprint as well a a multi instances for klipper and for octoprint.
It can be found here, this is still a work in progress but it is
fully functional, AFAIK:
`https://github.com/manu7irl/klipper-DWC2-installer.git`
 Dwc2 works wonders with klipper I am using it almost a year without no
issues.

**Comment by trevjonez** [comment]
@KevinOConnor let me know what you think best approach is for this PR. I totally see the point of concern that temp spooling ends up being a distant edge case.

It sounds like there is growing desire for things that make extras like `[web_dwc2]` easier to integrate. I am going to open a new issue ticket to discuss an idea that may be a good hook point for doing extras and module edits without having to directly edit sources in this repo.

**Comment by KevinOConnor** [comment]
Thanks.  It does sound interesting, but I don't think this is currently a good fit for the Klipper master branch.  So, I'm going to close this.

-Kevin

**Pull request closed without merging**
