### PR TITLE
generic bigtreetech skr v1.1

### PR DESCRIPTION
**Pull request by rmcbc**
Finaly put my BIGTREETECH SKR V1.1 to work with klipper, made a generic configuration file to help others to configure this board.

Signed-off by: Rui Caridade (rui.mcbc@gmail.com)

### CODE REVIEW

**Comment by derdigge** [comment]
@rmcbc @KevinOConnor Thanks for pointing me here. I reviewed the config and pins are looking good. Looks very similar to my cr10 config. Maybe it is a good idea to add the printer name here. So people know what it is. My nozzle is homing on an endstop insteah of a probe. I added it here for reference and or inspiration. Good Job @rmcbc 

[printercfg.zip](https://github.com/KevinOConnor/klipper/files/2756806/printercfg.zip)

**Comment by rmcbc** [comment]
@derdigge the objective of this config, is not for a specific printer but for people to know what pins to use.
My printer is self made so my configuration is good only for me.
See this only as an example, you have to setup up your end points position , bed size, maximum speed, acceleration, etc.

**Comment by derdigge** [comment]
Kevin asked me to comment so i reviewed all the pins as i finished configs for two printers with that board.

**Comment by rmcbc** [comment]
@derdigge if you have specify printers you should publish those configurations, that way you can help others with the same printers.

**Comment by jakep82** [comment]
I don't think it's wise to include probe, homing override, or bed_mesh sections in a generic board config file.  They have nothing to do with pin mappings, and could lead to future Github issues when people are confused.  It's also not necessary to include details about what drivers you were using in the top comments.  Basically, this should be a copy of the generic-ramps.cfg file, just with different pins and slightly modified comments.  I would also follow that example and comment out the 5th driver.

**Comment by KevinOConnor** [comment]
Thanks.  I agree with @jakep82's comments.  Also, the signed-off-by line should contain a current email address - as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .

I can update the file to make it look like the other "generic-xyz.cfg" files if you prefer.

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor I remove all stuff related to a specific printer and let there only the pin config. And signed the pull request as you said.

**Comment by rmcbc** [comment]
I think now it's cleaner and pin-out oriented.

**Comment by KevinOConnor** [comment]
Thanks.  The example config files need to be valid config files (that specify a [printer] and similar sections) so that we can run the regression tests on them.  (For further details, take a look at how each example config is added to test/klippy/printers.test.)  It's preferable to use simple cartesian printer kinematics for the example configs to try and keep them simple while still being valid config files.

-Kevin

**Comment by rmcbc** [comment]
Done.
Rui.

**Comment by simpson1991** [comment]
hey im using your config, but there is no Display so here is my Config of a RepRapDiscount Display for the skr board maybe you can add these lines for other users :)
And thx for your work it helped me a lot :D

# "RepRapDiscount 128x64 Full Graphic Smart Controller" type displays
[display]
lcd_type: st7920
cs_pin: P0.16
sclk_pin: P0.15
sid_pin: P0.18
encoder_pins: ^P3.25, ^P3.26
click_pin: ^!P2.11

**Comment by jakep82** [comment]
One comment on the Full Graphic display.  I actually hooked this same display up to the SKR board on Saturday and ran into one problem.  The buzzer is connected to pin P1.30, and for me this pin appears to be high by default.  I had to add the following section in my config to turn the buzzer off.

`[static_digital_output my_output_pins]
pins:  !P1.30`

**Pull request closed without merging**
