### PR TITLE
SCREWS_TILT_CALCULATE calculate the number of knob turns to get a perfect bed level.

### PR DESCRIPTION
**Pull request by rmcbc**
Add SCREWS_TILT_CALCULATE calculate the number of knob turns to get a perfect bed level.

IMPORTANT: This only work if you have a BL Touch, Inductive sensor or other type of sensor.

Example config:
  [screws_tilt_adjust]
  screw1: -5,30
  screw1_name: front left screw
  screw2: 155,30
  screw2_name: front right screw
  screw3: 155,190
  screw3_name: rear right screw
  screw4: -5,190
  screw4_name: read left screw
  probe_z_start: 10
  move_speed: 50
  screw_thread: CW-M3

See example-extras.cfg and Manual_Level.md for more information.

Signed-off-by: Rui Caridade <rui.mcbc@gmail.com>

### CODE REVIEW

**Comment by rmcbc** [comment]
Send: BED_SCREWS_CALCULATE
Recv: // probe at -5.000,30.000 is z=2.487500
Recv: // probe at 155.000,30.000 is z=2.460000
Recv: // probe at 155.000,190.000 is z=2.515000
Recv: // probe at -5.000,190.000 is z=2.472500
Recv: // front left screw (Base): X -5.0, Y 30.0, Z 2.48750
Recv: // front right screw : X 155.0, Y 30.0, Z 2.46000 : Adjust -> <O 00:03
Recv: // rear right screw : X 155.0, Y 190.0, Z 2.51500 : Adjust -> O> 00:03
Recv: // read left screw : X -5.0, Y 190.0, Z 2.47250 : Adjust -> <O 00:02
Recv: ok

This means that:
- front left screw is the reference point you must not change it.
- front right screw must be turned should be turned clockwise 3 minutes. <O 00:03
- rear right screw must be turned should be turned counter-clockwise 3 minutes.  O> 00:03
- read left screw must be turned should be turned clockwise 3 minutes. <O 00:02

Notes: When you have for example <O 01:15 it means a a full turn followed by a quarter turn.

**Comment by Stephan3** [comment]
Maybe I got it wrong but isn't this functionality already present with quad_gantry_level ?

**Comment by rmcbc** [comment]
@Stephan3 doesn't look like the same thing, this command tell how much do you have to turn the sprint screw from the bed to level it. I been using for a while and it level the bed perfectly.
The quad_grantry_level seems to be some king of distortion plot, not a system that tell you how much do you have to turn the nobs to level the bed.
But I might be wrong.

**Comment by frankvdh** [comment]
Ummm... In case anyone is thinking of using this with deltas, you shouldn't
be adjusting the bed (once it has been set perpendicular to the towers).
This perpendicularity is a fundamental assumption of delta geometry.
Adjusting the bed to compensate for other geometry errors will introduce
new errors. Adjustment for out-of-level motion of the effector should be
done by adjusting the end-stop positions.

I think the same applies to Cartesian printers... you shouldn't be
adjusting the bed to compensate for an out-of-square X or Y axis.

**Comment by Stephan3** [comment]
@rmcbc oh okay, i got it. You want to do it manualy :D
then good luck

**Comment by KevinOConnor** [comment]
Thanks.  Interesting.  What's the gain of using a probe to level the screws as opposed to levelling the screws with the "paper test"?

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor It's simple, it calculates what knobs to turn, direction and quantity, after two or three interactions the bed is leveled.
Of course, the paper test works also, but I personally like this one more.
It's a different approach to the same problem, if you have something to measure the bed distortion why not using it.

**Comment by jakep82** [comment]
I really like this idea.  I actually created my own gcode macro several weeks ago that probes each corner, and I use the raw data to level my bed.  Having a module that does the math for me would be really nice.

**Comment by KevinOConnor** [comment]
Okay, thanks.  My high-level feedback is that the documentation needs to be more clear that this command and the additional parameters are optional, and that the new command is only available if the printer has an automatic Z probe.

Some comments:
- The code needs to be wrapped to 80 columns.
- It's not a good idea to call G28 from the script.  (Some printers have elaborate homing procedures and it can be impractical to home from a calibration script.)
- self.screws is already available as self.states['screws'].
- Instead of screw_thread and know_direction, how about using config.getchoice() with "M3", "M4", "M5", "CW-M3", etc. options?  (Where CW-M3 would be clockwise M3 bolt.)
- shouldn't the code lookup the probe x/y offset and account for that when probing?  (`printer.lookup_object("probe").get_offsets()`)

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor I follow your tips and complete the documentation.

**Comment by rmcbc** [comment]
@KevinOConnor I'm trying to make "screws_thread" optional but can't find a clean ways to do it, so I use this code:
        try:
            self.thread = config.getchoice('screw_thread', threads,
                                           default="CW-M3")
        except Exception as e:
            self.thread = 0
Is there  better ways to do it?

**Comment by rmcbc** [comment]
@KevinOConnor now it's solved.
Wrote:
self.thread = config.getchoice('screw_thread', threads, default="CW-M3")
A must be:
self.thread = config.getchoice('screw_thread', threads, default='CW-M3')

**Comment by dushyantahuja** [comment]
This is a great idea, will this work with a bed that has only 3 screws?

**Comment by rmcbc** [comment]
I never try with 3 screws but I think the principle is the same. If you can, please try and give us feedback.

**Comment by dushyantahuja** [comment]
Would setting 3 screws in the configuration instead of 4 work?

**Comment by rmcbc** [comment]
[bed_screws]
screw1: x1,y1
screw1_name: front center screw
screw2: x2,y2
screw2_name: rear right screw
screw3: x3,y3
screw3_name: rear left screw
horizontal_move_z: 10
speed: 50
probe_speed: 3
screw_thread: CW-M3

- Replace "x1,y1", "x2,y2" and "x3,y3" with you screw positions.

**Comment by dushyantahuja** [comment]
tried with three screws - received the following error:
Internal error on command:"BED_SCREWS_CALCULATE"
[klippy.log](https://github.com/KevinOConnor/klipper/files/2921106/klippy.log)

**Comment by rmcbc** [comment]
To me it seems that you are configuring the system wrong (my fault I have to limit the screw position looking at steppers limits):
[bed_screws]
screw1 = -20,150
screw2 = 500,0
screw3 = 500,300

But your bed dimensions are much shorter:
[stepper_x]
position_endstop = 0
position_max = 310 
[stepper_y]
position_endstop = 0
position_max = 310

You must move in your case the BLTouch to the position that it stays near the screw and register that position. And must do it to the 3 using you example. You have a 500 that is out side of the X and Y max positions.

**Comment by rmcbc** [comment]
And something is strange because in your log it says:
"NameError: global name 'homing' is not defined"
I don't know what is missing in your config file.
I have this for my 220 x 220 bed and BLTouch :
[bltouch]
x_offset: 35
y_offset: 0
[homing_override]
set_position_z: 0
axes: z
gcode:
	G90
	G1 Z10 F800
	G28 X0 Y0
	G1 X75 Y110 F6000     ;X=110-x_offset
	G28 Z0
	G1 Z15

**Comment by rmcbc** [comment]
I test it with 3 screws and have no error.

**Comment by KevinOConnor** [comment]
Thanks.  I do think this is interesting.  However, I'm a little unsure of how this integrates with the current code.  In particular, I see the current bed_screws.py code as targeting users that don't have an automatic Z probe.  So, I fear adding this to the bed_screws.py code will confuse users that don't have an automatic probe - as just seeing automatic probe options in the config may convince users that lack the hardware to look elsewhere.

I think this might make sense to place in its own "extras" module.  Perhaps screws_tilt_adjust.py?

The other observation is that, at a high level, what this code does is very similar to z_tilt.py.  Just that the code instructs the user to alter the screws instead of directly commanding z motors.  As such, some of the features in z_tilt.py (like using ProbePointsHelper, being able to define screws outside the bed region, being able to defining multiple probe sample counts, being able to define probe points other than at the screw locations themselves, etc.) seem like they would be useful.

As a minor note, FWIW, I find the "O>" to be confusing - perhaps one could use CW and CCW instead?

-Kevin

**Comment by KevinOConnor** [comment]
Thinking about it further, if you have four or more bed screws then you probably want the math in quad_gantry_level.py .  Alas, I'm not sure how the calculations in that module work.  @VoronDesign - do you have a brief description of how the calculations in that module work?

-Kevin

**Comment by rmcbc** [comment]
Going to dot it that way, it's more clean. Thanks @KevinOConnor

**Comment by VoronDesign** [comment]
Quad Gantry is calculating how far the actuators need to move to level a gantry and make it a plane. The math is pretty simple: take 4 points in 3D space. Plot 2 side-to-side lines and find where those lines intersect the Y axis on each side. Then plot 2 more lines that represent the Y axis to find the Z coordinate of the 4 corners. 

In this case the math doesn’t need to be that complicated since you’re probing almost on top of the place you’re adjusting, and the thing you’re trying to correct is already a flat plane (hopefully). The error in this approximation is negligible.

**Comment by rmcbc** [comment]
@KevinOConnor I follow your tips and as @VoronDesign says the Quad Gantry calculations are too complex for this feature, I also think this is enough to get good results.
The important thing of this feature is to get the bed almost leveled and the bed mesh does the fine tuning.

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks okay to me.  I think this code really should use probe.ProbePointsHelper().  Also, please rebase this work into one commit and add the module name and signed-off-by line to the commit message (see - https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md ).

-Kevin

**Comment by rmcbc** [comment]
@KevinOConnor Follow you last tips.
Close this PR and create a new one.

**Pull request closed without merging**
