### PR TITLE
makefile: fix cross build

### PR DESCRIPTION
**Pull request by andryblack**
Allow cross-build Klipper and linux mcu. As example I build openwrt based packages for raspberry-pi.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Some comments:
1. I'm not sure the iquote change is worthwhile - the linux hack works for now and I fear adding complexity to the main makefile.  If it is necessary then it would need to be in a separate commit from the other changes (so that we can easily revert if necessary).
2. I'm not sure I understand the readelf change.  I don't think we should add complexity to the main makefile for it.  Can you explain what the issue is?

-Kevin

**Comment by andryblack** [comment]
Sorry, but I dnt see additional complexity on this changes at all. This allow build linux-mcu on different hosts: x86 linux, macos without local patching makefiles.It is same as build firmare on as example for stm32. You dnt install gcc and other build tools on stm32 boards, instead build it on `big` host.

**Comment by KevinOConnor** [comment]
FWIW, I don't understand what the readelf change does.  In general, I'd prefer not to make platform specific changes to the main makefile (in particular, for not common platforms like macos).

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  It looks like the conversation has concluded on this, so I think we can close it.

-Kevin

**Pull request closed without merging**
