### PR TITLE
avrsim: migrated to Python 3

### PR DESCRIPTION
**Pull request by dmbutyugin**
Note that the latest simulavr 1.1.0 does not support Python 2 anymore.

Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by dmbutyugin** [comment]
@KevinOConnor Note that this patch does not require the rest of Klipper to be migrated to Python 3. I have run it in this hybrid mode - avrsim running with Python 3, but the main Klipper running with Python 2.

FWIW, it looks like one cannot get simulavr running with Python 2 these days (I was not able to build an older release such that it actually runs with Klipper, and the latest release 1.1.0 only works with Python 3). So it may make sense to integrate this patch into the mainline Klipper ahead of the full migration to Python 3, as a new developer may not be able to debug Klipper under simulavr otherwise.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by KevinOConnor** [comment]
Oh - I missed this PR was for the work-python-20200616 branch.  I'll bring it over to the master branch.  I don't see a concern with porting some of the standalone scripts to Python3.

Cheers,
-Kevin

**Comment by dmbutyugin** [comment]
@KevinOConnor Hmm, this `work-python-20200616` branch does not exist, does it? Anyway, I sent this pull request for the branch with active work on Python 3 support because I was not sure about your plans for the master. Though it would make sense to port this script to Python 3 already, since right now I do not see any other way to run Klipper under the simulavr emulator. And it can be handy on some occasions.

**Comment by KevinOConnor** [comment]
Sorry, meant work-python3-20200616 branch.

I also committed this to the master branch (commit 054762da).

-Kevin

**Pull request merged**
