### PR TITLE
Lulzbot TAZ6 w/ Dual v3 Toolhead Config

### PR DESCRIPTION
**Pull request by radensb**
module: LULZBOT TAZ6 DUAL V3 CONFIG FILE SUPPORT

Detailed config file for supporting all features of Lulzbot TAZ6 with dual v3 toolhead.

Signed-off-by: Ryan Densberger <magshooterz@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks good to me.

One thing that I think should be changed though, is that the sample config files shouldn't copy-and-paste the parameter descriptions from example-extras.cfg.  Also, it would be preferable if they didn't have commented out config settings.  The reason for this is, from time to time we change the parameter descriptions and sometimes change the parameter names.  It becomes a maintenance burden to have to find and update every instance of the old parameters in comments of example config files.

-Kevin

**Comment by radensb** [comment]
My thought in leaving some of the settings commented was to illustrate some of the defaults that I figured could be useful tweaks, however, I see your point with things changing and the maintenance upkeep. I have just made some advancements to this config using the jinja syntax to optimize some macros and remove redundancy. I will merge those changes and remove the commented settings to update the PR as you suggest. Thanks Kevin.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by lbibass** [comment]
So, just to clarify: this config supports the washer style homing system that the TAZ 6 uses? 

Therefore, just some copy and pasting of the homing routines should allow this config to work with the TAZ 6 with just a single extruder?

**Comment by radensb** [comment]
> So, just to clarify: this config supports the washer style homing system that the TAZ 6 uses?

Correct.

> Therefore, just some copy and pasting of the homing routines should allow this config to work with the TAZ 6 with just a single extruder?

Yes. In fact, there is a member, clee, from the lulzbot forums that was testing my config with modifications to support the single extruder. I assume that he will update the single extruder config submission when it gets worked out. If using my config, anything that has coordinates with regards to the nozzle will need to be adjusted. I used the stock Lulzbot START block coordinates and factored in the delta Y and delta X offsets for my dual toolhead manually. The same could be done for the single extruder toolhead. I think you only need to tweak the location of the home switch, wiper pad, and where you want the single nozzle to land on the washers.

**Pull request merged**
