### PR TITLE
update avrsim pty attr

### PR DESCRIPTION
**Pull request by kargeor**
Signed-off-by: Georgios Karnas <kargeor@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I'm not sure what's being fixed here.  The create_pty() code is the same code that the main klippy.py process uses to create its pseudo-tty (see klippy/util.py:create_pty() ), and I've seen reports in the past that the code runs on OSX.

-Kevin

**Comment by kargeor** [comment]
This helped me solve a "transient" problem where the pty would not work around half of the time I started the sim.
By reading the [unix docs](https://linux.die.net/man/3/tcgetattr), I found that problems can exist when sending binary data, and there exists a function `cfmakeraw()`. The code here does the equivalent settings.

**Comment by KevinOConnor** [comment]
I'm not sure what the status of this PR is.

My feedback is that it would need to pass the build test cases and the updates to avrsim.py should follow the existing conventions of that file (specifically, not using `from termios import *` syntax).  Also, it would help if we could narrow down to the particular termios setting that is important to set.

Thanks,
-Kevin

**Comment by kargeor** [comment]
> My feedback is that it would need to pass the build test cases and the updates to avrsim.py should follow the existing conventions of that file (specifically, not using `from termios import *` syntax).

I can do that.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
