### PR TITLE
Upgrade pyserial version, set exclusive access when opening serial ports on POSIX systems.

### PR DESCRIPTION
**Pull request by DanielJoyce**
Latest PySerial version is 3.4. Upgrading to this will allow us to exclusively access serial ports on POSIX systems.

### CODE REVIEW

**Comment by DanielJoyce** [comment]
I just the exclusive access fix here since its small and makes.

**Comment by KevinOConnor** [comment]
Thanks.  I agree we should upgrade to the latest version of PySerial.  However, in practice most people don't rerun the install scripts on an upgrade.  This means:
- We should upgrade all the dependencies to the latest versions and verify everything works well.
- We'll need to check the dependencies and give a sane error message if they are not met.  (Otherwise, we'll get flooded with error reports.)
- Document the upgrade requirement in docs/Config_Changes.md .
- I've been meaning to try Jinja2 support in Klipper.  If more packages will be needed, I'd prefer to batch that change with any package upgrades.

So, I agree with this change, but I think we're a month or so out from merging it.  (I don't expect you to accomplish all of the above.)

-Kevin

**Comment by DanielJoyce** [comment]
Then it sounds like upgrade needs to rerun part of install, or at least run pip install, and split out the requirments into a pip_requirements.txt file.

**Comment by KevinOConnor** [comment]
The recommended software upgrade steps do include package dependency checks: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-upgrade-to-the-latest-software

But, I know in practice that many people skip the full upgrade steps.  So, if we change the package dependencies I think we need to also make it more clear to users that they do need to rerun the full steps.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, as part of the merge of PR #1141, I've updated the version requirements of all the python packages.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  Now that the prerequisites have been updated, I've gone ahead and reapplied the original patch (commit 7373e920).

-Kevin

**Pull request closed without merging**
