### PR TITLE
bed_mesh:  Account for Probe Offsets in configuration

### PR DESCRIPTION
**Pull request by Arksine**
This request modifies the ProbePointsHelper class to optionally subtract the x and y probe offsets from the supplied points.  

Also included are several other updates:
- Logging is now improved, and it is now possible to print generated points to the terminal
- Some attributes are refactored with names that are more descriptive
- Checks on interpolation are tightened.  Its no longer possible to use lagrange interpolation for more than 6 samples.

Finally a bed_mesh.md document has been added that hopefully better explains how to configure bed_mesh and its various options.

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!  In general it looks good to me.  I have a couple of minor comments:

1. If ProbePointsHelper.use_offsets is enabled, should the finalize_callback() code be passed coordinates with the X, Y, and Z offsets applied?  If at some later point we change ProbePointsHelper to apply them, will that adversely impact the bed mesh code?  The reason I ask is that PR #2218 (along with the now closed #1611) ultimately want to have different XYZ offsets for each probe attempt.  In the long run, applying the offsets within ProbePointsHelper may make that easier to accomplish.

2. The phrase "probe offsets are accounted for" is used a few times in the new documentation.  I wonder if we could find an alternative phrase as I find that wording to be confusing (the probe offsets have always been accounted for by the bed mesh code).  Maybe something like: "the coordinates are relative to the probe location".

3. Just out of curiosity, will this new code make it any easier to account for issue #1482?

4. The documentation indicates "all saved profiles will need to be manually removed from the SAVE_CONFIG section".  What happens if a user does not manually remove an existing profile?

-Kevin

**Comment by Arksine** [comment]
Hi Kevin, some answers to your questions:

1) The finalize() callback for Bed Mesh can be easily modified to accept coordinates that are already offset.    In fact, 67b0b19b2a29833d13845c2e949f5c8b7f8f3c83 helps accomplish this, as it moves the application of the X and Y offsets out of the ZMesh class.   I would simply need to remove the application of the X,Y, and Z offsets from the finalize() callback.  I can add that to this PR if you would like.

2) You have a good point.  I'll change the docs.

3) I completely forgot about that issue.  I think its an easy fix, I just need to apply an X and/or Y offset to the Z lookup.  There are two ways I could go about this.  The first is to simply create a new bed_mesh gcode, something like BED_MESH_OFFSET X=x Y=y that allows the user to change the offset.  The other option is to have SET_GCODE_OFFSET look up the bed_mesh printer object, and if it exists it could call a function that passes the offsets to the mesh.

4)  Unfortunately the mesh will be applied incorrectly if they don't remove the old profiles.  The min_x, min_y, max_x, and max_y now already have their respective x and y offsets applied...so an old profile will contain the wrong values.  I could add some code to create backward compatibility with those old profiles if you think it is prudent.  The old profiles contain x and y offsets, whereas a new one will not.  I could attempt to parse them from the config and if they exist I can add them to the min/max values.

**Comment by KevinOConnor** [comment]
Thanks.

> The finalize() callback for Bed Mesh can be easily modified to accept coordinates that are already offset. In fact, 67b0b19 helps accomplish this, as it moves the application of the X and Y offsets out of the ZMesh class. I would simply need to remove the application of the X,Y, and Z offsets from the finalize() callback. I can add that to this PR if you would like.

Okay, great.  So, it sounds like the coordinates stored in the user's config file have the offsets applied?

It's fine if you wish to make the change to finalize_callback() now, but I don't think it needs to be tied to this PR.

> I think its an easy fix, I just need to apply an X and/or Y offset to the Z lookup. There are two ways I could go about this. The first is to simply create a new bed_mesh gcode, something like BED_MESH_OFFSET X=x Y=y that allows the user to change the offset. The other option is to have SET_GCODE_OFFSET look up the bed_mesh printer object, and if it exists it could call a function that passes the offsets to the mesh.

I'd say add `BED_MESH_OFFSET`.  It doesn't need to be tied to this PR though.

> Unfortunately the mesh will be applied incorrectly if they don't remove the old profiles. The min_x, min_y, max_x, and max_y now already have their respective x and y offsets applied...so an old profile will contain the wrong values. I could add some code to create backward compatibility with those old profiles if you think it is prudent. The old profiles contain x and y offsets, whereas a new one will not. I could attempt to parse them from the config and if they exist I can add them to the min/max values.

I don't think we need to be backwards compatible.  However, if it's possible to detect that a profile is invalid then I'd suggest not loading it during startup (and thus not save it during the next SAVE_CONFIG).  That way, we could make the Config_Changes.md say something like "reprobe all current profiles as existing profiles will no longer work" instead of asking the user to manually clear the config file.  Thoughts?

-Kevin

**Comment by Arksine** [comment]
I went ahead and fixed up the documentation, hopefully it will make a bit more sense for readers.

>Okay, great. So, it sounds like the coordinates stored in the user's config file have the offsets applied?

Yes, this is correct.

>I'd say add BED_MESH_OFFSET. It doesn't need to be tied to this PR though.

Sounds good on BED_MESH_OFFSET.  

>I don't think we need to be backwards compatible. However, if it's possible to detect that a profile is invalid then I'd suggest not loading it during startup (and thus not save it during the next SAVE_CONFIG). That way, we could make the Config_Changes.md say something like "reprobe all current profiles as existing profiles will no longer work" instead of asking the user to manually clear the config file. Thoughts?

I think your suggestion of detecting old profiles and skipping them is a good idea.  What I think I will do is add a "version" option to each saved profile.  If it doesn't exist then I know its an old profile.  This also gives us a graceful way of dealing with incompatible profiles in the future should they need to change again.

If the profile is incompatible I'll tag them for removal and print a message to the log. After the printer is ready I'll check for incompatible profiles and remove then using `configfile.remove_section()`.

**Comment by KevinOConnor** [comment]
Thanks.  As we discussed off-line, given the holidays, this is something that I think we should look to merge in early January.

-Kevin

**Comment by glowtape** [comment]
Would probably worthwhile to include an example of some actual math that spits out the mesh_min and _max coordinates from the actual area you want to probe in respect to the probe offset. And some blurb about choosing sufficient distance from the bed edges according to probe offsets and actual toolhead freedom. At the very least over in the Voron Discord, people keep getting confused about it.

**Comment by Arksine** [comment]
@glowtape When this is merged mesh_min and mesh_max will directly define the boundaries that will be probed, so no math should be required.  For example, if you want a mesh that starts probing at (30,30) and ends at (220,220), those coordinates are your mesh_min and mesh_max.  The math is done internally to move the tool to the correct position so the probe is centered at (30,30) to begin.
 
 One reason for this pull request is the confusion you mention. as I'm sure you are aware, in the old (current) implementation people must define the tool position rather than the mesh position.

I can add something about choosing coordinates that will not move the tool outside of the configured x/y boundaries.  I'm hesitant to use language here with regards to the bed, as on some printers its perfectly acceptable to move the tool off of the bed during probing.

**Comment by JohnEdwa** [comment]
My current bed is 235x235, my X max is 253, and my probe offset makes it so that the maximum X I can probe it's something like X212.   
If I tell this to probe X10 to X225, will it go as far as it can (X212), or will it error out requiring me to calculate what the actual max I can ask is?   
With Marlin, you (can) do it from the other way, you set the minimum inset from the edges of the bed (in this case 10) and it probes as close as it can.

**Comment by Arksine** [comment]
@JohnEdwa You will get an error during the probing procedure if the tool moves out of bounds.  Doing boundary checking tricky due an infinite number of different printer configurations in Klipper.  Marlin's configurations are hardcoded, this makes it easier for them to support something like you describe.

Certainly I could add more configuration options that clearly define the bed location, the tool range, and a mesh inset, then clip the mesh based on that information.  Perhaps I will look into it for a future PR.  At this point I don't feel that the tradeoff of requiring more configuration vs requiring the user to calculate their maximum tool range is worth it.

**Comment by JohnEdwa** [comment]
> Marlin's configurations are hardcoded, this makes it easier for them to support something like you describe.

Marlin overall has a "soft" boundary checking, as an example if your firmware limit is lower than what you set up in your slicer (Ender 3 default is 220x220 and you set 235x235 in Cura) it just clips everything above 220 to 220. Which to be honest I kinda feel is too dumbed down.

>I can understand the advantage of the "user friendly" approach of Marlin's method, however I don't love the idea "just doing what's close enough" when the module is not correctly configured

But if you don't, then this changes very little as it would still require the user to manually calculate "[bed_mesh] max_point = [stepper_x] position_max + [bltouch] x_offset". It doesn't matter much if the probe offset is on one side of the equation or the other.   

>Doing boundary checking tricky due an infinite number of different printer configurations in Klipper.

I think the biggest problem that would solve a lot of issues is that Klipper doesn't actually have any idea of the concept of the bed size, unlike Marlin. You have endstops, min and max axis positions, but nowhere in the config do you say "The bed is physically 235 by 235". As far as Klipper is concerned, my bed is from X0 to X252 by Y-4 to Y235.

If in the [printer] section you were forced to set up the bed_x_size and bed_y_size, they could then be used, with all the offset and such, to simply say "the bed mesh inset of 30 means probe as close as you possibly can between30 to bed_width-30" and so on.

**Comment by Arksine** [comment]
>But if you don't, then this changes very little as it would still require the user to manually calculate "[bed_mesh] max_point = [stepper_x] position_max + [bltouch] x_offset". It doesn't matter much if the probe offset is on one side of the equation or the other.

This pull request addresses confusion about the mesh location in the configuration.   They thought that min_point and max_point were referencing the probe when it was referencing the nozzle.  That is now resolved.

I'm willing to consider creating a tool to help the user with calculating the absolute min/max points the mesh can be, however not as part of this pull request.  I think it would require some work in the kinematics modules, otherwise bed_mesh would have to fetch configuration for each type of kinematics, and bed_mesh would have to be updated each time new kinematics are added.  That would not be an ideal scenario.

**Comment by mtw3d** [comment]
> If in the [printer] section you were forced to set up the bed_x_size and bed_y_size, they could then be used, with all the offset and such, to simply say "a bed mesh inset of 30 means probe as close as you possibly can between 30 to bed_width-30" and so on.

Just FWIW, if you implement these settings, you would also need to add a `bed_min_x` and `bed_min_y` setting, because the 0,0 point is not always the min point

**Comment by JohnEdwa** [comment]
>Just FWIW, if you implement these settings, you would also need to add a bed_min_x and bed_min_y setting, because the 0,0 point is not always the min point

Where the 0,0 bed corner is located is an offset from the axis endstop locations, and Klipper already has "position_endstop" for this. The bed *size* is a measurement in millimetres from 0 to some value, as that's how you measure things.

**Comment by mtw3d** [comment]
Ok, that makes sense!

**Comment by Arksine** [comment]
@JohnEdwa While that is true, it is also possible that the tool's range is beyond the bed area, so it can't be assumed that the bed starts at position_endstop.

**Comment by JohnEdwa** [comment]
Isn't the "position_endstop" defined as being an offset from the edge of the bed in the first place? I guess technically I could have my bed start at X-4 Y-9 if I wanted to, but I don't see a reason for anyone not to place X0 Y0 at the corner of the bed (at least the printable area of it).

For me, the X-axis "position_endstop" is -4, because once I've homed the X-axis, the 0 of the bed is 4mm away. The bed then continues for 235mm which is the part Klipped doesn't know about, and position_max is at 253, as that is how far it can travel before hitting something and what I need so my BLtouch can get as close to the edge as possible (X-offset being -43mm, as it's on the left side of the print head).

**Comment by glowtape** [comment]
position_endstop is the position in coordinate space relative to the bed's zero point (IIRC). If your 0,0 is in the middle, position_endstop would be way negative. Or way large if your endstops at at the maximum position. I have a 300x300mm bed, with zero in the minimum corner and position_endstop is 305mm and 303mm for X and Y respectively.

**Comment by glowtape** [comment]
I ran this today on the latest master. Appears to work fine and as intended.

**Comment by Coffee0297** [comment]
@Arksine have the ``BED_MESH_OUTPUT`` changed? it seems like it outputs the real probed points insted on the bicubic/legrange mesh as is in printer.cfg? 

i made a 12x12x3 mesh, wich in ``BED_MESH_OUTPUT`` gave me a 34x34? grid of numbers.
i dont get the 34,34 as its 36,36? 

if i rember corect before the change it was the legrange/bicubig mesh it outputed. 
like = https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/issues/92#issuecomment-430741520

its bugging the bed mesh virtualiser and its not the real mesh

you can also just ping me on discord in annex server (coffee)

-Tonny

**Comment by Arksine** [comment]
@Coffee0297 If you create an issue and include a log file, along with the terminal output from bed_mesh output, I can probably do more to help.

The short answer is that the only change to BED_MESH_OUTPUT is the addition of the PGP option, for example:
```
BED_MESH_OUTPUT PGP=1
// bed_mesh: generated points
// Index | Tool Adjusted | Probe
// 0 | (11.0, 1.0) | (35.0, 6.0)
// 1 | (52.0, 1.0) | (76.0, 6.0)
// 2 | (93.0, 1.0) | (117.0, 6.0)
// 3 | (134.0, 1.0) | (158.0, 6.0)
// 4 | (175.0, 1.0) | (199.0, 6.0)
// 5 | (216.0, 1.0) | (240.0, 6.0)
// 6 | (216.0, 39.4) | (240.0, 44.4)
// 7 | (175.0, 39.4) | (199.0, 44.4)
// 8 | (134.0, 39.4) | (158.0, 44.4)
// 9 | (93.0, 39.4) | (117.0, 44.4)
// 10 | (52.0, 39.4) | (76.0, 44.4)
// 11 | (11.0, 39.4) | (35.0, 44.4)
// 12 | (11.0, 77.8) | (35.0, 82.8)
// 13 | (52.0, 77.8) | (76.0, 82.8)
// 14 | (93.0, 77.8) | (117.0, 82.8)
// 15 | (134.0, 77.8) | (158.0, 82.8)
// 16 | (175.0, 77.8) | (199.0, 82.8)
// 17 | (216.0, 77.8) | (240.0, 82.8)
// 18 | (216.0, 116.2) | (240.0, 121.2)
// 19 | (175.0, 116.2) | (199.0, 121.2)
// 20 | (134.0, 116.2) | (158.0, 121.2)
// 21 | (93.0, 116.2) | (117.0, 121.2)
// 22 | (52.0, 116.2) | (76.0, 121.2)
// 23 | (11.0, 116.2) | (35.0, 121.2)
// 24 | (11.0, 154.6) | (35.0, 159.6)
// 25 | (52.0, 154.6) | (76.0, 159.6)
// 26 | (93.0, 154.6) | (117.0, 159.6)
// 27 | (134.0, 154.6) | (158.0, 159.6)
// 28 | (175.0, 154.6) | (199.0, 159.6)
// 29 | (216.0, 154.6) | (240.0, 159.6)
// 30 | (216.0, 193.0) | (240.0, 198.0)
// 31 | (175.0, 193.0) | (199.0, 198.0)
// 32 | (134.0, 193.0) | (158.0, 198.0)
// 33 | (93.0, 193.0) | (117.0, 198.0)
// 34 | (52.0, 193.0) | (76.0, 198.0)
// 35 | (11.0, 193.0) | (35.0, 198.0)
```

The output from BED_MESH_OUTPUT has remained unchanged. It first prints some mesh data with the "info" prefix, then prints the interpolated mesh straight to the terminal.  Visualizers should be able to capture that data.

As far as your grid, 34 sounds correct if you are using default values for mesh_pps.  If you have 12 probed points on an axis you have 11 segments.  If you are interpolating and 2 points per segment, that is 11 * 2 = 22 interpolated points.  Add the 12 probed points and you have a mesh size of 34 points along that axis.

**Comment by Coffee0297** [comment]
@Arksine there you go 👍 
-Tonny

**Comment by shanewarner** [comment]
Was the BED_MESH_OFFSET feature ever implemented?

**Pull request merged**
