### PR TITLE
Some additions to temperature and LCD Menu pins (Wanhao i3)

### PR DESCRIPTION
**Pull request by cfelicio**
Hi Kevin,

Thanks so much for your explanation on how to find the pins for the LCD. I was able to get it working on my Wanhao, so I'm submitting the change to help other people in case they stumble on the same issue.

I also had very odd temperature readings using the example config file, and that was fixed by changing the pullup_resistor value, as suggested in a Wanhao Forum.

Signed-off-by: Carlos Felicio (cfeliciomobil@gmail.com)

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  The filename shouldn't be changed (the 2017 is for when the printer was released).  On the encoder pins, does "^!PA2, ^!PA1" work better than "^PA2, ^PA1" for you? (On my ramps board, I need to remove the ! or there is a delay in response when going clockwise to counter-clockwise and vice-versa.)

-Kevin

**Comment by cfelicio** [comment]
Umm, good question. It seems to be working well, but let me try with the alternative setting to compare, and I will let you know. I will make another edit to revert the file name back and potentially change this one if it works better. :)

**Comment by cfelicio** [comment]
Ok I tried it out, it feels a little more responsive with your suggestion. Thanks Kevin! :)

**Comment by KevinOConnor** [comment]
Thanks.  I reworded the pullup comment and committed this change (commit 79632878)

-Kevin

**Pull request closed without merging**
