### PR TITLE
extruder_stepper: Support changing synced extruder on the fly

### PR DESCRIPTION
**Pull request by theophile**
Add support for syncing to active extruder and changing synced extruder via extended gcode

Signed-off-by: Christopher Meredith <chmeredith@gmail.com>

### CODE REVIEW

**Comment by ndupont-net** [comment]
This looks great, do you think it would be feasable to extend it further to allow an extruder to be synced to another one ?
With all that COVID nonsense, I've had the opportunity to print in duplicate mode with the chimera in spite of the meager 17.5mm space between the nozzles. I currently have to edit printer.cfg to swap pins back and forth to activate that duplicate mode.

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback is that this looks useful and would be good to merge.  I have a few comments:

1. Do we need a `sync_to_active` config option?  I suspect users would already be defining gcode_macros for ACTIVATE_EXTRUDER, and thus it would not be difficult to also switch any extruder_stepper devices in the same macros.
2. We want to avoid directly accessing `extruder.stepper` from external code, as this becomes a maintenance burden (this is described briefly in docs/Code_Overview.md).  I suggest replacing `extruder.set_trapq()` with a new `extruder.sync_stepper_to_extruder(stepper)` function that does both the trapq setup and the set_position() work.  Then use that in extruder_stepper.py.
3. The command name SET_EXTRUDER_STEPPER could be misleading.  How about SYNC_STEPPER_TO_EXTRUDER instead?
4. The call to `printer.lookup_object()` can return an error - use `printer.lookup_object(extruder_name, None)` and then explicitly check for None and raise a gcode error if it's not valid.  (Otherwise, an invalid name would result in a "internal error" shutdown.)
5. This work will conflict slightly with #2824.  FYI, I plan to merge #2824 first.

-Kevin

**Comment by theophile** [comment]
Thanks @KevinOConnor. 

1. You're probably right about not needing the `sync_to_active` config option. That was a case of including it because I could. I'll take it out to simplify matters.
2. I'll give this a shot and see if I can figure out how to do that. FWIW, the existing extruder_stepper.py already directly calls `extruder.set_trapq()` so even if this PR doesn't end up getting merged, that may need to be fixed.
3. I agree and had the same thought. I'll fix that.
4. I will take a look and see if I can figure it out.
5. I assume this refers to the "Use new GCodeCommand wrappers" commits. I'll update to use the new convention.

**Comment by theophile** [comment]
OK @KevinOConnor, I fixed 1, 3, 4, and 5. I started attempting #2 but it quickly became apparent that I was in over my head. I figured I'd go ahead and push what I had for now.

**Comment by theophile** [comment]
FWIW, I'd like to request a variance on Travis's insistence on an 80-character max line length for this one. The only reason for the above failed check is that line 35 of extruder_stepper.py is 81 characters long. I've seen a couple other places in the current code where a line runs slightly longer than 80 characters so I was hoping this one would be OK.

**Comment by KevinOConnor** [comment]
All of the code is currently limited to 80 characters.  Unfortunately, making exceptions is much more work than keeping everything to 80 characters.  For this case a simple solution is to do `epos = extruder.stepper.get_command_position()` and then use epos on the following line.  Note, however, that directly accessing the `extruder.stepper` member variable is not something we'd want to do (https://github.com/KevinOConnor/klipper/pull/2824#issuecomment-623706409).

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by theophile** [comment]
@KevinOConnor, sorry about the delay. I've fixed the line-length problem, which I think leaves only your comment about directly accessing `extruder.stepper` from external code. I fear that is beyond my skill level to address. If that's a deal breaker then I guess this PR should be closed unless someone else can handle that part. On the other hand, the existing extruder_stepper.py in master already directly calls `extruder.set_trapq()`, so if that is going to have to be changed anyway, maybe this PR could be merged first and then the whole file updated.

**Comment by KevinOConnor** [comment]
Thanks.  I merged this and a follow up commit to avoid accessing the internal extruder state (commit 739e6e73).

-Kevin

**Pull request merged**
