### PR TITLE
TMC2130 spi daisy chain 

### PR DESCRIPTION
**Pull request by smark-**
Starting from @sensile work, I've implemented the possibility to have multiple tmc2130 drivers in a daisy-chain configuration. The same can be applied to the TMC5160 but I plan on making a separate pull request should this be merged

### CODE REVIEW

**Review by KevinOConnor — COMMENTED** [review]
Thanks.  See my comments below.

Also, the signed-off-by line would need to contain your full name - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md 

-Kevin

**Comment by smark-** [comment]
Thank you very for your review @KevinOConnor. I agree with your feedbacks and I've changed it accordingly.

**Comment by KevinOConnor** [comment]
Okay, thanks.  However, it looks like this code still uses "shared pins", would create multiple objects in the micro-controller for a single chain, and each instance would have its own mutex instead of using one mutex for the whole chain.

-Kevin

**Comment by smark-** [comment]
Hi @KevinOConnor, the only reason to have "shared_pins" is to get rid of the error given by the same pin used multiple times as cs_pin. How do you suggest to solve it otherwise?

**Comment by KevinOConnor** [comment]
The solution is to have a single host object for all drivers using a chain (with a single spi object, and a single mutex).  This is necessary because otherwise a register read operation on one driver could race with an operation on another driver and the results would be corrupted.  (That is, a single mutex is necessary to ensure only one driver on a chain is using that chain at any given time.)  As an example, see how tmc_uart.py handles this (there is only one instance of a MCU_TMC_uart_bitbang class for all tmc drivers that share a uart pin.)

-Kevin

**Comment by smark-** [comment]
I've changed such as a single instance of MCU_TMC_SPI is created to prevent a race condition. I've also extended the feature to the TMC5160

**Review by KevinOConnor — COMMENTED** [review]
It does look like it is getting closer.  However, every stepper motor driver needs to have its own unique `fields` object - it isn't valid for multiple drivers to share the same instance.  Thus, I think there should be one MCU_TMC_SPI object for each stepper motor driver, and one "MCU_TMC_spi_chain" for each chain.  (As tmc_uart.py does it.)

-Kevin

**Comment by smark-** [comment]
@KevinOConnor I hope I've closed the gap. Let me know

**Comment by smark-** [comment]
@KevinOConnor did you have the time to check this out?

**Comment by KevinOConnor** [comment]
I did take a look.  The code is still using a mutex for every driver instead of sharing the same mutex for all drivers on the chain.  When I get a chance I'll try to put together the changes to show what I think the code should look like.

-Kevin

**Comment by smark-** [comment]
Hi @KevinOConnor , did you have the time to prepare an example for me to fix the code?

**Comment by KevinOConnor** [comment]
Sorry - I haven't been able to.  The main issue is that a new mutex is created in every MCU_TMC_SPI class instance - but a single mutex needs to be shared between every MCU_TMC_SPI_chain class - otherwise the locking doesn't actually prevent a single spi chain from being used by two different drivers at the same time.

-Kevin

**Comment by smark-** [comment]
No problem. I've moved the mutex from the MCU_TMC_SPI class instance to the MCU_TMC_SPI_chain class instance which is shared amongst all the steppers on the same chain. @KevinOConnor could you check if this solution works?

**Comment by smark-** [comment]
@KevinOConnor did you have the chance to review my last commit?

**Comment by KevinOConnor** [comment]
Thanks.  I rebased this branch and made some changes to the config reading.  That code is available on the work-tmcspi-20210220 branch (commit d3b3a65b).  If you can confirm that code works and you are okay with changes then I'll go ahead and commit it.

-Kevin

**Comment by smark-** [comment]
Hi Kevin, there's just a simple issue. The variable "ppins" is not defined in the lookup_tmc_spi_chain function. I've tried to push the change to the work-tmcspi-20210220 branch but I'm not allowed to. If you fix that, the rest works just fine

**Comment by KevinOConnor** [comment]
Thanks.  I committed it to the master branch (commit c7688c6b).

-Kevin

**Pull request closed without merging**
