### PR TITLE
heater: Add get_status() function

### PR DESCRIPTION
**Pull request by simonkuehling**
This gives access to a list of available heater names in gcode macros as printer.heater.available_heaters (Edited after change of implementation, see conversation below)

Signed-off-by: Simon Kühling <mail@simonkuehling.de>

### CODE REVIEW

**Comment by simonkuehling** [comment]
Hi Kevin - this is my proposed solution to issue #2094 .
Happy to hear your thoughts on this, or if you would change anything.
- Simon

**Comment by KevinOConnor** [comment]
Thanks.  As a high-level comment, it seems a little odd to be listing the g-code id from the heater get_status().  I would think that heater's get_status() would contain something like: { 'available_heaters': ["extruder", "extruder1", "bed_heater"] }.  The g-code id is an attribute of the heater, so I would think it would be something found in each heater's get_status() method.

FWIW, another approach to this issue might be to add a `SHOW_HEATERS` command.  For example, something like:
```
SHOW_HEATERS
// HEATER=extruder GCODE_ID=T0 TEMPERATURE=202.4 TARGET=200
// HEATER=extruder1 GCODE_ID=T1 TEMPERATURE=25.2 TARGET=0
// HEATER=heater_bed GCODE_ID=B TEMPERATURE=60.0 TARGET=60
```

-Kevin

**Comment by simonkuehling** [comment]
Thanks for your comments!

I agree that the gcode_id is generally an attribute of each heater. I think I might have been under the false assumption that the gcode_id was only defined in generic_heater instances (where it is sourced from the config during initialization) - but not defined in the extruder or heater_bed objects. Looking into the code again, I was probably wrong with that...

In this case, a `heater.get_status() --> { 'available_heaters': ["extruder", "extruder1", "bed_heater"] }` would totally make sense to me, as you suggested.

A `SHOW_HEATERS` command would be an alternative, but I would think the above method would be more universal - as you can easily implement this as a macro once `printer.heater.available_heaters` would be available.

Shall I change the PR to the `available_heaters` route, then?
Or is it better to open a new PR, reference that on here and close this one?

**Comment by KevinOConnor** [comment]
> Shall I change the PR to the available_heaters route, then?
Or is it better to open a new PR, reference that on here and close this one?

It's a little easier to update this PR, but either approach is fine.

-Kevin

**Comment by simonkuehling** [comment]
I just found a challenge with the new implementation: While we do now have access to the list of available heaters through `printer.heater.available_heaters`, there is no consistent access to query each heater's `get_status()` in a macro right now (where I would provide the gcode_id information) - as "extruder", "extruder1" and "heater_bed" can be accessed via
```
printer.extruder
printer.extruder1
printer.heater_bed
```
but generic heaters can only be accessed through e.g.
```
printer["generic_heater chamber_heater"]
```
My goal was to be able to do a "reverse lookup" of the heater name from its gcode_id in a macro - to build a `SET_HEATER_TEMPERATURE_BY_GCODE_ID` command. Maybe it is a good idea to have the mapping provided through the PrinterHeaters class after all?

**Comment by KevinOConnor** [comment]
It's possible to always use the second form - for example:
```
{ for name in printer.heater.available_heaters }
    ECHO { printer[name].gcode_id }
{ endfor }
```

-Kevin

**Comment by simonkuehling** [comment]
For all standard type heaters (extruders, heater_bed) that is working both ways, correct. The problem is that any `[heater_generic]` heater is not available through its name alone:

What works:
```
printer.extruder
printer.extruder1
printer.heater_bed
printer.["extruder"]
printer.["extruder1"]
printer.["heater_bed"]
printer.["heater_generic chamber_heater"]
```
but not
```
printer.chamber_heater
printer["heater_generic extruder"]    // obviously...
```
From the heater name itself we cannot check whether it is a standard type heater or one configured through the `[heater_generic]` module... I mean, without actually matching the name against a pattern of known "system" names like `extruder`, `extruder1`, `heater_bed` etc in the macro. But this isn't feeling like the right way to do it for me.

Ideas to solve this:
* We could add a consistent access route to all heaters by name through the `PrinterHeaters.get_status()` like `heater.get_status() --> { 'available_heaters': ["extruder", "extruder1", "heater_bed"], 'extruder': extruder.get_status(), 'extruder1': extruder1.get_status(),... }`. But again, that is not very clean as well because of its redundancy.
* Instead of returning a list of names, we could return the heater.get_status() objects themselves through `PrinterHeaters.get_status()` like `heater.get_status() --> { 'available_heaters': [extruder.get_status(), extruder1.get_status(), heater_bed.get_status()]`.
The could be used like this:
```
{% for heater in printer.heater.available_heaters %}
    ECHO { heater.gcode_id }
{% endfor %}
```

**Comment by simonkuehling** [comment]
That would be consistent, right. The change would also need some minor adjustments in `[verify_heater]` - most obviously the config name declaration would need to change from

```[verify_heater my_custom_heater]```
to
```[verify_heater heater_generic my_custom_heater]```
but that should be pretty readable and easy to understand still, do you agree?

**Comment by simonkuehling** [comment]
@KevinOConnor I just updated the PR with an implementation of the changes needed. Besides making sure your build server checks are all passing, I also verified it to work on my test setup that has a `[heater_generic chamber_heater]` with `[heater_fan]` and `[verify_heater]` running.

The `SET_HEATER_TEMPERATURE` command does accept the new heater name format with spaces in it just fine, as long as there are quotes around it. Example:
```SET_HEATER_TEMPERATURE HEATER="heater_generic chamber_heater" TARGET=80```

**Comment by KevinOConnor** [comment]
Thanks.  I'd say it is mostly there, but there are a few changes that I think should be made.

I don't think it is worthwhile to break all the current generic_heater users - instead, register_sensor() can just do something like `self.available_heaters.append(config.get_name())` and self.heaters can continue to use the short heater names.  The short heater name can also be exported in the heater's get_status() call if desired.

Finally, for long term maintenance reasons, code in one python module must not peak into the member variables of classes in other modules - so gcode_id must be either passed to the Heater() constructor or a new Heater.setup_gcode_id() method should be added.  (Or, perhaps, the sensor classes should have a get_gcode_id() method.)

-Kevin

**Comment by simonkuehling** [comment]
Thanks again for your feedback, very good points. You're right, I would have broken backwards compatibility... 

I reworked the changes along your suggestions and updated the commit.
For setting the `gcode_id` I opted for a dedicated `setup_gcode_id()` method that is called from within `register_sensor()` as I feel it is well placed there in one spot...
Although the gcode_id could also very strictly be viewed as a Sensor property, I think it is better placed in the Heater class like this - since this is the functional entity that is configured and addressed in use.

**Comment by KevinOConnor** [comment]
Unless I've missed something, I think this would break temperature_sensor and temperature_fan.  That is, it's possible to call register_sensor() on something that isn't a heater.

-Kevin

**Comment by simonkuehling** [comment]
Oh, well, I guess this defeats my initial decision to assume each sensor in M105 reports is actually a heater in the first place...

I'll rework the gcode_id handling to be an attribute of the sensor objects and make `register_sensor()` directly use that instead of fetching from the config on its own..

Also I will probably add a `SHOW_HEATERS` command like you suggested earlier as the host actually needs to actively query that to discover all heaters.

**Comment by simonkuehling** [comment]
@KevinOConnor, I am a bit lost in the sensor classes - hoping for a pointer into the right direction.. My thought would be to add a new `Sensor` class (in extras/sensor.py) as a parent to all temperature sensor classes which will provide the `setup_gcode_id()` function either by an argument provided or fetched from the config. But I have trouble understanding the hierarchy of the different classes in `spi_temperature`, `adc_temperature` and `thermistor`. Can you explain in a nutshell which of them would need to inherit from `Sensor` here?

I would see `CustomLinearResistance`, `CustomLinearVoltage`, `CustomThermistor` and `SensorBase` as candidates. Correct?

**Comment by KevinOConnor** [comment]
I fear I'm just sending you in circles.  I don't know the best way to add this functionality.

One simple solution is to export the gcode id to sensor config section name from `printer.heater` - something like:
```python
    def register_sensor(self, config, psensor, gcode_id=None):
        ...
        self.gcode_id_to_sensor_name[gcode_id] = config.get_name()
    def get_status(self, eventtime):
        return {'available_heaters': list(self.available_heaters), 'gcode_id': dict(self.gcode_id_to_sensor_name)}
```

-Kevin

**Comment by simonkuehling** [comment]
@KevinOConnor after moving back and forth quite a number of times again, I propose to go the simplistic approach to just expose all the info through the `available_heaters` handle and let the user implement anything around that (like a `SHOW_HEATERS` command or such) through custom macros for now. 
This keeps code changes to a minimum as all the other solutions required quite a bit of refactoring... Yet still all the functionality that I initially aimed at can be realized with this.
```
print.heater.available_heaters
-> [{ 'name': 'extruder',      'config_name': 'extruder',                     'gcode_id': 'T0'},
    { 'name': 'heater_bed',    'config_name': 'heater_bed',                   'gcode_id': 'B' },
    { 'name': 'custom_heater', 'config_name': 'heater_generic custom_heater', 'gcode_id': 'C' }]
```

Do you agree?

**Comment by KevinOConnor** [comment]
I agree that we should try to keep this simple.  Along those lines, I think the changes can be limited to just the PrinterHeaters class.

I'm leery of associating a gcode_id to a heater, as the gcode_id is a hack for M105.  It's the temperature sensor that has a gcode_id (for reporting via M105) and not the heater.  In the future a heater may not have a gcode_id or may have multiple gcode_ids, or something similar.  I'm leery of defining the command template interface around the bizarre limitations of the old g-code commands.

Is there a concern with exporting `printer.heater.gcode_ids = {'T0': 'extruder0'}` and `printer.heater.available_sensors = ["extruder0"]` and `printer.heater.available_heaters = ["extruder0"]`?  I would think you could build your list above with just a little macro work - for example:

```
{% set mymap = {gcode_id: printer[cfgname]
                for gcode_id, cfgname in printer.heater.gcode_ids.items()
                if cfgname in printer.heater.available_heaters}
 %}

-Kevin

**Comment by simonkuehling** [comment]
I do as well think that both M105 and gcode-ids are reminiscent of older days with different limitations than we have today on hardware like Klipper is running on. We might as well avoid using it in this case here all together to lay the groundwork for prettier solutions, right?

With these two lists:
```
printer.heater.available_heaters = ["extruder", "heater_bed", "heater_generic my_custom_heater"]
printer.heater.available_sensors = ["extruder", "heater_bed", "heater_generic my_custom_heater", "temperature_sensor electronics_temp"]
```
...and the addition of `get_status() -> .temperature` variable in `[temperature_sensor]` (added this in a separate commit to the PR)...

We can now build all different functionalities as a macro like:
* custom temperature report using config-names instead of gcode-ids (replacing M105)
* list of available heaters that need temperature controls
* list of additional sensors that are "read only" (no temperature controls, no target temp)

Backwards compatibility is kept clean, as well...

**Comment by KevinOConnor** [comment]
Okay, thanks.

-Kevin

**Pull request merged**
