### PR TITLE
Fix for multi-mcu FIRMWARE_RESTART bug

### LINKED ISSUE #1013: Resetting multiple MCUs via command fails
I have 4 MCUs connected to Klipper. When I change the config, I reset everything with the `RESTART` command. This reliably fails to reset all MCUs. On the first `RESTART` it fails to reset the first MCU, on the second try it resets the first and fails on the second MCU, on the third try it resets MCUs 1 and 2 but fails on the third, on the fourth try it fails on the fourth MCU. Only on the fifth try it resets all 4 MCUs and Klipper reports `ready`.

I expect it to reset all MCUs on the first try.

One of the errors copied from the log:
```
MCU error during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 140, in _connect
    cb('connect')
  File "/home/pi/klipper/klippy/mcu.py", line 768, in printer_state
    self._connect()
  File "/home/pi/klipper/klippy/mcu.py", line 623, in _connect
    self._check_config()
  File "/home/pi/klipper/klippy/mcu.py", line 581, in _check_config
    self._name,))
error: Failed automated reset of MCU 'axis_d'
Failed automated reset of MCU 'axis_d'
```

[klippy_resetproblem.log](https://github.com/KevinOConnor/klipper/files/2693820/klippy_resetproblem.log)

### PR DESCRIPTION
**Pull request by KevinOConnor**
This should hopefully fix #1013.

@vladbabii - fyi

-Kevin

### CODE REVIEW

**Comment by vladbabii** [comment]
@KevinOConnor i will test in a couple of hours. Many thanks!

**Comment by vladbabii** [comment]
Sometimes it fails with
```
Traceback (most recent call last):
  File "/opt/klipper/klippy/serialhdl.py", line 92, in connect
    identify_data = self._get_identify_data(connect_time + 5.)
  File "/opt/klipper/klippy/serialhdl.py", line 65, in _get_identify_data
    raise error("Timeout during identify")
error: Timeout during identify
```

But if i leave it for a bit or click on firmware restart it will re-connect. Doing a firmware reset automated test now and see if i can make it not connect anymore.

**Comment by vladbabii** [comment]
The only error i can reproduce now is but rarely and it fixes itself automatically in a couple of seconds - i think it has more to do with the board ( skr mini 1.1 ) since the "mcu" board works every time.

```
Starting serial connect
Loaded MCU 'mcu' 80 commands (v0.7.0-794-g8f5c15d-20190914_205332-octopus / gcc: (GCC) 5.4.0 binutils: (GNU Binutils) 2.26.20160125)
MCU 'mcu' config: RECEIVE_WINDOW=192 BUS_PINS_spi=PB3,PB2,PB1 SERIAL_BAUD=250000 STEP_DELAY=-1 ADC_MAX=1023 PWM_MAX=255 RESERVE_PINS_serial=PE0,PE1 BUS_PINS_ti=PD0,PD1 MCU=atmega2560 STATS_SUMSQ_BASE=256 CLOCK_FREQ=16000000
Starting serial connect
Got error 0 in read: (0)Success
Timeout on serial connect
Traceback (most recent call last):
  File "/opt/klipper/klippy/serialhdl.py", line 92, in connect
    identify_data = self._get_identify_data(connect_time + 5.)
  File "/opt/klipper/klippy/serialhdl.py", line 57, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
  File "/opt/klipper/klippy/serialhdl.py", line 156, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
  File "/opt/klipper/klippy/serialhdl.py", line 225, in get_response
    raise error("Timeout on wait for '%s' response" % (self.name,))
error: Timeout on wait for 'identify_response' response
Unable to open port: [Errno 16] could not open port /dev/printerhill_0: [Errno 16] Device or resource busy: '/dev/printerhill_0'
```

Maybe also add board name into "Starting serial connect" - I imagine it's one message per board?

**Comment by KevinOConnor** [comment]
Okay, thanks.  I committed this change.  It sounds like the identify_response thing is an unrelated issue.

-Kevin

**Pull request merged**
