### PR TITLE
adc: Enable ADC support for samd51 devices

### PR DESCRIPTION
**Pull request by FHeilmann**
This enables ADC support on the samd51 port.

Signed-off-by: Florian Heilmann <Florian.Heilmann@gmx.net>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Wish we could reduce some of those #if statements.  (Perhaps by adding gpio_adc_to_regs() and gpio_adc_to_chan() like the src/atsam/sam4e_afec.c does.)  I'm fine with merging this as is though.

-Kevin

**Comment by FHeilmann** [comment]
I'll see if I can remove some of those ifdefs

**Comment by FHeilmann** [comment]
Here's my attempt. Let me know what you think!

Florian

**Comment by KevinOConnor** [comment]
Thanks. Lets merge this - any code rearrangements are easier done on top of working code.

-Kevin

**Pull request merged**
