### PR TITLE
Create printer-tronxy-x5sa-pro-2020.cfg

### PR DESCRIPTION
**Pull request by morganfw**
A working configuration example for 2020 Tronxy X5SA Pro V2 printer (https://tronxy.com/x5s-series/x5sa-pro.html) with CXY-V6 board and no Touchscreen funcionalities because separated LCD firmware needed.
Silent TMC2225 drivers soldered on board.
The Self-levelling plate sensor is a blue Tronxy XY-08N model.
Direct Drive is a Titan Extruder Clone "3:1" gear ratio.

Signed-off-by: Morgan Barresi <morganfw@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Are you sure on the rotation_distance settings?  The values don't look right - perhaps the printer has 0.9 degree steppers (and thus should be using `full_steps_per_rotation: 400` with rotation_distances doubled)?

Also, note there are some new guidelines for example configs at: https://www.klipper3d.org/Example_Configs.html

-Kevin

**Comment by morganfw** [comment]
Hi Kevin,
Titan Extruder Clone stepper motor is Tronxy and label is "SL42STH40-1684A-23", by specifications is a 1.8 degree Nema17 and gear ratio is 3:1, I will do more investigations.

I've applied some modifications following guidelines.

Thank you

Signed-off-by: Morgan Barresi morganfw@gmail.com

**Comment by morganfw** [comment]
Hi Kevin,
Tronxy support answered me that is a 1.8 degree stepper motor, below the answer:

"The motor angle is 1.8 degrees. The difference between the Titan extruder and the ordinary extruder is that the modulus of the gear is different."

Have changed the gear ratio to "66:22".

The filament flow is correct with rotation_distance configured in printer.cfg, I will try again later the rotation_distance test, but I don't know what else to do to understand why the rotation_distance is so low.

**Comment by morganfw** [comment]
I did the rotation_distance test again and the value is always on 11.xyz

**Comment by KevinOConnor** [comment]
Do you know what stepper motor drivers are on the board?  Perhaps they are using 32 microsteps.  That could also explain the discrepancy in rotation_distance.

-Kevin

**Comment by morganfw** [comment]
The stepper motor drivers are TMC2225-SA in standalone mode soldered on the board.
Based on documentation here https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2225_Datasheet_Rev1.11.pdf the drivers are capable STEP/DIR Interface with 4, 8, 16 or 32 microstep pin setting.

So I shoud modify config like this:

```
[stepper_x]
[...]
microsteps: 32
rotation_distance: 40
[...]

[stepper_y]
[...]
microsteps: 32
rotation_distance: 40
[...]

[stepper_z]
[...]
microsteps: 32
rotation_distance: 8
[...]

[extruder]
microsteps: 32
rotation_distance: 22.478
gear_ratio: 66:22
[...]
```

Is that correct?
Thank you

**Comment by KevinOConnor** [comment]
Okay, thanks.  I committed this change and made some minor changes on top (commit dcf6d30a).

-Kevin

**Pull request merged**
