### PR TITLE
Convert pressure advance to "weighted average smoothing"

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is a proposal to convert the pressure advance code from the recently introduced "smooth pressure advance" to an updated "weighted average smooth pressure advance".  I expect that most users will not notice much of a difference with this change.  However, I think the new code may do a better job at scaling to larger `pressure_advance` and `pressure_advance_smooth_time` values.

Testing would be welcome:
`cd ~/klipper ; git fetch ; git checkout origin/work-weightpa-20191214 ; sudo service klipper restart`

The graph below shows the extruder motor movement with the current "smooth pa" code.  It shows two extrusion moves that have a non-zero corner velocity between them.  The second move ends in a non-zero cornering velocity to a non-extrusion move.

extruder_smooth

The graph highlights a couple of quirks in the current "smooth pa" code.  The first is in the generated pressure during the cornering move (see the middle of the bottom "offset" chart).  It shows the current code will decrease the pressure, increase the pressure, flat-line the pressure, and then increase the pressure.  This is odd - almost certainly it would be better to decrease the pressure and then increase the pressure without any plateaus.  The second quirk is in the velocity chart at the end of the extrusion - it shows the extruder motor slowing down and then performing an instantaneous velocity change.  I'm not concerned about the instantaneous velocity change, but it is certainly odd to slow the extruder prior to it - it would almost certainly be better to perform a more aggressive slow down that goes all the way to zero.

The idea for a "weighted average" originates from @dmbutyugin in the #2030 thread.  The corresponding graph with the code on this branch looks like:

extruder_weighted

The new code doesn't have the quirks noted above and it results in overall "smoother" extruder motor movement.

One downside of the new code is that for the same values of `pressure_advance_smooth_time` this code will command the stepper motor to a larger absolute velocity and acceleration.  This effect can be easily mitigated by increasing the `pressure_advance_smooth_time` parameter, however.

It's worth noting that all of the effects highlighted here are occurring at time periods measured in milliseconds.  Thus, I don't expect to see significant differences in overall print results.

-Kevin

### CODE REVIEW

**Comment by robustini** [comment]
@KevinOConnor I want to test it, what parameter to start with suggestions for pressure_advance_smooth_time?
My pressure_advance here is 0.468, calculated with the method in the wiki (0 + 23.4 * 0.002).

**Comment by KevinOConnor** [comment]
You shouldn't need to tune pressure_advance_smooth_time.  This branch should work with the same settings as the current code.

If you wish to test with a different pressure_advance_smooth_time, the general procedure is to first tune pressure_advance (as described in the documentation).  Then, one can run `RESTART` to return to normal printer settings, run `TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=SMOOTH_TIME START=.005 FACTOR=.003`, and then print the square tower calibration print (same print as in the pressure advance docs).  One can then inspect the corners of the test print to see the impact of the pressure_advance_smooth_time setting.

-Kevin

**Comment by robustini** [comment]
> 
> 
> You shouldn't need to tune pressure_advance_smooth_time. This branch should work with the same settings as the current code.
> 
> If you wish to test with a different pressure_advance_smooth_time, the general procedure is to first tune pressure_advance (as described in the documentation). Then, one can run `RESTART` to return to normal printer settings with pressure_advance enabled, run `TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=SMOOTH_TIME START=.005 FACTOR=.003`, and then print the square tower calibration print (same print as in the pressure advance docs). One can then inspect the corners of the test print to see the impact of the pressure_advance_smooth_time setting.
> 
> -Kevin

Thanks Keni for reply!
Ok, i try for different value.

**Comment by robustini** [comment]
Tested, obviously there is no difference in printing, but the noise of the extruder stepper has decreased slightly during PA.

**Comment by bigsubgit** [comment]
Hello everyone, I want to test it. Now my pressure_advance value is .0523 (in direct drive).

**Comment by robustini** [comment]
@KevinOConnor, i think there's a problem with this pull request, two prints have already stopped me while with the branch master it never happened to me.
The error is "Internal error on command:"G1", see the log:

[klippy.log](https://github.com/KevinOConnor/klipper/files/4008117/klippy.log)

**Comment by ProfDrYoMan** [comment]
Tried. PA value 0.12 (zesty nimble), smooth time 0.02.
E-Stepper is less loud.

Quality is the same.

Go, from my side. :)

**Comment by KevinOConnor** [comment]
Thanks for the feedback.  I'll look to merge this next week.  (I want to keep the repo in a "soft freeze" for the holidays.)

-Kevin

**Comment by dmbutyugin** [comment]
Hi Kevin, as I was looking into smoothing, one thing occured to me. Right now, if I'm not mistaken, smooth PA code always divides the integral by hst[^2], even if there was not enough moves to integrate over (e.g. in the beginning and end of printing, or on the queue flush). Should the code, perhaps, also compute how much time it did integrate over?

**Comment by KevinOConnor** [comment]
> Right now, if I'm not mistaken, smooth PA code always divides the integral by hst[^2], even if there was not enough moves to integrate over (e.g. in the beginning and end of printing, or on the queue flush). 

Thanks for reviewing.  The `trapq_add_move()` and `trapq_check_sentinels()` code is intended to ensure that the range of moves is always complete and gap free.  So, when the extruder code walks the list of moves it will always find +-half_smooth_time movement.  The high-level code (eg, `flush_step_generation()`, `_update_move_time()`, `note_step_generation_scan_time()`) is supposed to ensure that the low-level code is only requested to generate steps after a sufficient number of moves are queued.  (That high-level logic to flush and restart the queues is painful, and that complexity is the reason it took so long to get "smooth pa" merged.)

Cheers,
-Kevin

**Comment by dmbutyugin** [comment]
Thanks Kevin,

> The `trapq_add_move()` and `trapq_check_sentinels()` code is intended to ensure that the range of moves is always complete and gap free.

I somehow missed trapq_check_sentinels that it updates `start_pos`, and was under the impression that the code will 'under-integrate' the integral with 0 values outside the integral range. Just a quick question then, is it OK that it does not update `start_pos` of `head_sentinel` (e.g. when the printing is [re-]started on a non-zero extruder position, e.g. after the temperature change, etc.)?

**Comment by KevinOConnor** [comment]
> Just a quick question then, is it OK that it does not update start_pos of head_sentinel

The `trapq_add_move()` code would insert a "null" move into the queue that has `start_pos` fillled.  So, it shouldn't be necessary to alter `head_sentinel`.  (Admittedly though, with commit 54149e38, updating `head_sentinel->start_pos` might be more clear.)

> e.g. after the temperature change

FYI, a temperature change wouldn't normally lead to a `flush_step_generation()` call, and only that call would result in a restart of the queue.

-Kevin

**Comment by Markus-1984** [comment]
> You shouldn't need to tune pressure_advance_smooth_time. This branch should work with the same settings as the current code.
> 
> If you wish to test with a different pressure_advance_smooth_time, the general procedure is to first tune pressure_advance (as described in the documentation). Then, one can run `RESTART` to return to normal printer settings with pressure_advance enabled, run `TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=SMOOTH_TIME START=.005 FACTOR=.003`, and then print the square tower calibration print (same print as in the pressure advance docs). One can then inspect the corners of the test print to see the impact of the pressure_advance_smooth_time setting.
> 
> -Kevin

Hi Kevin,

it would be nice to put these tuning tower command to the PA wiki after the PA Tuning. Cause many people don´t know what the PA smooth time value is for.

-Markus

**Pull request merged**
