### PR TITLE
Update printer-tevo-flash-2018.cfg

### PR DESCRIPTION
**Pull request by RadianceNL**
By default the printer comes installed with a 0.4mm nozzle so changed that in the configuration file.
Aditionally I've added some more information about the setup I'm using.

Signed-off-by: Jeroen van der Does <twistit@gmail.com>

### CODE REVIEW

**Comment by jakep82** [comment]
The stock printer includes a "Tevo Titan" extruder which is a clone of an E3D product.  These config files are intended to be starting points for unmodified commercially available printers.

**Comment by RadianceNL** [comment]
I've just made some small changes because I should've explained I use the fully upgraded version of the Flash and by default it comes with a 0.4mm nozzle so changed that in the configuration as well.

@jakep82 I understand but the motor directions should be the same, only the steps could be different.

**Comment by KevinOConnor** [comment]
Thanks.  I'm happy to change the nozzle diameter to 0.4mm (if that's the stock nozzle).  I don't understand the additional comments added though.  The target audience for the config directory is stock printers.  If you think the config may need some tweaking on a stock printer then perhaps we should update the config comments to say something like - "This config has only been tested on a Tevo flash with a Bondtech BMG extruder - if using a stock printer it may be necessary to update the extruder step_distance parameter."

-Kevin

**Comment by RadianceNL** [comment]
I've updates the comments to make it a bit more clear.
You can order this printer in various versions.

Standard: No dual Z and no BLTouch
Dual Z: No BLTouch
Full: Dual Z, genuine BLTouch and TCM2100 drivers

I own a full version and upgraded the Titan Extruder to a BMG extruder.
The stock printer comes with a Volcano hotend so I increased the default nozzle diameter from 0.4 to 0.6mm because I was having trouble with clogs on 0.4mm.
I've read serval people in the Tevo Flash community changed their nozzle diameter so I thought it was a good point to add a bit of comment about usage with a 0.6mm nozzle because I had some issues with the default max_extrude_cross_section.

**Comment by KevinOConnor** [comment]
Thanks.  Note that I generally don't look at pull requests that don't pass the build test cases.  Looks like there is some whitespace issues that would need to be resolved before committing (click on the travis-ci links to track it down).

A max_extrude_cross_section=2.16 does not seem right (and increasing it would not prevent a "timer too close" error), so I would be reluctant to document that.  The default cross section of 1.44 should be more than sufficient for any sane extrusion (that's 2.4mm wide for a .6mm layer height).

-Kevin

**Comment by KevinOConnor** [comment]
I've gone ahead and made the nozzle change and some comment updates (commit 74f9da83).  Let me know if further changes are needed.

-Kevin

**Pull request closed without merging**
