### PR TITLE
Update generic-bigtreetech-skr-mini-e3.cfg

### PR DESCRIPTION
**Pull request by TheDogee**
Got this up and running on my Ender 3 with a few changes required to the pin polarity and step sizes.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, the generic-xxx.cfg files are intended to describe a set of electronics.  The printer-xxx.cfg files are intended to describe a particular stock printer.  The changes you've made apply to a particular printer, but don't generally apply to the electronics.

That said, I don't mind updating the example electronics files if that is generally helpful.  However, @AshIzat expressed a preference when this was originally committed.

-Kevin

**Comment by TheDogee** [comment]
Perhaps this is the wrong place to put it, but this board is advertised as
being a drop in upgrade specifically for the ender 3 (note the E3 in the
name), so it makes sense that the config would match the printer for which
it was intended? The other ender 3 specific printer cfg file is for the
stock creality board. Would it make more sense to create a printer specific
file for the ender 3 with this upgrade board installed?

**Comment by KevinOConnor** [comment]
Ah, that's a good point.  I guess it makes sense to have generic-bigtreetech-skr-mini-e3.cfg match printer-creality-ender3-2018.cfg where it can.

We don't generally include example configs for non-stock printers.  (The fear is that there are too many combinations of non-stock modifications to meaningfully track.)

Thanks,
-Kevin

**Comment by TheDogee** [comment]
Will leave it up to you, and thanks for the work you have put into Klipper!

**Pull request closed without merging**
