### PR TITLE
Draft: skew_correction: add auto skew correction

### PR DESCRIPTION
**Pull request by ayufan**
Some printers have a calibration points
that can be used to perform automated skew
correction by finding their position relative
to print head.

This algorithm is different than found in [Prusa-Firmware](https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/xyzcal.cpp).
It is definitely less refined, but it appears to produce exactly the same results with one
caveat: likely it can handle smaller skews, up to the radius of a calibration point.

Algorithm:
1. For each corner perform:
2. Look for 4 edges of a circle (a moment when probe stops engaging on z-hop)
3. Find the best circle (using 3 out of 4 points) with the most distinct points
4. Iterate till the subsequent circles produce the same center
5. Calculate skew following [the ABCD](https://www.klipper3d.org/skew_correction.html)

Configuration parameters:
- `gantry_corners`: unsure if this is correct name, but it indicates a corners to test in ABCD order
- `z_position`: it is the highest possible Z that still engages PINDA but nozzle does not hit the bed
- ` z_hop/speed/z_speed`: self explanatory
- `radius`: search radius for circle
- `iterations`: a max number of iterations to look for the most consistent circle

Example usage:

```ini
[skew_auto_calibration]
gantry_corners: # taken from Prusa-Firmware
  12, 4
  12, 196
  220, 196
  220, 4
speed: 50
z_position: 1.5
z_hop: 1.0
z_speed: 30

[skew_correction]
```

Example output:

```txt
11:10:08 $ SKEW_AUTO_CALIBRATION
11:10:44 // (12.0, 4.0): Iteration 0: (10.801, 5.82) / 4.228 / 2.180
11:11:18 // (12.0, 4.0): Iteration 1: (12.261, 6.289) / 3.649 / 1.533
11:11:51 // (12.0, 4.0): Iteration 2: (12.563, 6.445) / 3.451 / 0.341
11:12:32 // (12.0, 4.0): Iteration 3: (12.524, 6.414) / 3.508 / 0.050
11:12:32 // (12.0, 4.0): Found at (12.524, 6.414)
11:13:07 // (12.524, 198.414): Iteration 0: (12.733, 198.441) / 3.292 / 0.210
11:13:42 // (12.524, 198.414): Iteration 1: (12.717, 198.441) / 3.313 / 0.016
11:13:42 // (12.0, 196.0): Found at (12.717, 198.441)
11:13:53 // edge not found for (220.717, 198.441)-(214.717, 198.441)
11:14:20 // (220.717, 198.441): Iteration 0: (220.296, 198.399) / 3.358 / 0.423
11:14:27 // edge not found for (220.296, 198.399)-(214.296, 198.399)
11:14:57 // (220.717, 198.441): Iteration 1: (220.358, 198.422) / 3.305 / 0.066
11:15:05 // edge not found for (220.358, 198.422)-(214.358, 198.422)
11:15:31 // (220.717, 198.441): Iteration 2: (220.35, 198.422) / 3.313 / 0.008
11:15:31 // (220.0, 196.0): Found at (220.35, 198.422)
11:16:11 // (220.35, 6.422): Iteration 0: (219.886, 6.293) / 3.186 / 0.482
11:16:45 // (220.35, 6.422): Iteration 1: (219.862, 6.437) / 3.245 / 0.146
11:17:16 // (220.35, 6.422): Iteration 2: (219.87, 6.382) / 3.204 / 0.055
11:17:53 // (220.35, 6.422): Iteration 3: (219.87, 6.43) / 3.219 / 0.047
11:17:53 // (220.0, 4.0): Found at (219.87, 6.43)
11:17:53 // SET_SKEW XY=282.946,282.455,207.346
```

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@Arksine - do you have any thoughts on this?

-Kevin

**Comment by Arksine** [comment]
I took an initial look at this and have some minor comments.

1) I think `bed_skew_points` or something similar probably makes more sense than `gantry_corners`, as the coordinates are relative to the bed
2) This might be intentional, however I noticed that you are echoing `SET_SKEW` over the pty.  If your intention is to actually set the skew, you could look up the `gcode` object and call `run_script_from_command()`.

I'll test this on my MK3 and provide more feedback.  At an initial glance it seems that it should do what we expect it to do and would be a good addition.

**Comment by dewi-ny-je** [comment]
If you merge this, please update the documentation with examples and instructions, because even if I'm aware of the current procedure, I don't understand steps 2-4 as described here.

**Comment by KevinOConnor** [comment]
Thanks.  Due to time constraints on my side, I'd prefer not to track draft PRs in the main Klipper repository.  Perhaps the Klipper Discourse would be an alternative?

-Kevin

**Pull request closed without merging**
