### PR TITLE
Added support for st7565 display

### PR DESCRIPTION
**Pull request by PuffyZA**
I couldn't get my st7565 to work with the existing display options, so I decided to give it a go and add support for it and thought it might be useful to others. Please let me know if anything needs to be changed.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  How does this differ from the existing st7567 support?  Is it just that the reset pin is toggled at startup?

-Kevin

**Comment by PuffyZA** [comment]
It's pretty much the same as at the base uc1701 with a reset pin that is toggled on startup, I didn't want to change any existing classes but can refactor.

I'm not terribly familiar with these things, I had a look at the st7657 which specifies an rs_pin, which from what I can tell is a different thing (Register Select pin) to a reset pin? Though the code then does refer to it as a reset pin so I wasn't sure.

All the documentation and existing libraries supported both the uc1701 and the st7565 with the only difference I could find being toggling the reset pin.

**Comment by KevinOConnor** [comment]
Okay, thanks.  I was able to add reset pin support to the uc1701 code.  Could you retry with the latest code on the master branch using uc1701 along with a `rst_pin`?  (Commit 2d97e0e2.)

-Kevin

**Comment by PuffyZA** [comment]
Perfect, will test as soon as I'm home.

**Comment by PuffyZA** [comment]
Works perfectly 👍  The default contrast is very low, but easily fixed via the config. Thanks for getting this sorted  :)

**Pull request closed without merging**
