### PR TITLE
WIP probe: Turn off heated bed while probing

### PR DESCRIPTION
**Pull request by HWiese1980**
When using a capacitive probe sensor the EM field of a heating heated
bed might interfere with the probe. For this purpose while probing the
heated bed is deactivated and re-set to its original target temperature
after probing is done.

Signed-off-by: Hendrik Wiese <klipper@hwiese.com>

### CODE REVIEW

**Comment by HWiese1980** [comment]
Just to add to this: interference might lead to inaccurate results when probing

**Comment by HWiese1980** [comment]
Darn, sorry about the whitespace errors. I'm not used to write python code in `vim`...

**Comment by HWiese1980** [comment]
Your CI is rather picky... 🤔

**Comment by HWiese1980** [comment]
Well, that took some doing...

**Comment by FHeilmann** [comment]
This should be configurable. Otherwise long probing sequences can lead to significant temperature changes in the bed which can mess with the probed points due to thermal expansion.

I used this back in RRF and had to disable this feature due to my bed cooling down significantly during bed mesh probings and such.

**Comment by HWiese1980** [comment]
Okay, I'll go on and try to make it configurable. I'm not sure right now how to solve this for only a single probe run, but I'll see what I can do. 

If a `PROBE` were okay to do two subsequent probes, like when homing, I'd just say, make one probe run (with heater on) until the probe triggers, turn heater off, make second run from a configurable distance, and turn heater back on. That way both problems are solved. Heater isn't turned off for too long and probe isn't interfered by the EM field. 

Do you happen to have an idea how to improve the approach?

**Comment by FHeilmann** [comment]
I can definitely say that users should be able to turn it on and off according to their needs. Again, I would never want to turn this off because my probe accuracy relies on a steady temperature on the bed.

As far as making it configurable goes, you can use the existing configuration parameters as a guide on how to get the information into the extra. That will allow you to extend the if statements in your existing code to also check those configurated parameters.

As far as the usage of the probe as endstop goes, have a look into the ProbeEndstopWrapper and it's home_prepare and home_finalize functions. That would be my best guess, anyway.

**Comment by HWiese1980** [comment]
Yeah, absolutely. I'll first of all make it switchable. 

For the time being consider this PR _work in progress_.

**Comment by KevinOConnor** [comment]
If there is a desire to power off the bed during a probe, wouldn't it be simpler to just have the user make a MY_PROBE gcode_macro that disables the bed, does the probe, and then reenables the bed heater?

-Kevin

**Comment by HWiese1980** [comment]
Indeed, if there's a way to temporarily store the desired target temperature...

**Comment by jakep82** [comment]
Why is this necessary at all?  If you want to probe after heating, but with the bed off, then just include a couple extra lines in the start gcode in your slicer.

```
M190 S{bed_temperature}
M140 S0
G28
PROBE
M190 S{bed_temperature}
```

**Comment by fxbisto** [comment]
What about disabling bed heater _just as_ the probe starts to lower and as soon as second trigger for that point is done heating is re-enabled? It would please both the people who suffer with sensors picking up EMI and those whose bed's cool too quickly?

**Comment by HWiese1980** [comment]
@jakep82 Because I would want such core behavior in the firmware of my printer. I might use different slicers for different tasks and don't want too much redundant code there. It's too risky for me to forget about it when trying a new slicer or in otherwise mess up keeping track of it, and wonder why my prints won't work anymore. 

@fxbisto That's the plan...

**Comment by KevinOConnor** [comment]
Thanks.  My high-level comment is that I don't think we should tie the probing code to the bed heater in the mainline Klipper repo.  As I understand it, the majority of users don't need or want the bed changing during probing.  For those (relatively few) users that have a probe that requires the bed heater to be disabled, it should be possible for those users to manually ensure probing is done when the bed heater is not enabled.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, with PR #1689 it should be possible to automate the heater enable/disable via the probe activate/deactivate config.  For example:

```
[probe]
...
activate_gcode: DISABLE_BED
deactivate_gcode: M140 S{printer["gcode_macro DISABLE_BED"].target}

[gcode_macro DISABLE_BED]
variable_target: 0
gcode:
  SET_GCODE_VARIABLE MACRO=DISABLE_BED VARIABLE=target VALUE={printer.heater_bed.target}
  M140
```

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this PR as it looks like the conversation has concluded.

-Kevin

**Pull request closed without merging**
