### PR TITLE
Feature: support half-stepping rotary encoders

### PR DESCRIPTION
**Pull request by nickbrennan01**
The existing implementation of the RotaryEncoder class only emits movement events after the encoder has cycled through 4 states. Some encoders only cycle through 2 states per physical detent, and so require two physical "clicks" to generate one menu movement.

This feature allows the user to select a step setting appropriate for their printer's encoder.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@mcmatrix - do you have any comments on this?

**Comment by mcmatrix** [comment]
Thanks. I'll check it.

**Comment by mcmatrix** [comment]
The first impression is good.
Everything was working for me.
I was only able to test with an encoder that has 4 transitions per detent.

Current encoder algorithm has odd behaviour (when I have inv. pins ^!ar33, ^!ar31) to skip a step after the direction change. This new implementation will also fix that. 
After this encoder steps same both ways.

I'm just thinking, could the attribute name `encoder_steps_per_detent` confuse end-user with encoder moving steps in the display. Maybe `encoder_transitions_per_detent` is better?

**Comment by modmt** [comment]
I modified the buttons.py and menu.py (deleted red text and added green text) and also added the encoder_steps_per_detent in the cfg but I always get an error.
Did anybody else tried this and got it to work? 

error

**Comment by deltamelter** [comment]
Is this pending some other work?  Seems like this was fixed but never merged.  Can we get this config option to support different resolution rotary encoders enabled?  Currently my LCD is display only because the menu is very difficult to navigate.

**Comment by susisstrolch** [comment]
I'd suggest to merge this feature.
There are at least two cases known to me (11to3, susisstrolch) where this feater fixes a otherwise non-working encoder.

**Pull request closed without merging**
