### PR TITLE
Merge SAM3/SAM4 code and add support for the SAM4S8C chip

### PR DESCRIPTION
**Pull request by KevinOConnor**
This change is in preparation for support of the Duet2 Maestro, which uses the SAM4S8C chip.  Due to similarities between the SAM3X8E, SAM4E8E, and SAM4S8C chips, this change series starts by merging the SAM3 and SAM4 code.  This change also adds support for USB on the SAM4 chips.

@FHeilmann - Unfortunately, this series is likely to break the SAM4E8E code.  I thought the SAM4S8C chip would be the same as the SAM4E8E without the floating point hardware, but the chips are actually quite different.  The SAM4S8C doesn't have the cache, it only has 16 bit timers, and it uses the SAM3 style ADC hardware.  (The performance isn't nearly as good on this chip either - likely because of the cache and 16-bit timers.)  On the upside, if the SAM4E8E does come up on this branch then it should have USB support working.

-Kevin

### CODE REVIEW

**Comment by alecplumb** [comment]
I have installed this branch on my Voron2 printer with a Duet Wifi MCU (with Duex5 expansion board). After running `make flash` I had to press the Reset button on the Duet in order to see the new USB device id (the default `/dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00`). I changed my printer.cfg to use the new serial device id.

I am currently printing, and have verified that the duex fan headers (configured with `[sx1509]`) and stepper drivers on both boards function as expected.

**Comment by FHeilmann** [comment]
@alecplumb already confirmed it working, I'll also take a swing at this port after new years. Thanks for taking the time to keep the sam4e, now the duet is a true first class citizen of the klipper-verse :P

**Comment by Grimpster** [comment]
This is great news! Can't wait to get back to klipper with the Meastro. But is the cache that important? I mean, RTOS is somewhat a nice thing. Or am I talking out of my league here? :)
-I know that the duet team rate this the most advanced board made, but they saved out on a few weird things.

Is the port still in dev or can one start to play around with it on the maestro ?

**Comment by KevinOConnor** [comment]
I've merged the SAM4S8C code into the master branch.  (Duet2 Maestro support is still being worked on.)

-Kevin

**Pull request closed without merging**
