### PR TITLE
gcode: Make homed information appear in GET_POSITION response

### PR DESCRIPTION
**Pull request by proto3**
AFAIK the only way to know if a stepper is homed is to try a G1 and to see if it get an error.
I propose to add this information to GET_POSITION.
In GET_POSITION reponse, kinematic fields will be set as 'Unhomed' until the corresponding axis is homed.

### CODE REVIEW

**Comment by proto3** [comment]
It appears that rotary delta is the only kinematic to not request eventtime argument in get_status(). I don't know why this one in particular, but interestingly none of the other kinematic make use of eventtime.
Maybe we can simply remove eventtime from all kinematic's get_status(). The only call I found (but I could have missed some) is in toolhead.py/get_status().

**Comment by GarthSnyder** [comment]
Just FYI, you can access the list of homed axes through Jinja as `printer.toolhead.homed_axes`.

**Comment by KevinOConnor** [comment]
The lack of eventtime in `get_status()` on rotary delta was an error - should be fixed now (commit 9e8c4770).  We do want `get_status()` to take that parameter because that's standardized throughout the code (as used by gcode_macro and the display code).

The GET_POSITION command is primarily intended as a diagnostic tool (eg, see https://www.klipper3d.org/Code_Overview.html#coordinate-systems ).  So, we don't want to suppress the coordinate information just because the axis is not considered "homed".  We could add the homing status to GET_POSITION, but as Garth indicates that information can also be obtained (along with all the other info in GET_POSITION) from gcode_macros (as described at https://www.klipper3d.org/Command_Templates.html ).

Thanks.
-Kevin

**Comment by KevinOConnor** [comment]
Okay, it seems like we can close this.

-Kevin

**Pull request closed without merging**
