### PR TITLE
Increasing measure stability

### PR DESCRIPTION
**Pull request by test3210-d**
module: hall_filament_width_sensor
Increasing measure stability

Signed-off-by: Denis Ignatenko deniss979@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I'll commit if you wish, but the code looks a little odd.  The new `self.diameter_old` is always equal to `self.diameter` and `self.diameter_new` is not initialized in the constructor.  It seems the new code could do `self.diameter = (2.0 * self.diameter + new_diameter) / 3.0` which would be more clear I think.

Cheers,
-Kevin

**Comment by test3210-d** [comment]
Yes, it's my mistake. The code  left from my trying to take the average of 3 dimensions, but it has no advantages over your solution

**Comment by KevinOConnor** [comment]
Thanks.  Happy to add if you want me to, but note that the latest code here adds an otherwise unused `self.diameter_old` variable in the constructor.

-Kevin

**Comment by test3210-d** [comment]
Sorry, Fixed

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by mcmatrix** [comment]
@test3210-d Just for info that after `git pull`, my sensor calibration went wrong.
If previously the ADC results were near these values
```
cal_dia1 = 1.51
raw_dia1 = 10269
cal_dia2 = 1.97
raw_dia2 = 10711
```
then now raw readings are for filament `ADC1= 2591.0 ADC2=1334.0`.
Will try to recalibrate.

**Comment by test3210-d** [comment]
> @test3210-d Just for info that after `git pull`, my sensor calibration
> went wrong `// Filament dia (measured mm): -5.08614388703`.
> If previously the ADC results were near these values
> 
> ```
> ADC1= 5865.0 ADC2=4597.0 RAW=10462.0
> Filament dia (measured mm): 1.71
> ```
> 
> ```
> cal_dia1 = 1.51
> raw_dia1 = 10269
> cal_dia2 = 1.97
> raw_dia2 = 10711
> ```
> 
> then now raw readings are for filament `ADC1= 2599.0 ADC2=1334.0 RAW=3933.0`.
> Nothing changed in config.
> 
> EDIT:
> After reverting to the previous commit `c9daefd97f61c8e291dcee6496fcfb5bf3926576`
> readings are okay again.
> 
> Will try to recalibrate and see the result after that.

i don't understand why
in my case
old version

Recv: ADC1= 2483.0 ADC2=5518.0 RAW=8001.0
new 
Recv: // ADC1= 2488.0 ADC2=5517.0 RAW=8005.0

but try decrease ADC_SAMPLE_COUNT = 49
to ADC_SAMPLE_COUNT = 30
maybe variable overflow, your sensor some different

 ~/klipper/klippy/extras/hall_filament_width_sensor.py

**Comment by mcmatrix** [comment]
```
ADC_REPORT_TIME = 0.500
ADC_SAMPLE_TIME = 0.01
```
Ok I tried these settings.

```
ADC_SAMPLE_COUNT = 10
// ADC1= 5876.0 ADC2=4590.0 RAW=10466.0
```
```
ADC_SAMPLE_COUNT = 20
// ADC1= 5875.0 ADC2=4591.0 RAW=10466.0
```
```
ADC_SAMPLE_COUNT = 30
// ADC1= 541.0 ADC2=4590.0 RAW=5131.0
```
```
ADC_SAMPLE_COUNT = 40
// ADC1= 1875.0 ADC2=589.0 RAW=2464.0
```
```
ADC_SAMPLE_COUNT = 49
// ADC1= 2609.0 ADC2=1324.0 RAW=3933.0
```

It looks like when the sample count is under 20 then readings are normal but over that
the raw ADC values will change.

I'm using BTT SKR V1.4 board.
```
Loaded MCU 'mcu' 77 commands (v0.8.0-426-g8ac81fed-20200422_143709-Repetier-Server / gcc: (15:5.4.1+svn241155-1) 5.4.1 20160919 binutils: (2.27-9+9) 2.27)
MCU 'mcu' config: BUS_PINS_i2c1=P0.1,P0.0 BUS_PINS_i2c0=P0.28,P0.27 BUS_PINS_i2c2=P0.11,P0.10 BUS_PINS_i2c1a=P0.20,P0.19 BUS_PINS_ssp1=P0.8,P0.9,P0.7 STEP_DELAY=2 ADC_MAX=4095 BUS_PINS_ssp0=P0.17,P0.18,P0.15 RESERVE_PINS_USB=P0.30,P0.29,P2.9 CLOCK_FREQ=100000000 MCU=lpc1768 STATS_SUMSQ_BASE=256
Configured MCU 'mcu' (1024 moves)
Starting heater checks for heater_bed
Starting heater checks for extruder
Starting Klippy...
Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.8.0-530-g1d2746f1'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.13 (default, Nov 24 2017, 17:33:09) \n[GCC 6.3.0 20170516]'
```

**Comment by test3210-d** [comment]
Ok, all clear/ I use atmega2560  based board - 10bit adc. - max value 1023 
LPC1769 have 12 bit adc resolution (x4 from atmega)  = max value 4095
50 samples of 1024 = 51200 lower of 65535
50 samples of 4096 = higer of 65535
max samples count 16 for 12 bit adc :(
fix needed
ADC_REPORT_TIME = 0.500
ADC_SAMPLE_TIME = 0.03
ADC_SAMPLE_COUNT = 15

**Comment by mcmatrix** [comment]
Great, thanks!

**Pull request merged**
