### PR TITLE
Use the same low-level Z adjustment code in z-tilt and quad-gantry-level

### PR DESCRIPTION
**Pull request by KevinOConnor**
This pulls out the two patches to unify the low-level z steppers that was discussed in PR #1658.

-Kevin

### CODE REVIEW

**Comment by fessyfoo** [comment]
I didn't identify the root cause of the issue yet but this code isn't working right for QGL.  
repeated runs of QGL eventually diverge.      note in the following repeated runs the stepper_z2 adjustment just keeps growing. 

```
Send: quad_gantry_level
Recv: // probe at 60.000,35.000 is z=2.909972
Recv: // probe at 60.000,169.000 is z=2.924972
[...]
Recv: // probe at 194.000,169.000 is z=2.959972
Recv: // probe at 194.000,35.000 is z=2.924972
Recv: // Gantry-relative probe points:
Recv: // 0: 2.090028 1: 2.075028 2: 2.040028 3: 2.075028
Recv: // Actuator Positions:
Recv: // z: 2.101942 z1: 2.107156 z2: 1.968347 z3: 2.086247
Recv: // Average: 2.065923
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.036019
Recv: // stepper_z1 = -0.041233
Recv: // stepper_z2 = 0.097576
Recv: // stepper_z3 = -0.020324
Recv: ok
[...]
Send: quad_gantry_level
[...]
Recv: // probe at 60.000,35.000 is z=2.877576
Recv: // probe at 60.000,169.000 is z=2.912576
Recv: // probe at 194.000,169.000 is z=2.982576
[...]
Recv: // probe at 194.000,35.000 is z=2.917576
Recv: // Gantry-relative probe points:
Recv: // 0: 2.122424 1: 2.087424 2: 2.017424 3: 2.082424
Recv: // Actuator Positions:
Recv: // z: 2.161229 z1: 2.140878 z2: 1.884865 z3: 2.089888
Recv: // Average: 2.069215
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.092014
Recv: // stepper_z1 = -0.071663
Recv: // stepper_z2 = 0.184350
Recv: // stepper_z3 = -0.020673
Recv: ok
[...]
Send: quad_gantry_level
Recv: // probe at 60.000,35.000 is z=2.824350
Recv: // probe at 60.000,169.000 is z=2.889350
Recv: // probe at 194.000,169.000 is z=3.029350
[...]
Recv: // probe at 194.000,35.000 is z=2.904350
Recv: // Gantry-relative probe points:
Recv: // 0: 2.175650 1: 2.110650 2: 1.970650 3: 2.095650
Recv: // Actuator Positions:
Recv: // z: 2.250947 z1: 2.221514 z2: 1.709489 z3: 2.108265
Recv: // Average: 2.072553
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.178393
Recv: // stepper_z1 = -0.148960
Recv: // stepper_z2 = 0.363065
Recv: // stepper_z3 = -0.035711
Recv: ok
[...]
Send: quad_gantry_level
[...]
Recv: // probe at 60.000,35.000 is z=2.713065
Recv: // probe at 60.000,169.000 is z=2.843065
Recv: // probe at 194.000,169.000 is z=3.113065
[...]
Recv: // probe at 194.000,35.000 is z=2.873065
Recv: // Gantry-relative probe points:
Recv: // 0: 2.286935 1: 2.156935 2: 1.886935 3: 2.126935
Recv: // Actuator Positions:
Recv: // z: 2.441533 z1: 2.363157 z2: 1.388027 z3: 2.143531
Recv: // Average: 2.084062
Recv: // Making the following Z adjustments:
Recv: // stepper_z = -0.357471
Recv: // stepper_z1 = -0.279095
Recv: // stepper_z2 = 0.696035
Recv: // stepper_z3 = -0.059469
Recv: ok
[...]
```

**Comment by fessyfoo** [comment]
I think the issue is the negative adjustments.   QGL produces adjustments in both the positive and negative direction.  I think the z_tilt code doesn't do the right thing in that case. 

Any reason not to use the QGL algorithm which just applies the adjustment to each stepper individually?    Or probably there's a reason to the z_titlt algorithm additively moving the steppers?

**Comment by KevinOConnor** [comment]
Thanks. It looks like z_tilt is passing "negative adjustments" in - which is weird.  I'll take a look at fixing z_tilt.  I think I can put together a test case too - which should make it easier to confirm correctness.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I added a test case (c037d273) for z_tilt_adjust and quad_gantry_level.  I've also updated the code and verified that (at least for the test case) both old and new code now make the same relative adjustments on z_tilt_adjust and quad_gantry_level.

Note, that there is a difference in absolute z position after quad_gantry_level with the new code (but not on z_tilt_adjust).  This shouldn't matter for the voron2 (as I believe the procedure is to re-home the Z after quad_gantry_level).  We can make it match behaviour, but I don't think the new code makes more sense.

-Kevin

**Comment by KevinOConnor** [comment]
Actually, on closer inspection, the old and new quad_gantry_level code produces the same results (at least for the test case) - the difference in absolute z_offset was just a quirk in the test case (fixed in 64214255).

-Kevin

**Comment by fessyfoo** [comment]
Ok, i tested manually and this new branch doesn't diverge with 10s of runs of quad_gantry_level. 

So LGTM.  

I'm guessing this is the change that fixed it, I think it means that the adjustments for QGL were backwards.   

```
% git diff 2ae641ede8b7381c3a974e158ba8ae64d6cb7cb2 9d26ff5c1f9352a76a206c53d61b00cb4e229f63  extras/z_tilt.py           
diff --git a/klippy/extras/z_tilt.py b/klippy/extras/z_tilt.py
index ad16372..5d98400 100644
--- a/klippy/extras/z_tilt.py
+++ b/klippy/extras/z_tilt.py
@@ -29,14 +29,15 @@ class ZAdjustHelper:
         gcode = self.printer.lookup_object('gcode')
         curpos = toolhead.get_position()
         # Report on movements
-        positions = zip(adjustments, self.z_steppers)
-        stepstrs = ["%s = %.6f" % (s.get_name(), so) for so, s in positions]
+        stepstrs = ["%s = %.6f" % (s.get_name(), a)
+                    for s, a in zip(self.z_steppers, adjustments)]
         msg = "Making the following Z adjustments:\n%s" % ("\n".join(stepstrs),)
         gcode.respond_info(msg)
         # Disable Z stepper movements
         for s in self.z_steppers:
             s.set_ignore_move(True)
         # Move each z stepper (sorted from lowest to highest) until they match
+        positions = [(-a, s) for a, s in zip(adjustments, self.z_steppers)]
         positions.sort()
         first_stepper_offset, first_stepper = positions[0]
         z_low = curpos[2] - first_stepper_offset
@@ -106,7 +107,7 @@ class ZTilt:
         y_adjust = new_params['y_adjust']
         z_adjust = (new_params['z_adjust'] - z_offset
                     - x_adjust * offsets[0] - y_adjust * offsets[1])
-        adjustments = [-(x*x_adjust + y*y_adjust + z_adjust)
+        adjustments = [x*x_adjust + y*y_adjust + z_adjust
                        for x, y in self.z_positions]
         self.z_helper.adjust_steppers(adjustments, speed)
 
```

`positions = [(-a, s) for a, s in zip(adjustments, self.z_steppers)]`  being key. 


I have to admit this stepper_adjust code made me feel dumb.  I got lost multiple times trying to follow it.   took me a while to note that the last adjustment is simply made by set_position() without an actual move.  Also was hard for me to recognize that the inverted stepper adjustments was wrong.  just because of the symmetry.   

Anyhow.  I think it works now.  the more cautious adjusting is nice.  though I think QGL was always producing a balanced adjustment which is why it's always got a couple negative adjustments paired with positive ones.

**Comment by KevinOConnor** [comment]
Thanks for the feedback.  I agree that the z adjustment code is complex - I have difficulty following it myself.  Now that it is unified we can look to simplify (and/or better document) the code.

The quad_gantry_level code was quite a bit simpler than the z_tilt z adjustment code.  However, (as we discussed off-line) my fear is the simpler code could cause stress on the bed/gantry in some corner cases.  For example, if Z0 and Z3 were 50mm higher than Z1/Z2 then the quad_gantry_level code would start by moving Z0 down 25mm (then move Z1 up 25mm, then Z2 up 25mm, then Z3 down 25mm).  My fear is that the initial Z0 move could place stress on the machine (as it would be forcing a twist on the bed/gantry).  In contrast, in the above example, the z_tilt code would simultaneously move Z0/Z3 up 50mm.

-Kevin

**Pull request merged**
