### PR TITLE
graph_motion: changed velocity profile, added jerk-limit calculations

### PR DESCRIPTION
**Pull request by dmbutyugin**
graph_motion: changed velocity profile, added jerk-limit calculations

Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I pulled it commit fd6737f5 to the work-resonsnace-20190928 branch.  I'm leery of pulling in the velocity change to 135mm/s because I think 100mm/s is a much more common speed in daily usage.  So, I agree 100mm/s can show some misleading results, but I think the handful of people using this test script will probably know that and can test accordingly.

Thanks again,
-Kevin

**Comment by dmbutyugin** [comment]
Thanks! Yes, 135 mm/s is more 'artificial' velocity. It was constructed for 3000 mm/s^2 acceleration, but others may be using different acceleration values.

Separately, would make sense to add negative velocities to the testing profile? For example, to cover the case of cornering at around 30-45-60 degrees - then the velocity could go from 100 mm/s to X mm/s and then jump to -X * cos(theta). X could be determined from the cornering formula. I added this test case to my local branch - and it seems to show more displacement during cornering - but did not push such changes to github

**Comment by KevinOConnor** [comment]
> Separately, would make sense to add negative velocities to the testing profile? 

I hadn't thought of that.  It does raise a similar question - would a test print better show the effects of resonance if it has a corner that results in a positive to negative velocity on one of the axes?

Separately, one of the ideas I was toying with is the ability to have a simulator read the micro-controller command output.  That way, one could see what the simulation does for an arbitrary print.  One of the challenges however, is that the amount of data from a real print is typically huge, which can make it harder to run tests.

-Kevin

**Comment by dmbutyugin** [comment]
> > Separately, would make sense to add negative velocities to the testing profile?
> 
> I hadn't thought of that. It does raise a similar question - would a test print better show the effects of resonance if it has a corner that results in a positive to negative velocity on one of the axes?

It seems that such corners could get more smoothed and less precise (due to larger offset). It makes some sense - the average, even weighted, can be further away from the tip of the angle. I'm not 100% certain about more ringing, maybe worth some testing. In general, I want to adjust the ringing test model to have notches of different depth, to be able to test different acceleration timings in one go and get more 'real' test. Maybe it would make sense to change the shape of the cuts for some notches to form shaper, non-square angles.

> Separately, one of the ideas I was toying with is the ability to have a simulator read the micro-controller command output. That way, one could see what the simulation does for an arbitrary print. One of the challenges however, is that the amount of data from a real print is typically huge, which can make it harder to run tests.

That would be great to have. 3dprintersim runs its own move calculations, and cannot fully simulate all processes that happen inside Klipper.

**Pull request closed without merging**
