### PR TITLE
Add support for temperature-triggered fan.

### PR DESCRIPTION
**Pull request by bmc0**
I think @w1ebr has something equivalent to merge so perhaps preference should be given to him, but here's my code anyway. Seems to work, though I can't say I've tested it very thoroughly.

Signed-off-by: Michael Barbour <barbour.michael.0@gmail.com>

### CODE REVIEW

**Comment by bmc0** [comment]
No, this is slightly different (See #317).

**Comment by KevinOConnor** [comment]
Thanks!  I got the impression that @w1ebr's work was based on top of your code, so I merged it.

**Comment by bmc0** [comment]
Alright. By the way, I just realized that I forgot to add a note about the `pullup_resistor` and `adc_voltage` parameters, so you may want to add that for the sake of completeness.

**Comment by wizhippo** [comment]
Any chance this could be changed a bit so it uses a pid loop so the fan goes faster as the temp rises?

**Pull request merged**
