### PR TITLE
Add get_status and TRY_STOP_ON_ENDSTOP to manual_stepper.py

### PR DESCRIPTION
**Pull request by kakou-fr**
Hi,

I have now a fully functional MMU on klipper.
I just need to add two feature to manual_stepper.py : 
1) get_status() that return the endstop status (open or TRIGGERED)
2) TRY_STOP_ON_ENDSTOP that not generate an error if the homing doesn't work (and so stop the execution of a MACRO).

I also posted my configuration as an example for a SKR 1.3 on the printer, and a SKR mini in the MMU.

It's my first klipper code patch, so maybe i don't use the good function ... feel free to correct me if something is badly writted

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

Commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Unfortunately, it's not valid to query the micro-controller in a get_status() method.  The get_status() method can't "pause" during its execution (as otherwise, the printer state could change within a get_status() call and that could cause internal errors in other parts of the Klipper code).  Since any query to the micro-controller would require waiting for the response, this isn't valid.

The TRY_STOP_ON_HOME looks fine to me.

-Kevin

**Comment by kakou-fr** [comment]
So how could I do it properly ?
Define something like : 
MANUAL_STEPPER STEPPER=drive_stepper QUERY_ENSTOP
that update a variable, and return this variable with get_status ?

**Comment by KevinOConnor** [comment]
I suspect writing a python module would be the most robust way of handling this.  That said, I'm not familiar with the mmu2, so I don't know if this is also possible via macros and how they should be developed.

-Kevin

**Comment by kakou-fr** [comment]
All is already developed with macro. The only thing i needed is the possibility to check the status of the PINDA and extruder endstop.

**Comment by kakou-fr** [comment]
new proposal : 
get_status return the last query test : None (never queried), open or TRIGGERED
get_endstop_status update the state
add a parameter to MANUAL_STEPPER : UPDATE_ENDSTOP_STATUS that call get_endstop_status

**Comment by KevinOConnor** [comment]
Thanks.

I still don't see a signed-off-by line containing your real name.  That would be required in order to commit.

It's fine to add a get_status() method that will report the status from the last query.  If doing that, I recommend adding the code to klippy/extras/query_status.py.  Please also do that in a separate commit from mmu support.

This series also adds a config/printer.cfg which should be removed.  Also, the newly added config/printer-mmu-remix.cfg should be named something like config/sample-mmu.cfg .

-Kevin

**Comment by kakou-fr** [comment]
I added my real name in signed-off-by.

I also removed the printer.cfg / printer-mmu-remix.cfg, i will rename printer-mmu-remix.cfg to sample-mmu.cfg and submit it in an other PR.

**Comment by kakou-fr** [comment]
It's ok for you ?

**Comment by KevinOConnor** [comment]
Sorry for my delay in responding.

At a high-level I think the code is fine.  But, I do think it would be better to move the endstop status reporting code to klippy/extras/query_endstop.py as I think it would be better to consolidate the endstop code in one location.

-Kevin

**Comment by kakou-fr** [comment]
my problem is that the status is related to the manual stepper. I can put the UPDATE code to the query_endstop.py, but the get_status will only report the status of the last queried endstop. It's ok for you ?

**Comment by KevinOConnor** [comment]
I added the reporting capability to query_endstops.py (commit 512ad4b3).  Unless I've missed something, you should be able to query the status via `{printer.query_endstops.last_query["manual_stepper my_stepper"]}`.

-Kevin

**Comment by kakou-fr** [comment]
ok your code work, so i only put the TRY_STOP_ON_HOME, added a QUIET parameter to QUERY_ENDSTOPS to not return the state and only update it, and updated the docs.

**Comment by kakou-fr** [comment]
It's ok for the integration of these patch ? I wait it in order to publish the mmu configuration

**Comment by KevinOConnor** [comment]
Sorry for the delay.  As a high-level comment it looks fine to me.

As a minor comment, is it necessary to add the QUIET parameter to QUERY_ENDSTOPS?  If so, it should be in a separate commit as it isn't related to the other changes.

For the change to manual_stepper - I think it might be worthwhile to use the existing STOP_ON_ENDSTOP parameter - perhaps something like if STOP_ON_ENDSTOP=2 (or -2) then it will stop on hitting the endstop and not raise an error even if it doesn't hit the endstop.  I can look at implementing this, but it'll likely take me a week or so to get to it.

Thanks.
-Kevin

**Comment by KevinOConnor** [comment]
FYI, I added the ability to ignore errors via the existing STOP_ON_ENDSTOP (commit 15f21be5).

-Kevin

**Comment by kakou-fr** [comment]
thks, for the QUIET parameter, it is just to not add a lot of information during the MMU operation and in the MMU traces. but it could also be a new gcode like UPDATE_ENDSTOPS

**Comment by KevinOConnor** [comment]
Okay.  FYI, I expect some code changes coming soon to query_endstop.py (there's interest due to backend http development), so if possible I'd prefer to reduce changes to it for now.  (I don't want to add user facing options/commands and then have to announce breaking changes in a couple of months.)

Let me know if you can't continue without that change though.

-Kevin

**Comment by kakou-fr** [comment]
yes this change can wait, it's just comestic. I will update my mmu config with the last change and post it in a new PR.

**Pull request closed without merging**
