### PR TITLE
config: Create printer-wanhao-duplicator-6-monoprice-ultimate-2016.cfg

### PR DESCRIPTION
**Pull request by cliffraccani**
Initial version.

Based on original Marlin source for Wanhao Duplicator 6.

Original source: <https://github.com/garychen99/Duplicator-6-firmware-version-3.1>

Signed-off-by: Cliff Raccani <bramhall45@hotmail.com>

### CODE REVIEW

**Comment by cliffraccani** [comment]
Sorry about that.
Capitalised and inserted a space.
Have edited original.
Many thanks.

**Comment by KevinOConnor** [comment]
One more question - I like to have date's in the configs - what year is your printer from?  (Doing some internet searches, it looks like this printer was released in 2016?)

-Kevin

**Comment by cliffraccani** [comment]
Yes I would agree, 2016. I have had the Monoprice Ultimate for approx. 2 weeks! Half price special on amazon UK (£399), could not pass it up.
It is a Zortrax m200 and ultimaker 2 clone. Once you work out the kinks this is the best printer for the money, even at the full price. The hardware is shared with the Zortrax and most parts are interchangeable. It uses some of the Ultimaker 2 software and an Ultimaker 2 clone board. The Wanhao Duplicator 6 is exactly the same printer, which the Monoprice is a re-badge of, but is £100 dearer.
They have just released the MK 2 Plus version which adds auto bed levelling and not much more.
Will you be changing the filename or will I?

**Comment by KevinOConnor** [comment]
Thanks.  I made some changes to the config and committed this (commit 67c62349).  The changes are mostly to the comments so the file is more similar to the other files.  I also removed the pressure advance settings (every filament has different pressure advance so there are no good defaults).  I also set the serial port to /dev/ttyACM0 - every board is likely to have a different unique id so the id on your board is unlikely to work on other printers.

Can you verify that the "restart: command" is needed - it's unusual to find an AVR board that doesn't support the default arduino restart method.  Also, how did you calculate the `scale: 2.782` parameter?  My read of the marlin code would be that it should be a scale of 2.0.

-Kevin

**Comment by KevinOConnor** [comment]
Oh - I also mapped the pins to the hardware names instead of using the arduino aliases.  It's generally preferable to avoid the arduino aliases unless one is actually using a board that has an arduino on it (like a ramps board attached to an arduino).

-Kevin

**Comment by cliffraccani** [comment]
I said I was a 'noob' and was wanting to learn.
It was a weekend project for me, to see if I could produce a starting point for others wanting to try Klipper. I am fully aware that you have a vision and want things to be at your standard. I understand this, and respect it.

The reference to the original code that my printer was using:
#Pin assignemets based on original firmware:
#https://github.com/garychen99/Duplicator-6-firmware-version-3.1
#file: pins.h - Motherboard = 72
This has been removed from the file, again this is your call but the information to all your questions and anyone else's for that matter, can be found at that repository.
Is it not useful for someone to  see the origins of the settings by having a reference to it. In my view you have removed useful information.

Again as a total 'noob' in all this, I had originally used the pin assignments you prefer. On reflection, felt that someone coming from a Marlin origin would prefer 'ar' pin assignments. Also seeing as you offered an 'ar' option, I used it and this made the conversion less error prone; for me any way.

Regarding the restart_method, I merely noticed that most of your example printers used 'command'. Obviously, the distinction was lost on me as I assumed any communication from Klippy to Host would require a 'command' like message.

I am glad you left the reference in regarding the display. I, as a total 'noob' would like to attempt, as another little project, the integration of this display into Klipper. Any suggestions and pointers to achieving this would be greatly received. I have a couple of decades of experience writing C/C++
 in a Banking environment but am new to embedded systems. Hey, I'm retired now, so I can do the stuff I find interesting right. We didn't use git then of course, so that's another learning curve. But, hey, I'm up for it.

I must say the fact that a total 'noob' could produce a config file in a weekend, with your help, speaks volumes to this great system of yours. 

Kind regards
Cliff

**Comment by KevinOConnor** [comment]
Thanks for the feedback.

I view the config directory as documentation; documentation with an audience of "users with a printer that want to run Klipper".  I like to keep the config examples focused on that audience.  I got the impression that some of the comments in the original submission were targeted at developers.  That information is useful, but I don't think the config directory is a good location for it.  (I fear it can add confusion to the common task of "I just want to use my printer").

If you feel the link needs to be there, I will add it back.

I did notice the link is effectively a link to a rar file, so I have not gone through the steps to pull it down, uncompress it, and check the code.  Does the `scale: 2.782` come from that code?

Getting support for display would be great.  It's a bit of work though - if I understand correctly it uses I2C - which would mean adding support for the AVR TWI peripheral to the mcu code.  Take a look at how src/lpc176x/i2c.c does that.  Then it would require adding display support to the host code - take a look at how klippy/extras/display/uc1701.py does that.

Cheers,
-Kevin

**Comment by KevinOConnor** [comment]
FYI, I've removed the "restart: command" as it generally isn't needed on avr based micro-controllers.  Let me know if you have further comments or if you go on to implement display support.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, we recently added support to Klipper for the SSD1306 display.  It shouldn't be too difficult to add support for the SSD1309 display.  If I understand it correctly, the SSD1306 and SSD1309 differ only in their initialization sequence.

-Kevin

**Comment by KeiferMiller** [comment]
> I did notice the link is effectively a link to a rar file, so I have not gone through the steps to pull it down, uncompress it, and check the code. Does the scale: 2.782 come from that code?

I was also curious.  From the rar's `pins.h` file:

`
//Motor current PWM conversion, PWM value = MotorCurrentSetting * 255 / range
#define MOTOR_CURRENT_PWM_RANGE 2782
`

Hope this saves someone else a few minutes of rar extractor downloading.
Keifer

**Pull request closed without merging**
