### PR TITLE
bed_mesh re-probe when probe measurement is over threshold

### PR DESCRIPTION
**Pull request by Sprk-nl**
module: bed_mesh: re-probe when probe measurement is over threshold

User Configuration:

[bed_mesh]
probe_ac_thresh: 0.05 ; max difference between probe measurements of a position
probe_ac_retry: 3 ; Measurement retries of a position

Signed-off-by: Gaston Bougie <gaston.bougie@gmail.com>

### CODE REVIEW

**Comment by Sprk-nl** [comment]
More ideally I'm looking in to a function where you can define 
the accuracy for the [bltouch] and [bed_mesh].
perhaps even one which follows the accuracy over time and reports if the % over threshold is rising.
This code does the job perfect for leveling within thresholds.

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks okay to me.  One issue, however, is the new config parameters will need to be documented in config/example-extras.cfg.  Also, I think it would be preferable to spell out the config names (eg, "accuracy_threshold").

As a minor note (not a merge stopper), _automatic_probe_point() is getting pretty large and I think the code would be a little more readable if the accuracy checks were in a new method.

-Kevin

**Comment by KevinOConnor** [comment]
Oh - as an additional note - if the retries are exhausted without finding an acceptable measurement then I think the code should raise an error.  Continuing on with a bad measurement is likely to cause a bigger issue for the user.

-Kevin

**Comment by Sprk-nl** [comment]
Totally agree.
The config names spelled out hit the 70 character limit, so this was a hasty fix :)
I would like to do more with the probing results: give the user a choice what to do when the probe was inaccurate: 
- stop the measurement
- Log it with the results
- Use the average of all measurements
- Show the percentage of failed or within threshold and by how much of a percentage
- Give a better user output, terminal readable and json.

First step: code cleanup and documentation update.

**Comment by KevinOConnor** [comment]
I recommend against adding complexity in the failure case.  I can't see any real world situation where a user would want to continue with a bad measurement - prompting the user when there isn't a real choice just adds confusion.  If a user doesn't care about the accuracy they can update their config to disable retries or to increase the tolerance.

-Kevin

**Comment by Sprk-nl** [comment]
>  If a user doesn't care about the accuracy they can update their config to disable retries or to increase the tolerance.
>
Ok. That's indeed a clear approach. and good food for documentation

**Comment by KevinOConnor** [comment]
FYI, I added some basic tolerance support to Klipper (commit c92aca74).

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I'm going to close this PR as I think the basic support is now in the master branch.

-Kevin

**Pull request closed without merging**
