### PR TITLE
quad_gantry_level: Support retries

### PR DESCRIPTION
**Pull request by fessyfoo**
first pass, open to any feedback.  cc @mzbotreprap  

support retrying QUAD_GANTRY_LEVEL a configurable number of times
to a configurable tolerance both in the config or as parameters.

by default keeps original behavior of no retries.

adds parameters RETRIES and RETRY_TOLERANCE
adds config options retries and retry_tolerance

### CODE REVIEW

**Comment by VoronDesign** [comment]
Neat! While you're at it, you should add an error message if the delta is getting progressively worse, which would indicate the Z motor numbering is wrong.

**Comment by fessyfoo** [comment]
Added error message  if the delta grows between retries.

**Comment by doowrednu** [comment]
Nice - would also be good to add a safety feature that prevents quad from trying to do a correction that might break things - if your probe fires early for whatever reason and trys to do an 8mm correction in one corner - I would like to see it fail if a correction is over 4mm

**Comment by fessyfoo** [comment]
@doowrednu  #1510

**Comment by fessyfoo** [comment]
After some feedback in testing of this and a similar z_tilt_adjust change. I'm considering changing the test for wether to retry to be based on the amount of z adjustment rather than the the difference between highest and lowest probed heights.     a subtle difference.  but should be more intuitive. and should  

closing for now.   will reopen shortly.

**Comment by fessyfoo** [comment]
reopened as #1658

**Pull request closed without merging**
