### PR TITLE
Improved support for the MTW Create and added the MTW MendelMax 3

### PR DESCRIPTION
**Pull request by mtw3d**
Signed-off-by: Mike Payson mikepayson@gmail.com

### CODE REVIEW

**Comment by pusewicz** [comment]
@mtw3d Please rebase your commits and squash them. There should be just 1 commit adding the files.

**Comment by mtw3d** [comment]
I apologize, I am not a programmer. Can you tell me what this means?

**Comment by KevinOConnor** [comment]
It looks like your git repository got confused with various merges.  You can do a web search for "git rebase" to figure out how to rebase the changes on top of the master Klipper branch.  However, it might be simpler for you to clone a clean Klipper repository, copy the config files into that repository, commit them, and then push that PR.

Currently, the git history on this PR is confused, so I can't tell what's being proposed.

-Kevin

**Comment by mtw3d** [comment]
Go ahead and just kill that merge request for now, I have made further changes to the file being merged so it will be easier to just do a fresh request once I figure out the problem.

**Pull request closed without merging**
