### PR TITLE
Add term to the heater power, proportional to the extruder speed

### PR DESCRIPTION
**Pull request by gayuha**
I added a Kc factor to the PID. This increases the duty cycle of the heater to compensate for the cooldown caused by the plastic melting.
In my case, a value of 9 reduces the dip and then overshoot of the temperature after a fast, mid-air, extrusion-only move. In real prints though I didn't notice a significant difference. Maybe a slight look-ahead will work better (compensate for future moves).

It was previously requested in these issues: #573 #2175

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Interesting.

FWIW, though, I'm reluctant to add changes like this unless there's a real-world use case that shows significant improvement with it.  In my experience, adding "tuning knobs" to the PID increases complexity, increases time people spend trying to tune it, and ultimately yields little advantage.

I do agree that a "feed forward" PID - or perhaps something based on a "first order plus delay time" (fopdt) - could be very useful.  I think we'd need the "full solution" in that case though - calibration commands, tuning docs, wide spread testing, etc.

Cheers,
-Kevin

**Comment by gayuha** [comment]
I agree. Just wanted to hear your thoughts. I'll look into fopdt, never heard of it. I've seen something similar in Repetier firmware, maybe I'll look into it.

**Comment by KevinOConnor** [comment]
Thanks.  I have a really old branch with experiments on FOPDT - https://github.com/KevinOConnor/klipper/tree/work-fopdt-20180405 .  (The run-time code didn't work well at all, but the HEATER_CALIBRATE command did a surprisingly good job at finding the fopdt constants.)  If I get a chance I'll try to rebase that branch.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, thanks.  I'm going to close this as it looks like the conversation has concluded.

-Kevin

**Pull request closed without merging**
