### PR TITLE
config: Updated Wanhao Duplicator i3 Plus cfg

### PR DESCRIPTION
**Pull request by agentnoise**
updated hotend PID values
set bed to PID control and added PID values
updated bed max_temp
set max_extrude_only_length to 200.  This allows for proper e-steps calibration
updated e-steps value
set all axis homing speed to 30
set MCU baud rate

Signed-off-by: max holden <malxholden@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
If you're having a problem with a baud of 250000, I'd like to see a log of the session.  (Compile for 250000, flash the micro-controller, change the config file to use the default of 250000, provide the resulting klippy.log file in a new issue.)

@dgz - can you review the other parts of this request?  (Sorry, for the spurious reference on the other commit.)

**Comment by dgz** [comment]
PID on the bed is a good change, the standard config in my ice cold basement causes the bed temperature to swing about 4 degrees while maintaining.
I haven't done a PID tune on my extruder so I don't have any thoughts on those updates.

I'm not so sure about the change to extruder steps. Stock config is 96 steps/mm (0.010417 mm/step) and depending on who you ask on the internet you'll get a suggested range of 94-100 steps/mm. This change works out to 117 steps/mm which seems high as a starting point.

**Comment by agentnoise** [comment]
@dgz For the bed, we should all really be using PID.  There is good evidence it help with some z [artifacting](https://www.akeric.com/blog/?p=4276) I tested the e-steps with what it came with but was not hitting the mark.  My printer has always needed about that level of E-steps, might just be mine though.    The config I posted consistently keeps my hotend at less than [half a degree](https://imgur.com/g9pcOAy) of target temp.  The original config was fluctuating a couple of degrees and was struggling to get to higher temps(220+). 

@KevinOConnor  I did get it working with 250000 by re-flashing the MCU

**Comment by KevinOConnor** [comment]
Okay, thanks.  I updated just the heater settings (and the homing speed for x/y) - commit 6fa95e12.

**Pull request closed without merging**
