### PR TITLE
Add gcode command for temperature_fan.py

### PR DESCRIPTION
**Pull request by nashuar**
module: TEMPERATURE_FAN.PY

I added a gcode command for setting the target temperature of temperature_fan.
Example gcode: SET_TEMPERATURE_FAN_TARGET temperature_fan=chamber target=35.0

Signed-off-by: Martin Nowroth madnoth@gmail.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks fine but I do have a couple of comments:
- the signed-off-by line needs a current email address - see https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md
- a gcode command handler should only ever return gcode.error() exceptions - otherwise it will result in an "internal error" that shuts down the micro-controller and host software.
- it seems odd that the default target temperature for the command would be 40.  Shouldn't the parameter always be provided?  Or, perhaps return it to the config file default?

Cheers,
-Kevin

**Comment by nashuar** [comment]
I implemented your suggestions and hope you are ok with my changes. 
Best regards
Martin

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me (though it would be nice to remove the now unused error() definition at the top of the file).  @wizhippo - do you have any comments on this change?

-Kevin

**Comment by wizhippo** [comment]
Like thank you.

**Comment by nashuar** [comment]
Followed your recommendation and removed the error part you mentioned. 

Best regards
Martin

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
