### PR TITLE
Added PWM value (int, half scale) to M105 output

### PR DESCRIPTION
**Pull request by senseisimple**
This adds a third value to the M105 value for PWM (power output) which allows graphing and visualization of the temp vs 'realtime' pwm value on the heater. This greatly helps with troubleshooting PID and pid_integral_max values when the PID calibration alone isn't enough to prevent wide oscillations with a strong heater (i.e. E3D Volcano).

This value is simply copied from the already available last_pwm_value variable and so accurately reflects 0 when there is none without any additional logic.

The M105 output is changed from the current (example):
`Recv:21:59:51.063: ok B:24.7 /0.0 T0:21.7 /0.0`
to
`Recv:21:59:51.063: ok B:24.7 /0.0 @0 T0:21.7 /0.0 @0`
`Recv:21:59:51.063: ok B:24.7 /55.0 @127 T0:21.7 /195.0 @55`

This is a screenshot from Repetier Server with the new value.
https://i.imgur.com/yVnaUi0.png

Note that the PWM value is converted from the 0.00 to 1.0 floating value to 0-255 integer and then halved to match Marlin's output (0-127 max) for those applications which display it according to marlin. IMO this isn't ideal because as far as i can tell from looking into the matter, the halved output value seems to be arbitrary and severely limits granularity where a high level of such is provided by Klipper.

I was thinking to add a multiplier or divisor config option to allow for customizing the value on M105 output (i.e. default is no multiplier (1) so M105 output would be 0-255 or 0.5 to make it 0-127 ) alternatively a mode: i.e. [default]: off, "float": 0.000-1.000, "marlin": int 0-127, "integer": 0-255   I think the mode style would be easier to use, am open to suggestion.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback, however, is that I'm reluctant to change the output of M105.  I'm leery of adding "new functionality" to "old g-code".

I do see the value in being able to query and monitor the PWM output values.  Adding the information to the `get_status()` method so that it is available from the "webhooks api server" and from "gcode macros" would be useful.  That would allow users to query the information from external programs and/or custom g-code commands of their choice.

Separately, commits need to have a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by WindoC** [comment]
I do a similar pull request before https://github.com/KevinOConnor/klipper/pull/1785 😄

**Comment by yschroeder** [comment]
However this will be implemented, I second this feature as being useful. I remember this being available on our ancient printer running Repetier Host to control it (Octoprint didn't exist yet). I really want to be able to judge if my heater can keep up with the speed. Also this should be displayed nicely by OctoKlipper but that is a separate topic.

**Comment by KevinOConnor** [comment]
I'm going to close this as I don't think it's the direction we should take for the master Klipper branch.  If there is interest in expanding the `get_status()` results with PWM info then feel free to sumbit a PR with that.

-Kevin

**Comment by dewi-ny-je** [comment]
@senseisimple have you considered adding that value to get_status as suggested? then a custom M105 could be provided with a macro.
I had this "improved" M105 since my Printrbot in 2013 (which was running an ancient Marlin, FYI) and I assumed it was standard, in fact. Prusa also supports it: https://forum.prusaprinters.org/forum/english-forum-general-discussion-announcements-and-releases/parsing-m105-results/

Getting the value in realtime is surely useful, as @yschroeder  said.

**Comment by KevinOConnor** [comment]
FYI, the "power" field was added to get_status() in commit 77add956.

-Kevin

**Pull request closed without merging**
