### PR TITLE
filament_switch_sensor:  Replace BaseSensor with RunoutHelper

### PR DESCRIPTION
**Pull request by Arksine**
As suggested in #2505, the BaseSensor has been replaced with a RunoutHelper.  Filament Sensor implementations may instantiate a RunoutHelper object and call its "note_filament_present" method with the filament state (True if present, False otherwise).  To initialize filament state the first call to note_filament_present should be no later than 2 seconds after the printer enters the "Ready" state.

This PR has no impact on configuration or behavior of the filament_switch_sensor.

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!  Looks good to me.  If there are no further comments I'll commit in a couple of days.

FYI, one thing I noticed is that the note_filament_present() command directly calls gcode.run_script().  This means that note_filament_present() could block, which could make its caller re-entrant.  This isn't a problem for SwitchSensor (the only user of RunoutHelper), but it may be an issue for future users.  So, something to take a look at in future updates.

-Kevin

**Comment by Arksine** [comment]
I did remove the reactor callbacks that execute the event handlers, as I was thinking that they were unnecessary.  Good point about the possibility of affecting other implementations.  It won't hurt for me to add them back, I'll go ahead and do it later today.

**Comment by Arksine** [comment]
I added a couple of commits today, the first should take care of any potential future re-entry issues, the second simply adds a get_status() method.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Pull request merged**
