### PR TITLE
TMC2130, TMC2209, TMC5160 homing current

### PR DESCRIPTION
**Pull request by blondak**
Reducing TMC current while homing #1850

### CODE REVIEW

**Comment by blondak** [comment]
Yeah, its related to manly to sensoreless homing, but not only for this case. I'm not familiar with python but, if there exits something like a interface, that expose set_current, there can be "universal" module for setting homing current independent on used drivers.

**Comment by KevinOConnor** [comment]
All the tmc drivers support a SET_CURRENT command, so the TMCVirtualEndstop class could issue that before/after the homing.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, I looked at the most recent code.  It shouldn't be necessary to add "events", as the endstop code already gets invoked via home_prepare() and home_finalize() calls - which are intended to allow modules to run g-code commands.  Also, the latest code invokes gcode._cmd_mux() - it's not valid to run private methods of classes in other files in Klipper (this is mentioned briefly in docs/Code_Overview.md).  I think the command you're looking for is gcode.run_script_from_command().

-Kevin

**Comment by rafaljot** [comment]
There is PrusaOwners fork. 
https://github.com/PrusaOwners/klipper/blob/master/config/printer-prusa-i3-mk3-2017.cfg

It is already done there.

**Comment by KevinOConnor** [comment]
FYI, in general the new code looks good to me.  One change that I think should be made is to not store a reference to the config object past the "init phase".  Otherwise, it can cause confusion (as config error reporting only makes sense during the "init phase".)

I do think that this change would be something to merge after the v0.8.0 release (#2037).

FWIW, a slightly different approach would be for each class to pass in its "CurrentHelper" class to the "TMCVirtualPinHelper" class - that could allow for more direct manipulation of the current during homing.

Thanks,
-Kevin

**Comment by thunders82** [comment]
Hi @KevinOConnor 
It doesn't look like this one has been merged. Do you have any timeline to implement it ?
Apologies in advance if I missed something.

Thank you

**Comment by KevinOConnor** [comment]
Sorry for the delay in reviewing.  My high-level feedback is that the functionality looks useful.  However, I think it may make sense to refactor the "current helper classes" before making this change.  In particular, there's currently a bit of duplicated code between tmc2130, tmc5160, and tmc2660.py, and it looks like this addition adds to that duplication.  I'll try to look at reducing that duplication over the next few weeks.  We can then look again at merging this.

-Kevin

**Comment by mrx23dot** [comment]
Does this include bed leveling with sensorless TMC2209?

**Comment by KevinOConnor** [comment]
FYI, PR #3974 implements a refactoring of the TMC set_current implementations.

FWIW, though, I did notice a couple of things with this PR:
1. This change enables the regular run current immediately after the homing sequence ends.  However, with sensorless homing, that would occur while the carriage is still pressed against the frame.  Ideally, somehow, the full current would only be enabled after the carriage is moved away from the frame.
2. It would be nice if the homing current was applied for all homing operations, and not just sensorless homing.

-Kevin

**Comment by freighttt** [comment]
is there a way for us normies to give this a try? ive copied over the relevant changed files but i dont think its gone into effect? working with the backend stuff its way above my pay grade, so feel free to tell me to bugger off and wait for the official implementation ;-)

**Comment by KevinOConnor** [comment]
It looks like this PR is inactive.

-Kevin

**Pull request closed without merging**
