### PR TITLE
stm32: enable chipid as usb serial number.

### PR DESCRIPTION
**Pull request by mattthebaker**
Signed-off-by: Matt Baker <baker.matt.j@gmail.com>

### CODE REVIEW

**Comment by mattthebaker** [comment]
PR for review. I tested this on stm32f042 and stm32f103. I don't have an f4 board available to test on. The hex string conversion code is duplicated 3 times counting lpc176x, may be worth refactoring.

**Comment by KevinOConnor** [comment]
Thanks.  Yeah, I think refactoring the descriptor filling code would help.  How about the two patches on the work-chipid-20191124 branch (commit 58a5b7f7 followed by commit be862804)?  I also tested this on my stm32f103 and stm32f446 boards without issue.

-Kevin

**Comment by mattthebaker** [comment]
The structure in the patches looks really good. The lengths and multiplications by two look like they may be slightly off. I'll build and test the code on my lpc/stm32f0/stm32f1 tonight.

**Comment by KevinOConnor** [comment]
Okay, thanks.  FYI, I made some minor changes to the work-chipid-20191124 branch to hopefully make the string limits a little simpler.  I also added in support for samd21/samd51 ids as it was pretty trivial.

Interestingly, AVR doesn't have a hardware unique id.  The sam3/sam4 does, but it doesn't look super simple.

-Kevin

**Comment by mattthebaker** [comment]
Are there AVRs with hardware USB? About the best you can do if there isn't a factory unique ID is look for oscillator, adc, or similar factory calibration bits that may vary unit to unit. It wouldn't be guaranteed but given any couple of devices they may be unique enough. The SAMs look complicated like the LPC was.

**Comment by mattthebaker** [comment]
I'm still a little unsure about the string length multiplies by two, but if the serial is coming out correct it must be fine.

**Comment by KevinOConnor** [comment]
> Are there AVRs with hardware USB?

Yes - the atmega32u4, at90usb646, and at90usb1286 are supported.  These chips aren't very common, and I don't think it's an issue to have the user manually set a serial id in "make menuconfig" if they need that.

-Kevin

**Comment by mattthebaker** [comment]
I can confirm that work-chipid-20191124 branch is working as expected on stm32f042/stm32f103/lpc1768.

**Comment by KevinOConnor** [comment]
Great - thanks!  I committed that branch the master branch.

-Kevin

**Comment by mattthebaker** [comment]
Great! Closing this PR.

**Pull request closed without merging**
