### PR TITLE
config: Added pins for LCD encoder and button click on Creality Ender 3

### PR DESCRIPTION
**Pull request by controla**
- now that menus are a thing, here's the pins to be able to use them.

Signed-off-by: Gonzalo Ramírez <controla@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  For the encoder, does "^!PD2, ^!PD3" work better than "^PD2, ^PD3" on the ender3?  (On my ramps board, I need to remove the ! or there is a delay in response when going clockwise to counter-clockwise and vice-versa.)

-Kevin

**Comment by controla** [comment]
You are right, just tested it and there is one extra step needed for the encoder to register direction changes, so it's best to remove the ! from the pin.

**Comment by KevinOConnor** [comment]
Thanks.

**Comment by faboaic** [comment]
I am new to github and need to check how all this works... 

But I used the encoder and click button settings from Ender-3 config in my cr-10 and Ender-2 and it worked perfectly.
Maybe someone can add it to cr-10 (Melzi,  non 'S' ) and Ender-2  ?
Thanks, 
Fabian

**Comment by KevinOConnor** [comment]
@faboaic - thanks.  Just to be clear, you added the following:
```
encoder_pins: ^PD2, ^PD3
click_pin: ^!PC0
```

to both the printer-creality-cr10-2017.cfg and printer-creality-ender2-2017.cfg printers and the menu works correctly?  If so, I'll go ahead and add that.

-Kevin

**Comment by faboaic** [comment]
Exactly. 

CR-10 with slightly adapted printer-creality-cr10-2017.cfg:

```
[display]
lcd_type: st7920
cs_pin: PA3
sclk_pin: PA1
sid_pin: PC1
encoder_pins: ^PD2, ^PD3
click_pin: ^!PC0

```
Ender-2 with little adapted printer-creality-ender2-2017.cfg:
```
[display]
lcd_type: uc1701
cs_pin: PA3
a0_pin: PA1
encoder_pins: ^PD2, ^PD3
click_pin: ^!PC0
```

Bad quality video showing that it works well.  ;)
https://youtu.be/SEN9W43vnfQ

Thanks so much, 
Fabian

**Comment by oderwat** [comment]
I can confirm this changes for the Ender 3 too (afaik they all have more or less the same board, with minor details changed over time).

**Comment by KevinOConnor** [comment]
Thanks.  (Commit b6567926)

-Kevin

**Pull request merged**
