### PR TITLE
Create tronxy-x5s-gt2560-e3d-gold-bltouch.cfg

### PR DESCRIPTION
**Pull request by riddlez666**
My config for my custom setup but useful for others regardless.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  What's custom about this config?

Also, the probe speed of 80 seems high - is that needed due to something particular with the bltouch?  It looks like the homing override homes the Z twice (which I guess is actually four times due to the normal double home mechanism) - is that also something particular with the bltouch?

-Kevin

**Comment by riddlez666** [comment]
Its got to do with not being able to move until xy and z are homed so it does it at 0,0 then middle of bed, i would love to home x,y then go center of bed drop 5mm then extend probe then do z. i will keep this config updated as i improve my printer. and a bilinear probe of 4 x 4 G29 command would be awesome.

**Comment by riddlez666** [comment]
its also using a geeetech gt2560 board with ultimaker pinouts so its speacial in its own right.

**Comment by KevinOConnor** [comment]
Okay, thanks.  It should be possible to home the Z only once - I added a config/sample-bltouch.cfg file with feedback from yourself and others.  Can you confirm if the settings there work for you?

**Comment by riddlez666** [comment]
Looks like it does and is at least a starting point for users to use this setup as a probe, you miss understand me i need a override to allow x and y to home then move to center of x and y to probe z. Is this possible am i missing a setting?

**Comment by riddlez666** [comment]
Still learning the firmware i found my answer.

**Comment by KevinOConnor** [comment]
Thanks.  I'm going to close this as I think most users will be interested in what is now in sample-bltouch.cfg .

**Pull request closed without merging**
