### PR TITLE
bme280:  Add support for BME280 environmental sensor

### PR DESCRIPTION
**Pull request by Arksine**
In addition to support for the BME280, this PR contains i2c read support for AVR platforms and i2c support for the linux mcu.  The sensor implementation has been tested using the above platforms as well as the SAM3X with an Arduino Due.

Below is the example configuration I used to test the sensor connected to a Raspberry Pi:

```
[temperature_sensor chamber]
sensor_type: BME280
i2c_mcu: linux
i2c_bus: i2c.1
gcode_id: AMB

[gcode_macro query_bme280]
default_parameter_SENSOR: bme280 chamber
gcode:
    {printer.gcode.action_respond_info(
        "Temperature: %.2f C\n"
        "Pressure: %.2f hPa\n"
        "Humidity: %.2f%%" % (
            printer[SENSOR].temperature,
            printer[SENSOR].pressure,
            printer[SENSOR].humidity))}
```

The temperature will show up in responses to M105 and the above macro can be used to query humidity and pressure in addition to temperature.

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks!  I'm not sure about the rate change in the avr i2c code, but everything else looks good to me.

For the avr i2c code, I'm not sure this would do the right thing if there were two devices on a single i2c bus and the user somehow configured one device at 100k and a second device at 400k.  Also, if the avr code has a divide by an arbitrary variable it causes gcc to bloat the code (as it has to emit all the code to perform software based division).  That may not be desirable on some of the flash starved avr chips (like the atmega168/328).  An alternative may be to explicitly check for 100k or 400k so that gcc can compile-time calculate the division.

-Kevin

**Comment by Arksine** [comment]
No problem.  I just pushed a commit to add an option in the KConfig for i2c speed.  If it looks good I can squash it with the original avr i2c commit, or if you would prefer I can drop  it.

**Comment by KevinOConnor** [comment]
FWIW, I'd say the rate is something we'd want to set at runtime and not compile time.  Since it's not really related to the bme280 might be best to pull it out for now - that way it doesn't complicate the rest of the changes.

-Kevin

**Comment by Arksine** [comment]
Makes sense.  Rate configuration dropped.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Pull request merged**
