### PR TITLE
delta_calibrate: Show statistic info about delta_calibrate process

### PR DESCRIPTION
**Pull request by andri-ys**
After running delta_calibrate, it will show these additional info :
- x, y, and z coordinates of each probe location
- count of probing points
- the average of z probe position (could be useful to approximate the z-probe offset)
- standard deviation of z position (useful to have some clue about the calibration quality), a perfect calibration would have stdev == 0

Signed-off-by: Andri YS <andri.ys.st@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
FYI, the delta calibration code already outputs information on each probe point and the total error to the klippy.log file.  (The error reported to the log is the variance, which is the square of stddev.)  Also, note that the Klipper convention is to not directly access member variables of classes defined in other python files (as doing so increases long-term maintenance costs).

-Kevin

**Comment by andri-ys** [comment]
Hi Kevin,

Thanks for taking the time to review this PR.

> FYI, the delta calibration code already outputs information on each probe point and the total error to the klippy.log file. (The error reported to the log is the variance, which is the square of stddev.) Also, note that the Klipper convention is to not directly access member variables of classes defined in other python files (as doing so increases long-term maintenance costs).
> 
> -Kevin

I do aware about the information generated for each probe point, but I believe this is different from the statistic of the delta calibration process as a whole. The former is more suitable to assess the quality of the probe, while the latter is a good hint about the quality of the mechanical movement as a whole. 

FYI, I was using Marlin previously, and in Marlin the delta calibration is an iterative process, using standard deviation as the goal. So the process is repeated automatically until the SD hits a low point. I found that the SD value is a good hint about the quality of the printer itself. For example, I can't get a low SD value if there is a loose screw in the arm. I still took this approach after using Klipper, so I will repeat the calibration process (or checking the arms for loose screw etc) until the SD value is low enough. I initially using spreadsheet to calculate the SD value, before I realize I could do it directly from the code.

Please let me know what you think about the value of providing this kind of information to the user. If you think this is valuable enough, I could try refactor the code to conforms better to the convention.

Thanks in advance, and thanks for the great work.

Regards,
Andri

**Comment by KevinOConnor** [comment]
Thanks.

The delta calibration process works by calculating the error between each measured position and its desired position, it then tries different delta parameters, and then calculates the new error using those values.  It iterates through these new delta paramaters until it can no longer reduce that error.  The process is technically referred to as "coordinate descent".

So, the new code appears to be reporting essentially the same thing already calculated during the main calibration code.  (The `total_error` determined in `calibrate_params()` is the variance, which is the square of standard deviation.)

The delta calibration code has quite a bit of complexity, so my high-level feedback is that I'm leery of adding any additional complexity to that process.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I'm going to close this as it looks like the conversation has concluded.

-Kevin

**Pull request closed without merging**
