### PR TITLE
spi_flash: Support firmware dictionary validation

### PR DESCRIPTION
**Pull request by jschuh**
Updates firmware validation to use a dictionary if provided (or found
when updating from the default out/ directory).

Validation without a dictionary still checks the following (in order):
1. Active firmware's raw dictionary changed after update
2. Checksum of firmware.cur matches expected

Signed-off-by: Justin Schuh <code@justinschuh.com>

This PR depends on #4381. Hopefully I did this right, since it's the first time I've stacked PRs. I would have expected the diff to be against the other PR, but the UI seems to display a much larger diff against master.

### CODE REVIEW

**Comment by jschuh** [comment]
@Arksine, I wanted to check if you're okay with the way I split this out from #4381. Kevin suggested that the script should always validate the dict if one is passed, but I know you're concerned about user error as well. So, I kept the dictionary as an optional switch and have the shell script provide a default `out/firmware.dict` only if it's also using the default `out/firmware.bin`. That seemed like a good way to address both concerns, but I'm open to other suggestions.

**Comment by Arksine** [comment]
Looks ok to me, it seems that the user will have to explicitly enter the wrong dictionary path for it to be a problem.

**Comment by jschuh** [comment]
Thanks, that was my take as well. If you're okay with it, then I think this patch and #4381 should be good to go?

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
