### PR TITLE
add backlash setting for x , y , z axis

### PR DESCRIPTION
**Pull request by rizpardazan**
hello all
i think backlash setting is necessary for a printer especially for Z axis , please add an option to add backlash to axis.
thank you

### CODE REVIEW

**Comment by Arksine** [comment]
Did you mean for this to be an issue?

**Comment by rizpardazan** [comment]
> Did you mean for this to be an issue?

no , this is a feature request

**Comment by theopensourcerer** [comment]
A pull request is NOT a "feature request".

**Comment by KevinOConnor** [comment]
This pull request appears to have been opened in error.  It looks like a dup of issue #1144.

-Kevin

**Pull request closed without merging**
