### PR TITLE
Ubuntu 20.04 install script with forcing python2

### PR DESCRIPTION
**Pull request by OlegRomanenko**
1. Installs python2 explicitly
2. Makes python2 as default python
3. Installs latest pip (specially for python2.7)

klippy.log:
```Starting Klippy...                                                                                                                                                                                                                                                                                                             
Args: ['/home/slader/klipper/klippy/klippy.py', '/home/slader/printer.cfg', '-l', '/tmp/klippy.log']                                                                                                                                                                                                                           
Git version: 'v0.9.1-165-gdc033d82'                                                                                                                                                                                                                                                                                            
CPU: 4 core ?                                                                                                                                                                                                                                                                                                                  
Python: '2.7.18 (default, Aug  4 2020, 11:16:42) \n[GCC 9.3.0]'                                                                                                                                                                                                                                                                
Building C code module c_helper.so                                                                                                                                                                                                                                                                                             
Start printer at Sun Jan 24 09:03:37 2021 (1611468217.4 4434.3)                                                                                                                                                                                                                                                                
```

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks, but I'm not comfortable with scripts that download code from a website and then run that code as root.

This was raised previously in PR #3564 .  I just changed the install scripts to not require python-virtualenv (commit dd7b98cc).  Last I checked, that was the only change needed to install Klipper on ubuntu 20.04.

-Kevin

**Comment by OlegRomanenko** [comment]
Yes, I agree with you. But there is no pip package for python2 in ubuntu 20.04. And there is no python-serial package in apt. 
So, I found only this option to install pip.

**Comment by KevinOConnor** [comment]
It worked for me when I tested with 20.04 images.  (Though it is possible the github test images customized the python packages in some way.)  As stated in #3564, klipper does not require a python2 version of pip/virtualenv to install - it just needs python2 when running the application.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this because, as far as I know, the existing ubuntu install script should work fine (as of commit dd7b98cc).

-Kevin

**Pull request closed without merging**
