### PR TITLE
WIP: Calibration guide specific to Klipper

### PR DESCRIPTION
**Pull request by grigi**
This is my WIP attempt at compiling a calibration guide, specifically for Klipper.

The guide is still very raw, and is still missing much content or proper integration with the existing docs.

I don't want to duplicate any of the existing docs that we already have, so will probably break this up into an index document,and then sub-documents.
To make it "flow" with the existing docs I will very likely have to restructure existing parts of `Overview.md`.

I also haven't properly considered the implications of referring to external guides. For example Triffid Hunter's guide on reprap, or Teaching Tech or 3D Print Beginner guides which are all excellent resources (some of which are Marlin-specific in part)

Do I add a qualification to indicate the Marlin specific parts that should be ignored? Should I just point to the exact information and trust that the reader doesn't go ahead and try to run some Marlin Specific gcode that fails and then logs an issue that our docs are wrong?
Is it even allowed? I'm not seeing external references in the current docs?

This will take some time to hash out properly, and I'd love lots of info and ideas to make this a good starting point for anyone. :slightly_smiling_face: 

This was primarily motivated by my struggles to get some of the basics like a good first layer dialed in with manual bed levelling and Klipper (which was so different from the Marlin experience that it was actually a revelation when I finally figured out the right way).
Also my struggles with getting good Resonance Compensation with acceptably little smoothing (https://github.com/KevinOConnor/klipper/issues/3027) to requests about tuning (https://github.com/KevinOConnor/klipper/issues/3592) and some interesting discussions (https://github.com/KevinOConnor/klipper/issues/3596)

DONE:
* [x] Tuning outline
* [ ] Restructure index
* [x] Mechanical checks
* [ ] PID
* [ ] Bed levelling
  * [ ] Current bed levelling doc assumes no significant Z-backlash, which is a naïve assumption (and wrong for my printer)
* [ ] Extruder step calibration
* [ ] Slicer flow calibration
  * [ ] How is TT doing it badly? What is the correct way?
* [ ] Safe max print speed
  * [ ] Softer filaments such as Nylon/TPU flows much worse when there is backpressure (such as when printing)
* [ ] square_corner_velocity (equivalent of jerk)
* [ ] Pressure advance
* [ ] Retraction tuning
* [ ] Resonance compensation
  * [ ] Mention that this may reduce fine details, and is mostly recommended for when you're battling with resonances.

Signed-off-by: Nickolas Grigoriadis <nagrigoriadis@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Interesting, thanks.

> I also haven't properly considered the implications of referring to external guides. For example Triffid Hunter's guide on reprap, or Teaching Tech or 3D Print Beginner guides which are all excellent resources (some of which are Marlin-specific in part)

I think it's okay to reference external articles.  The Pressure Advance guide does this now and we also have a few links to calibration objects on thingiverse.  One of the challenges here is that some guides do really well on one topic, but will have subtle errors on other topics.  For example, the teaching tech calibration article does a really great job on most topics, but offers (as I understand it) really bad advice on "slicer flow calibration".  Also, Klipper has some useful calibration tools (eg, TUNING_TOWER and Z_ENDSTOP_CALIBRATE) that the external documents wont mention.

I did take a look through your current documentation notes.  I have some high-level comments, but don't take them too seriously.  They're just for discussion points.

FWIW, I prefer guides that provide "actionable items" over guides that offer "general advice".  For example, I prefer advice like "apply approximately 2 grams of Acme X19000 SuperLube to the X rail and move the X carriage back and forth to spread the grease along the rail" over advice like, "make sure your rails are lubricated".  This is, of course, a challenge for Klipper documentation as we don't know what type of robot the user has (eg, it may not even have rails).

I find reading guides most helpful when I don't know what the solution is, or even what the root cause of the problem is.  One of my concerns with "general advice" is that I fear it can sometimes make it harder to find a solution.  As an example, if I'm having an issue with "print warping" I may want to read a calibration guide.  If I find advice to "stiffen my frame", it may lead me to research what that means, what it would entail for my particular printer, and if doing that is likely to correct the issue I'm seeing (print warping in this example).

Along the same lines, I'd be leery of offering safety advice in the Klipper documentation.  We don't know what type of device the user is using, nor the environment it is running in.  (For example, is it a $200 3d printer with low-quality wiring, a laser cutter that requires eye protection, or a plasma cutter that needs a water bath to prevent toxic fumes.)  We thus have no ability to provide meaningful safety advice.  I'd feel really bad if a user followed the steps of a general safety guide and then actually felt some sense of safety from that.

There is, of course, topics that we can provide meaningful advice on.  Things that are Klipper specific (square_corner_velocity, pressure advance, input shaper, etc) are areas that we know well and can offer authoritative information on.

Again, just some high-level thoughts.
-Kevin

**Comment by grigi** [comment]
Thanks for those thoughts, it is good feedback.

What is there right now isn't really representative, but more just a mind dump. It should take shape over the next few weeks.

> Also, Klipper has some useful calibration tools (eg, TUNING_TOWER and Z_ENDSTOP_CALIBRATE) that the external documents wont mention.

Yes, I have used that to do retraction calibration, but then you need to set the slicer up to use firmware retraction, etc... it can be quite troublesome.
Until we can do something like on teaching Tech site, where we generate gcode, it's not a solution i would want to recommend, but it also needs special config...
But we can improve that at a later stage.

Your advice re specific advice and safety advice is good, and I'll try to follow it.

For example "stiffening your frame" on an Anet A8 is totally different to a Ender 3, or even an Ender 5. If you want specific advice it needs to be very thorough and with lots of qualifications. I should probably outsource it to other existing guides.

As I see it, this guide is supposed to have two use-cases:
* Someone wants to know what the recommended Klipper calibration steps are (e.g. new or from a different software, e.g. Marlin)
* Someone that is already comfortable with it, but just want a reference of easy instructions to follow.

I'd like to cater for both.

**Comment by newphreak** [comment]
As for retraction tuning, when using firmware retraction within klipper it's really easy to tune.
I have a bowden setup and use teaching tech's stl for the tuning, which is 38mm high.
These are my values for bowden tuning on an ender 3 v2 with bmg extruder:
```
SET_RETRACTION RETRACT_LENGTH=2.4 RETRACT_SPEED=25 UNRETRACT_EXTRA_LENGTH=0 UNRETRACT_SPEED=27
;TUNING_TOWER COMMAND=SET_RETRACTION PARAMETER=RETRACT_LENGTH START=0.8 FACTOR=0.15 ;0.8mm to 6.5mm
TUNING_TOWER COMMAND=SET_RETRACTION PARAMETER=RETRACT_SPEED START=10 FACTOR=1.35 ;10mm/s to 40mm/s retract speed
;TUNING_TOWER COMMAND=SET_RETRACTION PARAMETER=UNRETRACT_SPEED START=10 FACTOR=1.35 ;10mm/s to 40mm/s unretract speed
;TUNING_TOWER COMMAND=SET_RETRACTION PARAMETER=UNRETRACT_EXTRA_LENGTH START=0.0 FACTOR=0.03 ;0mm to 0.2mm extra restart
;<Factor> x <measured length> + <start> = value
;Or, you can pause when it looks good. run GET_RETRACTION and stop the print.
```
These are just undocumented tests I've done by trial and error.

Base tests should have an option for a set bowden length option, and DD I guess. But this might be worth looking at to get an idea how to make and write a standarized test.

**Comment by grigi** [comment]
Thank you, that is helpful. I know I tried a similar thing but had to slice using G10 and G11 instead of regular retraction.
This does mean one can't use Cura for it without advanced plugins that modify the gcode for example.
The slic3r derivatives can all do it, I have no idea about the rest.
So I'm loathe to recommend it, unless we can pre-generate the gcode like TeachingTech does.

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by grigi** [comment]
I have serious time constraints at the moment, and basically got my printer working "just fine" for now.
(I did learn about some very distinct issues that could probably be improved in the documentation, which I can put in.)

What is the minimum we can chop this PR down to, to make it worthwhile?
I'm hoping that with a place to start and expand it other people can help?

**Comment by dewi-ny-je** [comment]
I'm preparing a calibration and tuning guide to be published at least initially on my website. It is based on Klipper and I will link external resources to avoid duplication of work. It will include the procedure, the requirements for each step, the directions about which steps to repeat depending on what has changed in your setup.
I'm also slowly filming some rudimentary videos to show how to do it, at least when similar videos around do not satisfy me or are not klipper-related.
I'm also providing macros.

It's a slow project and it was meant as help for myself but but I'll do it publicly.
So far I have max flow calibration (text and video, not published) and step distance (only text).

**Comment by grigi** [comment]
> I'm preparing a calibration and tuning guide to be published at least initially on my website. It is based on Klipper and I will link external resources to avoid duplication of work. It will include the procedure, the requirements for each step, the directions about which steps to repeat depending on what has changed in your setup.
> I'm also slowly filming some rudimentary videos to show how to do it, at least when similar videos around do not satisfy me or are not klipper-related.
> I'm also providing macros.
> 
> It's a slow project and it was meant as help for myself but but I'll do it publicly.
> So far I have max flow calibration (text and video, not published) and step distance (only text).

That's awesome. Thank you.
I'm just suffering from severe lack of time. Do you have some part of the guide already completed?

**Comment by dewi-ny-je** [comment]
@grigi Just uploaded.
https://www.marzocchi.net/Olafsen/3DPrint/3DPrint

**Comment by KevinOConnor** [comment]
> What is the minimum we can chop this PR down to, to make it worthwhile?
I'm hoping that with a place to start and expand it other people can help?

As a high-level comment, it might be easier to forgo a "general calibration guide for newbies" and instead focus on tuning one Klipper specific variable at a time.  See, for example, my notes at #3158 .

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as I don't think we need to track this as an open item in the Klipper repo.  I'm happy to add documentation when you are ready.

-Kevin

**Pull request closed without merging**
