### PR TITLE
Temperature measurement using SPI is working again in a Beaglebone

### PR DESCRIPTION
**Pull request by ramezquitao**
The modifications made on work-thermocouple-20180521 made a few months ago to allow SPI temperature sensors to work on the replicape+beaglebone did not work with the latest developments of Klipper.  This was fixed

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks - good to hear it is working again.

Commits to Klipper require a signed-off-by line - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Also, white-space changes would need to be in commits separate from commits that change functionality.  Otherwise, it makes it harder to review changes and it complicates tools like "git bisect".

Are the functionality changes limited to support for specifying the spi bus and for not having a "cs pin"?  If so, I think we should just state the bus in the config instead of using special pin names - see the tmc2660.py code for an example.  I'll also try to put together some test code.

-Kevin

**Comment by ramezquitao** [comment]
Hi Kevin


I'm sorry about the white spaces.  My emacs is configured for autoformating
python files for PEP8. I will disable for further contributions. About the
signoff-by. Sorry I forgot to do it in the commit comment. What should I
do, re create my repo with the commits with the sign off line?
The idea here is that klipper is using the Linux configuration of the SPI
bus (linux spidev driver), so the CS pin is controlled by linux and not by
the python code. I tried to pass the configuration using the spi_bus
configuration parameter, and not using the spi_pin, but klipper is
expecting me to pass information in the spi_pin option (there is an error
if I dont use the spi_pin option in the config file). So this is why I
decided to use the pin and not the bus option. Any suggestion on how to do
this in a better way?

Regards

Ricardo

**Comment by KevinOConnor** [comment]
Thanks for looking at this.  Nothing to worry about with the whitespace and signed-of-by lines - I just wanted to make sure you knew the steps needed for me to commit a change.

Can you retest with your code and config on top of the new spi helper code (discussed in #903).  Hopefully you can just use "host:None" for the sensor_pin and an explicit bus for the spi_bus parameters.

-Kevin

**Comment by KevinOConnor** [comment]
It looks like this PR was replaced by #952, so I'm going to close this one.

-Kevin

**Pull request closed without merging**
