### PR TITLE
probe: Add support for probe slow down

### PR DESCRIPTION
**Pull request by nythil**
Added an option to increase probing accuracy by first doing a fast
probe, backing off, and then performing a slow probe. This allows
to set a reasonable probe speed for bed leveling while retaining
the accuracy of a slow probe speed.

This a solution for #1297 and a partial solution for #1249.

### CODE REVIEW

**Comment by Maglin** [comment]
Or just probe at 50mms like I do after you waste days/weeks of your time to come to the conclusion that your inductive probe is indeed more accurate than you want to believe.  

/shrug

**Comment by nythil** [comment]
I actually need a really slow probing speed (max 1mm/s) to get reasonable repeatability. The dc42 probe is so sensitive that even the slightest bed springiness or resonance makes it trigger erratically. When probing slowly it gives nice, sub-20 micron repeatability. This, however, makes bed mesh leveling painfully slow.

**Comment by nythil** [comment]
Another idea occurred to me. Kevin has noted that during probing / bed leveling the FW already knows the Z position to some degree. This information can be used to simply slow down just before the probe is expected to trigger (instead of probing fast and backing off).

**Comment by KevinOConnor** [comment]
Thanks.  As you noted above, wouldn't it be simpler to create a gcode_macro that did a regular move to the desired location and then just did the slow probe?  That is, I'm not sure what gain there is in doing a "fast probe".

-Kevin

**Comment by nythil** [comment]
That's true - the fast probe/slow probe implementation would make sense only for an extremely uneven bed. That's why I changed the code since first proposing the idea. Now there would be only a single probe with the option of slowing down just before the expected trigger point. This helps with mesh bed leveling, during which the probe is allowed to travel and retract quickly, but is slowed down during the actual probing.

**Comment by CptHungarian** [comment]
Hi nythil, first of all thank you very much for this option. When I try to add this option to the config in the latest release I get this "Option 'slowdown_dist' is not valid in section 'probe'" error message. This hasn't been released yet? Btw I also have a DC42 probe and I can confirm that a slower probing speed indeed increases the repeatability. This  is exactly why I wanted to try this feature. Cheers.

**Comment by nythil** [comment]
Hey. It's not been merged yet. It needs some more work. For example, if slowdown_dist is too low and probe is triggered too early, the probing operation will fail. I need a couple of days to iron the kinks out, as time permits.

**Comment by KevinOConnor** [comment]
I'm not sure adding additional fields to the config file makes sense for this.  Why not just always probe at the slower speed?  (Users can move to the probing position using standard G1 commands at a faster speed).

If it is desirable to have the ability to probe at different speeds, then I'd recommend adding a SPEED parameter to the PROBE command instead of adding additional fields to the config file.

-Kevin

**Comment by nythil** [comment]
This is actually not about the PROBE command itself, but rather ProbePointsHelper and commands that use it (bed mesh leveling and bed tilt adjust). ProbePointsHelper moves the toolhead to a number of positions and invokes PROBE command in each: `self.gcode.run_script_from_command("PROBE")`.

With the dc42 IR probe I get a significant improvement in standard deviation with **very** slow speeds, e.g. 0.5mm/s. This, however, makes probing the entire bed take ages - this is the biggest issue. One optimization would be to decrease sample_retract_dist and horizontal_move_z. Another one (proposed in this patch) to raise and lower the probe at regular speed, and add a slow down in the final portion of a probing move.

Yet another, simpler solution has just occurred to me: making lift_speed in ProbePointsHelper configurable independently of the regular probing speed. This way a) sample_retract_dist and horizontal_move_z could be reduced to a minimum, b) the regular probing speed could be set to a very low value, c) lift_speed could be set to a reasonable, higher value. I think this would accomplish the goal too. Would this be preferable for you?

**Comment by KevinOConnor** [comment]
Yes, thanks.  I'd make lift_speed configurable (with it defaulting to the minimum of speed and probe.speed).

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  At a high-level the approach seems good to me.  However, I'm not sure the implementation is correct.  If the user first implements a manual probe and then implements an automatic probe, the lift speed may be calculated differently.  (That is, I think the code would need to store self.config_lift_speed separately from self.lift_speed.)

-Kevin

**Comment by nythil** [comment]
Hi. I've been pretty busy lately. I'll get back to you on this in the next few days.

**Comment by KevinOConnor** [comment]
What's the status of this PR?

Thanks,
-Kevin

**Comment by nythil** [comment]
Now lift speed is being restored correctly on each probe start

**Comment by KevinOConnor** [comment]
FYI, this will conflict with PR #1698.  In that PR, the probing logic is moved from ProbePointsHelper to PrinterProbe.  I think this change will need to be rebased on top of that branch.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, since the probe lift is now primarily done in the PrinterProbe class - this change would need to be reworked to define the lift speed there.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, lift speed is now a config and command option for PROBE and related commands (commit c36fe76d).

-Kevin

**Comment by nythil** [comment]
Thanks for keeping up the good work! Sadly, it's been ages since I last used my 3D printer. I may give this a try the next time I do.

**Comment by DroneMang** [comment]
Has this been implemented somehow? I need something like this for my BLtouch. Thanks.

**Pull request closed without merging**
