### PR TITLE
Fluid LCD display

### PR DESCRIPTION
**Pull request by skuznetsov**
Added flexible presentation of information to LCD display
Also added support for M117 (display string)

### CODE REVIEW

**Comment by skuznetsov** [comment]
Here is a preview how does it look like:
image

**Comment by KevinOConnor** [comment]
Thanks.  It would help if you could break this change up into multiple separate changes.  For example, the M117 change, the fan character change, the layout change, etc.  This will help with reviewing and make "git bisect" work better (should that ever be needed).

-Kevin

**Comment by skuznetsov** [comment]
Ok. Will do.

**Comment by skuznetsov** [comment]
I closed this PR and will create another one.
Do you want to have three different commits for features in one PR or three different PRs?
Three different PRs will be difficult to make at once so I will have to do it piece by piece after you will approve base PR for fluid display.
Please let me know which method do you prefer.

**Comment by KevinOConnor** [comment]
On Sun, Jun 10, 2018 at 07:44:47PM -0700, Sergey Kuznetsov wrote:
> I closed this PR and will create another one.
> Do you want to have three different commits for features in one PR or three different PRs?
> Three different PRs will be difficult to make at once so I will have to do it piece by piece after you will approve base PR for fluid display.
> Please let me know which method do you prefer.

Three commits in one PR is fine.  If possible do the simplest commits
first (eg, M117 support, then fan character, then display changes).

-Kevin

**Pull request closed without merging**
