### PR TITLE
docs: added an apt update to measuring_resonance

### PR DESCRIPTION
**Pull request by shiftingtech**
Signed-off-by: Ben Eastep shifting@shifting.ca

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks - looks fine to me.  @dmbutyugin , do you have any comments?

-Kevin

**Comment by dmbutyugin** [comment]
@shiftingtech I'm fine with the change either, but could you describe what kind of scenario you are trying to avoid/fix? My only tiny concern is that the update may pull in, well, updates of the package index, and the subsequent install command may need to pull a lot of updated dependencies. But perhaps this is exactly intentional?

**Comment by shiftingtech** [comment]
I'm trying to avoid package not found errors.

The thing is, when you don't run apt update,  you have the potential to be
using stale packages indexes.  Stale packages indexes don't result in
getting older packages,  they result in getting no package at all (because
the old file is no longer on the mirror)

Also, apt install is pretty good about only pulling updates that are
directly required, so I don't see it as likely to cascade out of control


Ben

**Comment by dmbutyugin** [comment]
Yes, I suppose that can be a real risk (if the index is too stale). So OK, thanks!

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
