### PR TITLE
Add hardware PWM documentation

### PR DESCRIPTION
**Pull request by mrvanes**
This addition explains how to enable and use hardware pwm support on a Raspberry Pi using the Linux host mcu.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine but needs a signed-off-by line.

-Kevin

**Comment by Alexdad76** [comment]
Is it possible to use this method to control the laser instead of using a PWM fan?
Instead of this [https://github.com/KevinOConnor/klipper/pull/4128](url)

**Comment by mrvanes** [comment]
No, I don't think this will help controlling laser. The challenge in 4128 is to execute pin commands quicker than the current queueing system allows. This PR only describes how to controll a hardware PWM pin, which is subject to the same queueing mechanism currently implemented in Klipper.
@KevinOConnor I signed the commit, I think everything is in place to merge?

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
