### PR TITLE
Filament_runout_sensor: Added a module to deal with filament sensors

### PR DESCRIPTION
**Pull request by paulodrugos**
Signed-off-by: Paulo Drugos paulodrugos@gmail.com

### CODE REVIEW

**Comment by alecplumb** [comment]
This should include a `QUERY_FILAMENT_SENSOR` command so that a user can determine whether the sensor is triggered (this will be very helpful for anybody setting up and testing a runout sensor).

**Comment by paulodrugos** [comment]
The "state" parameter its not enough to keep track of multiple sensors. For multiple sensors I also need to know the pin that triggered the callback.

Any ideias?

**Comment by KevinOConnor** [comment]
Thanks.  Why does the module take a list of pins instead of just one pin?  Have you been able to confirm that OctoPrint does something sane during filament change sequences (where the pin may be toggling due to load/unload process)?

-Kevin

**Comment by paulodrugos** [comment]
The module acceps one or more pins, for one or more sensors.
The module only triggers pause in octoprint when the toolhead is printing, so, until the user resume the print, any changes in the sensor will be ignored.

**Comment by KevinOConnor** [comment]
Okay, thanks.  If it's for two separate sensors I think the user should define two separate config sections (eg, [filament_runout_sensor my_first_extruder] and [filament_runout_sensor my_second_extruder]).

-Kevin

**Comment by jakep82** [comment]
I would think you would want to follow the established convention.  Something like QUERY_FILAMENT_SENSOR SENSOR=EXRUDER1.

**Comment by paulodrugos** [comment]
But how I register a command to execute in two different instances?

If i remove the line:
`gcode.register_command("QUERY_FILAMENT_SENSOR",None)`
That remove any previous registered function to this name, the firmware stops working. 

Checking the register_command function (gcode.py line 58), its not possible register a function twice under the same name...

**Comment by KevinOConnor** [comment]
Use gcode.register_mux_command() - see klippy/extras/servo.py as an example.

-Kevin

**Comment by paulodrugos** [comment]
Thanks a lot, will look there!

**Comment by paulodrugos** [comment]
Done!

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.  If there are no further comments I'll look to commit in the next few days.

-Kevin

**Comment by paulodrugos** [comment]
Theoretically if the pause option in the display works to pause a print from virtual SD, the filament runout sensor should it too. They both use the same command `action:pause`

When I get a spare time, will test to ensure that the module work...

**Comment by KevinOConnor** [comment]
In order to pause a virtual_sdcard print, the code would need to detect that a virtual_sdcard is registered (printer.lookup_object("virtual_sdcard", None) != None) and then ask the virtual_sdcard to pause its print (with something like: virtual_sdcard.cmd_M25() ).  I think it would be good to extend both the menu and the filament_runout_sensor code to do this, but I don't think it's a prerequisite.

-Kevin

**Comment by paulodrugos** [comment]
Looks like its easy to implement the virtual SD into filament_runout_sensor, but the fact that virtual_sdcard is registered does not imply that the current job was started via virtual SD, right? 

There's a way to determine which pause method the filament_runout_sensor should use to the current print job?

**Comment by KevinOConnor** [comment]
It's possible to extend the virtual_sdcard.py code to export a method that reports if it is active.  However, I suspect it's harmless to just always pause both OctoPrint and virtual_sdcard.  (If you look at virtual_sdcard.cmd_M25(), it doesn't do anything if a print is not active.)

-Kevin

**Comment by KevinOConnor** [comment]
@trevjonez - to answer your last question - the "button" mechanism (which is used by the filament runout_sensor to detect the change in filament status) is only accurate to within a few milliseconds.  It's technically possible to backtrack that rough time to within a move, but the code to do that would need to be written.  However, a pause request would only stop new movement commands - so the pause itself would only take effect after all moves in the lookahead queue are drained - that's typically about 2 seconds of movement.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  If you get a chance, could you rebase this to the current master (github shows a conflict with the latest code).

-Kevin

**Comment by paulodrugos** [comment]
@KevinOConnor I messed up my branch with the rebase...  created a new pull request ( #1098 ) that should merge fine with master....  
Sorry about that.

**Pull request closed without merging**
