### PR TITLE
Fix grammar and typos for the new arc config

### PR DESCRIPTION
**Pull request by pusewicz**
This PR fixes the grammar for the newly added arc configuration.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I agree with the change, but it'd need to have a signed-off-by line.

@achmed20 - FYI.

-Kevin

**Comment by pusewicz** [comment]
@KevinOConnor Updated!

**Comment by KevinOConnor** [comment]
Thanks - alas, this conflicted with the recent reorg of example-extras.cfg (the description is now in the "Optional G-Code features" section.  I can cut-and-paste your update in, though, if rebasing is a pain.

-Kevin

**Comment by pusewicz** [comment]
Sure, I wasn't sure if I rebased correctly. I'll do it again.

**Comment by pusewicz** [comment]
@KevinOConnor Rebased.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
