### PR TITLE
Improvements to CAN bus ID generation. And added a small fast hash library

### PR DESCRIPTION
**Pull request by bondus**
There were ID collision in the CAN bus unique ID generation. 
I found a small and fast little hash library that solved that problem.

### CODE REVIEW

**Comment by bondus** [comment]
Typo. Should be small fast hash library...

**Comment by KevinOConnor** [comment]
Thanks.  Looks fine to me.  @Delsian - do you have any comments?

-Kevin

**Comment by Delsian** [comment]
Yes, nice variant, thanks!

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
