### PR TITLE
HallFilamentWidthSensor: Use current width instead of nomal width while delay is not over

### PR DESCRIPTION
**Pull request by matpab**
I have a very long Bowden after the sensor (about 700mm) and I am using filament which isn't varying very much but every spool is different. 
So for me, the more exact guess of the current width in the melting area is the current reading of the sensor, therefore I added an option that enables the use of the current width while the first reading isn't in place.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@test3210-d , FYI.

-Kevin

**Comment by test3210-d** [comment]
I see and think it's good idea for bowden

**Comment by test3210-d** [comment]
I test, work fine

**Comment by KevinOConnor** [comment]
@test3210-d - Okay, do you wish me to commit this then?

-Kevin

**Comment by test3210-d** [comment]
@KevinOConnor - yes

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
