### PR TITLE
Add gantry leveling (ruled hyperbolic parabola correction)

### PR DESCRIPTION
**Pull request by mzbotreprap**
module: QUAD_GANTRY_LEVEL

Adds gantry level routine that conforms a moving gantry to the stationary bed plane. Corrects both tilt and twist using simplified representation of ruled hyperbolic parabola to calculate individual Z actuator corrections.

Requires 4 Z motors.

Signed-off-by: Maks Zolin - mzolin@vorondesign.com

### CODE REVIEW

**Comment by volcom8190** [comment]
samples and sample_retract_dist throw an error when trying to square the gantry with this pull request, looks like it cant take the average when probing the same spot multiple times

**Comment by mzbotreprap** [comment]
Can you post the error, or trace from Klipper log?

**Comment by KevinOConnor** [comment]
Thanks.  I have a few minor comments:
* It seems this code is quite specific to printers with four Z steppers and I'm concerned that the name "gantry_level" is too generic - how about something like "quadgantry_level"?
* It doesn't look like the mathutil module is actually used in the code.
* It looks like probe_location should be removed in favor of the existing [probe] x/y_offset parameters.  (Specifically, the finalize() method is now passed the x, y, and z offsets of the probe.)

-Kevin

**Comment by mzbotreprap** [comment]
Thanks Kevin. Agree with all the above.

The probe offset thing got merged in after I was done hacking on this. I prefer this stay with the probe code anyway so I’ll refactor accordingly.

**Comment by KevinOConnor** [comment]
Thanks.  Code looks fine to me, but I noticed the signed-off-by line is missing - see:
https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by mzbotreprap** [comment]
I should RTFM :) I’ll add this shortly

**Comment by Maglin** [comment]
I have tested the latest changes to the quad_gantry_level and everything is checking out fine with me.  Multi-probe and averaging of probe points are working as is the squaring routine.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Pull request merged**
