### PR TITLE
heater_fan.py : progressive heater fan

### PR DESCRIPTION
**Pull request by ndupont-net**
Modified speed logic that increases the fan power for each active heater
Typical use-case : a chimera hotend with a large fan.

Signed-off-by: Nicolas Dupont <ndupont@ndupont.net>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  FYI, I'm leery of changing the fan speed of heater_fan instances "automatically" for fear it could lead to resonance with the PID.  My high-level feedback is that this might be something more appropriate for controller_fan or temperature_fan.  Finally, it should also be possible to just manually control fan speeds using output_pin config sections and gcode_macros.

-Kevin

**Comment by ndupont-net** [comment]
Hi Kevin,
Once it is tuned to an appropriate level, and if you don't try to make it track the hotend temperature, where should PID resonance come from ?

Nicolas

**Comment by KevinOConnor** [comment]
> where should PID resonance come from ?

I don't know, and I don't want to find out.  The heater_fan module was designed so that its heaters always see exactly one fan speed, so as to minimize the fan speed itself interacting with the heater control logic.  This PR would change that and my high-level feedback is that I don't think that's a good idea.  I understand that you have some requirements that need more fan control - my feedback is that a different module, manual control, or perhaps an entirely new module is a better location.

Cheers,
-Kevin

**Comment by ndupont-net** [comment]
ok then, I'll keep it for me and continue to merge every new release to my own mods

**Comment by ndupont-net** [comment]
Actually a new module is the perfect solution for me, it will ease the merges with the main branch, thanks for the tip !
Nicolas

**Pull request closed without merging**
