### PR TITLE
Add config file for Longer3D LK4 Pro

### PR DESCRIPTION
**Pull request by timgir**
Like said the title, I write a config file for Longer3D LK4 Pro.

Alfawise U30 Pro & Longer3D LK4 Pro is, for me, same printer some my config file should be work this Alfawise U30 Pro but I don't have this printer for test my config file.

Signed-off-by: Timothée Girard <timgir@timotheegirard.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it looks fine to me.  However, new configs will need to use `rotation_distance` as the step_distance parameter is now deprecated.

-Kevin

**Comment by KevinOConnor** [comment]
Also, all the printer-xxx.cfg files should end in a year.  Just add a rough year from when the printer you tested with was introduced.

-Kevin

**Comment by timgir** [comment]
Hi Kevin !

Thanks for review & advices :) I made the requested changes.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
