### PR TITLE
Update Probe_Calibrate.md

### PR DESCRIPTION
**Pull request by Hywelmartin**
#1777 
for newcomers that follow the guide this will help..

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I don't understand this change.  What's wrong with the current implementation?  Is there something that can be changed in the code to prevent it?

-Kevin

**Comment by Hywelmartin** [comment]
When you do a probe test it starts from Z10 regardless of probe offset, the offset + some hight could be a minimum hight to start this  or maybe throw an error...

So yes some smartness could be added to the code..

**Comment by KevinOConnor** [comment]
Okay, thanks.  That sounds like a code defect.

-Kevin

**Comment by KevinOConnor** [comment]
I think this should be fixed now (commit 364c22fe).

-Kevin

**Comment by Hywelmartin** [comment]
that will do the trick... closing this then...

**Comment by Hywelmartin** [comment]
did a quick test...
ran
`PROBE`
then
`PROBE_ACCURACY` 

the tool head was placed at probe height Z:-0.118  and didn't go up to `sample_retract_dist = 10`

`Send: PROBE_ACCURACY
Recv: // PROBE_ACCURACY at X:-0.832 Y:-0.744 Z:-0.118 (samples=10 retract=10.000 speed=30.0
Recv: // probe at -0.832,-0.744 is z=-0.218259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe at -0.832,-0.744 is z=-0.118259
Recv: // probe accuracy results: maximum -0.118259, minimum -0.218259, average -0.128259, median -0.118259, standard deviation 0.030000`

If I do it from a height above `sample_retract_dist = 10` it also seems to ignore set height and make the probing from that height..
`Send: PROBE_ACCURACY
Recv: // PROBE_ACCURACY at X:-0.832 Y:-0.757 Z:65.738 (samples=10 retract=10.000 speed=30.0
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe at -0.832,-0.757 is z=-0.121558
Recv: // probe accuracy results: maximum -0.121558, minimum -0.121558, average -0.121558, median -0.121558, standard deviation 0.000000`

Is this a real problem??? I don't think so..

**Comment by KevinOConnor** [comment]
That's the intended behaviour of the new code.  Hopefully it's not a problem.

-Kevin

**Pull request closed without merging**
