### PR TITLE
CoreXZ kinematics

### PR DESCRIPTION
**Pull request by VoronDesign**
Adding CoreXZ kinematics to Klipper. Heavily based on CoreXY kinematics for obvious reasons.

Signed-off by: Maks Zolin <mzolin@vorondesign.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Looks good to me.  If there are no other comments, I'll look to commit in a few days.

(FWIW, as a very minor thing, I found the comment "Corexy config was used as a template." in example-corexz.cfg to be confusing.  Maybe that statement isn't needed?)

Cheers,
-Kevin

**Comment by VoronDesign** [comment]
Thanks Kevin. I can remove that statement. Simply wanted to pay homage to the blatant copypasta. :)

I think at some point down the line I’d like to make a unified core* kinematics that will handle all the permutations, simply to eliminate redundant code.

**Comment by KevinOConnor** [comment]
> I think at some point down the line I’d like to make a unified core* kinematics that will handle all the permutations, simply to eliminate redundant code.

Yeah, I saw that as well.  I don't think there's any harm with the minor duplication introduced by corexz, but I agree if we add coreyz (or similar) then we may want to revisit.

If you do update the commit, you may also want to add config/example-corexz.cfg to klippy/tests/printers.test as that'll enable some basic test cases for the new kinematics.  (No worries though, I can add it after committing this patch.)

-Kevin

**Comment by VoronDesign** [comment]
Ok, wording changed, and I added corexz to printers.test

**Pull request merged**
