### PR TITLE
Host keepalive module

### PR DESCRIPTION
**Pull request by mcmatrix**
During some long-running gcode, Klipper may appear not responding to the host. 
The **host keepalive** module will send `busy: processing` messages to the host when Klipper is busy 
so the host won’t try to reconnect.
It's similar to what Marlin has.

### CODE REVIEW

**Comment by mcmatrix** [comment]
Don't merge yet.

**Comment by FHeilmann** [comment]
I think you can replace the counter functionality by simply returning 
`eventtime + self._interval` instead of `eventtime + 1`. That way your handler will be called every `self._interval` seconds

**Comment by KevinOConnor** [comment]
I'm concerned that implementing the g-code "busy protocol" is more work than it looks.  As I understand the protocol, if OctoPrint detects that it is in use then it will only give 3 seconds of idle time instead of the normal 30 seconds.  That means that Klipper's main thread would need to always respond within a second or so.  There's definitely some code right now that can't guarantee that (like coordinate descent calibration code).  Klipper uses threads for cases where it has some real-time requirements - like PID handling. I'm leery of auditing all the code using the main thread, and leery of having to do that for all future code.

The default behavior of OctoPrint seems more sane to me - it uses a much larger timeout and it clears the timer if it gets any message from Klipper.  In my opinion, the "busy protocol" is another half-baked g-code extension that complicates the protocol with marginal benefits.  In my opinion, it is a bizarre comms error detection mechanism tacked on to the last bizarre comms error detection mechanism (line numbers).  Like most g-code "enhancements", I'd prefer to avoid it if possible.

-Kevin

**Comment by mcmatrix** [comment]
Thanks for the feedback.
I'm using Repetier-Server and it was my first idea how to solve timeouts.
I can also specify `communication timeout` seconds in config but I didn't want to set it very long.

Repetier-Server has XML profile for Klipper firmware. At the moment it's basically copy of Marlins profile.
It's using "standard" marlin response for resetting timeout.
`<response type="resetTimeout">^(echo:)?busy:</response>`

It supports `regex` so right now I'm thinking that maybe it will work if I'll make it
to accept any non-whitespace response.

**Comment by KevinOConnor** [comment]
Were you able to resolve this via Repetier-Server settings?

-Kevin

**Comment by mcmatrix** [comment]
I hope so.
Haven't had much printing time.
I'll close this at the moment.

**Pull request closed without merging**
