### PR TITLE
config: Add Wanhao Duplicator 9 MK1

### PR DESCRIPTION
**Pull request by mdshw5**
Also applies to the Monoprice Maker Pro MK1.
This config is based on the version from Chris Barnes (https://www.facebook.com/Jarannis)
found on https://pastebin.com/raw/wm8PQezy. This config was mostly working and I
only had to change a few things:

  - updated key names for min_point and max_point to mesh_min and mesh_max
  - enabled PID control
  - tweaked bounds to allow movement during mesh leveling
  - removed all comments
  - decreased homing speed slightly
  - sane bed mesh sample defaults

Signed-off-by: Matt Shirley <mdshw5@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.

The current Klipper convention is to place the approximate year the printer was released in the file name.  What year was this printer released?

FYI, there are a couple of sections that I think should be left at their defaults as I don't think they make good general recommendations for an example config: no pressure_advance setting (there is no good default as every filament is different), no respond section, no pause_resume section.  I can make these changes on commit if you prefer.

-Kevin

**Comment by mdshw5** [comment]
Thanks @KevinOConnor - I agree with all of your comments and welcome any changes you'd like to make to generalize this profile. As far as I can tell the printer was released in early 2018, but can't find a definitive reference. Klipper has made a real improvement to this machine - it's got some real design issues including a very buggy build of Marlin :)

**Comment by mdshw5** [comment]
@KevinOConnor I've incorporated your feedback, also renamed the file including the release date of the printer. IMO this is ready to merge unless there are further issues. Thanks so much for your help!

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
